### PR TITLE
Fix failing LiveTradingDataFeed unit tests

### LINKED ISSUE #3181: Unit test HandlesManyCustomDataSubscriptions fails intermittently in Travis
#### Expected Behavior

- No unit test fails intermittently
#### Actual Behavior

- `LiveTradingDataFeedTests.HandlesManyCustomDataSubscriptions` is failing intermittently during Travis builds
```
Errors and Failures:
1) Test Failure : QuantConnect.Tests.Engine.DataFeeds.LiveTradingDataFeedTests.HandlesManyCustomDataSubscriptions
     Expected: greater than 5
  But was:  2

at QuantConnect.Tests.Engine.DataFeeds.LiveTradingDataFeedTests.HandlesManyCustomDataSubscriptions () [0x00101] in <2bd3c06dd3554490a8627b8a15185e2b>:0
```
#### Potential Solution

- Review unit test behavior. Might be a peformance related issue (execution is slower in Travis causing it to fail)
#### Reproducing the Problem

Travis buils
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Martin-Molinero**
#### Description

- In some tests `SymbolCache.GetSymbol` was being called before `AddData`, throwing an exception when launched as single tests.
- `HandlesManyCustomDataSubscriptions` was failing both locally and in Travis (only occasionally). This behavior started since #3040 was merged. The PR made the LTDF loop slightly slower, and it doesn't reach the time for the data to be released, since its incrementing the frontier in seconds and each data point had a minute gap.
   - Updating `CustomMockedFileBaseData` to respect configuration increment. Note: increasing the frontier step also solved the issue
#### Related Issue

Closes #3181
#### Motivation and Context

Failing unit tests
#### Requires Documentation Change

N/A
#### How Has This Been Tested?

Unit and regression tests
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Engine/DataFeeds/CustomMockedFileBaseData.cs [hunk 1]
```diff
@@ -24,12 +24,12 @@ namespace QuantConnect.Tests.Engine.DataFeeds
...
     public class CustomMockedFileBaseData : BaseData
     {
-        private int _minutesToAdd;
+        private int _incrementsToAdd;
         public static DateTime StartDate;
 
         public override BaseData Reader(SubscriptionDataConfig config, string line, DateTime date, bool isLiveMode)
         {
-            var start = StartDate.Add(TimeSpan.FromMinutes(_minutesToAdd++)).ConvertFromUtc(config.DataTimeZone);
+            var start = StartDate.AddTicks(config.Increment.Ticks * _incrementsToAdd++).ConvertFromUtc(config.DataTimeZone);
```
Comment (StefanoRaggi) [inline Tests/Engine/DataFeeds/CustomMockedFileBaseData.cs]: Wow, thanks for finding this, totally missed it! 👍
