### PR TITLE
Fix bug in ConsumeMultipleMinutes() test

### LINKED ISSUE #6080: IsolatorLimitResultProviderTests.ConsumeMultipleMinutes() fails sometimes
#### Expected Behavior

`IsolatorLimitResultProviderTests.ConsumeMultipleMinutes()` fails only when a change related with `IsolatorLimitResultProvider.cs` file is done
#### Actual Behavior

`IsolatorLimitResultProviderTests.ConsumeMultipleMinutes()` fails with changes that are not related with `IsolatorLimitResultProvider.cs`
#### Potential Solution

Sleep the thread 100ms instead of 20ms in this action https://github.com/QuantConnect/Lean/blob/master/Tests/Common/IsolatorLimitResultProviderTests.cs#L125
```c#
Action code = () =>
{
    // lets give the monitor time to register the initial time
    Thread.Sleep(100);
    for (int i = 0; i < 4; i++)
    {
        timeProvider.AdvanceSeconds(45);           
        // give the monitoring task time to request more time
        Thread.Sleep(100);
    }
};
```
#### Reproducing the Problem

Run the test sometimes
```
  Failed ConsumesMultipleMinutes [189 ms]
  Error Message:
     Expected: 3
  But was:  2

  Stack Trace:
     at QuantConnect.Tests.Common.IsolatorLimitResultProviderTests.ConsumesMultipleMinutes() in /__w/Lean/Lean/Tests/Common/IsolatorLimitResultProviderTests.cs:line 139
```
#### System Information

GH Test system
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Marinovsky**
Sometimes 20ms wasn't enough time for the timer to kick in so the action code advanced faster than the timer and finally there were less invocations than expected
#### Description

- Fix bug in `IsolatorLimitResultProviderTests.ConsumeMultipleMinutes()`
- Change calls to `Thread.Sleep()` with `autoResetEvent.WaitOne()` in `IsolatorLimitResultProviderTests.cs`
#### Related Issue

Closes #6080 
#### Motivation and Context

With this change the test `ConsumeMultipleMinutes()` will only fail when a breaking change related with `IsolatorLimitResultProvider.cs` is done
#### Requires Documentation Change

This change does not require changes or updates to documentation
#### How Has This Been Tested?

`IsolatorLimitResultProviderTests.ConsumeMultipleMinutes()` was ran 500 times giving the timer 15ms to kick in. This test case failed and the same happened when giving less time than 20ms. Then it was used an AutoResetEvent to advance in the action code at the same time as the timer kicked in. `ConsumeMultipleMinutes()` was ran 2000 times and then all the tests in the file were ran.
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Scheduling/TimeConsumer.cs [hunk 1]
```diff
@@ -1,4 +1,4 @@
-﻿/*
+/*
```
Comment (Martin-Molinero) [inline Common/Scheduling/TimeConsumer.cs:1]: nit - should avoid these changes

File: Common/Scheduling/TimeMonitor.cs [hunk 2]
```diff
@@ -26,7 +26,7 @@ namespace QuantConnect.Scheduling
     /// </summary>
     public class TimeMonitor : IDisposable
     {
-        private readonly List<TimeConsumer> _timeConsumers;
+        protected readonly List<TimeConsumer> _timeConsumers;
```
Comment (Martin-Molinero) [inline Common/Scheduling/TimeMonitor.cs:29]: nit - `_timeConsumers`  -> `TimeConsumers` would be nice to add the xml documentation and a remarks section mentioning it's protected for testing, same for `ProcessConsumer`

File: Tests/Common/IsolatorLimitResultProviderTests.cs [hunk 3]
```diff
@@ -122,15 +122,18 @@ public void ConsumesMultipleMinutes()
...
             {
                 // lets give the monitor time to register the initial time
-                Thread.Sleep(100);
+                timeMonitorEvent.WaitOne();
                 for (int i = 0; i < 4; i++)
                 {
                     timeProvider.AdvanceSeconds(45);
                     // give the monitoring task time to request more time
-                    Thread.Sleep(20);
+                    timeMonitorEvent.WaitOne();
```
Comment (Martin-Molinero) [inline Tests/Common/IsolatorLimitResultProviderTests.cs:136]: Awesome to see these sleeps removed! ✨ 
The improvements could probably be expanded into all the tests in this fixture?

File: Tests/Common/IsolatorLimitResultProviderTests.cs [hunk 4]
```diff
@@ -140,7 +143,7 @@ public void ConsumesMultipleMinutes()
             Assert.IsTrue(provider.Invocations.TrueForAll(invoc => invoc == 1));
 
             // give time to the monitor to register the time consumer ended
-            Thread.Sleep(50);
+            _timeMonitor.RemoveAll();
```
Comment (Martin-Molinero) [inline Tests/Common/IsolatorLimitResultProviderTests.cs:146]: I think force calling `RemoveAll` here removes the purpose of the test assert, because it's asserting the production implementation is removing those consumers that ended, maybe this can be achieved in some other way?

**Review by Martin-Molinero — CHANGES_REQUESTED** [review]
A hard one, ty @Marinovsky! Leaving a couple of requests

**Review by Martin-Molinero — APPROVED** [review]
Sweet, no sleep ❤️
