### PR TITLE
GDAX brokerage updates

### LINKED ISSUE #3527: Incomplete Order Requests In Coinbase Brokerage
#### Expected Behavior
The sum of partially filled orders should sum up to the order ticket quantity.

#### Actual Behavior
In a live deployment with Coinbase brokerage, we had the following events:
1 - Using `SetHoldings` to buy ETHUSD works as expected:
```
SetHoldings("ETHUSD", 1m):
OrderId: 1 New Market order for 194.50301212 units of ETHUSD 1564667040
2019-08-01T17:44:26.9027140Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557814,"maker_order_id":"3de848cd-5485-4a3e-9400-2b76ea36497e","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"1.38890293","price":"213.81000000","product_id":"ETH-USD","sequence":7108812352,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9039470Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557815,"maker_order_id":"93ea5fd6-3f26-4a42-a68b-b134ee11e81f","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"10.00000000","price":"213.81000000","product_id":"ETH-USD","sequence":7108812354,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9040960Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557816,"maker_order_id":"cd271d47-8287-4732-81c8-b1c964877ff2","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"10.00000000","price":"213.81000000","product_id":"ETH-USD","sequence":7108812356,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9042340Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557817,"maker_order_id":"4b6d66f0-5a3b-47a9-b9e4-d4905f551baa","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"2.00000000","price":"213.81000000","product_id":"ETH-USD","sequence":7108812358,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9043790Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557818,"maker_order_id":"0679b400-82e2-424d-bfb3-96dedd6d165b","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"0.54069135","price":"213.81000000","product_id":"ETH-USD","sequence":7108812360,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9045240Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557819,"maker_order_id":"763476a5-5334-4831-963c-ac01d87a597a","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"1.20522880","price":"213.81000000","product_id":"ETH-USD","sequence":7108812362,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9046690Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557820,"maker_order_id":"fe7963cd-a6b6-4891-944a-07430ba6e808","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"0.25407985","price":"213.81000000","product_id":"ETH-USD","sequence":7108812364,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9048120Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557821,"maker_order_id":"df614d37-ada8-4c26-98e9-b948aaf3b196","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"9.00000000","price":"213.81000000","product_id":"ETH-USD","sequence":7108812366,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9049560Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557822,"maker_order_id":"673ff21d-b067-47c4-8376-470d8118e4b2","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"5.01688414","price":"213.85000000","product_id":"ETH-USD","sequence":7108812368,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9051160Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557823,"maker_order_id":"348b062f-6b3a-4c8f-b5e9-ad9ebba05cda","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"16.72170760","price":"213.87000000","product_id":"ETH-USD","sequence":7108812370,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9052540Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557824,"maker_order_id":"831e2d82-3c75-45e2-b0d0-811011c61b0e","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"10.00000000","price":"213.88000000","product_id":"ETH-USD","sequence":7108812372,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9054010Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557825,"maker_order_id":"7b58bcaf-63eb-4957-b5d4-87db0711020e","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"0.93000000","price":"213.93000000","product_id":"ETH-USD","sequence":7108812374,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9055420Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557826,"maker_order_id":"c71dc717-4911-4a41-abd9-1d80d97286e3","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"21.90150763","price":"213.93000000","product_id":"ETH-USD","sequence":7108812376,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9056880Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557827,"maker_order_id":"faef3dae-1d68-475d-9c59-d260c9c9d611","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"10.00000000","price":"213.94000000","product_id":"ETH-USD","sequence":7108812378,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9058270Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557828,"maker_order_id":"241a60c7-1d24-431a-9b7e-3f63e4bdbe75","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"0.01000000","price":"213.95000000","product_id":"ETH-USD","sequence":7108812380,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9059800Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557829,"maker_order_id":"e64d4dc7-ba92-4764-b7f7-ea834aeb85a6","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"0.10013813","price":"213.98000000","product_id":"ETH-USD","sequence":7108812382,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9061190Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557830,"maker_order_id":"c39e598c-e1f2-4afb-a3ac-dec86e838dcf","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"0.01000000","price":"214.00000000","product_id":"ETH-USD","sequence":7108812384,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9062780Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557831,"maker_order_id":"ac69f03e-31b3-4fa8-a537-8aa58bccf070","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"0.04000000","price":"214.00000000","product_id":"ETH-USD","sequence":7108812386,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9064270Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557832,"maker_order_id":"53a23f1c-2d07-4b92-bb1b-dd7674880e9c","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"15.71985228","price":"214.00000000","product_id":"ETH-USD","sequence":7108812388,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9065750Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557833,"maker_order_id":"0810cfe2-144d-4ec1-8af2-78827a684edd","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"0.04754112","price":"214.01000000","product_id":"ETH-USD","sequence":7108812390,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9067420Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557834,"maker_order_id":"00af4ee8-746a-4bdb-98b5-4710223d3684","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"4.64057544","price":"214.02000000","product_id":"ETH-USD","sequence":7108812392,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9068850Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557835,"maker_order_id":"57bc811c-4ccf-4107-9efc-f5e71ee6147e","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"1.21000000","price":"214.02000000","product_id":"ETH-USD","sequence":7108812394,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9070270Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557836,"maker_order_id":"eb3d2bd3-336e-451e-affe-07ca0a3bfec2","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"3.54101965","price":"214.04000000","product_id":"ETH-USD","sequence":7108812396,"time":"2019-08-01T17:44:26.773000Z"}
2019-08-01T17:44:26.9071680Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50557837,"maker_order_id":"a302d63d-f6cb-43cf-86e5-d644a45534cc","taker_order_id":"ee726a60-f82e-4d6b-bc25-adc0e3d4ea51","side":"sell","size":"70.22488320","price":"214.06000000","product_id":"ETH-USD","sequence":7108812398,"time":"2019-08-01T17:44:26.773000Z"}
```
2 - Using `SetHoldings` to close the position did not handle well the partially filled orders and only a set of order match came from Coinbase. Instead of sell 194.50301212 units of ETHUSD, it just sold about 23 units.
```
SetHoldings("ETHUSD", 0m):
OrderId: 2 New Market order for -194.50301212 units of ETHUSD 1565181600.00197
2019-08-07T16:40:00.1341350Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50677719,"maker_order_id":"9687606f-ccb9-4eac-a2ba-c73e4909433c","taker_order_id":"925a4ec7-fee5-4903-883a-970a38bd2ec0","side":"buy","size":"1.95000000","price":"221.84000000","product_id":"ETH-USD","sequence":7142769390,"time":"2019-08-07T16:40:00.117000Z"}
2019-08-07T16:40:00.1343470Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50677720,"maker_order_id":"a6c25e7e-f7c8-470b-a6ef-4039a9cc2bf7","taker_order_id":"925a4ec7-fee5-4903-883a-970a38bd2ec0","side":"buy","size":"1.35484263","price":"221.83000000","product_id":"ETH-USD","sequence":7142769392,"time":"2019-08-07T16:40:00.117000Z"}
2019-08-07T16:40:00.1345210Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50677721,"maker_order_id":"dfea57ba-d1be-44e0-9957-0ac2506fe457","taker_order_id":"925a4ec7-fee5-4903-883a-970a38bd2ec0","side":"buy","size":"0.01900000","price":"221.82000000","product_id":"ETH-USD","sequence":7142769394,"time":"2019-08-07T16:40:00.117000Z"}
2019-08-07T16:40:00.1346580Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50677722,"maker_order_id":"ef3f101e-52db-4739-b456-efcf2229385e","taker_order_id":"925a4ec7-fee5-4903-883a-970a38bd2ec0","side":"buy","size":"10.00000000","price":"221.82000000","product_id":"ETH-USD","sequence":7142769396,"time":"2019-08-07T16:40:00.117000Z"}
2019-08-07T16:40:00.1348200Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50677723,"maker_order_id":"4edc62ef-0915-4f17-a696-e48ac5940496","taker_order_id":"925a4ec7-fee5-4903-883a-970a38bd2ec0","side":"buy","size":"10.00000000","price":"221.81000000","product_id":"ETH-USD","sequence":7142769398,"time":"2019-08-07T16:40:00.117000Z"}
2019-08-07T16:40:00.1349820Z TRACE:: GDAXBrokerage.OrderMatch(): Match: ETH-USD {"type":"match","trade_id":50677724,"maker_order_id":"34e6de31-f273-4086-95d3-305cb7659cad","taker_order_id":"925a4ec7-fee5-4903-883a-970a38bd2ec0","side":"buy","size":"0.28762059","price":"221.75000000","product_id":"ETH-USD","sequence":7142769400,"time":"2019-08-07T16:40:00.117000Z"}
```
Note that the last event status is `Filled`, so Lean "believes" the order was fulfilled.
```
OrderID: 2 Symbol: ETHUSD Status: Filled Quantity: -0.28762059 FillPrice: 221.75  OrderFee: 0.15944966458125 USD Message: GDAX Match Event Sell
```
3: Finally, since the algorithm retry to sell the 170.8915489 units of ETHUSD (the remaining of 194.50301212) and it failed with insufficient funds.
```
SetHoldings("ETHUSD", 0m):
OrderId: 3 New Market order for -170.8915489 units of ETHUSD 1565181660.00127
Warning - Code: -1 - Order failed, Order Id: 3 timestamp: 8/7/2019 4:41:00 PM quantity: -170.8915489 content: {"message":"Insufficient funds"}
```
#### Potential Solution
N/A

#### Reproducing the Problem
Live algorithm that places a "big" order to Coinbase.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### LINKED ISSUE #3709: GDAX Not Sending All Partial Fills
#### Expected Behavior
Large market orders fully filled

#### Actual Behavior
Market order fill events do not sum to the order total.

#### Potential Solution
When there are partially open market orders, do reconcile the brokerage every few seconds to ensure large orders are fully reconciled.

#### Reproducing the Problem
Send an order for 1 BTC
 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues]  
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
- Fixed websocket authentication failure for `"user"` channel
- Removed `"matches"` channel, now using authenticated `"user"` channel for order fills
- Send `BrokerageMessageEvent` as `Error` instead of `Warning` for subscription and authentication failures

#### Related Issue
Closes #3709 
Closes #3527 

#### Motivation and Context
- Occasionally missing order fills
- Error in algorithm logs: `Failed to subscribe - user channel requires authentication`

#### Requires Documentation Change
No.

#### How Has This Been Tested?
- Local and cloud testing with real trades with both total and partial fills.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Brokerages/GDAX/GDAXBrokerage.Messaging.cs [hunk 1]
```diff
@@ -321,66 +323,38 @@ private void OnL2Update(string data)
...
+        private void OnMatch(string data)
         {
             // deserialize the current match (trade) message
             var message = JsonConvert.DeserializeObject<Messages.Matched>(data, JsonSettings);
 
-            if (_isDataQueueHandler)
+            if (string.IsNullOrEmpty(message.UserId))
             {
-                EmitTradeTick(message);
+                // message received from the "matches" channel
```
Comment (Martin-Molinero) [inline Brokerages/GDAX/GDAXBrokerage.Messaging.cs:333]: > message received from the "matches" channel

But we are not subscribing to `matches` anymore?

File: Brokerages/GDAX/GDAXBrokerage.Messaging.cs [hunk 2]
```diff
@@ -549,17 +520,17 @@ public override void Subscribe(IEnumerable<Symbol> symbols)
                 return;
             }
 
-            var token = GetAuthenticationToken(JsonConvert.SerializeObject(payload), "GET", "/users/self/verify");
+            var token = GetAuthenticationToken(string.Empty, "GET", "/users/self/verify");
```
Comment (Martin-Molinero) [inline Brokerages/GDAX/GDAXBrokerage.Messaging.cs:523]: Nice! 👍 
Should the `GetAuthenticationToken` `body` parameter be remove? Maybe a comment why its an empty string

File: Brokerages/GDAX/GDAXBrokerage.Messaging.cs (hunk 1 above)
Comment (StefanoRaggi) [reply Brokerages/GDAX/GDAXBrokerage.Messaging.cs:333]: Correct, `GDAXBrokerage` does not subscribe to `matches` anymore, but `ChannelNames` is `virtual` and is overridden in `GDAXDataQueueHandler` which has `matches` in the list.

File: Brokerages/GDAX/GDAXBrokerage.Messaging.cs (hunk 2 above)
Comment (StefanoRaggi) [reply Brokerages/GDAX/GDAXBrokerage.Messaging.cs:523]: `GetAuthenticationToken` is also used to sign REST API requests and the body is used there.

The empty string for the WebSocket authentication seems to be undocumented 😕 
found the usage in the Coinbase library source:
https://github.com/coinbase/coinbase-pro-trading-toolkit/blob/master/src/exchanges/coinbasePro/CoinbaseProFeed.ts#L235

**Comment by jaredbroad** [comment]
🎉 wa hoo!
