### PR TITLE
Fixes NoMethodMatchPythonExceptionInterpreterTests

### LINKED ISSUE #2366: Fixes NoMethodMatchPythonExceptionInterpreterTests
#### Expected Behavior
`NoMethodMatchPythonExceptionInterpreterTests` tests a method with a invalid argument.

#### Actual Behavior
`NoMethodMatchPythonExceptionInterpreterTests` is testing `QCAlgorithm.Log(Int32)` which was invalid, but has been made valid.

#### Potential Solution
Use another invalid method call. For since `QCAlgorithm.SetCash(String)`

#### Reproducing the Problem
Run this unit test.

#### System Information
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
Changes the method call that should fail to `AddCash(String)`.

#### Related Issue
Closes #2366 

#### Motivation and Context
Change unit test when API change.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Running this unit test.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Exceptions/NoMethodMatchPythonExceptionInterpreterTests.cs [hunk 1]
```diff
@@ -56,7 +56,7 @@ public void Setup()
         [TestCase(typeof(KeyNotFoundException), ExpectedResult = false)]
         [TestCase(typeof(DivideByZeroException), ExpectedResult = false)]
         [TestCase(typeof(InvalidOperationException), ExpectedResult = false)]
-        [TestCase(typeof(PythonException), ExpectedResult = true)]
+        [TestCase(typeof(PythonException), ExpectedResult = false)]
         public bool CanInterpretReturnsTrueForOnlyNoMethodMatchPythonExceptionType(Type exceptionType)
```
Comment (mchandschuh) [inline Tests/Common/Exceptions/NoMethodMatchPythonExceptionInterpreterTests.cs]: Isn't this test method name misleading? I don't see a `NoMethodMatchPythonException` test case?

Comment (AlexCatarino) [reply Tests/Common/Exceptions/NoMethodMatchPythonExceptionInterpreterTests.cs]: Agree, but it follows the pattern of the other tests.
Can we changed for `CanInterpretReturnsFalseForAnyGivenExceptionType`? Any suggestion?
