### PR TITLE
Fix SmartInsiderTests failing test

### LINKED ISSUE #4594: Smart Insider fields not present in SmartInsiderEventType
#### Expected Behavior

`SmartInsiderConverter` must process raw data flawlessly.

#### Actual Behavior

It fails with because there are unexpected values for the `EventType` property. The unexpected values is `Plan Re-started`.

#### Potential Solution

Add the new values into the `SmartInsiderEventType` object.

#### Reproducing the Problem

Try processing raw data from `SmartInsider` for 2020-07-27

#### System Information

Linux, current Lean master.

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Jay-Jay-D**
#### Description

SmartInsiderIntention.FromRawData method doesn't read the raw data as they come from SmartInsider, it needs a filtering of some columns that is performed in SmartInsiderConverter.Process method.

That's added to the failing test.

#### Related Issue

Closes #4594 

#### Motivation and Context

All test must be green.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

Run all tests.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [ ] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Data/Custom/SmartInsiderTests.cs [hunk 1]
```diff
@@ -133,19 +134,36 @@ public void SerializeRoundTripSmartInsiderTransaction()
...
+                .ToList();
+
+            // Remove in descending order to maintain index order
+            // while we delete lower indexed values
+            tsv.RemoveAt(46); // ShowOriginal
+            tsv.RemoveAt(36); // PreviousClosePrice
+            tsv.RemoveAt(14); // ShortCompanyName
+            tsv.RemoveAt(7);  // CompanyPageURL
+
+            var filteredRawIntentionLine = string.Join("\t", tsv);
```
Comment (Martin-Molinero) [inline Tests/Common/Data/Custom/SmartInsiderTests.cs:159]: Seems we should push all this logic into `SmartInsiderIntention.FromRawData()`/make it shared with the processor
