### PR TITLE
PortfolioTarget.Percent returns null if error

### LINKED ISSUE #2384: PortfolioTarget.Percent should not set target to zero if error
#### Expected Behavior
In the zero price and buying power model error cases, the target should be set to the existing holding quantity, not to zero.

#### Actual Behavior
If there is an error, zero targets are currently returned.

#### Potential Solution
In this method, these two lines:
``` C#
    return new PortfolioTarget(symbol, 0);
```
should be changed to:
``` C#
    return new PortfolioTarget(symbol, security.Holdings.Quantity);
```

#### Reproducing the Problem
Unit tests:
``` C#
        [Test]
        public void PercentReturnsExistingHoldingsIfPriceIsZero()
        {
            const decimal holdings = 50;
            const decimal targetPercent = 1m;

            var algorithm = PerformanceBenchmarkAlgorithms.SingleSecurity_Second;
            algorithm.Initialize();
            algorithm.PostInitialize();
            var security = algorithm.Securities.Single().Value;
            security.SetMarketPrice(new Tick { Value = 0m });
            security.Holdings.SetHoldings(1m, holdings);

            var target = PortfolioTarget.Percent(algorithm, security.Symbol, targetPercent);

            Assert.AreEqual(security.Symbol, target.Symbol);
            Assert.AreEqual(holdings, target.Quantity);
        }

        [Test]
        public void PercentReturnsExistingHoldingsIfBuyingPowerModelError()
        {
            const decimal holdings = 50;
            const decimal targetPercent = 1m;

            var algorithm = PerformanceBenchmarkAlgorithms.SingleSecurity_Second;
            algorithm.Initialize();
            algorithm.PostInitialize();
            var security = algorithm.Securities.Single().Value;
            security.SetMarketPrice(new Tick { Value = 1m });
            security.Holdings.SetHoldings(1m, holdings);

            var buyingPowerMock = new Mock<IBuyingPowerModel>();
            buyingPowerMock.Setup(bpm => bpm.GetMaximumOrderQuantityForTargetValue(algorithm.Portfolio, security, targetPercent))
                .Returns(new GetMaximumOrderQuantityForTargetValueResult(0, "The portfolio does not have enough margin available."));
            security.BuyingPowerModel = buyingPowerMock.Object;

            var target = PortfolioTarget.Percent(algorithm, security.Symbol, targetPercent);

            Assert.AreEqual(security.Symbol, target.Symbol);
            Assert.AreEqual(holdings, target.Quantity);
        }
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
`PortfolioTarget.Percent` has been updated to return `null` instead of a target with zero quantity, if an error occurs.

#### Related Issue
Closes #2384

#### Motivation and Context
An error would cause existing positions to be closed.

#### Requires Documentation Change
Yes, new behavior.

#### How Has This Been Tested?
Unit tests included.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Algorithm/Framework/Portfolio/PortfolioTarget.cs [hunk 1]
```diff
@@ -68,14 +68,14 @@ public static IPortfolioTarget Percent(IAlgorithm algorithm, Symbol symbol, deci
...
-                return new PortfolioTarget(symbol, 0);
+                return null;
             }
 
             var result = security.BuyingPowerModel.GetMaximumOrderQuantityForTargetValue(algorithm.Portfolio, security, percent);
             if (result.IsError)
             {
-                algorithm.Log($"Unable to compute order quantity of {symbol}. Quantity set to zero. Reason: {result.Reason}");
-                return new PortfolioTarget(symbol, 0);
+                algorithm.Log($"Unable to compute order quantity of {symbol}. Quantity set to existing holdings. Reason: {result.Reason}");
```
Comment (mchandschuh) [inline Common/Algorithm/Framework/Portfolio/PortfolioTarget.cs]: Does this log message need to be updated?
