### PR TITLE
ApiDataProvider Zip Download Fixes

### LINKED ISSUE #4556: ApiDataProvider Creates File That Does Not Existe
#### Expected Behavior
If the file doesn't exist in QuantConnect Data Library, `ApiDataProvider` logs that it doesn't exist and continues.

#### Actual Behavior
`ApiDataProvider.Fetch` creates a file when there is correspondence in QuantConnect Data Library.

#### Reproducing the Problem
Use ApiDataProvider and fetch USDCAD.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

Stop the download and saving of bad responses from web api to zip files

#### Related Issue

Closes #4556
Related #4994

#### Motivation and Context

Using ApiDataProvider will create files even if the API response is not actually data. This fix seeks to stop the creation of these files since Lean will then load in corrupted data causing more problems down the line.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

Tested using the example in issue #4994

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Api/Api.cs [hunk 1]
```diff
@@ -814,8 +815,17 @@ public bool DownloadData(Symbol symbol, Resolution resolution, DateTime date)
...
             var client  = new RestClient(uri.Scheme + "://" + uri.Host);
             var request = new RestRequest(uri.PathAndQuery, Method.GET);
-            client.DownloadData(request).SaveAs(path);
 
+            // If the response is not a zip then it is not data, don't write it.
+            var response = client.Execute(request);
+            if (response.ContentType != "application/zip")
+            {
+                var message = JObject.Parse(response.Content)["message"].Value<string>();
+                Log.Trace($"Api.DownloadData(): Failed to download zip for {symbol} {resolution} data for date {date}, Api response: {message}");
```
Comment (Martin-Molinero) [inline Api/Api.cs:824]: Let's make this an Error log 👍

**Review by Martin-Molinero — APPROVED** [review]
