### PR TITLE
MaximumOrderQuantity Bug Fix

### LINKED ISSUE #5687: GetMaximumOrderQuantityForTargetBuyingPower Calculates Incorrect Quantity for Edge Cases
#### Expected Behavior
The calculated order quantity represents a weight that is equal to or less than the target.

#### Actual Behavior
In some edge cases, the weight is slightly higher. 

#### Potential Solution
Review the calculations. I would suggest factoring in the quantity holding only at the end.

#### Reproducing the Problem
```csharp
public void SetHoldings_LongerToLong_HighConstantFeeStructure(decimal leverage)
{
    Security msft;
    var algo = GetAlgorithm(out msft, leverage, 10000);
    //Set price to $25
    Update(msft, 25);
    //75% cash spent on 3000 MSFT shares.
    algo.Portfolio.SetCash(25000);
    algo.Portfolio[Symbols.MSFT].SetHoldings(25, 3000);
    var actual = algo.CalculateOrderQuantity(Symbols.MSFT, 0.5m);
    // TPV =  Cash + Holdings  - Fees  - Buffer => Target = TVP * 0.5
    // TPV = 25000 + 25 * 3000 - 10000 - 250 = 89750 => 89750 * 0.5 = 44875
    // Final Quantity = Target / Unit - Holdings Quantity
    // Final Quantity = 44875 / 25 - 3000 = 1795.0 - 3000 = -1205
    Assert.AreEqual(-1204m, actual);
    // 3000 - 1204 = 1796. Multiply by unit 1796 * 25 = 44900. Weight = 44900 / 89750 (TPV) = 0.50027855 > 0.5
    Assert.IsTrue(HasSufficientBuyingPowerForOrder(actual, msft, algo));
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

- Fix issue where resulting order quantity would place us higher than the target holding percentage
- Address order adjustment rounding problem

Note this is a "lighter" refactor version of the changes in #5702 that doesn't completely rewrite the function.  It aims to alleviate the issues in a similar way without a complete refactor. Those changes are still valid, and maybe in the future could be used as a refactor guideline as it is a bit more concise than this version.

#### Related Issue

Closes #5687 

#### Motivation and Context

This bug was a interesting one, basically with the previous implementation it was possible to get values out of BuyingPowerModel.GetMaximumOrderQuantityForTargetBuyingPower() that would actually put us over our target holding percentage. This is because once we got our order margin and target margin set we would not consider the total holdings or whether the order was positive/negative for adjustments. 

For a specific definition of satisfying our portfolio target:

TargetHoldingsMargin => Amount in dollars the target holdings will cost -> TargetHoldings * UnitMargin
TargetMarginAllocated => Amount of portfolio dollars dedicated to this holding -> Target Percentage * (TotalPortfolioValue - RequiredFreeBuyingPower)

    ✅ TargetHoldingsMargin <= TargetMarginAllocated 
    
    Target holdings MUST be less than portfolio target, these values are absolutes so even if we have a short TargetMarginAllocated of -970, we require the TargetHoldingsMargin to be > -970.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

All unit tests are passing, those that needed adjustments were verified

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Securities/BuyingPowerModelTests.cs [hunk 1]
```diff
@@ -0,0 +1,34 @@
+using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+using NUnit.Framework;
+using QuantConnect.Orders;
+using QuantConnect.Securities;
```
Comment (Martin-Molinero) [inline Tests/Common/Securities/BuyingPowerModelTests.cs:8]: nit - missing license and unrequired imports

`class BuyingPowerModelTests` -> `public class BuyingPowerModelTests`, missing testFixture

File: Tests/Common/Securities/BuyingPowerModelTests.cs [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+{
+    class BuyingPowerModelTests
+    {
+        // The only instance in which this function is used is when
+        // (Math.Abs(currentOrderMargin) > Math.Abs(targetMargin))
+        [TestCase(-1000, -900, 25)]
+        [TestCase(-900, -880, 25)]
+        [TestCase(1200, 1050, 25)]
+        [TestCase(1225, 1212, 25)]
+        public void OrderAdjustmentCalculation(decimal currentOrderMargin, decimal targetMargin, decimal perUnitMargin)
```
Comment (Martin-Molinero) [inline Tests/Common/Securities/BuyingPowerModelTests.cs:20]: Cool! Let's add a few more cases/asserts
- Where `currentOrderMargin` is less than `targetMargin`
- Where current and/or target margin/ perUnitMargin aren't already rounded values of the lot size, could even play with the lot size value
- Let's assert the resulting order quantity too, so it's explicit

File: Common/Securities/BuyingPowerModel.cs [hunk 3]
```diff
@@ -418,24 +415,19 @@ public virtual GetMaximumOrderQuantityResult GetMaximumOrderQuantityForTargetBuy
...
             }
 
-            var loopCount = 0;
-            // Just in case...
-            var lastOrderQuantity = 0m;
+            // Use the following loop to converge on a value that places us under our target allocation when adjusted for fees
+            var lastOrderQuantity = 0m;     // For safety check
+
+            var targetHoldingsMargin = ((direction == OrderDirection.Sell ? -1 : 1) * orderQuantity + parameters.Security.Holdings.Quantity) * absUnitMargin;
+            decimal orderMargin = orderQuantity * absUnitMargin;
```
Comment (Martin-Molinero) [inline Common/Securities/BuyingPowerModel.cs:422]: `targetHoldingsMargin` -> let's add `signed`
`orderMargin` -> let's add `abs`

**Review by Martin-Molinero — COMMENTED** [review]
Cool! Almost there 😃

File: Tests/Common/Securities/BuyingPowerModelTests.cs [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+        [TestCase(-35, 25, -900,1, -36)]   	    // -875
+        [TestCase(-34, 25, -880, 1, -35)]       // -850
+        [TestCase(48, 25, 1050, 1,42)]    	    // 1200
+        [TestCase(49, 25, 1212, 1,  48)]   	    // 1225
+        [TestCase(44, 25, 1200, 1, 48)]    	    // 1100
+        [TestCase(45, 25, 1250,1, 50)]    	    // 1125
+        [TestCase(80, 25, -1250, 1, -50)]       // 2000
+        [TestCase(45.5, 25, 1240, 0.5, 49.5)]   // 1125
+        [TestCase(45.75, 25, 1285, 0.25, 51.25)]// 1125
+        public void OrderAdjustmentCalculation(decimal currentOrderSize, decimal perUnitMargin, decimal targetMargin, decimal lotSize, decimal expectedOrderSize)
```
Comment (Martin-Molinero) [inline Tests/Common/Securities/BuyingPowerModelTests.cs:37]: I think missing cases where `currentOrderSize` < 0 & `targetMargin > 0`?

**Review by Martin-Molinero — APPROVED** [review]
Legit 🍏
Just minor request for a couple more test cases
