### PR TITLE
`Portfolio.UnsettledCashBook` update when quote currency is not the account currency

### LINKED ISSUE #6859: `Portfolio.UnsettledCashBook` is not updated when using `AccountCurrency` different from USD
#### Expected Behavior

LEAN updates the `UnsettledCashBook` regardless of the chosen `AccountCurrency`.

#### Actual Behavior

The `UnsettledCashBook` remains unchanged when using an `AccountCurrency` other than USD. 

#### Reproducing the Problem

Run [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_b74e91ec7b79c1673f012ce4da09a3ab.html) and view the log file. 

Excerpt of the log file:
```
2022-09-30 10:00:00 OrderEvent:
Time: 09/30/2022 14:00:00 OrderID: 3 EventID: 2 Symbol: TLT Status: Filled Quantity: -15 FillQuantity: -15 FillPrice: 103.3591 USD OrderFee: 1 USD

2022-09-30 10:00:00 OrderEvent:
Time: 09/30/2022 14:00:00 OrderID: 4 EventID: 2 Symbol: SPY Status: Filled Quantity: -3 FillQuantity: -3 FillPrice: 361.42 USD OrderFee: 1 USD

2022-09-30 10:00:00 CashBook:
Symbol      Quantity    Conversion = Value in AUD
USD: $      -61185.23 @     1.5434 = $-94431.13
AUD: $      100000.00 @       1.00 = $100000.0
-------------------------------------------------
CashBook Total Value:                $5568.87


2022-09-30 10:00:00 Unsettled CashBook:
Symbol      Quantity    Conversion = Value in AUD
AUD: $           0.00 @       1.00 = $0.0
-------------------------------------------------
CashBook Total Value:                $0.0
```

After the two order events, I would have expected an unsettled cash amount of ~2,600 USD. In fact, the USD currency is not even listed as part of the unsettled cash book. 

Note, it might not be related to the USD currency in particular, but rather to the fact that the account currency is not the same as the quote currency of the security.

#### System Information

QC Cloud

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

Hold securities quote currency cash instances in `Portfolio.UnsettledCashBook` to track unsettled cash amounts with currencies different thant the account currency.

#### Related Issue

Closes #6859 

#### Motivation and Context

When selling assets with currencies different than the account one, the unsettled cash amount was not being added to the unsettled cash book because there was no entry for currencies other than the account one.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

- Unit tests
- Regression algorithm

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Securities/SecurityPortfolioManager.cs [hunk 1]
```diff
@@ -96,7 +96,23 @@ public SecurityPortfolioManager(SecurityManager securityManager, SecurityTransac
...
-            CashBook.Updated += (sender, args) => InvalidateTotalPortfolioValue();
+            CashBook.Updated += (sender, args) =>
+            {
+                if (args.UpdateType == CashBook.UpdateType.Added)
+                {
+                    // add the same currency entry to the unsettled cashbook as well
+                    UnsettledCashBook.Add(args.Cash.Symbol, new Cash(args.Cash.Symbol, 0, args.Cash.ConversionRate));
+                }
+                // if updated, let's keep track of conversion rate changes
+                else if (args.UpdateType == CashBook.UpdateType.Updated &&
```
Comment (Martin-Molinero) [inline Common/Securities/SecurityPortfolioManager.cs:107]: > CashBook.UpdateType

Think we can take advantage we are changing these files to rename the enum to `CashUpdateType` and push it to Global.cs, think we would be able to get rid off the `using static` too

> // if updated, let's keep track of conversion rate changes

Nice catch! This is an interesting bug. If the cash instances shared the same `CurrencyConversion` instance I think we would be able to get around the need for this. We would need to push `_conversionRateNeedsUpdate` into `ICurrencyConversion` implementation though

**Review by Martin-Molinero — APPROVED** [review]
Thanks!
