### PR TITLE
Loader Support Full Algorithm Name

### LINKED ISSUE #5465: BrokerageSetupHandler fails when user FullName of algorithm
#### Expected Behavior

No error, should create algorithm instance by using either
- `FullName`, i.e. QuantConnect.Algorithm.CSharp.BasicTemplateAlgorithm
- `Name`, i.e. BasicTemplateAlgorithm

#### Actual Behavior

`BrokerageSetupHandler` throws exception

image

#### Potential Solution

`Loader` uses `SingleOrAlgorithmTypeName` extension method to find algorithm, but put `.` in the start of search string, that cause the issue

image

#### Reproducing the Problem

Use algorithm `FullName` to run Launcher

#### System Information

N\A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

Loader extension function was unable to load algorithm by full name, this PR remedies it by not including adding a dot before the name.

#### Related Issue

Closes #5465

#### Motivation and Context

Loader should be able to use the full algorithm name.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

Loader tests are still passing, also included an addition test case where we use the full algorithm name.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by Martin-Molinero — APPROVED** [review]

File: Common/Extensions.cs [hunk 1]
```diff
@@ -1764,16 +1764,21 @@ public static string GetStringBetweenChars(this string value, char left, char ri
...
-            // if there's more than one then find which one we should use using the algorithmTypeName specified
-            return names.Count == 1 ? names.Single() : names.SingleOrDefault(x => x.EndsWith("." + algorithmTypeName));
+            // If there's only one name use that guy
+            if (names.Count == 1) { return names.Single(); }
+
+            // If we have multiple names we need to search the names based on the given algorithmTypeName
+            // If the given name already contains dots (fully named) use it as it is
+            // otherwise add a dot to the beginning to avoid matching any subsets of other names
+            var searchName = algorithmTypeName.Contains(".") ? algorithmTypeName : "." + algorithmTypeName;
+            return names.SingleOrDefault(x => x.EndsWith(searchName));
```
Comment (Martin-Molinero) [inline Common/Extensions.cs:1781]: Cool!
