### PR TITLE
RoundDown fix for PeriodCountConsolidatorBase

### LINKED ISSUE #4915: Extensions.RoundDown for DateTime Unexpected Result
#### Expected Behavior
Round down `20190101` should result in `20181202`

#### Actual Behavior
Round down `20190101` results in `20181212`

#### Potential Solution
N/A

#### Reproducing the Problem
```csharp
[Test]
public void DateTimeRoundDownThirtyDays()
{
    var date = new DateTime(2019, 01, 01);
    var expected = date.Add(-TimeSpan.FromDays(30));
    var rounded = date.RoundDown(TimeSpan.FromDays(30));
    Assert.AreEqual(expected, rounded);
}
```
also
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class BasicTemplateAlgorithm : QCAlgorithm {
        public override void Initialize()  {
            SetStartDate(2019, 1, 1);

            AddEquity("SPY", Resolution.Daily);
            var c = new TradeBarConsolidator(TimeSpan.FromDays(30));
            c.DataConsolidated += OnDataConsolidated;
            SubscriptionManager.AddConsolidator("SPY", c);
        }

        public void OnDataConsolidated(object sender, TradeBar bar) {
            Log("Bar StartTime: " + bar.Time + ", EndTime: " + bar.EndTime);
        }
    }
}
```
the logs show:
```
2019-01-14 09:31:00 Bar StartTime: 12/13/2018 12:00:00 AM, EndTime: 1/12/2019 12:00:00 AM
2019-02-11 09:31:00 Bar StartTime: 1/12/2019 12:00:00 AM, EndTime: 2/11/2019 12:00:00 AM
2019-03-13 09:31:00 Bar StartTime: 2/11/2019 12:00:00 AM, EndTime: 3/13/2019 12:00:00 AM
2019-04-12 09:31:00 Bar StartTime: 3/13/2019 12:00:00 AM, EndTime: 4/12/2019 12:00:00 AM
2019-05-13 09:31:00 Bar StartTime: 4/12/2019 12:00:00 AM, EndTime: 5/12/2019 12:00:00 AM
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

- Add remarks to RoundDown and RoundUp regarding timespans larger than a day
- Modify behavior of `PeriodCountConsolidatorBase` classes to still accept timespans greater than 1 day but make bars generate off of initialization time instead of skewed RoundDown schedule; see #4915 

#### Related Issue

Closes #4915 

#### Motivation and Context

Weird behavior using RoundDown on timespans greater than a day. It is related to the rounding method used creating a rounded schedule for *ALL* time. This creates weird behavior on consolidators bar time ranges. See #4915 

#### Requires Documentation Change

I don't believe this was intend for this use initially but if there is any documentation regarding using timespans greater than a day with any consolidator construction such as `TradeBarConsolidator(TimeSpan.FromDays(30));` it should be updated to reflect the new behavior.

In an example: 
`TradeBarConsolidator(TimeSpan.FromDays(30));`
- My bars will be every 30 days from when consolidator is initialized
- Lets say my consolidator is created during init at 2/14 so,
Bars:
2/14 -3/15
3/15 - 4/14
etc

#### How Has This Been Tested?

Tests added to cover case of 30 days. Red/green light from master to this branch

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Data/PeriodCountConsolidatorTests.cs [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+ *
+*/
+
+using System;
+using NUnit.Framework;
+using QuantConnect.Data.Consolidators;
+using QuantConnect.Data.Market;
+using QuantConnect.Indicators;
+
+
```
Comment (Martin-Molinero) [inline Tests/Common/Data/PeriodCountConsolidatorTests.cs:23]: nit - `using QuantConnect.Indicators;` is unused, extra new line
Let's make `PeriodCountConsolidatorTests` public, think we can also add `Parallelizable(ParallelScope.All)`

**Review by Martin-Molinero — APPROVED** [review]
Nice! minor comments in the added tests

**Review by jaredbroad — APPROVED** [review]
