### PR TITLE
Makes SEC Downloader Check Actual File Size For Robustness

### LINKED ISSUE #3509: SEC Downlaoder fails silently
#### Expected Behavior

SEC Downloader should download all files reliable.

#### Actual Behavior

There was a case in which a file was downloaded as correct, but it was incomplete. 

#### Potential Solution

Checking MD5 and/or file sizes, if SEC provides that data.

#### Reproducing the Problem

Is not deterministic.

#### System Information

Linux.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by gsalaz98**
#### Description

Adds checks for file size before downloading the data so that we can retry in the case of corrupted data
#### Related Issue

Closes #3509 
#### Motivation and Context

Stability
#### Requires Documentation Change

No
#### How Has This Been Tested?

Local testing; unable to force a corrupted download, but in the case of the files not matching up within +- 1% bounds of SEC's stated file size, we attempt to re-download the data
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: ToolBox/SECDataDownloader/SECDataDownloader.cs [hunk 1]
```diff
@@ -89,6 +124,17 @@ public void Download(string rawDestination, DateTime start, DateTime end)
                             Log.Trace($"SECDataDownloader.Download(): Downloading temp filing archive to: {tmpFile}");
                             client.DownloadFile($"{BaseUrl}/Feed/{currentDate.Year}/{quarter}/{currentDate:yyyyMMdd}.nc.tar.gz", tmpFile);
 
+                            var tmpFileStat = new FileInfo(tmpFile);
+                            var tmpFileSizeInKB = tmpFileStat.Length / 1024;
+
+                            // Have max and low be +-1% of the stated file size
+                            if (tmpFileSizeInKB > fileSizeInKB + (fileSizeInKB * 0.01m) || tmpFileSizeInKB < fileSizeInKB - (fileSizeInKB * 0.01m))
```
Comment (Jay-Jay-D) [inline ToolBox/SECDataDownloader/SECDataDownloader.cs]: why the 1% buffer?

Comment (gsalaz98) [reply ToolBox/SECDataDownloader/SECDataDownloader.cs]: Stated file size might be a little skewed. I've observed a few files being 1-5kb larger or smaller from the file explorer. I figured 1% is small enough to be a reasonable lower and upper bound to allow room for flexibility and not have it fail if it's not exactly the same amount of KB as SEC says they are
