### PR TITLE
Fixes IndicatorBase.Update Method Time-stamping

### LINKED ISSUE #4271: Timestamp Mismatch Between Indicators of Different Type
#### Expected Behavior
Indicators of different type should have the same timestamp in `Current` property that matches the input `EndTime`

#### Actual Behavior
Indicators that implement `BarIndicator` and `TradeBarIndicator` have a 1-period lag.

#### Potential Solution
Use `input.EndTime` instead of `input.Time` in `IndicatorBase.Update` method.

#### Reproducing the Problem
```csharp
        [Test]
        public void IndicatorsOfDifferentTypeDiplaySameCurrentTime() {
            var algorithm = new QCAlgorithm();
            algorithm.SubscriptionManager.SetDataManager(new DataManagerStub(algorithm));
            var spy = algorithm.AddEquity("SPY");

            var indicatorTimeList = new List<DateTime>();
            // RSI is a DataPointIndicator
            algorithm.RSI(spy.Symbol, 14).Updated += (_, e) => indicatorTimeList.Add(e.EndTime);
            // STO is a BarIndicator
            algorithm.STO(spy.Symbol, 14, 2, 2).Updated += (_, e) => indicatorTimeList.Add(e.EndTime);
            // MFI is a TradeBarIndicator
            algorithm.MFI(spy.Symbol, 14).Updated += (_, e) => indicatorTimeList.Add(e.EndTime);

            var consolidators = spy.Subscriptions.SelectMany(x => x.Consolidators).ToList();
            Assert.AreEqual(3, consolidators.Count);   // One consolidator for each indicator

            var bars = new[] { 30, 31 }.Select(d =>
                new TradeBar(new DateTime(2020, 03, 04, 9, d, 0),
                             spy.Symbol, 100, 100, 100, 100, 1000));

            foreach (var bar in bars) {
                foreach (var consolidator in consolidators) {
                    consolidator.Update(bar);
                }
            }

            // All indicators should have the same EndTime
            Assert.AreEqual(1, indicatorTimeList.Distinct().Count());
        }
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
`IndicatorBase.Update` use `input.EndTime` instead of `input.Time` so that `input.Current.Time` (and `EndTime`) matches the `input.EndTime` and achieve consistent behavior across different indicator types (`IndicatorDataPoint`, `IBaseDataBar` and `TradeBar`)

#### Related Issue
Closes #4271

#### Motivation and Context
Bug fix.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Unit test.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Indicators/IndicatorBase.cs [hunk 1]
```diff
@@ -76,10 +75,10 @@ protected IndicatorBase(string name)
         /// <returns>True if this indicator is ready, false otherwise</returns>
         public bool Update(IBaseData input)
         {
-            if (_previousInput != null && input.Time < _previousInput.Time)
+            if (_previousInput != null && input.EndTime < _previousInput.EndTime)
```
Comment (jaredbroad) [inline Indicators/IndicatorBase.cs:78]: 💥
