### PR TITLE
Fix Forex/Crypto zero conversion rates during warm up

### LINKED ISSUE #1833: Forex/Crypto conversion rates are zero during warm up
#### Expected Behavior
Forex/Crypto conversion rates should be nonzero during warm up.

#### Actual Behavior
Conversion rates for currencies in the cashbook are zero until the end of warm up.

#### Potential Solution
`CashBook.EnsureCurrencyDataFeeds` should be called before the `AlgorithmManager` loop.

#### Reproducing the Problem
This algorithm outputs zero conversion rates during warm up:
``` C#
    public class TestConversionRatesDuringWarmup : QCAlgorithm
    {
        public override void Initialize()
        {
            SetStartDate(2018, 3, 1);  //Set Start Date
            SetEndDate(2018, 3, 1);    //Set End Date
            SetCash(10000);
            SetWarmUp(5);
            AddCrypto("BTCUSD", Resolution.Hour);
        }

        public override void OnData(Slice data)
        {
            Log($"BTC current price: {Securities["BTCUSD"].Price}");
            Log($"BTC conversion rate: {Portfolio.CashBook["BTC"].ConversionRate}");
        }
    }
```

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
In `AlgorithmManager.Run`, we now call `CashBook.EnsureCurrencyFeeds` before the loop, so all required internal feeds are added (needed by securities added with `AddSecurity` or currencies added with `SetCash`).

#### Related Issue
Fixes #1833

#### Motivation and Context
Conversion rates are zero during warmup, so any function internally calling `CashBook.Convert` throws this error: _"The conversion rate for XYZ is unavailable"_
This error check was added recently (#1815) to validate conversion rates before using them.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
The example algorithm in #1833 was verified both with `BTCUSD` and `EURUSD`.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/ect)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/AlgorithmManager.cs [hunk 1]
```diff
@@ -201,6 +202,16 @@ public void Run(AlgorithmNodePacket job, IAlgorithm algorithm, IDataFeed feed, I
                 }
             }
 
+            // add internal feeds for currencies added during initialization
+            var addedSecurities = algorithm.Portfolio.CashBook.EnsureCurrencyDataFeeds(algorithm.Securities, algorithm.SubscriptionManager,
+                MarketHoursDatabase.FromDataFolder(), SymbolPropertiesDatabase.FromDataFolder(),
+                DefaultBrokerageModel.DefaultMarketMap, SecurityChanges.None);
+            foreach (var security in addedSecurities)
```
Comment (mchandschuh) [inline Engine/AlgorithmManager.cs]: For posterity:

We can do it this way, but it just feels like the wrong way to get these subscriptions into the data feed. My original suggestion was added of these securities is a setup handler concern and not an algorithm manager concern. Another thought was to use the universe system to ensure these subscriptions exist within a universe -- but that can be a later refactor.
