### PR TITLE
QB Set Start Date Relative to Data Release

### LINKED ISSUE #4892: Research default Time
#### Expected Behavior

- Research history request of the last 6 bars returns yesterdays data
#### Actual Behavior

- Research default Time is yesterday `0:00` so it returns data of the prev day
#### Potential Solution

- If it's after 9am NY, we could set the Time to today 0:00
#### Reproducing the Problem

on the 28/10:
image

#### System Information
QC cloud
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

Set QuantBook start date to appropriate day relative to data release times

#### Related Issue

Closes #4892 

#### Motivation and Context

Fixes the issue described in #4892 where when starting a QB the StartDate is set to yesterday causing history requests to not reply with the most recent history.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

Local QBs to prove Algorithm time is as expected. Test was run ~5:30 10/28

Before:
image

After:
image

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Research/QuantBook.cs [hunk 1]
```diff
@@ -95,8 +95,21 @@ public QuantBook() : base()
...
+                var hourThreshold = Config.GetInt("qb-data-hour", 9);
+                
+                // If it is after our hour threshold; then we can use today 
+                if (newYorkTime.Hour >= hourThreshold)
+                {
+                    SetStartDate(newYorkTime);
+                }
+                else
+                {
+                    SetStartDate(newYorkTime - TimeSpan.FromDays(1));
```
Comment (Martin-Molinero) [inline Research/QuantBook.cs:110]: Thanks! I think it would be clearer if we kept existing behavior in this `else`, using `EndDate` -> `SetStartDate(EndDate);` but for the `if` above I think we should also set the end date to `newYorkTime`? We might want to double check what are the resulting dates being set for them

Comment (C-SELLERS) [reply Research/QuantBook.cs:110]: EndDate is set by base (`QCAlgorithm`) to `DateTime.Now.AddDays(-1)`; 

In the case of EndDate being -1 days from StartDate it doesn't cause any problems with History requests. I think this would only be an issue in the case of QB running as an Algorithm. 

In the `else` statement if we use EndDate it is possible for a user in UTC + 12 (with default 9AM hour threshold) to pass the first `if` and still set the date to same value. I figure this way we cover the edge case and never make requests for data that is not available yet.

Comment (C-SELLERS) [reply Research/QuantBook.cs:110]: I just checked setting `EndDate` to newYorkTime, but it actually has a verification check that stops anything greater than yesterday being set :/

```
            if (end > DateTime.Now.Date.AddDays(-1))
            {
                end = DateTime.Now.Date.AddDays(-1);
            }
```

So we won't be able to change it to the current day.

Comment (Martin-Molinero) [reply Research/QuantBook.cs:110]: Makes sense thank you, let's create a separate issue to fix the end date being off from the algorithm timezone

**Review by Martin-Molinero — APPROVED** [review]

**Review by jaredbroad — APPROVED** [review]
