### PR TITLE
Local Object Store Refactor and Fixes

### LINKED ISSUE #4811: LocalObjectStore.GetFilePath Rewrites Existing File With New Name
#### Expected Behavior
No file with duplicated information is created.

#### Actual Behavior
`LocalObjectStore.GetFilePath` creates a new file with information found in files loaded in `LocalObjectStore.Initialize`

#### Potential Solution
N/A

#### Reproducing the Problem
```python
import os
qb = QuantBook()

for i in range(2):
    qb.ObjectStore.Save(f'{chr(i+97)}.txt', f'{i}'*100)

keys = [str(j).split(',')[0][1:] for _, j in enumerate(qb.ObjectStore.GetEnumerator())]
sizes = [os.path.getsize(qb.ObjectStore.GetFilePath(key)) for key in keys]
for i in keys:
    path = qb.ObjectStore.GetFilePath(i)
    print(f"{i} - {path} - {os.path.getsize(path)/1e6:.1f} MB")
    print(f'Deleted? {qb.ObjectStore.Delete(i)}')
print(f"Total size: {sum(sizes)/1e6:.1f} MB in {len(sizes)} files")
```
Run this notebook once, the comment out lines 4 and 5, and run it again. We can see that there are more files in every new cell execution.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

- Refactor LocalObjectStore to no longer use temp copies of an object in `GetFilePath`, instead use the local copy, this fixes issue #4811.
- `GetFilePath` persists data before giving the requester the path.
- Fix for control checks to save data, logic was broken as it never counted the new data being added.
- Store data using conversion of keys to Base64 to handle odd key strings in path. The only limitation in chars in the key string is having '?' in the key. In a spot divisible by 3 this will cause Base64 to output '/' which is the only breaking case.
- New tests to prove behaviour

#### Related Issue

Closes #4811 

#### Motivation and Context

`LocalObjectStore`'s `GetFilePath` currently writes a copy of a requested object to a file in the ObjectStore's storage directory and returns this copies path; this works fine until you start Lean again and the copy is loaded into the LocalObjectStore as its own object.

To resolve this I have dropped the use of temp files altogether and will only store one file for each object, now when the user calls `GetFilePath` we ensure the data is written to storage and then return a path to it . This way there are no duplicates, the file is still retained and we can ensure the data in the file is up to date when requested.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

All regressions ran and passed, LocalObjectStore tests all pass, Travis tests pass in docker

Verified behaviour in Issue #4811 does not occur

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by Martin-Molinero — APPROVED** [review]
Thanks for the tests! 👍

**Review by jaredbroad — CHANGES_REQUESTED** [review]
IMHO AddTick, Create Temp folders -- are warning signals for a quick fix hiding an underlying design issue. When we see that we should reflect on what the underlying cause and motivations that got us to this point were.

LocalObjectStore should likely just _return the local file path_ which would eliminate the creation of duplicates. Cloud concerns should be addressed separately.

File: Engine/Storage/LocalObjectStore.cs [hunk 1]
```diff
@@ -250,7 +265,7 @@ public bool Delete(string key)
 
                 try
                 {
-                    var path = GetFilePathForKey(key);
+                    var path = PathForKey(key);
                     if (File.Exists(path))
                     {
                         File.Delete(path);
```
Comment (Martin-Molinero) [inline Engine/Storage/LocalObjectStore.cs:271]: I think `PersistData()` should clear the directory before writing to disk and we can remove this delete from here?

File: Tests/Common/Storage/LocalObjectStoreTests.cs [hunk 2]
```diff
@@ -305,6 +315,72 @@ public void DisposeRemovesEmptyStorageFolder()
...
+                Assert.IsTrue(qb.ObjectStore.ContainsKey("a.txt"));
+
+                // Assert the store has only a.txt
+                var store = qb.ObjectStore.GetEnumerator().AsEnumerable().ToList();
+                Assert.IsTrue(store.Count == 1);
+                Assert.IsTrue(store[0].Key == "a.txt");
+
+                // Create a copy for use using GetFilePath, check that it exists
+                var path = qb.ObjectStore.GetFilePath("a.txt");
+                Assert.IsTrue(File.Exists(path));
```
Comment (Martin-Molinero) [inline Tests/Common/Storage/LocalObjectStoreTests.cs:357]: Nice tests! We should also add the 'Delete' case: We add a key that gets persisted and later we delete it. When we create a new object store it shouldn't re load it

File: Engine/Storage/LocalObjectStore.cs [hunk 3]
```diff
@@ -279,19 +294,23 @@ public bool Delete(string key)
         /// <returns>The path for the file</returns>
         public string GetFilePath(string key)
```
Comment (Martin-Molinero) [inline Engine/Storage/LocalObjectStore.cs:295]: Realized we need this guy to be virtual since its calling `PersistData()` now

File: Tests/Common/Storage/LocalObjectStoreTests.cs [hunk 4]
```diff
@@ -305,6 +321,108 @@ public void DisposeRemovesEmptyStorageFolder()
...
+            {
+                Assert.IsTrue(_store.SaveString($"{i}", $"{i}"));
+            }
+
+            // Write 1 more; should throw
+            Assert.IsFalse(_store.SaveString("breaker", "gotem"));
+        }
+
+        [Test]
+        public void DeletedObjectIsNotReloaded()
```
Comment (Martin-Molinero) [inline Tests/Common/Storage/LocalObjectStoreTests.cs:391]: Cool! 👍

**Review by Martin-Molinero — APPROVED** [review]
