### PR TITLE
Handle insufficient margin for option exercise

### LINKED ISSUE #7815: Expand Duplicate Option Exercise Error Message to Diagnose Issue
#### Expected Behavior
Error message for duplicate option exercise would include information to reproduce the very rare bug, like a stack trace or information about the data / price / values that led to the issue.

#### Actual Behavior
At the moment, it just says to contact support but since the bug can't be reproduced easily it's impossible to make progress on. 
Runtime Error: Duplicate option exercise order request for symbol XLK 121020P00036000. Please contact support in BacktestingBrokerage.cs:line 481. 

#### Potential Solution
Capture as much information as possible and log it all. 

#### System Information
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

Handling insufficient margin for automatic option exercise, which was causing the "Duplicated option assignment..." exception mentioned in the related issue #7815.

With these changes, simulated option exercises are handled using the `Brokerage.OptionNofication` event to create the option exercise order instead of going through the order processor, so that the margin check is bypassed and the order is placed and filled. After this, we expect a margin call like shown in the new regression algorithm `InsufficientBuyingPowerForAutomaticExerciseRegressionAlgorithm`.

Note: about algorithm's stats change (orders hash): since simulated options exercises are now handled like expired options exercise, without going throught the order processor to place them, some order properties are not populated, like `OrderSubmissionData` and `PriceCurrency`, but this should be taclked in a separate PR to keep this clean. 

#### Related Issue

Close #7815 

#### How Has This Been Tested?

Regression algorithm

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Brokerages/OptionNotificationEventArgs.cs [hunk 1]
```diff
@@ -44,12 +49,31 @@ public OptionNotificationEventArgs(Symbol symbol, decimal position)
...
+        /// <summary>
+        /// Initializes a new instance of the <see cref="OptionNotificationEventArgs"/> class
+        /// </summary>
+        /// <param name="symbol">The symbol</param>
+        /// <param name="position">The new option position</param>
+        /// <param name="tag">The tag to be used for the order</param>
+        public OptionNotificationEventArgs(Symbol symbol, decimal position, string tag)
+        {
+            Symbol = symbol;
+            Position = position;
```
Comment (Martin-Molinero) [inline Common/Brokerages/OptionNotificationEventArgs.cs:61]: Nit - we could call `base` to set these

**Review by Martin-Molinero — APPROVED** [review]
Nice work! 💪

**Review by Martin-Molinero — APPROVED** [review]
Thank you 👍
