### PR TITLE
Bug 3905 factor file.apply method removes the factor file first row

### LINKED ISSUE #3905: FactorFile.Apply method removes the factor file's first row
#### Expected Behavior

The `FactorFile.Apply` method should be able to add or update new events, without modifying the factor file structure.

#### Actual Behavior

When new events are added with the `Apply` method, the first row of the factor file is removed.

#### Potential Solution

Fix the logic when parsing `FactorFileRow` into events.

#### Reproducing the Problem

Add the following asserts:
```cs
Assert.True(actual.First().Date == new DateTime(1998, 01, 02),
                $"Factor file first row changed from 1998-01-02 to {actual.First().Date:yyyy-MM-dd} after applying new event");
```
to the [apply method tests](https://github.com/QuantConnect/Lean/blob/master/Tests/Common/Data/Auxiliary/FactorFileTests.cs#L198).

#### System Information

Windows 7

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Jay-Jay-D**
#### Description

This PR fixes the `FactorFile.Apply` method. Previously, it removed the first row of the `FactorFile` object after applying a new event.

Also the Apply method now can handle duplicated events.

Finally, This PR adds support for exponential notation in QuantQuote's factor files.

#### Related Issue

Closes #3905 

#### Motivation and Context

First row in factor file is important because the factor files are read backwards.

#### Requires Documentation Change

No.

#### How Has This Been Tested?

Add new assertion to existing tests and added new tests.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Data/Auxiliary/FactorFileTests.cs [hunk 1]
```diff
@@ -227,8 +325,8 @@ public void AppliesSplitAndDividendAtSameTime()
             var factorFile = new FactorFile("AAPL", expected.SortedFactorFileData.Where(kvp => kvp.Value.PriceFactor >= .8m).Select(kvp => kvp.Value));
             var actual = factorFile.Apply(new List<BaseData>
             {
-                new Split(Symbols.SPY, reference.AddDays(-364), 100m, 1 / 2m, SplitType.SplitOccurred),
-                new Dividend(Symbols.SPY, reference.AddDays(-364), 12.5m, 100m)
+                new Split(Symbols.AAPL, reference.AddDays(-364), 100m, 1 / 2m, SplitType.SplitOccurred),
+                new Dividend(Symbols.AAPL, reference.AddDays(-364), 12.5m, 100m)
```
Comment (jaredbroad) [inline Tests/Common/Data/Auxiliary/FactorFileTests.cs]: 👍  Nice catch.

File: Common/Data/Auxiliary/FactorFile.cs [hunk 2]
```diff
@@ -315,7 +315,16 @@ public FactorFile Apply(List<BaseData> data, SecurityExchangeHours exchangeHours
...
 
-            var combinedData = GetSplitsAndDividends(data[0].Symbol, exchangeHours).Concat(data)
+            var splitsAndDividends = GetSplitsAndDividends(data[0].Symbol, exchangeHours);
+
+            var combinedData = splitsAndDividends.Concat(data)
+                .DistinctBy(e =>
+                    {
+                        var asSplit = e as Split;
+                        var eventType = asSplit == null ? "Dividend" : "Split";
+                        return $"{e.Symbol.ID}{eventType}{e.Time.ToStringInvariant(DateFormat.EightCharacter)}{e.Value.SmartRounding().Normalize()}";
```
Comment (mchandschuh) [inline Common/Data/Auxiliary/FactorFile.cs]: Do we need the symbol id in this expression? Isn't everything the same symbol? We basically just want to remove duplicates, so I think something like `${e.GetType().Name}{e.Time.ToStringInvariant(DateFormat.EightCharacter)}"` should suffice

File: Common/Data/Auxiliary/FactorFileRow.cs [hunk 3]
```diff
@@ -113,29 +113,20 @@ public static IEnumerable<FactorFileRow> Read(string permtick, string market, ou
...
-            var hasInfEntry = false;
             factorFileMinimumDate = null;
 
             var rows = new List<FactorFileRow>();
 
             // parse factor file lines
             foreach (var line in lines)
             {
-                if (line.Contains("inf"))
+                if (line.Contains("inf") || line.Contains("e+"))
```
Comment (mchandschuh) [inline Common/Data/Auxiliary/FactorFileRow.cs]: Hmm, does the `e+` actually mean it's inf? I suppose by convention we don't serialize using scientific notation, but perhaps more correctly we could define inf as `"inf"` or anything larger than, for example, `1e6`. If we are going to say that _all_ scientific notation equates to inf, then we'll want to document this behavior somewhere since it's unexpected. For example, a value such as `1.23e+2` would be flagged unexpectedly as an inf value

File: Tests/Common/Data/Auxiliary/FactorFileTests.cs [hunk 4]
```diff
@@ -295,6 +393,9 @@ public void EmptyFactorFileReturnsEmptyListForSplitsAndDividends(string contents
             Assert.IsEmpty(factorFile.GetSplitsAndDividends(Symbols.SPY, SecurityExchangeHours.AlwaysOpen(TimeZones.NewYork)));
         }
 
+      
+
```
Comment (mchandschuh) [inline Tests/Common/Data/Auxiliary/FactorFileTests.cs]: The style of the project uses a single blank line between functions.

File: Common/Data/Auxiliary/FactorFileRow.cs (hunk 3 above)
Comment (Jay-Jay-D) [reply Common/Data/Auxiliary/FactorFileRow.cs]: Exponential notation is treated as `inf ` is because of the loss of precision. In all cases, the represented number is a round up to a few (and sometimes wrong) decimals, E.g., 1.6e+6 when the correct factor is  1562500. I'll add that as comment.

Worth notice that there are only 6 factor files with exponential notation, 10 cases with `inf`, and 2 cases where both cases are present.
