### PR TITLE
Fix generic Slice.Get to handle TradeBar and QuoteBar for the same symbol

### LINKED ISSUE #2849: Slice does not support both TradeBar and QuoteBar for the same symbol
#### Expected Behavior
With `Crypto`, `Future` and `Option` security types we have multiple tick types and can receive both a `TradeBar` and a `QuoteBar` in the same time step.
We should be able to access the `TradeBar` with `slice.Get<TradeBar>()` and the `QuoteBar` with `slice.Get<QuoteBar>()`.

#### Actual Behavior
Currently only the last data type is accessible with the `slice.Get<T>` method.
Since many `QCAlgorithms.History` overloads automatically request both `TradeBar` and `QuoteBar` types, depending on the data order one of the two data types is not accessible, resulting in empty history results (although the data is actually present in the `Slice` instance).

#### Potential Solution
The `Slice.SymbolData` class and its callers should be refactored to support accessing multiple types of data.

#### Reproducing the Problem
This unit test shows the issue:
``` C#
        [Test]
        public void AccessesTradeBarAndQuoteBarForSameSymbol()
        {
            var tradeBar = new TradeBar(DateTime.Now, Symbols.BTCUSD,
                3000, 3000, 3000, 3000, 100, Time.OneMinute);

            var quoteBar = new QuoteBar(DateTime.Now, Symbols.BTCUSD,
                    new Bar(3100, 3100, 3100, 3100), 0,
                    new Bar(3101, 3101, 3101, 3101), 0,
                    Time.OneMinute);

            var tradeBars = new TradeBars { { Symbols.BTCUSD, tradeBar } };
            var quoteBars = new QuoteBars { { Symbols.BTCUSD, quoteBar } };

            var slice = new Slice(DateTime.Now, new BaseData[] { tradeBar, quoteBar }, tradeBars, quoteBars, null, null, null, null, null, null, null);

            var tradeBarData = slice.Get<TradeBar>();
            Assert.AreEqual(1, tradeBarData.Count);

            var quoteBarData = slice.Get<QuoteBar>();
            Assert.AreEqual(1, quoteBarData.Count);

            slice = new Slice(DateTime.Now, new BaseData[] { tradeBar, quoteBar });

            tradeBarData = slice.Get<TradeBar>();
            Assert.AreEqual(1, tradeBarData.Count);

            quoteBarData = slice.Get<QuoteBar>();
            Assert.AreEqual(1, quoteBarData.Count);
        }
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
The generic `Slice.Get<T>` method has been updated to handle the case the inclusion of both `TradeBar` and `QuoteBar` for the same symbol

#### Related Issue
Closes #2849 

#### Motivation and Context
This method is called internally by some `QCAlgorithm.History` overloads and this issue was causing only one data type to be returned.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
New unit test + history regression tests

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Data/SliceTests.cs [hunk 1]
```diff
@@ -145,5 +145,36 @@ public void EnumeratorDoesNotThrowWithTicks()
...
+            var quoteBarData = slice.Get<QuoteBar>();
+            Assert.AreEqual(1, quoteBarData.Count);
+
+            slice = new Slice(DateTime.Now, new BaseData[] { tradeBar, quoteBar });
+
+            tradeBarData = slice.Get<TradeBar>();
+            Assert.AreEqual(1, tradeBarData.Count);
+
+            quoteBarData = slice.Get<QuoteBar>();
+            Assert.AreEqual(1, quoteBarData.Count);
```
Comment (Martin-Molinero) [inline Tests/Common/Data/SliceTests.cs]: Maybe it would be good to assert some of the values on the `tradeBarData` and `quoteBarData`, detecting they are the expected `tradeBar` and `quoteBar`
