### PR TITLE
Infer data type from configs in bar count history requests

### LINKED ISSUE #8343: Option universe multi-symbol history request resolution
#### Expected Behavior

Resolution should not be required to make a canonical option symbol list history request for option universe data. It should be Daily by default.

#### Actual Behavior

Explicitly passing `Resolution.Daily` is required for a multi-symbol `OptionUniverse` history request

#### Potential Solution

Check `QCAlgorithm.CreateBarCountHistoryRequests`: it's explicitly using `typeof(BaseData)` as the requested type instead of trying to resolve it from the config. The default resolution for `BaseData` is minute.

#### Reproducing the Problem

```python
self.set_start_date(2015, 12, 24)
self.set_end_date(2015, 12, 24)

goog = self.add_option("GOOG").symbol
spx = self.add_index_option("SPX").symbol

history1 = self.history([goog, spx], 1)
history2 = self.history([goog, spx], 1, Resolution.Daily)
```

`history1` will be empty but `history2` will not. 

#### System Information

Windows 11
QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

Infer data type from configs in bar count history requests: when requesting history for a list of symbols, the requested data type was assumed to be `BaseData` instead of infering or getting it from the matched/created subscripton data configurations.

#### Related Issue

Closes #8343 

#### How Has This Been Tested?

Unit tests

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Algorithm/AlgorithmHistoryTests.cs [hunk 1]
```diff
@@ -415,62 +415,135 @@ public void TimeSpanHistoryRequestIsCorrectlyBuilt(Resolution resolution, Langua
...
+                var spxDate = new DateTime(2021, 01, 12);
+
+                yield return new TestCaseData(Resolution.Daily, Language.CSharp, spxCanonicalOption, true, spxDate, null, true);
+                yield return new TestCaseData(Resolution.Daily, Language.Python, spxCanonicalOption, true, spxDate, null, true);
+                yield return new TestCaseData(null, Language.CSharp, spxCanonicalOption, true, spxDate, Resolution.Daily, true);
+                yield return new TestCaseData(null, Language.Python, spxCanonicalOption, true, spxDate, Resolution.Daily, true);
+                yield return new TestCaseData(Resolution.Daily, Language.CSharp, spxCanonicalOption, false, spxDate, null, true);
+                yield return new TestCaseData(Resolution.Daily, Language.Python, spxCanonicalOption, false, spxDate, null, true);
+                yield return new TestCaseData(null, Language.CSharp, spxCanonicalOption, false, spxDate, Resolution.Daily, true);
+                yield return new TestCaseData(null, Language.Python, spxCanonicalOption, false, spxDate, Resolution.Daily, true);
```
Comment (Martin-Molinero) [inline Tests/Algorithm/AlgorithmHistoryTests.cs:468]: Nice! 👍

**Review by Martin-Molinero — COMMENTED** [review]
Thank you 👍
