### PR TITLE
Fix IndicatorBase.Equal implementation 

### LINKED ISSUE #3835: Equal Indicators must be equal
#### Expected Behavior

Equal Indicators must be equal

#### Actual Behavior

Equal Indicators are not equal. Not even equal to itself.

#### Potential Solution

Fix bug in `Equal` override method for `BaseIndicator`.

https://github.com/QuantConnect/Lean/blob/b9fcddb60394c76586426a131fa6fa09d6073390/Indicators/IndicatorBase.cs#L177

#### Reproducing the Problem

```cs
[Test]
public void EqualIndicatorsAreEqual()
{
    var indicator1 = new SimpleMovingAverage(5);
    var indicator2 = new SimpleMovingAverage(5);
    Assert.True(indicator1.Equals(indicator2));
}

[Test]
public void IndicatorMustbeEqualToItself()
{
    var indicator1 = new SimpleMovingAverage(5);
    Assert.True(indicator1.Equals(indicator1));
}
```

#### System Information

Local Win7

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Jay-Jay-D**
#### Description

This PR fixes an issue with the overridden method `IndicatorBase.Equals`

#### Related Issue

Closes #3835

#### Motivation and Context

Objects must be equal to itself, at least :)

#### Requires Documentation Change

No.

#### How Has This Been Tested?

Added unit test.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Indicators/IndicatorBase.cs [hunk 1]
```diff
@@ -184,7 +185,13 @@ public override bool Equals(object obj)
             // solely relying on reference semantics (think hashset/dictionary impls)
 
             if (ReferenceEquals(obj, null)) return false;
-            if (obj.GetType().IsSubclassOf(typeof (IndicatorBase<>))) return ReferenceEquals(this, obj);
+            var type = obj.GetType();   
+            if (type.IsSubclassOf(typeof(IndicatorBase<IndicatorDataPoint>))||
+                type.IsSubclassOf(typeof(IndicatorBase<IBaseDataBar>)) ||
+                type.IsSubclassOf(typeof(IndicatorBase<TradeBar>)))
```
Comment (Martin-Molinero) [inline Indicators/IndicatorBase.cs]: Nice!
Wonder if it would be better to check for the generic interface, to support any `IndicatorBase<T>`, maybe something like https://stackoverflow.com/a/18233467?

File: Tests/Indicators/IndicatorTests.cs [hunk 2]
```diff
@@ -155,6 +156,34 @@ public void EqualsMethodShouldNotThrowExceptions()
             Assert.IsFalse(res);
         }
 
+        [Test]
+        public void IndicatorMustBeEqualToItself()
```
Comment (Martin-Molinero) [inline Tests/Indicators/IndicatorTests.cs]: Awesome unit test! 👍

File: Indicators/IndicatorBase.cs (hunk 1 above)
Comment (Jay-Jay-D) [reply Indicators/IndicatorBase.cs]: TBH, I'm not sure how to implement it for the generic `T`, that was the cause of the issue. 

Also, I'm not sue if it worth, this set of generics was taken from the `CommonIndicatorTests`, that is used for *all* indicators.
https://github.com/QuantConnect/Lean/blob/b8b89ab0b60e05dae10c6072e7f9ea1313b378de/Tests/Indicators/CommonIndicatorTests.cs#L49

On top of that, the test added covers more than 40 indicators.

Comment (Martin-Molinero) [reply Indicators/IndicatorBase.cs]: Actually something like this https://stackoverflow.com/a/457708 is what we would need, sorry for sending the wrong link, `IndicatorBase<T>` is a class, not an interface 🤦‍♂. I did a quick test and it seems to work correctly

Comment (Jay-Jay-D) [reply Indicators/IndicatorBase.cs]: Done!

File: Indicators/IndicatorBase.cs [hunk 3]
```diff
@@ -184,8 +185,18 @@ public override bool Equals(object obj)
...
             if (ReferenceEquals(obj, null)) return false;
-            if (obj.GetType().IsSubclassOf(typeof (IndicatorBase<>))) return ReferenceEquals(this, obj);
+            var type = obj.GetType();
 
+            while (type != null && type != typeof(object))
+            {
+                var cur = type.IsGenericType ? type.GetGenericTypeDefinition() : type;
+                if (typeof(IndicatorBase<>) == cur)
+                {
+                    return true;
```
Comment (Martin-Molinero) [inline Indicators/IndicatorBase.cs]: Shouldn't it compare references here?

Comment (Martin-Molinero) [reply Indicators/IndicatorBase.cs]: I think we need a small unit tests which tests it returns false correctly
