### PR TITLE
Bug 4031 Change data depending on configuration

### LINKED ISSUE #4031: Options added after Initialize with already existing equity
#### Expected Behavior

- Options added after Initialize with already existing equity are deterministic and work correctly.
#### Actual Behavior

- Options require raw data mode but by default, equities use adjusted data mode. When an option is added and the underlying equity has already been added to Lean, it will set the data mode to raw https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Universe.cs#L78 `ConfigureUnderlyingSecurity()`, but the data of the underlying might of already been all loaded by the workers so this change has no effect in the data itself.

#### Potential Solution

- Existing equity subscription should be removed/discarded and a new subscription should be added using the raw data mode
#### Reproducing the Problem

See AddRemoveOptionUniverseRegressionAlgorithm
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AdalyatNazirov**
#### Description

Precalculate Raw and Adjusted data for `FileSystemDataFeed`. Choose one of them on demand depending on configuration settings.

#### Related Issue

Closes #4031

#### Motivation and Context

Options require raw data mode but by default, equities use adjusted data mode. When an option is added and the underlying equity has already been added to Lean, it will set the data mode to raw but the data of the underlying might of already been all loaded by the workers so this change has no effect in the data itself.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

- Manual testing
- Unit tests
- Benchmarks. Algorithhms are run on Intel i5 6200u, 8GB RAM, SSD. Use all SPY minute resolution for both BasicTemplateBenchmark and EmptyMinute400EquityBenchmark (hardcoded data source `equity\usa\minute\spy`). Due to test requirements we also need to provide factor files for all Symbols, so I hardcoded SPY factor file too. Results are below

image

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/DataFeeds/SubscriptionUtils.cs [hunk 1]
```diff
@@ -82,9 +92,21 @@ public static class SubscriptionUtils
...
                         }
 
-                        var subscriptionData = SubscriptionData.Create(subscription.Configuration, exchangeHours,
-                            subscription.OffsetProvider, enumerator.Current);
+                        var data = enumerator.Current;
+
+                        if (enablePriceScale && data?.Time.Date > lastTradableDate)
+                        {
+                            lastTradableDate = data.Time.Date;
+                            currentScale = GetScaleFactor(factorFile, config.DataNormalizationMode, data.Time.Date);
```
Comment (Martin-Molinero) [inline Engine/DataFeeds/SubscriptionUtils.cs:100]: There's a race condition between this `config.DataNormalizationMode` and the internal to `                         SubscriptionData subscriptionData = SubscriptionData.Create`, think we should get the mode once

File: Engine/DataFeeds/SubscriptionData.cs [hunk 2]
```diff
@@ -72,6 +80,41 @@ public static SubscriptionData Create(SubscriptionDataConfig configuration, Secu
                 data.Time = data.Time.ExchangeRoundDownInTimeZone(configuration.Increment, exchangeHours, configuration.DataTimeZone, configuration.ExtendedMarketHours);
             }
 
+            if (factor.HasValue && (factor.Value != 1 || configuration.SumOfDividends != 0))
```
Comment (Martin-Molinero) [inline Engine/DataFeeds/SubscriptionData.cs:83]: Let's simplify this behavior so we only support for now going from Any data mode -> Raw and other cases throw invalid operation exception 👍

**Review by Martin-Molinero — CHANGES_REQUESTED** [review]
Another hard issue solved! Almost there, let's just simplify behavior for now to fix the related issue 👍

**Review by Martin-Molinero — APPROVED** [review]
