### PR TITLE
Ensure that PeriodCountConsolidatorBase classes only consolidate a single symbol

### LINKED ISSUE #3872: Consolidators should only consolidate for a single symbol
#### Expected Behavior
Consolidators should not allow consolidation for multiple symbols.  Seeing more than one symbol in a consolidator is most likely a bug in an algorithm.

#### Actual Behavior
Consolidators allow tick/quote/tradebar data with multiple symbols.

#### Potential Solution
The symbol in the data being consolidated could be checked against the first symbol seen by the consolidator.

I have a change that I will send shortly.

#### Reproducing the Problem
I have a change that I will send shortly.

#### System Information
macOS (but not really relevant)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by RohanTalip**
#### Description
Ensures that consolidators derived from the PeriodCountConsolidatorBase class should only consolidate for a single symbol.

#### Related Issue

Closes #3872.

#### Motivation and Context

Without this change it is possible to incorrectly use a consolidator with multiple symbols, which can end up with incorrect data in the consolidator.

#### Requires Documentation Change

Probably not.  The exception should be self-explanatory.

#### How Has This Been Tested?

Unit tests.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Data/Consolidators/PeriodCountConsolidatorBase.cs [hunk 1]
```diff
@@ -115,6 +117,15 @@ protected PeriodCountConsolidatorBase(Func<DateTime, CalendarInfo> func)
         /// <param name="data">The new data for the consolidator</param>
         public override void Update(T data)
         {
+            if (symbol == null)
+            {
+                symbol = data.Symbol;
+            }
+            else if (symbol != data.Symbol)
+            {
+                throw new Exception($"Previous consolidated symbol ({symbol}) is not the same as in the current data ({data.Symbol})");
```
Comment (Martin-Molinero) [inline Common/Data/Consolidators/PeriodCountConsolidatorBase.cs]: Maybe it would be more precise if instead of using `Exception` we used `InvalidOperationException`, what do you think?

File: Tests/Common/Data/TradeBarConsolidatorTests.cs [hunk 2]
```diff
@@ -194,6 +194,41 @@ public void ConsolidatesOHLCV()
             Assert.AreEqual(300L, consolidated.Volume);
         }
 
+        [Test]
+        public void DoesNotConsolidateDifferentSymbols()
```
Comment (Martin-Molinero) [inline Tests/Common/Data/TradeBarConsolidatorTests.cs]: Awesome unit tests 👍

File: Common/Data/Consolidators/PeriodCountConsolidatorBase.cs (hunk 1 above)
Comment (RohanTalip) [reply Common/Data/Consolidators/PeriodCountConsolidatorBase.cs]: Good suggestion.  Done.

File: Tests/Common/Data/TradeBarConsolidatorTests.cs (hunk 2 above)
Comment (RohanTalip) [reply Tests/Common/Data/TradeBarConsolidatorTests.cs]: Thanks 😄

**Comment by jaredbroad** [comment]
Thank you @RohanTalip!
