### PR TITLE
Fill forward data points until delisted date

### LINKED ISSUE #4872: FillForwardEnumerator wont FF data after delisted event reached
#### Expected Behavior

- FillForwardEnumerator should FF the data **until** it reaches the delisting date
#### Actual Behavior

- Once the FillForwardEnumerator gets the delisted event of the underlying enumerator, even if it's missing 10 months compared with the current/last real data point it will emit it right awat and wont FF more data after that.
#### Potential Solution

- Review and refactor.
#### Reproducing the Problem

- Add an option contract for which you don't have data around the delisting data. Log the FillForward bars coming in into the algorithm.
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AdalyatNazirov**
**Shoudn't be merged until https://github.com/QuantConnect/Lean/pull/4941 merged**

#### Description

Do not return `Delisting` immediatelly, pass this dp through FF code

#### Related Issue

Closes #4872  

#### Motivation and Context

FillForwardEnumerator should FF the data until it reaches the delisting date.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

- unit tests. 
Existing regression tests were modified, i.e. removed workaround to force delisting events. After this removing some stats were also affected because of shift in the time (start of Market day vs start of AAPL market hours)

**before**

**after**

- regression test (check that data ff'ed after specific date until it reaches expiration date)

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs [hunk 1]
```diff
@@ -1238,6 +1240,297 @@ public void FillsForwardDaylightSavingTime(DateTime reference)
             fillForwardEnumerator.Dispose();
         }
 
+        [TestCase(15)]
+        [TestCase(18)]
+        [TestCase(19)]
+        [TestCase(21)]
+        public void FillForwardUntilDelisted(int warningDay)
```
Comment (Jay-Jay-D) [inline Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs:1247]: Great test!

File: Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs [hunk 2]
```diff
@@ -1238,6 +1240,297 @@ public void FillsForwardDaylightSavingTime(DateTime reference)
...
+            Assert.IsTrue(fillForwardEnumerator.MoveNext());  // 2014.06.05
+            Assert.IsTrue(fillForwardEnumerator.MoveNext());  // 2014.06.06
+
+            var counter = 0;
+            while (fillForwardEnumerator.MoveNext())
+            {
+                Assert.NotNull(fillForwardEnumerator.Current);
+                Assert.AreEqual(
+                    fillForwardEnumerator.Current.DataType != MarketDataType.Auxiliary,
+                    fillForwardEnumerator.Current.IsFillForward || (intermediateDay != 0 && fillForwardEnumerator.Current.Time.Day == expiry.Day + intermediateDay));
```
Comment (Jay-Jay-D) [inline Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs:1333]: nit: This assertion is complex to understand, maybe we can split it?

File: Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs [hunk 3]
```diff
@@ -1238,6 +1240,297 @@ public void FillsForwardDaylightSavingTime(DateTime reference)
...
+                    fillForwardEnumerator.Current.DataType != MarketDataType.Auxiliary,
+                    fillForwardEnumerator.Current.IsFillForward || fillForwardEnumerator.Current.Time == data[3].Time);
+                if (fillForwardEnumerator.Current.IsFillForward)
+                {
+                    dateSet.Add(fillForwardEnumerator.Current.Time.Date);
+                }
+            }
+
+            Assert.AreEqual(
+                (int)(data.Last().EndTime - data[1].EndTime).TotalDays + 1,
```
Comment (Jay-Jay-D) [inline Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs:1442]: Is there a reason to get the difference in days from the second object in `data` and then add 1?

Why don't you simply get the difference using the first element (index 0)?

File: Algorithm.CSharp/FillForwardUntilExpiryRegressionAlgorithm.cs [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+        public override void OnEndOfAlgorithm()
+        {
+            if (_options.Count != _contracts.Length)
+            {
+                throw new Exception($"Options weren't setup properly. Expected: {_contracts.Length}");
+            }
+
+            foreach (var option in _options)
+            {
+                for (DateTime date = _realEndDate; date < option.Key.ID.Date; date = date.AddDays(1))
```
Comment (Jay-Jay-D) [inline Algorithm.CSharp/FillForwardUntilExpiryRegressionAlgorithm.cs:95]: Sexy!

**Review by Jay-Jay-D — APPROVED** [review]
Well done @AdalyatNazirov!

I left some minor comments and nit.

File: Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs (hunk 3 above)
Comment (AdalyatNazirov) [reply Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs:1442]: oh. it's all about interpretation :D
If I put `data[0]` or `data[1].Time` you can interpret that that we have doubled data in the start, but in fact we should receive Aux and not-Aux data on last date (because of minute resolution). But you are right, in both case output is the same.

File: Algorithm.CSharp/FillForwardUntilExpiryRegressionAlgorithm.cs [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+
+namespace QuantConnect.Algorithm.CSharp
+{
+    /// <summary>
+    /// Regression algorithm checks FillForwardEnumerator should FF the data until it reaches the delisting date
+    /// replicates GH issue https://github.com/QuantConnect/Lean/issues/4872
+    /// </summary>
+    public class FillForwardUntilExpiryRegressionAlgorithm : QCAlgorithm, IRegressionAlgorithmDefinition
+    {
+        private DateTime _realEndDate = new DateTime(2014, 06, 07);
```
Comment (Martin-Molinero) [inline Algorithm.CSharp/FillForwardUntilExpiryRegressionAlgorithm.cs:33]: The end date of the contracts is the 21th, can see it easily in the securities SID bellow, the last day data is available is the 20th, which should be the value of `_realEndDate`

File: Algorithm.CSharp/FillForwardUntilExpiryRegressionAlgorithm.cs [hunk 6]
```diff
@@ -0,0 +1,163 @@
...
+        {
+            foreach (var value in data.OptionChains.Values)
+            {
+                foreach (var contact in value.Contracts)
+                {
+                    BaseData bar;
+                    bar = value.QuoteBars.FirstOrDefault(s => s.Key.ID.Equals(contact.Key.ID)).Value;
+                    if (bar == null)
+                    {
+                        bar = value.TradeBars.FirstOrDefault(s => s.Key.ID.Equals(contact.Key.ID)).Value;
```
Comment (Martin-Molinero) [inline Algorithm.CSharp/FillForwardUntilExpiryRegressionAlgorithm.cs:68]: `TradeBars` & `QuoteBars` are dictionaries keyed by symbols, think it might be clearer using the dictionary methods than Linq here

**Review by Martin-Molinero — COMMENTED** [review]
Nice one! 👍 
Leaving minor comments, and let's please update the PR description regarding why did the  regressions algorithms change

File: Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs [hunk 7]
```diff
@@ -1761,6 +1980,186 @@ public void FillsForward2AMOfSundayST()
...
+
+            Assert.AreEqual(
+                (int)(data.Last().EndTime - data[1].EndTime).TotalDays,
+                counter);
+
+            fillForwardEnumerator.Dispose();
+        }
+
+        [Test]
+        public void FillForwardNotDelistingAuxiliary()
```
[the remark this answers is not in the document]
Comment (AdalyatNazirov) [reply Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs:2074]: good catch! nothing, I think it was created during rebase.

**Review by Martin-Molinero — APPROVED** [review]
