### PR TITLE
Fix Api connection null ref and UnzipData encoding

### LINKED ISSUE #3909: Fix null reference exception, support encoding in Compression.UnzipData
These two commits are pulled out of #1040 as they're a quick and easy review and should be merged regardless of that issue's final result.

#### Expected Behavior

* Null reference exceptions shouldn't be thrown when checking `result.Success`. This was happening when receiving an empty string as a response.
* Support specifying an `Encoding` in `Compression.UnzipData` which calls int `string.GetBytes(Encoding)`. This issue here was the `GetBytes` function defaults to `Encoding.ASCII` which is _almost_ never a good idea, unless you're absolutely positive the character set will be restricted to 7 bits.

#### Actual Behavior

Null refs abound and `GetBytes` assumes single byte characters, failed on unicode characters, which are valid keys of a dictionar (string is C# are UTF16, double wide)

#### Potential Solution

Check response for null and allow specifying `Encoding`

#### Reproducing the Problem

Visual inspection.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by mchandschuh**
#### Description

* Support encoding in Compression.UnzipData
* Prevent null ref and log unsuccessful api responses

#### Related Issue

Fixes #3909 

#### Motivation and Context

These changes were made as part of working on #1040 but are valuable in isolation, particularly the encoding change in compression.

#### Requires Documentation Change

No.

#### How Has This Been Tested?

Unit test added for compression change and manually tested `ApiConnection` changes.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Api/ApiConnection.cs [hunk 1]
```diff
@@ -109,11 +109,16 @@ public bool TryRequest<T>(RestRequest request, out T result)
                     return false;
                 }
 
+                if (!restsharpResponse.IsSuccessful)
+                {
+                    Log.Error($"ApiConnect.TryRequest(): Content: {restsharpResponse.Content}");
```
Comment (mchandschuh) [inline Api/ApiConnection.cs]: I'm not sure if we want this here, but it was pretty useful for debugging. How often are we expecting unsuccessful messages, and is there any reason we _shouldn't_ log those responses?

File: Api/ApiConnection.cs [hunk 2]
```diff
@@ -109,11 +109,16 @@ public bool TryRequest<T>(RestRequest request, out T result)
...
+                }
+
                 responseContent = restsharpResponse.Content;
                 result = JsonConvert.DeserializeObject<T>(responseContent);
-                if (!result.Success)
+
+                if (result == null || !result.Success)
```
Comment (StefanoRaggi) [inline Api/ApiConnection.cs]: Nice catch! 
I was seeing quite a few null refs on these API calls in syslogs 👍

File: Api/ApiConnection.cs (hunk 1 above)
Comment (StefanoRaggi) [reply Api/ApiConnection.cs]: This error condition shouldn't be too frequent since exceptions should already be caught on L107,
agree with logging the error here.

File: Compression/Compression.cs [hunk 3]
```diff
@@ -192,8 +192,9 @@ public static bool ZipCreateAppendData(string path, string entry, string data)
         /// Uncompress zip data byte array into a dictionary string array of filename-contents.
         /// </summary>
         /// <param name="zipData">Byte data array of zip compressed information</param>
+        /// <param name="encoding">Specifies the encoding used to read the bytes. If not specified, defaults to ASCII</param>
         /// <returns>Uncompressed dictionary string-sting of files in the zip</returns>
-        public static Dictionary<string, string> UnzipData(byte[] zipData)
+        public static Dictionary<string, string> UnzipData(byte[] zipData, Encoding encoding = null)
         {
```
Comment (StefanoRaggi) [inline Compression/Compression.cs]: Nice!
