### PR TITLE
Bug Backtesting Brokerage Clones

### LINKED ISSUE #2846: Exercised/assigned option quantity used to compute Equity average price
#### Expected Behavior
When an option contract is exercised/assigned, the equity order average price must be the strike price

#### Actual Behavior
When an option contract is exercised/assigned, the equity order average price differs from the strike price.

#### Potential Solution
Do not account the option contract quantity when computing the quantity filled.

#### Reproducing the Problem
```python
from datetime import timedelta

class BasicTemplateOptionsAlgorithm(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2017, 2, 1)
        self.SetEndDate(2017, 3, 1)
        self.SetCash(100000)

        option = self.AddOption("IBM")
        self.option_symbol = option.Symbol
        option.SetFilter(-10, +10, timedelta(0), timedelta(30))


    def OnData(self,slice):
        if self.Portfolio.Invested: return

        chain = slice.OptionChains.GetValue(self.option_symbol)
        if chain is None:
            return
        contracts = sorted(chain, key = lambda x: x.Strike)
        if len(contracts) == 0: return
        symbol = contracts[-1].Symbol
        if not self.Portfolio.Invested:
            self.MarketOrder(symbol, 1)
 

    def OnOrderEvent(self, orderEvent):
        self.Debug("IBM Price "+str(self.Securities["IBM"].Price))
        self.Log(str(orderEvent))
```
The order event shows $200 for the assigned IBM shares, but the recoded order average price is $198.0198019802 USD (=200/101).

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### LINKED ISSUE #4445: Orders Being Partially Filled By The Same Bar in Backtesting
#### Expected Behavior
Do not try to fill an order with the same data.

#### Actual Behavior
1- For a single algorithm manager loop, the backtesting brokerage is triggered immediately for each order, and in the case of Market orders he fills immediately too. Also the backtesting brokerage is triggered at the end of each loop.
2- Once the backtesting brokerage gets an Order he creates a copy. So in the case of a partial fill the orders won't be updated, for example `LastFillTime`. Note that this is the Order which gets sent to the fill models. Since `LastFillTime` isn't sent, it can't use this information to decide whether it should emit a new partial fill + `1-` produces two fills per loop unless the fill model keeps track himself of the last fill time.

#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class CustomModelsAlgorithm : QCAlgorithm {
        private Security _security;
        private Symbol _spy;

        public override void Initialize() {
            SetStartDate(2013, 10, 01);
            SetEndDate(2013, 10, 31);
            _security = AddEquity("SPY", Resolution.Hour);
            _spy = _security.Symbol;
            _security.SetFillModel(new CustomFillModel(this));
        }

        public void OnData(TradeBars data) {
            var openOrders = Transactions.GetOpenOrders(_spy);
            if (openOrders.Count != 0) return;

            if (Time.Day > 10 && _security.Holdings.Quantity <= 0) {
                var quantity = CalculateOrderQuantity(_spy, .5m);
                MarketOrder(_spy, quantity, asynchronous: true); // async needed for partial fill market orders
            } else if (Time.Day > 20 && _security.Holdings.Quantity >= 0) {
                var quantity = CalculateOrderQuantity(_spy, -.5m);
                MarketOrder(_spy, quantity, asynchronous: true); // async needed for partial fill market orders
            }
        }

        public class CustomFillModel : ImmediateFillModel {
            private readonly QCAlgorithm _algorithm;
            private readonly Dictionary<long, decimal> _absoluteRemainingByOrderId = new Dictionary<long, decimal>();

            public CustomFillModel(QCAlgorithm algorithm) {
                _algorithm = algorithm;
            }

            public override OrderEvent MarketFill(Security asset, MarketOrder order) {
                decimal absoluteRemaining;
                if (!_absoluteRemainingByOrderId.TryGetValue(order.Id, out absoluteRemaining)) {
                    absoluteRemaining = order.AbsoluteQuantity;
                    _absoluteRemainingByOrderId.Add(order.Id, order.AbsoluteQuantity);
                }

                var absoluteFillQuantity = (int) (Math.Min(absoluteRemaining, 100));
                fill.FillQuantity = Math.Sign(order.Quantity) * absoluteFillQuantity;

                if (absoluteRemaining == absoluteFillQuantity) {
                    fill.Status = OrderStatus.Filled;
                    _absoluteRemainingByOrderId.Remove(order.Id);
                } else {
                    absoluteRemaining -= absoluteFillQuantity;
                    _absoluteRemainingByOrderId[order.Id] = absoluteRemaining;
                    fill.Status = OrderStatus.PartiallyFilled;
                }
                _algorithm.Log("CustomFillModel: " + fill);
                return fill;
            }
        }
    }
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

In the current implementation the `BacktestingBrokerage` passes around a clone of an order for processing. As a result when trying to make use of order variables such as `LastFillTime`, or `StopTriggered` that would be updated by the Backtesting Brokerage, it won't work since the Algorithms order is not updated.

In correcting this issue, I uncovered other issues related to the processing of `OptionExercised` orders. Without a clone the `OptionExercised` order takes on the value assigned by the ticket in `HandleOrderEvent()`, The initial tickets `AverageFillPrice` = 0 since the first event is removing the expired option. If I did not correct this problem after removing the `BackTestingBrokerage` clone, it would have allowed the option exercised price to be changed permanently to 0, therefore exercising a option to buy 100 shares of X at $0.

To fix this, I placed a conditional that if the `OrderType` is `OptionExercised`, the price is fixed and should not be changed.

Furthermore I had to make changes to some of our regression algorithms `OrderListsHash` to match the output. These changes have been analyzed and tested to be sure they reflects what the values should be.

Attached is a report on the Regression Algorithms that had to be changed and why.

[Regression Algorithm Changes Report.docx](https://github.com/QuantConnect/Lean/files/5119444/Regression.Algorithm.Changes.Report.docx)

#### Related Issue

Closes #4445 - With the clone removed the order will now have the `LastFillTime` updated
Closes #2846 - The `OptionExercised` order `price` will now not be skewed by the removal of the option. It is handled in the processing of the ticket.

#### Motivation and Context

Read above!

#### Requires Documentation Change

None

#### How Has This Been Tested?

All regression tests have been run and are successful. The changed regression algorithms are described in the attached document above.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Brokerages/Backtesting/BacktestingBrokerage.cs [hunk 1]
```diff
@@ -517,8 +517,7 @@ public override void Disconnect()
         /// <returns></returns>
         private void SetPendingOrder(Order order)
         {
-            // only save off clones!
-            _pending[order.Id] = order.Clone();
```
Comment (jaredbroad) [inline Brokerages/Backtesting/BacktestingBrokerage.cs:521]: Can we please add an order immutability regression test? I don't think we explicitly cover that -- something like we try 10 different ways to edit the order value but from QCAlgorithm layer it should be impossible

Comment (C-SELLERS) [reply Brokerages/Backtesting/BacktestingBrokerage.cs:521]: Added a regression algorithm for that, from what I see, it seems like I covered the only ways to try and modify the order. Since you only get the ticket in the algorithm I had to go through `Transactions`!

**Comment by C-SELLERS** [comment]
Closing to rerun Travis!

File: Algorithm.CSharp/BacktestingBrokerageRegressionAlgorithm.cs [hunk 2]
```diff
@@ -0,0 +1,274 @@
...
+    /// </summary>
+    /// <meta name="tag" content="backtesting brokerage" />
+    /// <meta name="tag" content="regression test" />
+    /// <meta name="tag" content="options" />
+    class BacktestingBrokerageRegressionAlgorithm : QCAlgorithm, IRegressionAlgorithmDefinition
+    {
+        private Security _security;
+        public Symbol Spy;
+        private Option _option;
+        public Symbol OptionSymbol;
```
Comment (Martin-Molinero) [inline Algorithm.CSharp/BacktestingBrokerageRegressionAlgorithm.cs:44]: nit - a couple of unrequired publics here

File: Algorithm.CSharp/BacktestingBrokerageRegressionAlgorithm.cs [hunk 3]
```diff
@@ -0,0 +1,274 @@
...
+            {
+                throw new Exception("OptionExercise order price should be strike price!!");
+            }
+        }
+
+        /// <summary>
+        /// PartialMarketFillModel that allows the user to set the number of fills and restricts
+        /// the fill to only one per bar.
+        /// </summary>
+        public class PartialMarketFillModel : ImmediateFillModel
```
Comment (Martin-Molinero) [inline Algorithm.CSharp/BacktestingBrokerageRegressionAlgorithm.cs:181]: nit - Let's make this class private too so it's not publicly available and adds noise into the namespace

File: Algorithm.CSharp/BacktestingBrokerageRegressionAlgorithm.cs [hunk 4]
```diff
@@ -0,0 +1,274 @@
...
+        }
+
+        /// <summary>
+        /// To verify OptionExercise orders is process correctly
+        /// </summary>
+        /// <param name="order">Order object to analyze</param>
+        public void VerifyOptionExercise(Order order)
+        {
+            // If the option price isn't the same as the strike price, its incorrect
+            if (order.Price != _optionStrikePrice)
```
Comment (Martin-Molinero) [inline Algorithm.CSharp/BacktestingBrokerageRegressionAlgorithm.cs:171]: Think we should assert quantities too. Let's also add an override of the `OnEndOfAlgorithm` where we assert the final status of the algorithms holdings, quantities and prices to make sure the modeling worked as expected

**Review by Martin-Molinero — APPROVED** [review]

**Review by Martin-Molinero — CHANGES_REQUESTED** [review]
Requires a rebase from master, some tests we added recently for the option filtering are failing

**Review by Martin-Molinero — APPROVED** [review]
