### PR TITLE
Fixes the exception message handling to return the python dll name

### LINKED ISSUE #2164: Missing information in DllNotFoundPythonExceptionInterpreter for Linux
#### Expected Behavior
The `DllNotFoundPythonExceptionInterpreter` message should read:
```
The dynamic-link library for python36 could not be found. Please visit https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md for instructions on how to enable python support in Unix
```
Note **python36**

#### Actual Behavior
The `DllNotFoundPythonExceptionInterpreter` message reads:
```
The dynamic-link library for  could not be found. Please visit https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md for instructions on how to enable python support in Unix
```
See #1746 messages from users.

#### Potential Solution
It looks like that a `DllNotFoundException` message does not have `'` `'`, `therefore string.GetStringBetweenChars` returns an empty string.

#### Reproducing the Problem
Run Lean in Linux with Python.Runtime.dll compiled for Windows.

#### System Information
Linux.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
Do not rely on `string.GetStringBetweenChars` to get the python dll name, because it is not bound by the same chars in Windows and Unix systems. Instead use 'python' string and limits the dll name to 10 characters.

#### Related Issue
Closes #2164 

#### Motivation and Context
Improve error messages.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Running Lean in both Windows and Linux (docker).

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Exceptions/DllNotFoundPythonExceptionInterpreter.cs [hunk 1]
```diff
@@ -48,8 +48,17 @@ public bool CanInterpret(Exception exception)
         public Exception Interpret(Exception exception, IExceptionInterpreter innerInterpreter)
         {
             var dnfe = (DllNotFoundException)exception;
+            
+            var startIndex = dnfe.Message.IndexOf("python");
+            var length = Math.Min(dnfe.Message.Length - startIndex, 10);
+            var dllName = dnfe.Message.Substring(startIndex, length);
+
+            length = dllName.IndexOf('\'');
```
Comment (mchandschuh) [inline Common/Exceptions/DllNotFoundPythonExceptionInterpreter.cs]: I believe it's possible that `DllNotFoundException` is thrown and have it not be related to python, so we should be careful here and expect strings that don't meet the pattern we expect. For example, we should handle 
```
if (startIndex < 0) // not python, emit a different message
```

In your tests, did you notice if the original message made it to the log file?

Comment (AlexCatarino) [reply Common/Exceptions/DllNotFoundPythonExceptionInterpreter.cs]: `DllNotFoundPythonExceptionInterpreter.CanInterpret` is only true if the exception message contains `python`, so `startIndex` is always greater than `-1`.

Yes, the original message makes to the log file.
Here is the message from the user in #1746:
> 20180322 19:51:24.602 ERROR:: Loader.TryCreatePythonAlgorithm(): System.Exception: AlgorithmPythonWrapper(): The dynamic-link library for could not be found. Please visit https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md for instructions on how to enable python support in Unix python3.6

The original message is **python3.6** in the end.

Comment (mchandschuh) [reply Common/Exceptions/DllNotFoundPythonExceptionInterpreter.cs]: awesome, love seeing the infrastructure working hard!

Comment (mchandschuh) [reply Common/Exceptions/DllNotFoundPythonExceptionInterpreter.cs]: So long as we're logging the full, original message, then this works for me.
