### PR TITLE
Decompressing AlgoSeek's OPRA files with SharpZipLib

### LINKED ISSUE #2163: AlgoSeekOptionsConverter 7zip implementation
#### Expected Behavior

A reliable way to decompress the massive AlgoSeek's OPRA files.

#### Actual Behavior

The actual implementation relying in `7zip` is very unstable. Given the wide variability in the OPRA file sizes (from 60MB up to +2GB), setting a time out is tricky and it doesn't assure it'll cover all possibilities.

Also sometimes the actual implementation simply throws `7Zip Exited Unsuccessfully`, meaning that the 7zip failed, even before the time out span passes. 

#### Potential Solution

One potential solution  is using some C# implementation (like `SharpZipLib`) for decompressing the data, with the limitation that raw data cannot be fully stored in memory.

#### Reproducing the Problem

The error is `7Zip Exited Unsuccessfully` hard to reproduce, given the same OPRA file and hardware sometimes  it fails, sometimes not. 

Also the `time out` error depends on the OPRA file size and the hardware were it is run. In a AWS EC2 `c4.2xlarge` instance, an OPRA file with more than 1GB, throws the error.

#### System Information

Ubuntu 16, AWS EC2 c4.2xlarge

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Jay-Jay-D**
#### Description

This PR implements a thread safe decompression of the huge AlgoSeek's opra files using SharpZipLib.

#### Related Issue

Fixes #2163 

#### Motivation and Context

As it was stated in the issue #2163, the wide range in opra files sizes plus some other not managed errors made the 7zip implementation unreliable.

#### How Has This Been Tested?

It was used successfully to convert several days without any error. 

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/ect)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs [hunk 1]
```diff
@@ -70,35 +72,43 @@ public AlgoSeekOptionsConverter(Resolution resolution, DateTime referenceDate, s
...
+            Parallel.ForEach(compressedRawDatafiles, parallelOptionsProcessing, compressedRawDatafile =>
             {
-                Log.Trace("Remote File :" + file);
-
-                var csvFile = Path.Combine(_source, Path.GetFileName(file).Replace(".bz2", ""));
-
-                Log.Trace("Source File :" + csvFile);
-
-                if (!File.Exists(csvFile))
+                var timer = DateTime.Now;
```
Comment (mchandschuh) [inline ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs]: should _always_ use `DateTime.UtcNow`

File: ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs [hunk 2]
```diff
@@ -70,35 +72,43 @@ public AlgoSeekOptionsConverter(Resolution resolution, DateTime referenceDate, s
...
-            Log.Trace("AlgoSeekOptionsConverter.Convert(): Loading {0} AlgoSeekOptionsReader for {1} ", files.Count(), _referenceDate);
+            var compressedRawDatafiles = Directory.EnumerateFiles(_remote, _remoteMask).Select(f => new FileInfo(f)).ToList();
+
+            Log.Trace("AlgoSeekOptionsConverter.Convert(): Loading {0} AlgoSeekOptionsReader for {1} ", compressedRawDatafiles.Count(), _referenceDate);
 
             //Initialize parameters
-            var totalLinesProcessed = 0L;
-            var totalFiles = files.Count();
+            var totalLinesProcessed = 0L;   
+            var totalFiles = compressedRawDatafiles.Count();
```
Comment (mchandschuh) [inline ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs]: should be able to use `Count` property instead of `Enumerable.Count` here since it's  list type.

File: ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs [hunk 3]
```diff
@@ -70,35 +72,43 @@ public AlgoSeekOptionsConverter(Resolution resolution, DateTime referenceDate, s
...
+                var decompressSuccessful = false;
+                var counter = 1;
+                do
                 {
-                    Log.Trace("AlgoSeekOptionsConverter.Convert(): Extracting " + file);
+                    var attempt = counter == 1 ? string.Empty : $" attempt {counter} of 3";
+                    Log.Trace($"AlgoSeekOptionsConverter.Convert(): Extracting {compressedRawDatafile.Name}{attempt}.");
+                    decompressSuccessful = DecompressOpraFile(compressedRawDatafile, rawDataFile);
+                    counter++;
+                } while (!decompressSuccessful && counter <= 3);
```
Comment (mchandschuh) [inline ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs]: Nice, love seeing retry logic!

File: ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs [hunk 4]
```diff
@@ -70,35 +72,43 @@ public AlgoSeekOptionsConverter(Resolution resolution, DateTime referenceDate, s
...
 
-                    var cmdArgs = " e " + file + " -o" + _source;
-                    RunZipper(zipper, cmdArgs);
+                if (!decompressSuccessful)
+                {
+                    Log.Error($"Error decompressing {compressedRawDatafile}. Process Stop.");
+                    throw new NotImplementedException();
```
Comment (mchandschuh) [inline ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs]: it's a shame, but this is totally the correct behavior. The OPRA file spec provides no guarantees regarding symbols spilling over between channel files, so if we don't extract _everything_ then we can't aggregate _anything_

File: ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs [hunk 5]
```diff
@@ -70,35 +72,43 @@ public AlgoSeekOptionsConverter(Resolution resolution, DateTime referenceDate, s
...
                 }
 
+                Log.Trace($"AlgoSeekOptionsConverter.Convert(): Extraction successful in {DateTime.Now - timer:g}, deleting {compressedRawDatafile.Name}.");
```
Comment (mchandschuh) [inline ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs]: use `UtcNow` please.

File: ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs [hunk 6]
```diff
@@ -70,35 +72,43 @@ public AlgoSeekOptionsConverter(Resolution resolution, DateTime referenceDate, s
...
+                File.Delete(compressedRawDatafile.FullName);
```
Comment (mchandschuh) [inline ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs]: info - can also be written as `compressedRawDatafile.Delete()` (See [`FileInfo.Delete`](https://msdn.microsoft.com/en-us/library/system.io.fileinfo.delete%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396))

File: ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs [hunk 7]
```diff
@@ -160,13 +170,13 @@ public void Convert()
                     Flush(processors, DateTime.MaxValue, true);
                     WriteToDisk(processors, waitForFlush, DateTime.MaxValue, flushStep, true);
 
-                    Log.Trace("AlgoSeekOptionsConverter.Convert(): Cleaning up extracted options file {0}", csvFile);
-                    File.Delete(csvFile);
+                    Log.Trace("AlgoSeekOptionsConverter.Convert(): Cleaning up extracted options file {0}", rawDataFile.FullName);
+                    File.Delete(rawDataFile.FullName);
```
Comment (mchandschuh) [inline ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs]: info - can also use `rawDataFile.Delete()`

File: ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs [hunk 8]
```diff
@@ -339,57 +349,33 @@ public void Clean(DateTime date)
...
-                            Log.Trace("7Zip Exited Successfully: " + cmdArgs);
-                        }
-                    }
+                    BZip2.Decompress(fileToDecompressAsStream, decompressedStream, true);
+                    outcome = true;
+                }
+                catch (Exception ex)
+                {
+                    Log.Error($"AlgoSeekOptionsConverter.DecompressOpraFile({compressedRawDatafile.Name}, {rawDatafile.Name}): SharpzipLib.BZip2.Decompress returned error: " + ex.Message);
+                    Console.WriteLine(ex.Message);
```
Comment (mchandschuh) [inline ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs]: is this `Console.WriteLine` intentional?

File: ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs [hunk 9]
```diff
@@ -339,57 +349,33 @@ public void Clean(DateTime date)
...
-                        {
-                            Log.Trace("7Zip Exited Successfully: " + cmdArgs);
-                        }
-                    }
+                    BZip2.Decompress(fileToDecompressAsStream, decompressedStream, true);
+                    outcome = true;
+                }
+                catch (Exception ex)
+                {
+                    Log.Error($"AlgoSeekOptionsConverter.DecompressOpraFile({compressedRawDatafile.Name}, {rawDatafile.Name}): SharpzipLib.BZip2.Decompress returned error: " + ex.Message);
```
Comment (mchandschuh) [inline ToolBox/AlgoSeekOptionsConverter/AlgoSeekOptionsConverter.cs]: _everytime_ we call `Log.Error` with an `Exception` in scope, we _must_ pass the exception object to the message, this ensures the full stack and all inner exceptions make it into the log. As written, the entire stack trace is lost.

File: ToolBox/QuantConnect.ToolBox.csproj [hunk 10]
```diff
@@ -45,6 +45,9 @@
     <Reference Include="EngineIoClientDotNet, Version=0.9.22.0, Culture=neutral, processorArchitecture=MSIL">
       <HintPath>..\packages\EngineIoClientDotNet.0.9.22\lib\net45\EngineIoClientDotNet.dll</HintPath>
     </Reference>
+    <Reference Include="ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73, processorArchitecture=MSIL">
+      <HintPath>..\packages\SharpZipLib.0.86.0\lib\20\ICSharpCode.SharpZipLib.dll</HintPath>
```
Comment (mchandschuh) [inline ToolBox/QuantConnect.ToolBox.csproj]: `QuantConnect.Compression` references a different version of this library. Please try using the same library and confirm that it works. Having multiple versions of packages quickly devolves into a modern form of dll-hell.
``` xml
<package id="ICSharpCode.SharpZipLib.dll" version="0.85.4.369" targetFramework="net45" />
```

**Comment by mchandschuh** [comment]
Thanks @Jay-Jay-D!
