### PR TITLE
Fixes PythonData.EndTime

### LINKED ISSUE #6601: PythonData EndTime Cannot Be Set
#### Expected Behavior
The `Time` and `EndTime` of Python Custom Data (`PythonData`) can be different and represent a period.

#### Actual Behavior
`PythonData.EndTime` inherits from `BaseData.EndTime` which is set by `BaseData.Time`. 

#### Potential Solution
Override `BaseData.EndTime` in `PythonData.EndTime` and remove the depency to `BaseData.Time`.

#### Reproducing the Problem
Verify that `BitCoin.Time` and `BitCoin.EndTime` have the same value in `CustomDataBitcoinAlgorithm.py`

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
The `EndTime` property of `PythonData` didn't override the base implementation in `BaseData`. Therefore `EndTime` was always set as `Time`.

Fixes Regression Tests
- The C# version of `Bitcoin` class needs to implement `EndTime`-
- Fixes regression tests

#### Related Issue
Closes #6601 

#### Motivation and Context
Bug fix.

#### Requires Documentation Change
Yes. The Importing data should show `EndTime` override in C# examples. 

#### How Has This Been Tested?
Regression tests.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by Martin-Molinero — APPROVED** [review]
Nice!

File: Common/Python/PythonData.cs [hunk 1]
```diff
@@ -32,6 +32,21 @@ public class PythonData : DynamicData
...
+        /// and as such we want to know the entire time span covered
+        /// </summary>
+        /// <remarks>
+        /// This property is overriden to allow different values for Time and EndTime
+        /// if they are set in the Reader. In the base implementation EndTime equals Time
+        /// </remarks>
+        public override DateTime EndTime
+        {
+            get => _endTime == default ? Time : _endTime;
+            set => _endTime = value;
```
Comment (jaredbroad) [inline Common/Python/PythonData.cs:48]: Is there a period? Does EndTime-Period = Time?

Comment (AlexCatarino) [reply Common/Python/PythonData.cs:48]: If users just define `Time` and `EndTime` it will be simpler than asking them to define a third variable `Period`. But we could define a `Period` too.
