### PR TITLE
Parallelize reading of fine fundamental data

### LINKED ISSUE #2189: Parallelize reading of fine fundamental data
#### Expected Behavior

Universes that use the fine fundamental data should not be exponentially slower than w/out fine data.

#### Actual Behavior

Fine universe algorithms are incredibly slow.

#### Potential Solution

Read fine fundamental data in parallel to improve performance.

#### Reproducing the Problem

Run an algorithm using the fine fundamental data and observe the performance slow down as more fine data is requested.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by mchandschuh**
#### Description

Read fine fundamental data in parallel

#### Related Issue

Closes #2189 

#### Motivation and Context

Faster is better!

#### Requires Documentation Change

No.

#### How Has This Been Tested?

Ran benchmarks in the cloud and observed performance increases proportional to the number of fine symbols selected. Using 10 fine symbols for a year the run time dropped from ~115 seconds to ~80 seconds.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/ect)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/DataFeeds/UniverseSelection.cs [hunk 1]
```diff
@@ -81,7 +82,9 @@ public SecurityChanges  ApplyUniverseSelection(Universe universe, DateTime dateT
                     var fineCollection = new BaseDataCollection();
                     var dataProvider = new DefaultDataProvider();
 
-                    foreach (var symbol in selectSymbolsResult)
+                    // use all available threads, the entire system is waiting for this to complete
+                    var options = new ParallelOptions{MaxDegreeOfParallelism = Environment.ProcessorCount};
+                    Parallel.ForEach(selectSymbolsResult, options, symbol =>
```
Comment (jaredbroad) [inline Engine/DataFeeds/UniverseSelection.cs]: 😎

Comment (Martin-Molinero) [reply Engine/DataFeeds/UniverseSelection.cs]: Beautiful! just out of curiosity, did you test using `> Environment.ProcessorCount`? Like `Environment.ProcessorCount * 1.5`, Maybe there is room for even more juice

Comment (mchandschuh) [reply Engine/DataFeeds/UniverseSelection.cs]: I did not try but I can. I wouldn't expect that to help since all of these reads are synchronous -- if we were doing async reads I would think we could squeeze a little more out of it

Comment (mchandschuh) [reply Engine/DataFeeds/UniverseSelection.cs]: @Martin-Molinero -- tried 1.5x and didn't notice and improvements (statistically insignificant delay was actually observed) -- hunch is that it's just extra overhead and the threads are simply competing each other
