### PR TITLE
Fix IBAutomater restarting after Dispose

### LINKED ISSUE #4807: IB is disposed of correctly
#### Expected Behavior

- IB is disposed of correctly
#### Actual Behavior

- IB is reconnecting after being disposed of
```
Trace:: LiveTradingRealTimeHandler.Run(): Exiting thread... Exit triggered: True
Trace:: DataManager.RemoveSubscription(): Removed QC-UNIVERSE-USERDEFINED-USA-EQUITY,QC-UNIVERSE-USERDEFINED-USA-EQUITY,Second,TradeBar,Trade,Adjusted,Internal
Trace:: DataManager.RemoveSubscription(): Removed SPY,SPY,Minute,TradeBar,Trade,Adjusted,Internal
Trace:: DataManager.RemoveSubscription(): Removed SPY,SPY,Second,TradeBar,Trade,Adjusted
Trace:: EventBasedDataQueueHandlerSubscriptionManager.Unsubscribe(): SPY
Trace:: InteractiveBrokersBrokerage.Unsubscribe(): Unsubscribe Request: SPY
Trace:: DataManager.RemoveSubscription(): Removed SPY,SPY,Second,QuoteBar,Quote,Adjusted
Trace:: DefaultAlphaHandler.Exit(): Exiting...
Trace:: DefaultAlphaHandler.Exit(): Ended
Trace:: StopSafely(): waiting for 'Result Thread' thread to stop...
Trace:: Debug: Brokerage Info: Requested market data is not subscribed. Displaying delayed market data.... Origin: Subscribe: SPY (STK SPY USD Smart)
Trace:: LiveTradingResultHandler.Run(): Ending Thread...
Trace:: LiveTradingResultHandler.SendFinalResult(): Starting...
Trace:: LiveTradingResultHandler.SendFinalResult(): Finished storing results. Start sending...
Trace:: LiveTradingResultHandler.SendFinalResult(): Ended
Trace:: Engine.Run(): Disconnecting from brokerage...
Trace:: InteractiveBrokersBrokerage.HandleConnectionClosed(): API client disconnected.
Trace:: InteractiveBrokersBrokerage.Connect(): IB message processing thread ended: #21
Trace:: InteractiveBrokersBrokerage.Dispose(): Disposing of IB resources.
Trace:: InteractiveBrokersBrokerage.HandleConnectionClosed(): API client disconnected.
Trace:: InteractiveBrokersBrokerage.OnIbAutomaterExited(): Exit code: -1
Trace:: InteractiveBrokersBrokerage.OnIbAutomaterExited(): IBGateway close detected, restarting IBAutomater and reconnecting...
Trace:: InteractiveBrokersBrokerage.HandleConnectionClosed(): API client disconnected.
Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): Loading IBGateway version: 974
Trace:: Engine.Run(): Disposing of setup handler...
Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): IBAutomater process started - Id:15180
Trace:: BrokerageSetupHandler.Setup(): Found data queue handler to dispose: QuantConnect.Brokerages.InteractiveBrokers.InteractiveBrokersBrokerage
Trace:: InteractiveBrokersBrokerage.Dispose(): Disposing of IB resources.
Trace:: InteractiveBrokersBrokerage.HandleConnectionClosed(): API client disconnected.
Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): StartIBGateway(): starting IBGateway
Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): StartIBGateway(): IBGateway started
Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): Window event: [WINDOW_ACTIVATED] - Window title: [IB Gateway]
Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): Window event: [WINDOW_OPENED] - Window title: [IB Gateway]
```
#### Potential Solution

N/A
#### Reproducing the Problem

- Windows & v974
```
    public class BasicTemplateAlgorithm : QCAlgorithm
    {
        public override void Initialize()
        {
            AddEquity("SPY", Resolution.Second);
        }
        public override void OnData(Slice data)
        {
            throw new Exception("PEPE");
        }
```
#### System Information

Windows
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
- Added missing check to prevent IBAutomater restart after `Dispose` is called

#### Related Issue
Closes #4807 

#### Motivation and Context
- IBAutomater restarting after IB Dispose

#### Requires Documentation Change
No.

#### How Has This Been Tested?
- Tested fix locally with algorithm included in #4807 

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs [hunk 1]
```diff
@@ -907,6 +909,8 @@ public override void Dispose()
         {
             Log.Trace("InteractiveBrokersBrokerage.Dispose(): Disposing of IB resources.");
 
+            _isDisposeCalled = true;
```
Comment (Martin-Molinero) [inline Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs:912]: Minor but we might wanna make this variable `volatile` since both code paths will be run by different threads? Also since we are at it, we could add a check at the top it's already true just return

**Review by Martin-Molinero — APPROVED** [review]
Nice 👍 minor suggestion
