### PR TITLE
Fix ambiguous future symbol error in IB brokerage

### LINKED ISSUE #2924: Error subscribing Futures symbol in Interactive Brokers with ambiguous specification
There are Futures symbols in Interactive Brokers that have the same `contract.Symbol` but are different contracts. For example the silver futures contract SI  (Futures.Metals.Silver in QC) with 5000 multiplier has the same Interactive Brokers symbol for both the 5000 and the 1000 multiplier.

#### Expected Behavior
The subscription is processed without error and Futures Chains are received for the subscribed contract.

#### Actual Behavior

20190220 10:59:44.540 Trace:: InteractiveBrokersBrokerage.Subscribe(): Subscribe Request: SI29K19
20190220 10:59:44.582 Trace:: InteractiveBrokersBrokerage.HandleError(): RequestId: 33 ErrorCode: 200 - The contract description specified for SI is ambiguous;. you must specify the multiplier or trading class.. Origin: Subscribe: FUT SI USD NYMEX
20190220 10:59:44.582 ERROR:: Brokerage.OnMessage(): Error - Code: 200 - The contract description specified for SI is ambiguous;. you must specify the multiplier or trading class.. Origin: Subscribe: FUT SI USD NYMEXErr

#### Potential Solution
Hack: In the class InteractiveBrokersBrokerage.cs line 1727 insert the following code in the method CreateContract:

`if (contract.Symbol.Equals("SI")) {
contract.Multiplier = "5000";
}`

Suggested solution: There are other futures contracts with the same problems: DAX in Interactive Brokers has the same symbol for both the DAX (25 multiplier) and mini DAX (5 multiplier). Since EUREX futures are still unsupported this has not been tested but the same could happen. I would suggest to refactor the IB symbol mapper in order to include the multiplier parameter for the contracts that require it. There should be a SI and SIL QC futures contracts that translate into SI 5000 multiplier and SI 1000 multiplier inside the CreateContract method. Likewise there should be a DAX and MDAX QC futures contracts that translate into DAX 25 multiplier and DAX 5 multiplier when sent to IB.

#### Reproducing the Problem
Subscribe the futures contract Futures.Metals.Silver from any algorithm.

#### System Information
Tested under Lean master in Ubuntu 18.04.1

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
- IB contracts used for subscriptions and future chain requests now include the Multiplier field, which is loaded from the symbol properties database.
- The `GetFuturesContractExchange()` method was unused and has been removed

#### Related Issue
Closes #2924 

#### Motivation and Context
- Solves the ambiguity for IB future contracts with same ticker but different contract multipliers.
- When loading future contracts for `Futures.Metals.Silver` (`SI`) (or subscribing to a single future contract) we will only request contracts with the `5000` multiplier (which is specified in the symbol properties database) instead of throwing the following exception:
```
ErrorCode: 200 - The contract description specified for SI is ambiguous; you must specify the multiplier or trading class.
```

**Note**: for now LEAN does not support future contracts with duplicate tickers but different multipliers in the SPDB, 
so for the `SI` example above the `1000` multiplier contracts are not supported.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
- Live algorithm subscribing to the SI future 

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs [hunk 1]
```diff
@@ -1875,6 +1861,9 @@ private Contract CreateContract(Symbol symbol, bool includeExpired, string excha
                                         _futuresExchanges[symbol.ID.Market] :
                                         symbol.ID.Market;
 
+                var symbolProperties = _symbolPropertiesDatabase.GetSymbolProperties(symbol.ID.Market, contract.Symbol, SecurityType.Future, Currencies.USD);
```
Comment (Martin-Molinero) [inline Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs:1864]: `contract.Symbol` is the IB mapped ticker, might not match the SPDB? We do have access to the `Symbol` instance here, maybe we could use it?

File: Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs [hunk 2]
```diff
@@ -2751,6 +2740,13 @@ public IEnumerable<Symbol> LookupSymbols(string lookupName, SecurityType securit
             }
             else if (securityType == SecurityType.Future)
             {
+                string market;
+                if (_symbolPropertiesDatabase.TryGetMarket(contract.Symbol, securityType, out market))
+                {
+                    var symbolProperties = _symbolPropertiesDatabase.GetSymbolProperties(market, contract.Symbol, securityType, Currencies.USD);
+                    contract.Multiplier = Convert.ToInt32(symbolProperties.ContractMultiplier).ToStringInvariant();
```
Comment (Martin-Molinero) [inline Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs:2747]: Curious why convert it to `int` instead of directly going from decimal to string?
The same comment about the `contract.Symbol` usages, maybe here we'll have to call the symbol mapper?

Comment (StefanoRaggi) [reply Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs:2747]: Seems all multipliers are integers and IB didn't like the string "5000.0" 😄 

You're right about the `contract.Symbol` usage, needs to be the LEAN ticker 👍

**Review by Martin-Molinero — APPROVED** [review]
Nice! 💯

**Comment by carriere4** [comment]
FYI - this is still an issue. I am getting the following error when requesting a SI futures contract:
`Server Error: The contract description specified for SI is ambiguous; you must specify the multiplier or trading class.`

**Comment by Martin-Molinero** [comment]
Hey @carriere4! You are reproducing this issue in QC cloud? Please provide a simple algorithm/steps to reproduce the issue and reopen https://github.com/QuantConnect/Lean/issues/2924, we will look into it ASAP. Thanks!
