### PR TITLE
Fixes Div by Zero exceptions in framework models

### LINKED ISSUE #2211: Equal Weighting Portfolio Construction Div by Zero
#### Expected Behavior
Framework classes should not throw.

#### Actual Behavior
Divide by zero error on some universes.

```
System.DivideByZeroException: Attempted to divide by zero.
at (wrapper managed-to-native) System.Decimal.FCallDivide(System.Decimal&,System.Decimal&)
at System.Decimal.op_Division (System.Decimal d1, System.Decimal d2) [0x00000] in <2e7c1c96edae44d496118948ca617c11>:0 
at QuantConnect.Algorithm.Framework.Portfolio.EqualWeightingPortfolioConstructionModel.CreateTargets (QuantConnect.Algorithm.Framework.QCAlgorithmFramework algorithm, QuantConnect.Algorithm.Framework.Alphas.Insight[] insights) [0x000d8] in <4c832c2253924cc19b425aa5deaa2a75>:0 
at QuantConnect.Algorithm.Framework.QCAlgorithmFramework.OnFrameworkData 
```

#### Potential Solution
Zero check and apply the solution to C# and Python.

#### Reproducing the Problem
```
class BasicTemplateFrameworkAlgorithm(QCAlgorithmFramework):
    def Initialize(self):
        self.SetStartDate(2018, 1, 5)   #Set Start Date
        self.SetEndDate(2018, 7, 5)    #Set End Date
        self.SetCash(100000)           #Set Strategy Cash
        fastPeriod = 7
        slowPeriod = 21
        count = 100
        self.UniverseSettings.Leverage = 2.0
        self.UniverseSettings.Resolution = Resolution.Daily
        self.SetUniverseSelection(EmaCrossUniverseSelectionModel(fastPeriod, slowPeriod, count))
        self.SetAlpha(ConstantAlphaModel(InsightType.Price, InsightDirection.Up, TimeSpan.FromMinutes(20), 0.025, None))
        self.SetPortfolioConstruction(EqualWeightingPortfolioConstructionModel())
        self.SetExecution(ImmediateExecutionModel())
        self.SetRiskManagement(NullRiskManagementModel())
```

#### System Information
Cloud

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
Adds missing zero checks to `EqualWeightingPortfolioConstructionModel` and `MaximumSectorExposureRiskManagementModel`. 

#### Related Issue
Closes #2211

#### Motivation and Context
Framework classes should not throw.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Manually running algorithm provided in issue #2211.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Algorithm.Framework/Risk/MaximumSectorExposureRiskManagementModel.cs [hunk 1]
```diff
@@ -38,6 +38,11 @@ public class MaximumSectorExposureRiskManagementModel : RiskManagementModel
             decimal maximumSectorExposure = 0.20m
             )
         {
+            if (maximumSectorExposure == 0)
+            {
+                throw new ArgumentOutOfRangeException("MaximumSectorExposureRiskManagementModel: the maximum sector exposure cannot be zero.");
```
Comment (mchandschuh) [inline Algorithm.Framework/Risk/MaximumSectorExposureRiskManagementModel.cs]: Can `maximumSectorExposure` be negative?

File: Algorithm.Framework/Portfolio/EqualWeightingPortfolioConstructionModel.cs [hunk 2]
```diff
@@ -60,6 +60,11 @@ public override IEnumerable<IPortfolioTarget> CreateTargets(QCAlgorithmFramework
                 .Where(x => x.CloseTimeUtc > algorithm.UtcTime)
                 .Select(x => x.Symbol).Distinct().ToList();
 
+            if (symbols.Count == 0)
+            {
+                return targets;
```
Comment (mchandschuh) [inline Algorithm.Framework/Portfolio/EqualWeightingPortfolioConstructionModel.cs]: Looking at this I noticed https://github.com/QuantConnect/Lean/pull/2266/files#diff-8b46b0f4f1c7d13b4660c2f0121a289cR55 -- I think he should returning `targets` as well, yes? Otherwise we may drop removed symbols.
