### PR TITLE
Solve bug in Tick Consolidator for Quote and Trade Tick types

### LINKED ISSUE #7450: Tick Consolidator not working as expected with TickType.Trade when no quote data is available
#### Expected Behavior

In the example below `OnTick` should be called even if there is no quote tick data available.

#### Actual Behavior

`OnTick` is not being called as the consolidator subscribed to the quote tick subscription even when the tick type is specified. 

#### Potential Solution

The provided tick type is currently ignored when the consolidator is being added to the subscription and the default tick type is being used. The issue can be fixed by only using the default tick type when it's not manually specified. 

https://github.com/QuantConnect/Lean/blob/76c0ab01ee7ad5a2a67e122a8f54ddb14a7ac498/Common/Data/SubscriptionManager.cs#L277-L281https://github.com/QuantConnect/Lean/blob/76c0ab01ee7ad5a2a67e122a8f54ddb14a7ac498/Common/Data/SubscriptionManager.cs#L164-L168
#### Reproducing the Problem

Running the following backtest with only trade tick data available.
``` csharp
 public class Example : QCAlgorithm
  {
      public override void Initialize()
      {
          SetStartDate(2023, 08, 01); 
          SetEndDate(2023, 08, 02); 

          var crypto = AddCrypto("BTCUSDT", Resolution.Tick, Market.Binance);
          var consolidator = Consolidate(crypto.Symbol, Resolution.Tick, TickType.Trade, (Tick tick) =>OnTick(tick));
      }

      private void OnTick(Tick tick)
      {
          //This will never be called when there is no quote tick data available even though TickType.Trade was selected
      }
  }
```
#### System Information

Not relevant

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Marinovsky**
#### Description

So far, when the user tried to consolidate tick data with a desired tick type, if the symbol was a Cfd, Forex or Crypto, by default it always picked a subscription with Quote tick type and thus ignored the desired tick type given by the user. Now, if the user has provided a desired tick type, LEAN will try to look for a subscription with that tick type. If not found, an exception will be thrown. To cover these changes, unit tests and regression tests have been made to assert the bug is actually solved by theses changes.
#### Related Issue

Closes #7450 
#### Motivation and Context

With this change users will be able to consolidate tick data with a desired tick type
#### Requires Documentation Change

N/A
#### How Has This Been Tested?

For the unit tests, it was asserted that the method `SubscriptionManager.IsSubscriptionValidForConsolidator()` returned the expected results in different scenarios that involve different resolutions, tick types, and output types.

For the regression tests, an algorithm was created that consolidated tick data with two requested tick types, namely Trade and Quote. Every time a new tick data was found, it asserted if the tick type was Quote or Trade according to the method in which the new tick data was found. Finally, at the end of the algorithm it was asserted that at least one tick data of each type was found, if not an exception was thrown.
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Data/SubscriptionManager.cs [hunk 1]
```diff
@@ -268,17 +275,25 @@ public void SetDataManager(IAlgorithmSubscriptionManager subscriptionManager)
...
+                if (desiredTickType == null)
+                {
+                    var tickType = LeanData.GetCommonTickTypeForCommonDataTypes(
                     consolidator.OutputType,
                     subscription.Symbol.SecurityType);
 
-                return subscription.TickType == tickType;
+                    return subscription.TickType == tickType;
+                }
+                else if (subscription.TickType != desiredTickType)
```
Comment (jhonabreul) [inline Common/Data/SubscriptionManager.cs:293]: If subscription's tick type is the same as the desired tick type, we coudl return true, we don't really need the method to continue doing any more checks outside of this `if`.
Maybe do this in a single check? Like doing `var tickType = desiredTickType ?? LeanData.GetCommonTickTypeForCommonDataTypes(consolidator.OutputType, subscription.Symbol.SecurityType);` and then just `return subscription.TickType == tickType;`?

File: Tests/Common/Data/SubscriptionManagerTests.cs [hunk 2]
```diff
@@ -265,6 +265,147 @@ public void GetsCustomSubscriptionDataTypes()
             Assert.AreEqual(expected, SubscriptionManager.IsSubscriptionValidForConsolidator(subscription, consolidator));
         }
 
+        [TestCase(SecurityType.Future, Resolution.Tick, typeof(Tick), TickType.Trade, null, typeof(TradeBar), true)]
```
Comment (jhonabreul) [inline Tests/Common/Data/SubscriptionManagerTests.cs:268]: Since resolution and dataType are always `Resolution.Tick` and `typeof(Tick)`, they could be removed from the test parameters

File: Algorithm.CSharp/CorrectConsolidatedBarTypeForTickTypesAlgorithm.cs [hunk 3]
```diff
@@ -29,7 +29,6 @@ public class CorrectConsolidatedBarTypeForTickTypesAlgorithm : QCAlgorithm, IReg
     {
         private bool _quoteTickConsolidatorCalled;
         private bool _tradeTickConsolidatorCalled;
-        private bool _openInterestTickConsolidatorCalled;
```
Comment (jhonabreul) [inline Algorithm.CSharp/CorrectConsolidatedBarTypeForTickTypesAlgorithm.cs:32]: Why was the open interest tick consolitator code removed here and in the Python algo?

**Review by jhonabreul — COMMENTED** [review]
Nice! 💯 Leaving a couple of minor comments

File: Common/Data/SubscriptionManager.cs (hunk 1 above)
Comment (Marinovsky) [reply Common/Data/SubscriptionManager.cs:293]: Hmm I see, that could be an option. However, I still wonder why don't you take into consideration this last check `consolidator.InputType.IsAssignableFrom(subscription.Type)`

File: Algorithm.CSharp/CorrectConsolidatedBarTypeForTickTypesAlgorithm.cs (hunk 3 above)
Comment (Marinovsky) [reply Algorithm.CSharp/CorrectConsolidatedBarTypeForTickTypesAlgorithm.cs:32]: Oh because Open Interest is just for futures and options, not for equities

**Review by Martin-Molinero — APPROVED** [review]
Nice! Thank you 🚀
