### PR TITLE
Fix setting brokerage model after adding security initializer

### LINKED ISSUE #9047: SetBrokerageModel Fails Silently
#### Expected Behavior
When we call SetBrokerageModel after Set/AddSecurityInitializer, log a message saying we should call it before, and use AddSecurityInitializer to override the brokerage model defaults.

#### Actual Behavior
See:
```csharp
if (!_userSetSecurityInitializer)
```
in 
https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.cs#L1365:L1389

#### Potential Solution
We could log the message, raise an exception, or create a CompositeSecurityInitializer where the Brokerage is the first.

#### Reproducing the Problem
```csharp
var seeder = new FuncSecuritySeeder(GetLastKnownPrices);
SetSecurityInitializer(x => seeder.SeedSecurity(x));
SetBrokerageModel(BrokerageName.InteractiveBrokersBrokerage);
Quit(SecurityInitializer.GetType().Name);
```
prints: `Quit(): FuncSecurityInitializer`:

If we use `AddSecurityInitializer`:

```csharp
var seeder = new FuncSecuritySeeder(GetLastKnownPrices);
AddSecurityInitializer(x => seeder.SeedSecurity(x));
SetBrokerageModel(BrokerageName.InteractiveBrokersBrokerage);
Quit(SecurityInitializer.GetType().Name);
```

prints: `Quit(): BrokerageModelSecurityInitializer`, so the `FuncSecuritySeeder` is lost. 

Correct outcome:

```csharp
SetBrokerageModel(BrokerageName.InteractiveBrokersBrokerage);
var seeder = new FuncSecuritySeeder(GetLastKnownPrices);
AddSecurityInitializer(x => seeder.SeedSecurity(x));
Quit(SecurityInitializer.GetType().Name);
```

prints: `Quit(): CompositeSecurityInitializer`

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

Fix setting brokerage model after adding security initializer. Now the brokerage model will be set and the corresponding `BrokerageModelSecurityInitializer` instances will be appended to the existing `CompositeSecurityInitializer`

#### Related Issue

Closes #9047 

#### How Has This Been Tested?

Unit tests

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Algorithm/QCAlgorithm.cs [hunk 1]
```diff
@@ -1368,7 +1368,15 @@ public void SetBrokerageModel(IBrokerageModel model)
             if (!_userSetSecurityInitializer)
             {
                 // purposefully use the direct setter vs Set method so we don't flip the switch :/
-                SecurityInitializer = new BrokerageModelSecurityInitializer(model, SecuritySeeder.Null);
+                var brokerageSecurityInitializer = new BrokerageModelSecurityInitializer(model, SecuritySeeder.Null);
+                if (SecurityInitializer is CompositeSecurityInitializer compositeSecurityInitializer)
+                {
+                    compositeSecurityInitializer.AddSecurityInitializer(brokerageSecurityInitializer);
```
Comment (AlexCatarino) [inline Algorithm/QCAlgorithm.cs]: If we do this, are we not putting the brokerage at the end? For example, say we set a custom fill model, then I think the brokerage will override it.

**Review by Martin-Molinero — APPROVED** [review]
Thank you!
