### PR TITLE
Fixes Expiry.EndOfMonth and Expiry.EndOfYear Methods

### LINKED ISSUE #4267: Expiry.EndOfMonth Returns Unexpected Values
#### Expected Behavior
`Expiry.EndOfMonth` returns the 1st day of the following month. 

#### Actual Behavior
Edge case in January:
```csharp
var x = Expiry.EndOfMonth(new DateTime(2020,1,31));   // x -> 20200130
var y = Expiry.EndOfMonth(new DateTime(2020,1,30));   // y -> 20200131
var z = Expiry.EndOfMonth(new DateTime(2020,1,29));   // z -> 20200201 (expected)
```
#### Potential Solution
Review and fix the logic.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
- Fixes `Expiry.EndOfMonth` and `Expiry.EndOfYear` Methods
- Adds unit tests for `Expiry.EndOf*` methods.

#### Related Issue
Closes #4267 

#### Motivation and Context
Bug fix.

#### How Has This Been Tested?
New unit tests.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/ExpiryTests.cs [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+
+using NUnit.Framework;
+using System;
+using System.Collections.Generic;
+using System.Linq;
+
+namespace QuantConnect.Tests.Common
+{
+    [TestFixture]
+    public class ExpiryTests
```
Comment (Martin-Molinero) [inline Tests/Common/ExpiryTests.cs:24]: Nice tests 👍
