### PR TITLE
Handle DivisionByZero exception in indicators

### LINKED ISSUE #7782: System.Exception: Attempted to divide by zero. in LogReturn indicator
```
 System.Exception: Attempted to divide by zero. in LogReturn.cs:line 60
 ---> QuantConnect.Exceptions.SystemExceptionInterpreter+SanitizedException: Attempted to divide by zero.
   at System.Decimal.DecCalc.VarDecDiv(DecCalc& d1, DecCalc& d2)
   at QuantConnect.Indicators.LogReturn.ComputeNextValue(IReadOnlyWindow`1 window, IndicatorDataPoint input) in Indicators\LogReturn.cs:line 60
   at QuantConnect.Indicators.IndicatorBase`1.ValidateAndComputeNextValue(T input) in Indicators\IndicatorBase.cs:line 340
   at QuantConnect.Indicators.IndicatorBase`1.Update(IBaseData input) in Indicators\IndicatorBase.cs:line 259
   at QuantConnect.Algorithm.QCAlgorithm.<>c__DisplayClass580_0.<RegisterIndicator>b__1(Object sender, IBaseData consolidated) in Algorithm\QCAlgorithm.Indicators.cs:line 2428
   at QuantConnect.Data.Consolidators.DataConsolidator`1.OnDataConsolidated(IBaseData consolidated) in Common\Data\Consolidators\DataConsolidator.cs:line 109
   at QuantConnect.Data.Consolidators.IdentityDataConsolidator`1.Update(T data) in Common\Data\Consolidators\IdentityDataConsolidator.cs:line 60
   at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, ISynchronizer synchronizer, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ILeanManager leanManager, CancellationToken token) in Engine\AlgorithmManager.cs:line 600
```
Maybe on this opportunity check all of the indicators for this bug? this is the third case I am opening in the past month for indicator bugs.
#### Expected Behavior
the strategy should continue running and not crash

#### Actual Behavior
the strategy crash

#### Potential Solution
make it so not crash

#### Reproducing the Problem
:{

#### System Information
windows 10 .NET 6

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Marinovsky**
#### Description

Prevent DivisionByZero exceptions in LEAN indicators when input data is extremely low, using a safe division method. This method returns a default or given value if the denominator of the division is zero. Additionally, it handles double-to-decimal cast exceptions.
#### Related Issue

Closes #7782 
#### Motivation and Context

With this change indicators won't throw division by zero exceptions when the given values are extremely low
#### Requires Documentation Change

N/A
#### How Has This Been Tested?

Each indicator was pumped with extreme low values and asserted it to not throw any divide by zero exception. Besides, the `Extensions.SafeDivision()` method was tested in different scenarios that could raise division by zero or casting exceptions.
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Indicators/LogReturn.cs [hunk 1]
```diff
@@ -62,8 +62,10 @@ protected override decimal ComputeNextValue(IReadOnlyWindow<IndicatorDataPoint>
             var value0 = window.Samples <= window.Size
                 ? window[window.Count - 1]
                 : window.MostRecentlyRemoved;
-
-            return (decimal)Math.Log((double)(valuef.Value / value0.Value));
+            var result = Math.Log((double)(valuef.Value.SafeDivision(value0.Value)));
+            return (result == Double.NegativeInfinity |
+                result == Double.PositiveInfinity |
+                result >= (double)Decimal.MaxValue) ? 0 : (decimal)result;
```
Comment (jaredbroad) [inline Indicators/LogReturn.cs:68]: Please expand it so more understandable—no need to keep it so condensed.
