### PR TITLE
Fix position group order quantity calculation for delta/target buying power

### LINKED ISSUE #7235: Wrong unit group from given position group
#### Expected Behavior

`PositionGroupKey.CreateUnitGroup()` respects the sign and unit quantity of each position/leg.

#### Actual Behavior

`PositionGroupKey.CreateUnitGroup()` changes the signs of the legs.

#### Potential Solution

Keep the original positions' quantity signs (as we keep the unit quantities) and use them in `PositionGroupKey.CreatePositions()` to respect the legs' signs.

#### Reproducing the Problem

Create a `CallCalendarSpread` position group and get the unit group from it.

```csharp
var contracts = chain
    .Where(contract => contract.Right == OptionRight.Call)
    .OrderBy(x => x.Expiry)
    ThenBy(x => x.Strike)
    ToList();
var shortCall = contracts.First();
var longCall = contracts.First(contract => contract.Expiry > shortCall.Expiry && contract.Strike == shortCall.Strike);

var strategy = OptionsStrategies.CallCalendarSpread(_optionSymbol, shortCall.Strike, shortCall.Expiry, longCall .Expiry);
Buy(strategy, 10);

// The short position quantity is -10 and the long one is 10
var group = Portfolio.PositionGroups.Single();

// The short position quantity here should be -1 but is 1. The long position quantity is correct, 1.
var unitGroup = group.Key.CreateUnitGroup();
```

For a covered call, the position unit quantity is ignored:

```csharp
var contracts = chain
    .Where(contract => contract.Right == OptionRight.Call)
    .OrderBy(x => x.Expiry)
    ThenBy(x => x.Strike)
    ToList();
var call = contracts.First();

var legs = new List<Leg> { Leg.Create(call .Symbol, -1), Leg.Create(call.Symbol.Underlying, 100) };
ComboMarketOrder(legs, 10);

var group = Portfolio.PositionGroups.Single();
Log($"Position group quantity: {group.Quantity}"); // Will log -10 because the first leg is the short option one
Log($"Position group underlying leg quantity: {group .GetPosition(call.Symbol.Underlying).Quantity}"); // Will log 1000 (10 * 100), which is correct 

var unitGroup = group.Key.CreateUnitGroup();
Log($"Unit position group quantity: {unitGroup.Quantity}"); // Will log 1
Log($"Unit position group option leg quantity: {unitGroup.GetPosition(call.Symbol).Quantity}"); // Will log 1, should be -1
Log($"Unit position group underlying leg quantity: {unitGroup.GetPosition(call.Symbol.Underlying).Quantity}"); // Will log 1, should be 100
```

#### System Information

Windows 11

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### LINKED ISSUE #7236: Incorrect position group side for some strategies
#### Expected Behavior

The `PositionGroupExtensions.GetPositionSide()` extension gets the right position side for every strategy definition.

#### Actual Behavior

The ` PositionGroupExtensions.GetPositionSide()` extension gets the wrong position side for some strategy definitions. If you **buy** a call calendar spread for instance, the position side returned by the extension method is `PositionSide.Short`, because the `PositionGroup.Quantity` is negative.

This can affect buying power calculations, for instance if you try to sell part of the strategy you bought, the order direction will be _sell_, the existing position side is _short_ and then [this](https://github.com/QuantConnect/Lean/blob/17639c399df5974435017d491b54f5d304b49b26/Common/Securities/Positions/PositionGroupBuyingPowerModel.cs#L449) would return false and the position reduction will not be taken into account for the buying power calculation.

#### Potential Solution

Have the `PositionGroup.Quantity` hold the quantity with the sign corresponding to the original order direction. Currently it is calculated using [the quantity and unit quantity of the first position in the group](https://github.com/QuantConnect/Lean/blob/17639c399df5974435017d491b54f5d304b49b26/Common/Securities/Positions/PositionGroup.cs#L86), so every strategy definition which first leg side is short would end up having the opposite sign of the original order.

#### Reproducing the Problem

```csharp
var contracts = chain
    .Where(contract => contract.Right == OptionRight.Call)
    .OrderBy(x => x.Expiry)
    ThenBy(x => x.Strike)
    ToList();
var shortCall = contracts.First();
var longCall = contracts.First(contract => contract.Expiry > shortCall.Expiry && contract.Strike == shortCall.Strike);

var strategy = OptionsStrategies.CallCalendarSpread(_optionSymbol, shortCall.Strike, shortCall.Expiry, longCall .Expiry);
Buy(strategy, 10);

var group = Portfolio.PositionGroups.Single();
Log($"Position group quantity: {group.Quantity}"); // Will log -10 even though we bought
Log($"Position group side: {group.GetPositionSide()}"); // Will log -1 (PositionGroup.Short)
```

#### System Information

Windows 11

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### LINKED ISSUE #7265: Unhandled InvalidOperationException in GetLongCallShortCallStrikeDifferenceMargin
#### Expected Behavior
Methods in ` OptionStrategyPositionGroupBuyingPowerModel` do not throw unhandled exceptions.

#### Actual Behavior
```
Runtime Error: Sequence contains more than one matching element in OptionStrategyPositionGroupBuyingPowerModel.cs:line 307
```

#### Reproducing the Problem
This is a version of IndexOptionBearCallSpreadAlgorithm where I removed SPY trading and I buy 100 instead of 1 bear call spread. I aimed for an insufficient buying power case, but got the exception. 

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_8860898ea497b79c1e06aad0ccab8da7.html

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

Currrently, the `PositionGroupBuyingPowerModel` is calculating the order size that requires a margin equal to the given delta, assuming a linear change in margin. This fix makes it so that it calculates the position group order quantity required to get the given buying power delta, or in other words, to get a final position group with a final margin that is at most a given percentaje of the total portfolio value.

The resulting quantity returned by `GetMaximumLotsForTargetBuyingPower` and `GetMaximumLotsForDeltaBuyingPower` is the quantity to order using the `parameters.PositionGroup` as template

- A positive target might mean increasing or decreasing the current position group:
    - If `parameters.TargetBuyingPower` < current used buying power, decreasing the current position.
    - If `parameters.TargetBuyingPower` > current used buying power, increasing the current position.
- A negative target buying power means you want to close the position and go towards the opposite side (invert).
- A positive delta buying power means you want to increase the current position.
- A negative delta buying power could mean two things:
    - If `currentUsedMargin + deltaBuyingPower >= 0`, decreasing the current position group, but staying in the same side.
    - If `currentUsedMargin + deltaBuyingPower < 0`, closing the current position group,  and going towards the opposite side (invert).

To have a more accurate implementation the following changes/fixes were made:

1. `PositionGroup.Quantity` for groups with multiple securities is now absolute, since there is not real general sense of "short" or "long" side when there are multiple securities involved. Single-position groups keep their sign.
2. The `PositionGroupBuyingPowerModel` works with the aboslute value of the position group quantity in order to be able to handle single-position groups as well.
3. The `OptionStrategyPositionGroupResolver.GetPositionGroups` method was fixed in order to set the right unit quantity for each resolved position.
4. `PositionExtensions.WithLots` now consideres the original position quantity sign.
5. `PositionGroupKey.CreateUnitGroup` is now a `PositionGroup` extension method.
6. `PositionGroupExtensions.GetPositionSide` was removed, for the same reason as (1).
      -  The new `PositionGroupExtensions.Closes` method is used instead to determine whether new target position group is a reduction of an existing position in `PositionGroupBuyingPowerModel.GetPositionGroupBuyingPower`.

**Notes:**
- `OptionStrategyMarginCallEventsAlgorithm` stats changed because the margin call order size changed for that algorithm. It was 2 but actually 1 was enough the get the portfolio back within the available margin. A check was added to the algorithm for future reference.

#### Related Issue

The bug was found while working on the solution for #7184
Closes #7235
Closes #7236
Closes #7265  

#### How Has This Been Tested?

- Unit tests.
- Regression algorithm.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Securities/OptionStrategyPositionGroupBuyingPowerModelTests.cs [hunk 1]
```diff
@@ -785,145 +801,152 @@ public void GetsMaintenanceMargin(OptionStrategyDefinition optionStrategyDefinit
...
             new TestCaseData(OptionStrategyDefinitions.CoveredCall, 10, 185000m / 10, +1),
             new TestCaseData(OptionStrategyDefinitions.CoveredCall, 10, -185000m / 10, -1),
             new TestCaseData(OptionStrategyDefinitions.CoveredCall, 10, -185000m, -10),
-            // Maintenance margin for CoveredCall with quantity -10 is 30000
+            new TestCaseData(OptionStrategyDefinitions.CoveredCall, 10, -185000m - 30000m, -20),    // Going from 10 to -10
             new TestCaseData(OptionStrategyDefinitions.CoveredCall, -10, 30000m / 10, +1),
             new TestCaseData(OptionStrategyDefinitions.CoveredCall, -10, -30000m / 10, -1),
             new TestCaseData(OptionStrategyDefinitions.CoveredCall, -10, -30000m, -10),
-            // Maintenance margin for ProtectiveCall with quantity 10 is 30000
+            new TestCaseData(OptionStrategyDefinitions.CoveredCall, -10, -30000m - 185000m, -20),   // Going from -10 to 10
```
Comment (Martin-Molinero) [inline Tests/Common/Securities/OptionStrategyPositionGroupBuyingPowerModelTests.cs:818]: 🤩

**Review by Martin-Molinero — APPROVED** [review]
Thank you 💪
