### PR TITLE
Fixes RenkoConsolidator for python

### LINKED ISSUE #1742: RenkoConsolidator returns None in Python
#### Expected Behavior

`RenkoConsolidator().DataConsolidated` should return the Event Handler method in Python
#### Actual Behavior

`RenkoConsolidator` defined two `DataConsolidated` and pythonnet is picking the first that is null. 

#### Reproducing the Problem

```
class RenkoConsolidatorAlgorithm(QCAlgorithm):
    def Initialize(self):

        self.SetCash(100000)
        self.SetStartDate(2012, 1, 1)
        self.SetEndDate(2013, 1, 1)
        self.AddEquity("SPY")
        renkoClose = RenkoConsolidator(2.5)
        renkoClose.DataConsolidated += self.renkoCloseHandler
        self.SubscriptionManager.AddConsolidator("SPY", renkoClose)
        
    def renkoCloseHandler(self, sender, bar):
        self.Log("CLOSE - {0} - {1} {2}".format(str(data.Time), data.Open, data.Close))
```
#### System Information

LEAN Cloud
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
- Missing `event` keyword prevented pythonnet to recognize `DataConsolidated` as a event handler.
- Adds python version of `RenkoConsolidatorAlgorithm`.

#### Related Issue
Closes #1742

#### Motivation and Context
It was not possible to attach events to renko consolidators.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Existing tests and new algorithm.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Data/Consolidators/RenkoConsolidator.cs [hunk 1]
```diff
@@ -111,6 +113,32 @@ public RenkoConsolidator(decimal barSize, Func<IBaseData, decimal> selector, Fun
...
+            : this(barSize, evenBars)
+        {
+            if (barSize < Extensions.GetDecimalEpsilon())
+            {
+                throw new ArgumentOutOfRangeException("barSize", "RenkoConsolidator bar size must be positve and greater than 1e-28");
+            }
+
+            Func<IBaseData, decimal> selectorWrapper;
+            selector.TryConvertToDelegate(out selectorWrapper);
+            _selector = selectorWrapper ?? (x => x.Value);
```
Comment (mchandschuh) [inline Common/Data/Consolidators/RenkoConsolidator.cs]: if we fail to convert it to a delegate *and* it's not null, shouldn't we throw an error? Presumably the user *thinks* their code is going to be used, but instead we'll just end up using the `Value` property.

File: Common/Data/Consolidators/RenkoConsolidator.cs [hunk 2]
```diff
@@ -111,6 +113,32 @@ public RenkoConsolidator(decimal barSize, Func<IBaseData, decimal> selector, Fun
...
+
+            Func<IBaseData, decimal> volumeSelectorWrapper;
+            volumeSelector.TryConvertToDelegate(out volumeSelectorWrapper);
+            _volumeSelector = volumeSelectorWrapper ?? (x => 0);
```
Comment (mchandschuh) [inline Common/Data/Consolidators/RenkoConsolidator.cs]: I think the same goes here -- can do something like this for both of them -- and perhaps, this should be moved into a helper method that isn't a `TryConvertXXX` but is a `ConvertXXX` -- sometimes we want to throw if we can't convert and other times we don't care, but :
``` csharp
if (volumeSelector != null)
{
    if  (!volumeSelector.TryConvertToDelegate(out _volumeSelector))
    {
        throw new ArgumentException("Unable to convert parameter 'volumeSelector' to delegate type Func<IBaseData, decimal>");
    }
}
else
{
    _volumeSelector = (x => 0);
}
```

File: Common/Data/Consolidators/RenkoConsolidator.cs [hunk 3]
```diff
@@ -26,7 +27,7 @@ public class RenkoConsolidator : IDataConsolidator
         /// <summary>
         /// Event handler that fires when a new piece of data is produced
         /// </summary>
-        public EventHandler<RenkoBar> DataConsolidated;
+        public event EventHandler<RenkoBar> DataConsolidated;
```
Comment (mchandschuh) [inline Common/Data/Consolidators/RenkoConsolidator.cs]: oh wow, this was a huge bug actually.

File: Common/Data/Consolidators/RenkoConsolidator.cs [hunk 4]
```diff
@@ -119,62 +147,39 @@ public RenkoConsolidator(decimal barSize, Func<IBaseData, decimal> selector, Fun
...
-            }
-        }
+        internal RenkoBar OpenRenkoBar => new RenkoBar(null, _openOn, _closeOn, _barSize, _openRate, _highRate, _lowRate, _closeRate);
 
         private void Rising(IBaseData data)
         {
             decimal limit;
 
-            while (_closeRate > (limit = (_openRate + BarSize)))
+            while (_closeRate > (limit = _openRate + _barSize))
```
Comment (mchandschuh) [inline Common/Data/Consolidators/RenkoConsolidator.cs]: >NO CHANGE REQUIRED

Interesting choice to convert these usages, also somewhat surprised we didn't turn them into automatic, get-only property, since `_barSize` is read-only already.

File: Common/Data/Consolidators/RenkoConsolidator.cs [hunk 5]
```diff
@@ -351,21 +351,16 @@ public void Scan(DateTime currentLocalTime)
...
             Consolidated = consolidated;
         }
 
         /// <summary>Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.</summary>
         /// <filterpriority>2</filterpriority>
-        public void Dispose()
-        {
-            _dataConsolidatedHandler = null;
-        }
+        public void Dispose() => _dataConsolidatedHandler = null;
```
Comment (mchandschuh) [inline Common/Data/Consolidators/RenkoConsolidator.cs]: Hmm, seems like an existing bug, but I think we can also set `DataConsolidated = null` here as well. As currently written, we're only clearing out event handlers on the `IDataConsolidator.DataConsolidated` event and not the well-typed `RenkoConsolidator.DataConsolidated` event.

File: Common/Data/Consolidators/RenkoConsolidator.cs (hunk 4 above)
Comment (AlexCatarino) [reply Common/Data/Consolidators/RenkoConsolidator.cs]: I left `BarSize` there, because it is a public property and removing it could break user's code.

Comment (mchandschuh) [reply Common/Data/Consolidators/RenkoConsolidator.cs]: of course! I wasn't recommending removing the `BarSize` property, was just stating that it appears we don't even need a `_barSize` field, since we could define the property as:
``` csharp
public decimal BarSize { get; }
```

and then have everyone reference that property and completely remove the `_barSize` field -- but no matter, what's here is great!

**Comment by mchandschuh** [comment]
Great sutff @AlexCatarino  -- if you find yourself using that tryconvert pattern again with a default value, consider making a utility method, maybe something of the form:

```csharp
public static ConvertToDelegate<T>(this PyObject pyObject, T defaultValue = null)
    where T : class
{
    if (pyObject == null)
    {
        return defaultValue;
    }

    T output;
    if (!pyObject.TryConvertToDelegate(out output)
    {
        return defaultValue;
    }

    return output;
}
```
