### PR TITLE
Fix bug in VolumeWeightedAveragePriceIndicator

### LINKED ISSUE #4964: VolumeWeightedAveragePriceIndicator reset
#### Expected Behavior

- `VolumeWeightedAveragePriceIndicator.Reset()` leaves residual unrequired `CompositeIndicator` instances on each call
#### Actual Behavior

- `VolumeWeightedAveragePriceIndicator.Reset()` calls `WeightedBy()` but does not dispose of the previous `WeightedBy` -> `CompositeIndicator` which will continue to receive updates
#### Potential Solution

- `VolumeWeightedAveragePriceIndicator`: Instead of creating a new `WeightedBy` could we reset it?
- `CompositeIndicator` should be disposed of correctly when no longer used.
- Review usages of the `CompositeIndicator` and make sure they are all disposed of correctly. This bug is probably happening in other use cases too.
#### Reproducing the Problem

`VolumeWeightedAveragePriceIndicatorTests.ComparesAgainstExternalDataAfterReset`
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Marinovsky**
#### Description

When this indicator was reset, instead of reset its VolumeWeightedAveragePrice composite indicator, it created a new one. So the previous was never disposed. In order to fix this, there was created a new indicator called `ResetCompositeIndicator.cs` that takes a composite indicator and an action to execute once the given indicator is reset. Therefore, when `Reset()` method is called in `VolumeWeightedAveragePriceIndicator`, the `VolumeWeightedAveragePriceIndicator` is reset instead of re-assigned. Immediately after , this `ResetCompositeIndicator` executes the given action to reset variables used in `IndicatorExtensions.WeightedBy()` method.

On the other hand, `IndicatorExtensions.cs` was reviewed to ensure this bug was not in other usages of `CompositeIndicator`
#### Related Issue

Closes #4964 
#### Motivation and Context

With this change, LEAN will no create a new composite indicator once `VolumeWeightedAveragePriceIndicator` is reset. Additionally, users will be able to assign an action to execute once certain indicator is reset.
#### Requires Documentation Change

This change does not require updates to documentation
#### How Has This Been Tested?

There was created a unit test that asserted `VolumeWeightedAveragePrice` field in `VolumeWeightedAveragePriceIndicator.cs` was the same before and after the indicator was reset
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Indicators/IndicatorExtensions.cs [hunk 1]
```diff
@@ -70,7 +70,7 @@ public static T Of<T>(this T second, IIndicator first, bool waitForFirstToReady
         /// <param name="weight">Indicator that provides the average weights</param>
         /// <param name="period">Average period</param>
         /// <returns>Indicator that results of the average of first by weights given by second</returns>
-        public static CompositeIndicator WeightedBy<T, TWeight>(this IndicatorBase<T> value, TWeight weight, int period)
+        public static ResetCompositeIndicator WeightedBy<T, TWeight>(this IndicatorBase<T> value, TWeight weight, int period)
```
Comment (jhonabreul) [inline Indicators/IndicatorExtensions.cs:73]: `ResetCompositeIndicator` can be a `CompositeIndicator` that overrides the `Reset` method, that way we don't change the `WeightedBy` API (keep returning `CompositeIndicator`) and users can still access every member of the `CompositeIndicator` as per usual.

File: Indicators/ResetCompositeIndicator.cs [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+ * limitations under the License.
+*/
+
+using QuantConnect.Data;
+using System;
+
+namespace QuantConnect.Indicators
+{
+    /// <summary>
+    /// Class that extends CompositeIndicator to execute a given action once is reset
```
Comment (jhonabreul) [inline Indicators/ResetCompositeIndicator.cs:22]: As commented in `WeightedBy` (and also in this summary), we can extend `CompositeIndicator`.

File: Indicators/ResetCompositeIndicator.cs [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+
+        /// <summary>
+        /// Gets current value of the given CompositeIndicator
+        /// </summary>
+        public IndicatorDataPoint Current => _compositeIndicator.Current;
+
+        /// <summary>
+        /// Gets a flag indicating when the given CompositeIndicator is ready
+        /// </summary>
+        public override bool IsReady => _compositeIndicator.IsReady;
```
Comment (jhonabreul) [inline Indicators/ResetCompositeIndicator.cs:44]: It should also override the remaining `CompositeIndicator` properties so that the users can access the inner composite indicator instance properties.

File: Indicators/ResetCompositeIndicator.cs [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+        {
+            _compositeIndicator.Reset();
+            _extraResetAction.Invoke();
+        }
+
+        /// <summary>
+        /// Updates the given CompositeIndicator
+        /// </summary>
+        /// <param name="input"></param>
+        /// <returns></returns>
```
Comment (jhonabreul) [inline Indicators/ResetCompositeIndicator.cs:82]: Missing param and returns comments

File: Tests/Indicators/VolumeWeightedAveragePriceIndicatorTests.cs [hunk 5]
```diff
@@ -82,5 +82,34 @@ public override void ResetsProperly()
...
+            foreach (var data in TestHelper.GetTradeBarStream(TestFileName))
+            {
+                indicator.Update(data);
+            }
+            Assert.IsTrue(indicator.IsReady);
+
+            var lastVWAP = indicator.GetVolumeWeightedAveragePrice();
+            indicator.Reset();
+            var newVWAP = indicator.GetVolumeWeightedAveragePrice();
+            Assert.IsTrue(Object.ReferenceEquals(lastVWAP, newVWAP));
```
Comment (jhonabreul) [inline Tests/Indicators/VolumeWeightedAveragePriceIndicatorTests.cs:100]: Perhaps assert new state (number of samples/not ready) of the VWAP after reset

**Review by jhonabreul — CHANGES_REQUESTED** [review]
Nice! Leaving a few comments:

- Could also add unit tests for this new `ResetCompositeIndicator` class, creating a composite indicator (any), wrapping it up with this class, updating until ready, resetting and asserting the state of each single indicator/part that composes it.
- Also could assert that each `CompositeIndicator` property when accessed in an instance of `ResetCompositeIndicator` is properly bypassed to the inner composite indicator. 
- Having these tests might be enough to revert changes in `Indicators/VolumeWeightedAveragePriceIndicator.cs` and keeping _vwap private and as a `CompositeIndicator`.

**Review by jhonabreul — APPROVED** [review]
Thank you! 🚀

File: Indicators/VolumeWeightedAveragePriceIndicator.cs [hunk 6]
```diff
@@ -74,9 +74,7 @@ public VolumeWeightedAveragePriceIndicator(string name, int period)
         /// </summary>
         public override void Reset()
         {
-            _price.Reset();
-            _volume.Reset();
```
Comment (Martin-Molinero) [inline Indicators/VolumeWeightedAveragePriceIndicator.cs:78]: We should still reset `_price/_volume` I think?

**Review by Martin-Molinero — APPROVED** [review]
Nice! minor comment 👍

**Review by Martin-Molinero — APPROVED** [review]
