### PR TITLE
Fix JSON deserialization for Split and Delisting

### LINKED ISSUE #2084: Split and Delisting objects not deserialized properly from JSON
#### Expected Behavior
All public properties should be deserialized.

#### Actual Behavior
The following properties are not deserialized:
- `Split.Type`
- `Split.SplitFactor`
- `Delisting.Type`

#### Potential Solution
Add the `[JsonProperty]` attribute to the above properties.

#### Reproducing the Problem
Deserialize a JSON string into `Split` or `Delisting` objects.

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
Add missing `[JsonProperty]` attributes to `Split` and `Delisting` properties

#### Related Issue
Closes #2084 

#### Motivation and Context
A few public properties are not being deserialized.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Unit tests included.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/ect)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Data/Auxiliary/AuxiliaryDataSerializationTests.cs [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+    {
+        private readonly JsonSerializerSettings _settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All };
+
+        [Test]
+        public void DeserializesSplitWarning()
+        {
+            var splitWarning = new Split(Symbols.AAPL, new DateTime(2014, 6, 9), 645.57m, 0.142857m, SplitType.Warning);
+
+            var json = JsonConvert.SerializeObject(splitWarning, _settings);
+            var deserialized = (Split)JsonConvert.DeserializeObject(json, _settings);
```
Comment (mchandschuh) [inline Tests/Common/Data/Auxiliary/AuxiliaryDataSerializationTests.cs]: no need to change, can also use syntax like `JsonConvert.DeserializeObject<Split>` instead of using the direct cast.
