### PR TITLE
Bug 4835 api tests failing

### LINKED ISSUE #4835: API Tests Failing
#### Expected Behavior

All API tests pass

#### Actual Behavior

image

Basic API tests are failing when they shouldn't be. Here is my findings:

Endpoint problems:
- CreateBacktest() is failing on the CSharpProject & PythonProject test; No error
- AddProjectFile() is failing on the FSharpProject test <= The error say it doesn't support file extension?? It is a .fs file? Did we remove FSharp?
- ReadPrices() is failing for both 1Symbol and MultipleSymbols, API response has no helpful data on the problem is.

Test Problem:
- GetDividends and GetSplits tests fail because the AAPL data does not match the asserted values. Endpoint seem to be working, but values are slightly off? Maybe an adjustment to the data?
- CRUD_ProjectFiles_SucessFully : The apis return on our fake file doesn't match the code I give it, in fact the response code attribute is null. Could be endpoint issue, requires more studying. 

For the brokerage/data provider tests, maybe we should seperate them since they require configs for each API?

#### Potential Solution

Go through and adjust tests, maybe separate brokerage tests for simplifying test fixtures 

#### Reproducing the Problem

Run RestApiTests with UserId and Token

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

API & API test fixes to reflect current web API.

#### Related Issue

Closes #4835 

#### Motivation and Context

Ref  #4835 

Address some dead API endpoints, cleanup of certain api test functions, fixes for misaligned lean to web api.

#### Requires Documentation Change

API Documentation

#### How Has This Been Tested?

All QuantConnect.Tests.Api tests are 

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/API/ApiIBTests.cs [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+            var compile = _api.CreateCompile(project.Projects.First().ProjectId);
+            Assert.IsTrue(compile.Success);
+
+            // Create default algorithm settings
+            var settings = new InteractiveBrokersLiveAlgorithmSettings(user,
+                                                                       password,
+                                                                       account);
+
+            // Wait for project to compile
+            Thread.Sleep(10000);
```
Comment (Martin-Molinero) [inline Tests/API/ApiIBTests.cs:87]: Think we could replace this (and the other cases) by a call to `_api.ReadCompile()` every 1sec, also as a way of testing that endpoint

File: Tests/API/ApiTradierTests.cs [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+                Assert.IsTrue(liquidateLive.Success);
+
+                // Stop live algorithm
+                var stopLive = _api.StopLiveAlgorithm(project.Projects.First().ProjectId);
+                Assert.IsTrue(stopLive.Success);
+
+                // Delete the project
+                var deleteProject = _api.DeleteProject(project.Projects.First().ProjectId);
+                Assert.IsTrue(deleteProject.Success);
+            }
```
Comment (Martin-Molinero) [inline Tests/API/ApiTradierTests.cs:109]: Pretty cool tests! 👍 They seem **very** similar though, I think we could create a base `ApiLiveTradingTests` (or similar) and abstract the core behavior into a method there?

**Review by Martin-Molinero — CHANGES_REQUESTED** [review]
Cool stuff! Leaving minor requests
The branch needs a rebase from `master` due to the rename QuantConnect.API to QuantConnect.Api

**Comment by C-SELLERS** [comment]
Currently working through web API problems, code on Lean side is ready for review.

**Comment by C-SELLERS** [comment]
All web API endpoint issues related to these tests have now been fixed, the only things left to be tested is Oanda, IB, FXCM, and Tradier specific tests. Do we have some test accounts to run these through or should I create some?

**Comment by C-SELLERS** [comment]
Issues with `live/*` endpoints in `ApiLiveTradingTest`, park this PR until more information on Web API params are given and fixes for `Api.cs` are in place.

**Comment by C-SELLERS** [comment]
@Martin-Molinero 

Alright fixes are in for `ApiLiveTradingTest`'s, unfortunately there is no demo Tradier account so I can't confirm that one passes but the core logic is shared and the rest all pass.

Also an issue with `LiveAlgorithmSettings_CanBeCreated_Successfully()` needs to be resolved but I created a ticket for it at #4864  Currently it will fail because it expects all supported Brokerages to have a LiveAlgorithmSettings subclass, we could remove the exception for the default case of the switch statement therefore allowing it to pass.

File: Brokerages/ApiPriceProvider.cs [hunk 3]
```diff
@@ -54,19 +54,8 @@ public ApiPriceProvider(int userId, string userToken)
...
-
-            var priceData = result.Prices.FirstOrDefault(x => x.Symbol == symbol);
-            if (priceData == null)
-            {
-                throw new Exception($"No price data available for symbol: {symbol.Value}");
-            }
-
-            return priceData.Price;
+            //NOP ReadPrices endpoint has been removed
+            throw new Exception("Prices endpoint is no longer supported");
```
Comment (Martin-Molinero) [inline Brokerages/ApiPriceProvider.cs:58]: nit - might be more precise to throw something like `InvalidOperationException`

File: Algorithm.CSharp/BasicTemplateAlgorithm.cs [hunk 4]
```diff
@@ -119,4 +119,4 @@ public override void OnData(Slice data)
             {"OrderListHash", "491919591"}
         };
     }
-}
+}
```
Comment (Martin-Molinero) [inline Algorithm.CSharp/BasicTemplateAlgorithm.cs:122]: nit - might be a nice git exercise to remove this file 😃

File: Tests/Api/ApiLiveTradingTests.cs [hunk 5]
```diff
@@ -0,0 +1,346 @@
...
+using NUnit.Framework;
+using QuantConnect.Api;
+using QuantConnect.Brokerages;
+using QuantConnect.Configuration;
+
+namespace QuantConnect.Tests.API
+{
+    [TestFixture, Ignore("These tests require configured and active accounts to Interactive Brokers, FXCM, Oanda, and Tradier " +
+         "as well as your Organization ID and available live nodes")]
+    class ApiLiveTradingTests
```
Comment (Martin-Molinero) [inline Tests/Api/ApiLiveTradingTests.cs:30]: Should be `public` I think? Not sure it will be found by the test framework if not

File: Tests/Api/ApiLiveTradingTests.cs [hunk 6]
```diff
@@ -0,0 +1,346 @@
...
+            Assert.IsTrue(liveLogs.Success);
+            Assert.IsTrue(liveLogs.Logs.Any());
+        }
+
+        /// <summary>
+        /// Runs the algorithm with the given settings and file
+        /// </summary>
+        /// <param name="settings">Settings for Lean</param>
+        /// <param name="file">File to run</param>
+        private void RunLiveAlgorithm(BaseLiveAlgorithmSettings settings, ProjectFile file)
```
Comment (Martin-Molinero) [inline Tests/Api/ApiLiveTradingTests.cs:286]: Ah beautiful!

**Review by Martin-Molinero — APPROVED** [review]
Looks good! Minor final comments

> Also an issue with LiveAlgorithmSettings_CanBeCreated_Successfully() needs to be resolved but I created a ticket for it at #4864 Currently it will fail because it expects all supported Brokerages to have a LiveAlgorithmSettings subclass

Since the fixture is ignored I think it looks good as is 👍

File: Algorithm.CSharp/BasicTemplateAlgorithm.cs (hunk 4 above)
Comment (C-SELLERS) [reply Algorithm.CSharp/BasicTemplateAlgorithm.cs:122]: Necessary change, removes /r/n from end of file. Important for test that uploads code and then reads the code in the cloud to compare.

File: Brokerages/ApiPriceProvider.cs (hunk 3 above)
Comment (C-SELLERS) [reply Brokerages/ApiPriceProvider.cs:58]: Gotcha!

File: Tests/Api/ApiLiveTradingTests.cs (hunk 5 above)
Comment (C-SELLERS) [reply Tests/Api/ApiLiveTradingTests.cs:30]: Got it! It seems to work anyway but might as well clarify that it is public!

File: Tests/Api/ApiLiveTradingTests.cs (hunk 6 above)
Comment (C-SELLERS) [reply Tests/Api/ApiLiveTradingTests.cs:286]: Thank you!
