### PR TITLE
Fix LiveEquityDataSynchronizingEnumerator for input data after the current time

### LINKED ISSUE #3335: LiveEquityDataSynchronizingEnumerator stops emitting if underlying data available earlier
#### Expected Behavior
The `LiveEquityDataSynchronizingEnumerator` should handle data from the underlying streams with timestamps greater than the current time.

#### Actual Behavior
The `LiveEquityDataSynchronizingEnumerator` stops emitting data if it receives data from the underlying streams with timestamps greater than the current time.

#### Potential Solution
n/a

#### Reproducing the Problem
Check the count of emitted data points in the existing `LiveEquityDataSynchronizingEnumeratorTests.SynchronizesData` 

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
Previously the enumerator would get stuck and stop emitting data if one of the underlying enumerators returned a data point with the time greater than the current time. The existing unit test would only emit the first data point for the two underlying streams.

The enumerator has been updated to support data points in the future and the unit test has been extended to assert both data point counts and values.

#### Related Issue
Closes #3335 

#### Motivation and Context
`LiveEquityDataSynchronizingEnumerator` not emitting data in some cases.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
- The existing unit test has been expanded to cover the failing case.
- An equity live algorithm has also been tested in the cloud

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by mchandschuh** [comment]
@StefanoRaggi -- can you provide a little more background as to what led to this? Was it our regular equity feed that received a future tick and then it permanently froze?

File: Engine/DataFeeds/Enumerators/LiveEquityDataSynchronizingEnumerator.cs [hunk 1]
```diff
@@ -120,7 +111,7 @@ public void Dispose()
         private bool DataPointEmitted(DateTime frontierUtc)
         {
             // check if any enumerator is ready to emit
-            if (_auxDataEnumeratorAdvanced && _auxDataEnumerator.Current != null && _tradeBarEnumeratorAdvanced && _tradeBarAggregator.Current != null)
+            if (_auxDataEnumerator.Current != null && _tradeBarAggregator.Current != null)
```
Comment (mchandschuh) [inline Engine/DataFeeds/Enumerators/LiveEquityDataSynchronizingEnumerator.cs]: When do we receive aux data in live mode? I'm thinking of a symbol change or a dividend event. IIRC, they come in almost 24 hours before they need to be emitted on the feed, BICBW, they might come down just-in-time.

I believe this was trying to support a case where we get aux data but we must wait for time to elapse before emitting it, and while waiting for time to elapse, we are still emitting from the `_tradeBarAggregator`. It looks like this behavior has been removed through removal of the enumerator advanced flags.

If possible, we should spin up some test algorithms with equities with known upcoming aux data events (dividends are the easiest) running at various data resolutions complete with some good logging.

Comment (StefanoRaggi) [reply Engine/DataFeeds/Enumerators/LiveEquityDataSynchronizingEnumerator.cs]: Yes, I believe the only aux data we currently have in live mode is split and dividend warnings and events, you wrote the scraper 😄 
Totally agree that the enumerator should emit the aux data only at the right time but the current version is not emitting if it comes in too early (i.e. the data has a timestamp greater than the current frontier).
The bug can be verified easily by running the existing unit test and counting the data points emitted (it will only emit 2 instead of 15):
https://github.com/QuantConnect/Lean/blob/master/Tests/Engine/DataFeeds/Enumerators/LiveEquityDataSynchronizingEnumeratorTests.cs#L31
With the fix, the updated test is now passing.

**Comment by StefanoRaggi** [comment]
@mchandschuh I only found the bug when running additional unit tests for the `LiveTradingDataFeed` (including aux data) and also found that the existing unit test was not working properly (just by counting the points emitted).

File: Engine/DataFeeds/Enumerators/LiveEquityDataSynchronizingEnumerator.cs (hunk 1 above)
Comment (mchandschuh) [reply Engine/DataFeeds/Enumerators/LiveEquityDataSynchronizingEnumerator.cs]: I suppose my real concern is if we emit this data at the wrong time then it can cause issues with live synchronization as it's `EndTime` will be used as a frontier. This will cause the live sync to wait until the end time is reach and if there's other data sitting behind it and it's not sorted, then we'll miss out on that data. Consider the following:

00:00 6.25.2019 we _receive_ aux data w/ end time 00:00 6.26.2019
Since we're emitting immediately, it will go down to live sync, where it will wait until 00:00 6.26.2019.
For the entire day of 6.25.2019, we'll continue to receive pricing data for that symbol, but since the aux data is blocking that enumerator due to frontier time checks, we won't receive any data on 6.25.2019 for that symbol. Once the clock ticks over to 6.26.2019, the aux data will get pushed through _and then_ all the pricing data from 6.25.2019 with timestamps in the past would then finally get pushed through all as a single `DataFeedPacket`

Is my analysis above incorrect? Were we able to run a bunch of equity algorithms with known upcoming splits/dividends events and _prove_ that the above case is not happening?

Comment (StefanoRaggi) [reply Engine/DataFeeds/Enumerators/LiveEquityDataSynchronizingEnumerator.cs]: > 00:00 6.25.2019 we receive aux data w/ end time 00:00 6.26.2019

Unless I'm missing something, this aux data point should not be emitted until 00:00 6.26.2019, 
given the end time frontier check in L120 and L140, right?
While the "early" aux data point is waiting for the end of day 25, price data should still be emitted on L131?

I will follow your suggestion and confirm this with an equity algorithm with an upcoming dividend/split.

**Comment by mchandschuh** [comment]
This is good to go following confirmation from @StefanoRaggi regarding the live equity test _with multiple resolutions_ to ensure the aux data doesn't break the price feed.

**Comment by StefanoRaggi** [comment]
This algorithm was started a few days before known upcoming dividends for a couple of stocks (at Hour and Daily resolutions):

``` C#
    public class TestLiveDividendsHourly : QCAlgorithm
    {
        public override void Initialize()
        {
            SetStartDate(2019, 1, 4);  //Set Start Date
            SetCash(100000);             //Set Strategy Cash
            
            AddEquity("BKSC", Resolution.Hour);
            AddEquity("MA", Resolution.Hour);
        }

        public override void OnData(Slice data)
        {
            foreach (var kvp in data.Dividends)
            {
                Debug($"{Time} - Symbol:{kvp.Key.Value} - {kvp.Value}");
            }

            foreach (var kvp in data.Bars)
            {
                Debug($"{Time} - Symbol:{kvp.Key.Value} - Close:{kvp.Value.Close}");
            }
        }
    }
```

Log for Hour resolution:

```
2019-07-05 06:42:49 Launching analysis for L-3adf1eb6a5833a3e3034f78fa2789337 with LEAN Engine v2.4.0.0.5950
2019-07-05 14:00:00 7/5/2019 10:00:00 AM - Symbol:BKSC - Close:19.02
2019-07-05 14:00:00 7/5/2019 10:00:00 AM - Symbol:MA - Close:269.12
2019-07-05 15:00:00 7/5/2019 11:00:00 AM - Symbol:BKSC - Close:19.02
2019-07-05 15:00:00 7/5/2019 11:00:00 AM - Symbol:MA - Close:270.23
2019-07-05 16:00:00 7/5/2019 12:00:00 PM - Symbol:BKSC - Close:19.02
2019-07-05 16:00:00 7/5/2019 12:00:00 PM - Symbol:MA - Close:271.0801
2019-07-05 17:00:00 7/5/2019 1:00:00 PM - Symbol:BKSC - Close:19.02
2019-07-05 17:00:00 7/5/2019 1:00:00 PM - Symbol:MA - Close:271.33
2019-07-05 18:00:00 7/5/2019 2:00:00 PM - Symbol:BKSC - Close:19.02
2019-07-05 18:00:00 7/5/2019 2:00:00 PM - Symbol:MA - Close:271.5898
2019-07-05 19:00:00 7/5/2019 3:00:00 PM - Symbol:BKSC - Close:19.1439
2019-07-05 19:00:00 7/5/2019 3:00:00 PM - Symbol:MA - Close:272.76
2019-07-05 20:00:00 7/5/2019 4:00:00 PM - Symbol:BKSC - Close:19.38
2019-07-05 20:00:00 7/5/2019 4:00:00 PM - Symbol:MA - Close:272.16
2019-07-08 04:01:52 7/8/2019 12:01:52 AM - Symbol:BKSC - Dividend: BKSC: 0.16 | 18.84
2019-07-08 04:01:52 7/8/2019 12:01:52 AM - Symbol:MA - Dividend: MA: 0.33 | 186.76
2019-07-08 14:00:00 7/8/2019 10:00:00 AM - Symbol:BKSC - Close:19.16
2019-07-08 14:00:00 7/8/2019 10:00:00 AM - Symbol:MA - Close:269.95
2019-07-08 15:00:00 7/8/2019 11:00:00 AM - Symbol:BKSC - Close:18.965
2019-07-08 15:00:00 7/8/2019 11:00:00 AM - Symbol:MA - Close:270.18
2019-07-08 16:00:00 7/8/2019 12:00:00 PM - Symbol:BKSC - Close:18.9674
2019-07-08 16:00:00 7/8/2019 12:00:00 PM - Symbol:MA - Close:270.34
2019-07-08 17:00:00 7/8/2019 1:00:00 PM - Symbol:BKSC - Close:18.9
2019-07-08 17:00:00 7/8/2019 1:00:00 PM - Symbol:MA - Close:270.58
2019-07-08 18:00:00 7/8/2019 2:00:00 PM - Symbol:BKSC - Close:18.8701
2019-07-08 18:00:00 7/8/2019 2:00:00 PM - Symbol:MA - Close:270.96
2019-07-08 19:00:00 7/8/2019 3:00:00 PM - Symbol:BKSC - Close:18.96
2019-07-08 19:00:00 7/8/2019 3:00:00 PM - Symbol:MA - Close:271.1181
2019-07-08 20:00:00 7/8/2019 4:00:00 PM - Symbol:BKSC - Close:19
2019-07-08 20:00:00 7/8/2019 4:00:00 PM - Symbol:MA - Close:271.2669
```

Log for Daily resolution:
```
2019-07-05 06:43:48 Launching analysis for L-4e7408e42f621aff13b8fe7375ef4825 with LEAN Engine v2.4.0.0.5950
2019-07-06 04:00:00 7/6/2019 12:00:00 AM - Symbol:BKSC - Close:19.1
2019-07-06 04:00:00 7/6/2019 12:00:00 AM - Symbol:MA - Close:272.2
2019-07-08 04:01:52 7/8/2019 12:01:52 AM - Symbol:BKSC - Dividend: BKSC: 0.16 | 18.84
2019-07-08 04:01:52 7/8/2019 12:01:52 AM - Symbol:MA - Dividend: MA: 0.33 | 186.76
2019-07-09 04:00:00 7/9/2019 12:00:00 AM - Symbol:BKSC - Close:18.72
2019-07-09 04:00:00 7/9/2019 12:00:00 AM - Symbol:MA - Close:271.23
```
