### PR TITLE
Fix DivideByZeroException in RSI indicator

### LINKED ISSUE #4007: RelativeStrengthIndex Divide By Zero Exception With QuoteBar Data
#### Expected Behavior
Lean indicators do not throw unhandled exceptions.

#### Actual Behavior
`RelativeStrengthIndex` throws `DivideByZeroException` with securities with quote data.

#### Potential Solution
N/A

#### Reproducing the Problem
```python
class RelativeStrengthIndexDivideByZeroException(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2014,5,1)
        
        symbol = self.AddCfd("XAUUSD", Resolution.Minute, Market.Oanda).Symbol
        self.RSI(symbol, 14, Resolution.Daily)
```
It does not throw with SPY.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
- Added a missing check for divide by zero in the `RelativeStrengthIndex (RSI)` indicator.

#### Related Issue
Closes #4007 

#### Motivation and Context
- `DivideByZeroException` 

#### Requires Documentation Change
No.

#### How Has This Been Tested?
- New unit test
- Test algorithm in #4007 

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Indicators/RelativeStrengthIndex.cs [hunk 1]
```diff
@@ -99,7 +99,13 @@ protected override decimal ComputeNextValue(IndicatorDataPoint input)
             }
 
             var rs = AverageGain / AverageLoss;
-            return 100m - (100m / (1 + rs));
+            if (rs == -1m)
+            {
+                // prevent division by zero
+                return 100m;
```
Comment (Martin-Molinero) [inline Indicators/RelativeStrengthIndex.cs]: Fix looks good 👍 
When the value of `rs` is getting close to -1, it starts returning values > 100 and later < -100. Curious if we should be limiting it to 0 to 100?

I get the following logs when adding a `Log.Trace($"{rsi.Current}");` in the unit test
```
200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 97.19626168224299065420560748
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 97.80219780219780219780219780
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 98.70129870129870129870129870
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 100
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 101.81818181818181818181818182
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 104.34782608695652173913043478
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 107.89473684210526315789473684
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 109.375
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 111.11111111111111111111111111
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 113.63636363636363636363636364
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 116.66666666666666666666666667
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 121.42857142857142857142857143
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 127.27272727272727272727272727
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 137.5
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 150
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 175.00000000000000000000000000
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 249.99999999999999999999999999
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 400.00000000000000000000000003
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 100
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - -200.00000000000000000000000003
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - -49.99999999999999999999999999
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 0
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 24.999999999999999999999999998
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 40.000000000000000000000000001
20200316 22:12:10.712 Trace:: 2020-03-17T01:12:10 - 50
```

Comment (StefanoRaggi) [reply Indicators/RelativeStrengthIndex.cs]: @Martin-Molinero I updated the indicator to handle the negative averages which were returning RSI values outside of the expected `[0..100]` range.
