### PR TITLE
Fix warming up bug in Stochastic indicator

### LINKED ISSUE #8405: warm_up_indicator fails to warm up Stochastic indicator
#### Expected Behavior

self.warm_up_indicator(symbol, indicator, timedelta(hours=1) warms up the Stochastic indicator.

#### Actual Behavior

self.warm_up_indicator(symbol, indicator, timedelta(hours=1) does not warm up the Stochastic indicator.

#### Potential Solution

Stochastic indicator extends IIndicatorWarmUpPeriodProvider so it is expected to work
potentially similar to #8246 

#### Reproducing the Problem

Below is code and output of warming up RSI and STO indicators with a manual history request (which works) and the warm_up_indicator() method, which works on the RSI but not the STO...

warmup-bug

```
from datetime import timedelta
from AlgorithmImports import *


class FT1Indexes(QCAlgorithm):
    def initialize(self):
        self.set_start_date(2024, 1, 1)  # monday = holiday..
        self.set_end_date(2024, 2, 1)
        self.set_cash(100000)

        self.spy = self.add_equity("SPY", Resolution.HOUR).symbol

        self.daily_consolidator = TradeBarConsolidator(timedelta(days=1))

        self._rsi = RelativeStrengthIndex(14, MovingAverageType.WILDERS)
        self._sto = Stochastic(14, 3, 3)
        self.register_indicator(self.spy, self._rsi, self.daily_consolidator)
        self.register_indicator(self.spy, self._sto, self.daily_consolidator)

        # warm_up indicator
        self.warm_up_indicator(self.spy, self._rsi, timedelta(days=1))
        self.warm_up_indicator(self.spy, self._sto, timedelta(days=1))


        self._rsi_history = RelativeStrengthIndex(14, MovingAverageType.WILDERS)
        self._sto_history = Stochastic(14, 3, 3)
        self.register_indicator(self.spy, self._rsi_history, self.daily_consolidator)
        self.register_indicator(self.spy, self._sto_history, self.daily_consolidator)

        # history warm up
        history = self.history[TradeBar](self.spy, 20, Resolution.DAILY)
        for bar in history:
            self._rsi_history.update(bar.end_time, bar.close)
            self._sto_history.update(bar)

    def on_data(self, data: Slice):
        if self.is_warming_up:
            return

        if data.contains_key(self.spy):
            chart_name = "warm_up_indicator"
            self.plot(chart_name, "RSI", self._rsi.current.value, Color.Red)
            self.plot(chart_name, "STO K", self._sto.stoch_k.current.value)
            self.plot(chart_name, "STO D", self._sto.stoch_d.current.value)

            chart_name = "History Warmup"
            self.plot(chart_name, "RSI", self._rsi_history.current.value)
            self.plot(chart_name, "STO K", self._sto_history.stoch_k.current.value)
            self.plot(chart_name, "STO D", self._sto_history.stoch_d.current.value)
```

#### System Information

cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Marinovsky**
#### Description

When a stochastic indicator was registered with a consolidator whose resolution differed the symbol one, the method `QCAlgorithm.WarmUpIndicator()` failed warming it up. Since `PeriodCountConsolidatorBase` class was used, it skipped the last bar from history, so the indicator received only `WarmingUpPeriod - 1` points. Thus, the indicator was left unready. Following the pattern of `RelativeStrenghtIndex` indicator, I increased `Stochastic.WarmUpPeriod` by one to solve this bug. I also added unit and regression tests to cover these changes.
#### Related Issue

Closes #8405 
#### Motivation and Context

With this change, Stochastic indicators registered with different resolution consolidators, will be warmed up by `QCAlgorithm.WarmUpIndicator()`
#### Requires Documentation Change

N/A
#### How Has This Been Tested?

Since I increased Stochastic's WarmUpPeriod by one, I had to update the unit test `StochasticTestsWarmsUpProperly()`. On the other hand, as a regression algorithm, I added the algorithm shared by the user reproducing the bug and asserted the bug was solved.
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Algorithm/QCAlgorithm.Indicators.cs [hunk 1]
```diff
@@ -3149,7 +3151,10 @@ private IEnumerable<Slice> GetIndicatorWarmUpHistory(IEnumerable<Symbol> symbols
 
                 try
                 {
-                    return History(symbols, periods, resolution, dataNormalizationMode: GetIndicatorHistoryDataNormalizationMode(indicator));
+                    var symbols = new[] { symbol };
+                    CheckPeriodBasedHistoryRequestResolution(symbols, resolution, null);
+                    historyRequest = CreateBarCountHistoryRequests(symbols, periods, resolution, dataNormalizationMode: GetIndicatorHistoryDataNormalizationMode(indicator)).Single();
+                    return GetSlicesFromHistoryRequests(historyRequest);
```
Comment (jhonabreul) [inline Algorithm/QCAlgorithm.Indicators.cs:3157]: Using the History() API might be enough, if you only need the request end time you could use QCAlgorithm.Time or UtcTime and convert it to the security's time zone to do the final consolidator scan

File: Algorithm.CSharp/StochasticIndicatorWarmsUpProperlyRegressionAlgorithm.cs [hunk 2]
```diff
@@ -0,0 +1,172 @@
...
+
+            WarmUpIndicator(_spy, _rsi, TimeSpan.FromDays(1));
+            WarmUpIndicator(_spy, _sto, TimeSpan.FromDays(1));
+
+            _rsiHistory = new RelativeStrengthIndex(14, MovingAverageType.Wilders);
+            _stoHistory = new Stochastic("SECOND", 14, 3, 3);
+            RegisterIndicator(_spy, _rsiHistory, dailyConsolidator);
+            RegisterIndicator(_spy, _stoHistory, dailyConsolidator);
+
+            var history = History(_spy, 15, Resolution.Daily);
```
Comment (jhonabreul) [inline Algorithm.CSharp/StochasticIndicatorWarmsUpProperlyRegressionAlgorithm.cs:60]: nit - for clarity, might use `Max(_rsi.WarmupPeriod, _sto.WarmupPeriod)` instead of `15`. And then tp update the indicators might use something like `history.TakeLast(indicator.WarmupPeriod)`

**Review by jhonabreul — COMMENTED** [review]
Good! Nice catch on the actual root issue. Leaving a couple comments
