### PR TITLE
Fix LiveTradingDataFeed.CreateDataSubscription with multiple tick types

### LINKED ISSUE #3163: TickConsolidator not receiving live ticks with multi-TickType subscriptions
#### Expected Behavior
The `TickConsolidator` should receive and process live ticks with `TickType.Trade` when subscribing to symbols with multiple tick types (`Crypto`, `Futures`, `Options`).

#### Actual Behavior
The `TickConsolidator` is receiving no ticks and never emits consolidated `TradeBars` in live mode.

#### Potential Solution
The `LiveTradingDataFeed` is not handling tick types properly when creating subscriptions for multiple tick types.

#### Reproducing the Problem
This algorithm works fine in backtesting, but fails to emit consolidated bars in Live mode:
``` C#
public class TestTickConsolidator : QCAlgorithm
{
    public override void Initialize()
    {
        SetStartDate(2016, 10, 07);
        SetEndDate(2016, 10, 08);
        SetCash(100000);

        SetBrokerageModel(BrokerageName.GDAX, AccountType.Cash);
        var security = AddCrypto("BTCUSD", Resolution.Tick);

        var tickConsolidator = new TickConsolidator(TimeSpan.FromMinutes(1));
        tickConsolidator.DataConsolidated += (sender, bar) =>
        {
            Debug($"{Time} Symbol:{bar.Symbol.Value} Close:{bar.Close} Volume:{bar.Volume}");
        };
        SubscriptionManager.AddConsolidator(security.Symbol, tickConsolidator);
    }
}
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
The `LiveTradingDataFeed.CreateDataSubscription` method has been updated to handle multiple tick types properly, with subscriptions at `Resolution.Tick`.
Only `Crypto`, `Future` and `Option` security types were affected by this bug.

#### Related Issue
Closes #3163 

#### Motivation and Context
`TickConsolidator` was not receiving ticks with `TickType.Trade` in live mode.
The reason was that the exchange data handlers were being overwritten (the subscription for the last tick type was the only one receiving ticks, previously added enumerators were created but not used).

#### Requires Documentation Change
No.

#### How Has This Been Tested?
The test algorithm included in #3163 was tested both locally and in the cloud.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/DataFeeds/LiveTradingDataFeed.cs [hunk 1]
```diff
@@ -311,19 +311,62 @@ protected Subscription CreateDataSubscription(SubscriptionRequest request)
                 {
                     // tick subscriptions can pass right through
                     var tickEnumerator = new EnqueueableEnumerator<BaseData>();
-                    _exchange.SetDataHandler(request.Configuration.Symbol, data =>
+
+                    switch (request.Configuration.TickType)
```
Comment (Martin-Molinero) [inline Engine/DataFeeds/LiveTradingDataFeed.cs]: Seems to me we might be able to join the 3 cases together under the same behavior, thoughts? + extra check in the `if` for the `UpdateSubscriptionRealTimePrice` call for `tick.TickType != TickType.OpenInterest`.
I think it would be great if we could add a unit test to cover the issue being fixed

**Comment by jaredbroad** [comment]
Thanks @StefanoRaggi, please rebase and will merge in
