### PR TITLE
Bug 4947 OnOrderEvent exceptions

### LINKED ISSUE #4947: Exception in OnOrderEvent does not fail regression test
#### Expected Behavior

- If regression test algorithm throws an exception in OnOrderEvent the algorithm stops and it fails
#### Actual Behavior

- If regression test algorithm throws an exception in OnOrderEvent the algorithm stops but does NOT fail
#### Potential Solution

- Review `BrokerageTransactionHandler`, add test reproducing issue
#### Reproducing the Problem

```
        public override void Initialize()
        {
            SetStartDate(2013, 10, 07);
            SetEndDate(2013, 10, 11);
            AddEquity("SPY", Resolution.Minute);
        }
        public override void OnData(Slice data)
        {
            if (!Portfolio.Invested)
            {
                SetHoldings(_spy, 1);
            }
        }
        public override void OnOrderEvent(OrderEvent orderEvent)
        {
            throw new Exception("OnOrderEvent exception");
        }
```
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

Have `AlgorithmManager` return when a runtime error is detected, this way we can force it to return a failed state instead of overwriting it with `Completed` status when breaking out of the loop.

#### Related Issue

Closes #4947 

#### Motivation and Context

Following a `RunTimeError` status we should expect that the algorithm will not only stop but also maintain that status instead of replacing with `Completed`. 

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

Regressions ran and passed successfully.
New regression added that is intended to fail.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/AlgorithmManager.cs [hunk 1]
```diff
@@ -689,6 +689,14 @@ public void Run(AlgorithmNodePacket job, IAlgorithm algorithm, ISynchronizer syn
                 results.SendStatusUpdate(AlgorithmStatus.Deleted);
             }
 
+            //Runtime Error.
+            if (_algorithm.Status == AlgorithmStatus.RuntimeError)
+            {
+                Log.Trace("AlgorithmManager.Run(): Algorithm RuntimeError...");
+                Log.Trace("RuntimeError:" + _algorithm.RunTimeError);
```
Comment (Martin-Molinero) [inline Engine/AlgorithmManager.cs:696]: Not sure we need `Log.Trace("RuntimeError:" + _algorithm.RunTimeError);` since it's being logged before? Or maybe above, when detecting the runtimeError, instead of `break` we could directly use `return` as done with all the other `AlgorithmStatus.RuntimeError` cases in this loop, keep it normalized 🤔

File: Algorithm.CSharp/OnOrderEventExceptionRegression.cs [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+using System.Collections.Generic;
+using QuantConnect.Data;
+using QuantConnect.Interfaces;
+using QuantConnect.Orders;
+
+namespace QuantConnect.Algorithm.CSharp
+{
+    /// <summary>
+    /// Regression Algorithm for testing engine behavior with throwing errors in OnOrderEvent
+    /// Should result in a RunTimeError status.
```
Comment (Martin-Molinero) [inline Algorithm.CSharp/OnOrderEventExceptionRegression.cs:26]: Cool! nit - maybe we can add a ref for the GH issue

**Review by Martin-Molinero — COMMENTED** [review]
Nice! minor suggestion

File: Engine/AlgorithmManager.cs (hunk 1 above)
Comment (C-SELLERS) [reply Engine/AlgorithmManager.cs]: Gotcha, I was little worried about line 176 in AlgorithmManager  breaking out of the loop after the error is posted and then it being set the complete again, but now that I took a deeper look at the sequence it makes sense that it would catch it on line 327 after processing all the data for that time slice.

Comment (Martin-Molinero) [reply Engine/AlgorithmManager.cs]: Yeah exactly 👍 because the status isn't being set before but by the AlgorithmManager at 329

**Review by Martin-Molinero — APPROVED** [review]
Nice! thanks 👍
