### PR TITLE
Remove Quandl from LEAN

### LINKED ISSUE #5934: Quandl to Nasdaq Data Link
#### Expected Behavior
Be able to get Quandl data that has moved to [Nasdaq Data Link](https://data.nasdaq.com/).

#### Actual Behavior
The current API endpoint, `https://www.quandl.com/api/v3/datasets/`, doesn't return data.

#### Potential Solution
Use `https://data.nasdaq.com/api/v3/datasets/` instead.

#### Reproducing the Problem
Run `CustomDataIndicatorExtensionsAlgorithm` and verify that no orders are placed.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Marinovsky**
#### Description

- Remove all Quandl mentions from LEAN keeping backwards compatibility with the rest of the project 
#### Related Issue

Closes #6079
Closes #5934
#### Motivation and Context

Quandl data has been merged with Nasdaq Data Link, so the old API is not working anymore
#### Requires Documentation Change

No
#### How Has This Been Tested?

Original unit and regression tests are still applicable
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Engine/DataFeeds/CustomLiveDataFeedTests.cs [hunk 1]
```diff
@@ -281,7 +277,7 @@ public void RemoteDataDoesNotIncreaseNumberOfSlices()
                         Assert.IsTrue(timeSlice.Slice.Values.Any(x => x.Symbol == symbols[0]), $"Slice doesn't contain {symbols[0]}");
                         Assert.IsTrue(timeSlice.Slice.Values.Any(x => x.Symbol == symbols[1]), $"Slice doesn't contain {symbols[1]}");
                         Assert.IsTrue(timeSlice.Slice.Values.Any(x => x.Symbol == symbols[2]), $"Slice doesn't contain {symbols[2]}");
-                        Assert.IsTrue(timeSlice.Slice.Values.Any(x => x.Symbol == symbols[3]), $"Slice doesn't contain {symbols[3]}");
+                        Assert.IsTrue(timeSlice.Slice.Values.Any(x => x.Symbol == symbols[2]), $"Slice doesn't contain {symbols[2]}");
```
Comment (Martin-Molinero) [inline Tests/Engine/DataFeeds/CustomLiveDataFeedTests.cs:280]: hm this assert is the same as the previous line, why are we changing it?

**Review by Martin-Molinero — CHANGES_REQUESTED** [review]
Thanks @Marinovsky! Leaving a few requests and concerns

File: Common/Extensions.cs [hunk 2]
```diff
@@ -2835,9 +2846,7 @@ public static string GetEnumString(this int value, PyObject pyObject)
         public static Type CreateType(this PyObject pyObject)
         {
             Type type;
-            if (pyObject.TryConvert(out type) &&
-                type != typeof(PythonQuandl) &&
-                type != typeof(PythonData))
+            if (pyObject.TryConvert(out type))
```
Comment (Martin-Molinero) [inline Common/Extensions.cs:2849]: Nice to see all the special handling removed 🎇

File: Common/Extensions.cs [hunk 3]
```diff
@@ -2505,11 +2505,22 @@ public static bool TryConvert<T>(this PyObject pyObject, out T result, bool allo
             {
                 try
                 {
+                    if (allowPythonDerivative)
+                    {
+                        result = (T)pyObject.AsManagedObject(type);
```
Comment (Martin-Molinero) [inline Common/Extensions.cs:2510]: Let's add a comment of **why** is this here. 
Would be awesome to expand the tests around `TryConvert` for the specific issues solved and handled here

**Review by Martin-Molinero — APPROVED** [review]
Nice! Thanks for the lean improvements, leaving a couple of minor & final requests!

**Review by Martin-Molinero — APPROVED** [review]
