### PR TITLE
Fix empty dataframe from QuantBook.Indicator

### LINKED ISSUE #2256: QuantBook: empty indicators data frame
#### Expected Behavior
If there is data for a given symbol, `QuantBook.Indicator` method returns a pandas data frame with the indicator information.

#### Actual Behavior
Although there is data for some symbols, the QuantBook.Indicator` method returns a empty data frame.

#### Potential Solution
Verify whether the history request that updates the indicator has data.

#### Reproducing the Problem
```python
btc = qb.AddCrypto("BTCUSD")
startDate = datetime(2016,12,1)
endDate = datetime(2018,4,1)
bb = BollingerBands(10, 2, MovingAverageType.Exponential)
bbdf = qb.Indicator(bb, "BTCUSD", startDate, endDate, Resolution.Daily)
print(bbdf.empty)
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
When a history request is made to update a indicator, it can return an empty enumerable if there is no data from the default data type (e.g.: `QuoteBar` for Crypto). In this case, the indicator should be updated with the available data.

We changed the History requests within `QuantBook.Indicator` the  to fetch `IEnumerable<Slice>` and assure that any data is present.

#### Related Issue
Closes #2256 

#### Motivation and Context
Bug fix.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Manually with code snipped provided in issue #2256.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Jupyter/QuantBook.cs [hunk 1]
```diff
@@ -488,12 +488,14 @@ private PyObject Indicator(IndicatorBase<IndicatorDataPoint> indicator, IEnumera
 
             selector = selector ?? (x => x.Value);
 
-            foreach (var bar in history)
+            foreach (var slice in history)
```
Comment (mchandschuh) [inline Jupyter/QuantBook.cs]: smart -- we should use slices for everything, makes it explicit how we need to handle the various data types.

File: Jupyter/QuantBook.cs [hunk 2]
```diff
@@ -488,12 +488,14 @@ private PyObject Indicator(IndicatorBase<IndicatorDataPoint> indicator, IEnumera
...
             {
-                var value = selector(bar);
-                indicator.Update(bar.EndTime, value);
+                foreach(var bar in slice.Values)
+                {
+                    var value = selector(bar);
```
Comment (mchandschuh) [inline Jupyter/QuantBook.cs]: I think sometimes `bar` here may be a `List<Tick>` -- see `SliceExtensions.PushThrough` to see if you need to do something similar to handle that case.

Comment (AlexCatarino) [reply Jupyter/QuantBook.cs]: `SliceExtensions.PushThrough` is just perfect. Updating the PR... 
Thanks!
