### PR TITLE
Fixes intraday delistings not occurring before contract expiry for Futures and FOPs

### LINKED ISSUE #4980: Delisting liquidation date - GetNextMarketOpen
#### Expected Behavior

- Seems the intent of `AlgoManager.ProcessDelistedSymbols()` is to liquidate on the market close after the delisting date
#### Actual Behavior

- The delisting trade happens 3 days after the delisting date, this is because at `GetNextMarketOpen() -> if (localDateTime < marketOpen)` for FOPs the market open matches the delisting time so it skips that date.
#### Potential Solution

- If the market is already open for `delistingTime` maybe use that instead of calling `GetNextMarketOpen` but this caused some unwanted behavior where the liquidation order got canceled by the `AlgoManager.HandleDelistedSymbols`,
#### Reproducing the Problem

- See `FutureOptionCallITMExpiryRegressionAlgorithm` & `FutureOptionPutITMExpiryRegressionAlgorithm` at https://github.com/QuantConnect/Lean/pull/4928
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by gsalaz98**
#### Description

  * Previously, we would wait until the next market open to
    liquidate futures and futures options contracts. Since these
    contracts can not be traded at the next market open and require
    intraday delisting, changes were made to liquidate at the first
    available place where we know the market is open. This means
    we now liquidate futures and FOPs intraday as a market order.

  * Maintains backwards compatability with equities and equity options
    delisting behavior

#### Related Issue

Partially fixes #4980 - #4973 will correct a few inconsistencies that are not covered in this PR
#### Motivation and Context

Ensure backtesting accuracy
#### Requires Documentation Change

Maybe
#### How Has This Been Tested?

New regression algorithm
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/AlgorithmManager.cs [hunk 1]
```diff
@@ -1041,8 +1041,18 @@ private static void ProcessDelistedSymbols(IAlgorithm algorithm, List<Delisting>
                 var delistingTime = delistings[i].Time;
                 var nextMarketOpen = security.Exchange.Hours.GetNextMarketOpen(delistingTime, false);
                 var nextMarketClose = security.Exchange.Hours.GetNextMarketClose(nextMarketOpen, false);
+                var futureOrFutureOption = security.Type == SecurityType.Future ||
+                    security.Type == SecurityType.FutureOption;
 
-                if (security.LocalTime < nextMarketClose)
+                // Legacy behavior, we want to liquidate at the next market open for any
+                // non-futures/FOPs assets with an expiry
+                if (!futureOrFutureOption && security.LocalTime < nextMarketClose)
```
Comment (Martin-Molinero) [inline Engine/AlgorithmManager.cs:1049]: Not fixing the original issue here, if `delistingTime` is at market open the `GetNextMarketOpen` will return the next day, missing something like:
```
                var nextMarketOpen = delistingTime;
                if (!security.Exchange.Hours.IsOpen(nextMarketOpen, false))
                {
                    nextMarketOpen = security.Exchange.Hours.GetNextMarketOpen(delistingTime, false);
                }
```
Suggest we extract this logic into a method we can unit test, or maybe it's this entire method 👍. So we can add some unit test cases for the different cases that could happen

File: Common/SecurityIdentifier.cs [hunk 2]
```diff
@@ -240,7 +240,7 @@ public decimal StrikePrice
                 {
                     if (SecurityType != SecurityType.Option && SecurityType != SecurityType.FutureOption)
                     {
-                        throw new InvalidOperationException("OptionType is only defined for SecurityType.Option and SecurityType.FutureOption");
+                        throw new InvalidOperationException("StrikePrice is only defined for SecurityType.Option and SecurityType.FutureOption");
```
Comment (Martin-Molinero) [inline Common/SecurityIdentifier.cs:243]: Nice 👍 , those evil copy & paste

File: Engine/DataFeeds/SubscriptionDataReader.cs [hunk 3]
```diff
@@ -284,8 +284,15 @@ public void Initialize()
...
-            // adding a day so we stop at EOD
-            _delistingDate = _delistingDate.AddDays(1);
+            var isFutureOrFutureOption = _config.Symbol.SecurityType == SecurityType.Future ||
+                _config.Symbol.SecurityType == SecurityType.FutureOption;
+
+            if (!isFutureOrFutureOption)
+            {
+                // adding a day so we stop at EOD for other asset classes except futures and futures options,
+                // since they expire on the same day as their expiry during market hours.
+                _delistingDate = _delistingDate.AddDays(1);
```
[the remark this answers is not in the document]
Comment (gsalaz98) [reply Engine/DataFeeds/SubscriptionDataReader.cs:294]: Without this change, I believe futures and FOPs will report the day after their expiry as a tradable date since we're not comparing with >= here: https://github.com/QuantConnect/Lean/blob/b432f63ac7ffca53042ff546cf544a5b00234a15/Engine/DataFeeds/SubscriptionDataReader.cs#L575

File: Algorithm.Python/FuturesAndFuturesOptionsExpiryTimeAndLiquidationRegressionAlgorithm.py [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+
+    def OnEndOfAlgorithm(self):
+        if not self.invested:
+            raise AssertionError("Never invested in ES futures and FOPs")
+
+        if self.delistingsReceived != 4:
+            raise AssertionError(f"Expected 4 delisting events received, found: {self.delistingsReceived}")
+
+        if self.liquidated != 3:
+            raise AssertionError(f"Expected 2 liquidation events, found {self.liquidated}")
```
Comment (Martin-Molinero) [inline Algorithm.Python/FuturesAndFuturesOptionsExpiryTimeAndLiquidationRegressionAlgorithm.py:100]: nit - `AssertionError` `Expected 2` but should be `3`

**Review by Martin-Molinero — APPROVED** [review]
Nice 👍  minor nit comment

File: Engine/DataFeeds/SubscriptionDataReader.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Martin-Molinero) [reply Engine/DataFeeds/SubscriptionDataReader.cs:294]: > I believe futures and FOPs will report the day after their expiry as a tradable date

The day after is the break condition of the loop, I think it has no effect. Reverting this change all test still pass, don't think it's required? Suggest we revert it if so

**Review by Martin-Molinero — CHANGES_REQUESTED** [review]

**Review by Martin-Molinero — APPROVED** [review]
