### PR TITLE
Show warning when defaulting to Equity in SetBenchmark

### LINKED ISSUE #2153: SetBenchmark Silent Default to Equity
#### Expected Behavior
Ideally the benchmark is resolved as BTCUSD not Equity.
```
SetBenchmark("BTCUSD");
AddCrypto("BTCUSD", Resolution.Minute);
```

#### Actual Behavior
BTCUSD added as Equity; and the AddCrypto line ignored. It was quite confusing as in this case the price was always $0 as there is no BTCUSD Equity. 

#### Potential Solution
Show a message about the Equity assumption? Scan market hours db to get security type? 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
A warning message has been added in `SetBenchmark(string symbol)` when no existing security is found and the new benchmark security is being added with `SecurityType.Equity`.

#### Related Issue
Closes #2153

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/ect)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Algorithm/QCAlgorithm.cs [hunk 1]
```diff
@@ -1060,9 +1060,16 @@ public void SetBenchmark(string symbol)
             // check existence
             symbol = symbol.ToUpper();
             var security = Securities.FirstOrDefault(x => x.Key.Value == symbol).Value;
-            _benchmarkSymbol = security == null
-                ? QuantConnect.Symbol.Create(symbol, SecurityType.Equity, Market.USA)
-                : security.Symbol;
+            if (security == null)
+            {
+                Debug($"Warning: SetBenchmark({symbol}): no existing security found, benchmark security will be added with {SecurityType.Equity} type.");
```
Comment (AlexCatarino) [inline Algorithm/QCAlgorithm.cs]: We could add the information that there is a method overload that accepts the `SecurityType`: `SetBenchmark(SecurityType, string)`.
