### PR TITLE
Fix MACD WarmUpPeriod and Updating

### LINKED ISSUE #5109: Incorrect MACD WarmUpPeriod & ComputeNextValue
#### Expected Behavior

Regarding the MovingAverageConvergenceDivergence indicator:
(1) The `WarmUpPeriod` is set to
`max(fastPeriod, slowPeriod) + signalPeriod`

(2) The `Signal` is only updated when `Fast` and `Slow` are ready.

(3) The `Histogram` is only updated when `Signal.IsReady` 

#### Actual Behavior

The three conditions above are not true. See [this related thread](https://www.quantconnect.com/forum/discussion/10229/moving-average-convergance-divergence-warm-up-period/p1).

#### Potential Solution

(1) Change [line 83](https://github.com/QuantConnect/Lean/blob/03efc1b735bb8b841eb04434f537ac3d798f5877/Indicators/MovingAverageConvergenceDivergence.cs#L83) to
`Math.Max(fastPeriod, slowPeriod) + signalPeriod`

(2 & 3) Add `IsReady` guards before updating `Signal` and `Histogram`.

#### Reproducing the Problem

Run [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_a50cbc073f15ad4aa0b4e4983109b15e.html) in the cloud. The logs show the MACD indicator `IsReady` when the internal `Fast` and `Slow` indicators are not ready.

#### System Information

Windows 10. Run in QC Cloud.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by DerekMelchin**
#### Description

The WarmUpPeriod of the MACD is corrected to include all internal indicators. In addition, we now only update the `Signal` and `Histogram` when the internal indicators used in their computations are ready.

#### Related Issue

Close #5109

#### Motivation and Context

Before this change, the MACD indicator could be ready while it's internal indicators are not ready. The backtest shared in the related issue demonstrates this.

#### Requires Documentation Change

No.

#### How Has This Been Tested?

The new indicator was run in the Cloud in[ this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_720865fb20fe671956a8afec7c7499da.html). The logs show the indicator now has the correct `IsReady` state.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes.  This probably needs a test added, but I'm not sure how to add unit tests to LEAN yet.
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Indicators/MovingAverageConvergenceDivergence.cs [hunk 1]
```diff
@@ -95,8 +96,16 @@ protected override decimal ComputeNextValue(IndicatorDataPoint input)
...
-            Signal.Update(input.Time, macd);
-            Histogram.Update(input.Time, macd - Signal.Current.Value);
+            if (Fast.IsReady && Slow.IsReady)
+            {
+                Signal.Update(input.Time, macd);
+            }
+                
+            if (Signal.IsReady)
+            {
+                Histogram.Update(input.Time, macd - Signal.Current.Value);
```
Comment (Martin-Molinero) [inline Indicators/MovingAverageConvergenceDivergence.cs:106]: Believe this `if` could be moved into the one above. 
Instead of consuming the `IsReady` properties, we could directly use the returned value from the Update calls since we already have them

**Review by Martin-Molinero — COMMENTED** [review]
Nice!
Some unit tests are failing because of this change, think we should add some new test too

File: Indicators/MovingAverageConvergenceDivergence.cs [hunk 2]
```diff
@@ -80,7 +81,7 @@ public MovingAverageConvergenceDivergence(string name, int fastPeriod, int slowP
             Slow = type.AsIndicator(name + "_Slow", slowPeriod);
             Signal = type.AsIndicator(name + "_Signal", signalPeriod);
             Histogram = new Identity(name + "_Histogram");
-            WarmUpPeriod = signalPeriod;
+            WarmUpPeriod = Math.Max(fastPeriod, slowPeriod) + signalPeriod - 1;
```
Comment (jaredbroad) [inline Indicators/MovingAverageConvergenceDivergence.cs:84]: Should we throw if `fast >= slow`? It'll result in zero or negative `var macd = Fast.Current.Value - Slow.Current.Value;` then weirdness in `Histogram.Update(input.Time, macd - Signal.Current.Value);`

Comment (DerekMelchin) [reply Indicators/MovingAverageConvergenceDivergence.cs:84]: Yes, good point. I'll add this tomorrow.

**Review by Martin-Molinero — APPROVED** [review]
