### PR TITLE
Bug 6115 adjust dates

### LINKED ISSUE #6115: Random Data Generator Date Mismatch for Futures
#### Expected Behavior
The date in zip file name and in the content are the same. `OpenInterest` files are generated.

#### Actual Behavior
The date in zip file name is different from the date in the content. I ran an algorithm with this data and it doesn't trigger `OnData`. Also, there are no `OpenInterest` files (see #5871).

#### Reproducing the Problem
```
lean data generate --start 20210101 --security-type Future --resolution Minute --symbol-count 1 --market cme
```
Capture

I have renamed the zip files to match the dates and the algorithm starts calling `OnData`.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AdalyatNazirov**
#### Description

Fix race condition

#### Related Issue

closes #6115 

#### Motivation and Context

bug, the date in zip file name and in the content should be the same

#### Requires Documentation Change

N/

#### How Has This Been Tested?

- manually
-
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/ToolBox/LeanDataWriterTests.cs [hunk 1]
```diff
@@ -71,6 +71,38 @@ private List<QuoteBar> GetQuoteBars(Symbol sym)
             };
         }
 
+        [Test]
+        public void LeanDataWriter_MultipleDays()
+        {
+            var leanDataWriter = new LeanDataWriter(Resolution.Second, _forex, _dataDirectory, TickType.Quote);
```
Comment (C-SELLERS) [inline Tests/ToolBox/LeanDataWriterTests.cs:77]: Good Test 👍🏽

File: Common/Data/LeanDataWriter.cs [hunk 2]
```diff
@@ -116,7 +116,7 @@ public void Write(IEnumerable<BaseData> source)
                             var fileData = currentFileData;
                             writeTasks.Enqueue(Task.Run(() =>
                             {
-                                WriteFile(file, fileData, data.Time);
```
Comment (C-SELLERS) [inline Common/Data/LeanDataWriter.cs:119]: Yeah this should've been passing lastTime originally. But removing the date variable all together and pulling it from the data is fine 👍🏽

**Review by C-SELLERS — APPROVED** [review]
Good fix
