### PR TITLE
Options premium in margin calculations

### LINKED ISSUE #7291: Premium in margin requirements
#### Expected Behavior

In IB, long options do not have margin requirements, neither initial nor maintenance. 

In Lean, since we account for the option premium, intial margin requirement for long options should include the premium.

On the other hand, short options should not include premium since it is credited to the user.

Call and put option margin reference from IB:

image
image

#### Actual Behavior

Lean includes options premium both for short/long options initial and maintenance margin.

#### Potential Solution

Review `OptionMarginModel` margin calculation methods and make sure the premium is only added for long options.

#### Reproducing the Problem

Reference code:
```csharp
var equity = CreateEquity();
equity.SetMarketPrice(new Tick { Value = 425m });

var callOption = CreateOption(Symbols.CreateOptionSymbol("SPY", OptionRight.Call, 300, new DateTime(2023, 08, 23)));
callOption.SetMarketPrice(new Tick { Value = 124m });
callOption.Underlying = equity;
callOption.Holdings.SetHoldings(124m, 1);

var putOption = CreateOption(Symbols.CreateOptionSymbol("SPY", OptionRight.Put, 300, new DateTime(2023, 08, 23)));
putOption.SetMarketPrice(new Tick { Value = 0.43m });
putOption.Underlying = equity;
putOption.Holdings.SetHoldings(0.43m, 1);

var buyingPowerModel = new OptionMarginModel();

Log.Debug($"Long call initial margin: {buyingPowerModel.GetInitialMarginRequirement(new InitialMarginParameters(callOption, 1m)).Value}");
Log.Debug($"Short call initial margin: {buyingPowerModel.GetInitialMarginRequirement(new InitialMarginParameters(callOption, -1m)).Value}");
Log.Debug($"Long call maintenance margin: {buyingPowerModel.GetInitialMarginRequirement(new InitialMarginParameters(callOption, 1m)).Value}");
Log.Debug($"Short call maintenance margin: {buyingPowerModel.GetInitialMarginRequirement(new InitialMarginParameters(callOption, -1m)).Value}");

Log.Debug($"Long put initial margin: {buyingPowerModel.GetMaintenanceMargin(MaintenanceMarginParameters.ForQuantityAtCurrentPrice(putOption, 1m)).Value}");
Log.Debug($"Short put initial margin: {buyingPowerModel.GetMaintenanceMargin(MaintenanceMarginParameters.ForQuantityAtCurrentPrice(putOption, -1m)).Value}");
Log.Debug($"Long put maintenance margin: {buyingPowerModel.GetMaintenanceMargin(MaintenanceMarginParameters.ForQuantityAtCurrentPrice(putOption, 1m)).Value}");
Log.Debug($"Short put maintenance margin: {buyingPowerModel.GetMaintenanceMargin(MaintenanceMarginParameters.ForQuantityAtCurrentPrice(putOption, -1m)).Value}");
```

Output:
```
Long call initial margin: 12400
Short call initial margin: -20899.999999999999999999999999
Long call maintenance margin: 12400
Short call maintenance margin: -20899.999999999999999999999999

Long put initial margin: 43.00
Short put initial margin: 3043.0000000000000000000000000
Long put maintenance margin: 43.00
Short put maintenance margin: 3043.0000000000000000000000000
```

#### System Information

Windows 11

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

This makes sure `OptionMarginModel` respects the following:
- Long options are paid 100% upfront, their initial margin requirement is their premium.
- Long option do not have maintenance margin requirements.
- Short options margin do not include premium since it is being credited.

There are some screenshots from IB in #7291 with references to maintenance and initial margin requirements for options.

Long naked call (selling a call without having the stock) IB reference:
image

Short naked call (buying a call without having the stock) IB reference:
image

Long naked put (selling a put without having the stock) IB reference:
image

Short naked put (buying a put without having the stock) IB reference:
image

#### Related Issue

Closes #7291 

#### How Has This Been Tested?

Exisiting unit tests (some were extended) and regression algorithms.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Securities/OptionStrategyPositionGroupBuyingPowerModelTests.cs [hunk 1]
```diff
@@ -903,19 +903,19 @@ public void GetsMaintenanceMargin(OptionStrategyDefinition optionStrategyDefinit
...
             new TestCaseData(OptionStrategyDefinitions.IronCondor, 10, -10000m, -10),
             new TestCaseData(OptionStrategyDefinitions.IronCondor, 10, -10000m - 10010m, -20),
-            new TestCaseData(OptionStrategyDefinitions.IronCondor, -10, 10010m / 10, +1).Explicit(),
-            new TestCaseData(OptionStrategyDefinitions.IronCondor, -10, -10010m / 10, -1).Explicit(),
-            new TestCaseData(OptionStrategyDefinitions.IronCondor, -10, -10010m, -10).Explicit(),
-            new TestCaseData(OptionStrategyDefinitions.IronCondor, -10, -10010m - 10000m, -20).Explicit(),
+            new TestCaseData(OptionStrategyDefinitions.IronCondor, -10, 10010m / 10, +1),
+            new TestCaseData(OptionStrategyDefinitions.IronCondor, -10, -10010m / 10, -1),
+            new TestCaseData(OptionStrategyDefinitions.IronCondor, -10, -10010m, -10),
+            new TestCaseData(OptionStrategyDefinitions.IronCondor, -10, -10010m - 10000m, -20),
```
Comment (Martin-Molinero) [inline Tests/Common/Securities/OptionStrategyPositionGroupBuyingPowerModelTests.cs:918]: 🍬 !

**Review by Martin-Molinero — APPROVED** [review]
Thank you!
