### PR TITLE
Fixes Consolidator Removal from Subscription Manager in Python Algorithms

### LINKED ISSUE #7099: `RemoveConsolidator` doesn't work in Python
#### Expected Behavior

When we call `RemoveConsolidator`, lean removes the consolidator we specify.

#### Actual Behavior

RemoveConsolidator works in C#, but not in Python.

#### Potential Solution

N/A

#### Reproducing the Problem

If we run [this C# backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_f0bc90581e05558c00742c74135c6916.html), we get
image

If we run [this Python backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_7bfe79a526300b04b336cf4bac5b7aae.html), we get
image

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
- Adds unit test: Asserts that we can remove a previously added consolidator.
- AddConsolidator Method Only Wraps Non-C# Consolidators: 
  - This behavior was implemented in `QCAlgorithm.RegisterIndicator` ([QCAlgorithm.Python.cs#L577](https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Python.cs#L577)) to avoid wrapping an object unnecessarily.

#### Related Issue
Closes #7099

#### Motivation and Context
Bug fix. Allow Python algorithms to remove indicators that were previously added.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
New unit test.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Data/SubscriptionManager.cs [hunk 1]
```diff
@@ -180,7 +180,11 @@ public void AddConsolidator(Symbol symbol, IDataConsolidator consolidator)
         /// <param name="pyConsolidator">The custom python consolidator</param>
         public void AddConsolidator(Symbol symbol, PyObject pyConsolidator)
         {
-            IDataConsolidator consolidator = new DataConsolidatorPythonWrapper(pyConsolidator);
+            if (!pyConsolidator.TryConvert(out IDataConsolidator consolidator))
+            {
+                consolidator = new DataConsolidatorPythonWrapper(pyConsolidator);
+            }
```
Comment (Martin-Molinero) [inline Common/Data/SubscriptionManager.cs:186]: Cool!

**Review by Martin-Molinero — APPROVED** [review]
