### PR TITLE
Fix BrokerageSetupHandler error when loading option/equity holdings/orders

### LINKED ISSUE #2461: Error getting account holdings from brokerage with option + equity holdings/orders
#### Expected Behavior
Existing option + equity holdings and/or open orders should be loaded from the brokerage with no errors.

#### Actual Behavior
If a brokerage account has existing option and equity holdings (or orders) for the same underlying **and** the equity is returned before the option from the brokerage, the following error is thrown:
```
During the algorithm initialization, the following exception has occurred: 
Error getting account holdings from brokerage:
The underlying equity asset (UVXY) is set to Adjusted,
please change this to DataNormalizationMode.Raw with the SetDataNormalization() method.
```

#### Potential Solution
The `BrokerageSetupHandler` should load options first, to ensure the underlying equity security is added with the raw data normalization mode.

#### Reproducing the Problem
Deploy a live algorithm to InteractiveBrokers with existing option and equity holdings (or open orders).

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
The `BrokerageSetupHandler` has been updated to load options first, to ensure the underlying equity securities are added with the raw data normalization mode.

#### Related Issue
Closes #2461 

#### Motivation and Context
Live runtime error at deploy time.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
New unit tests included.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/Setup/BrokerageSetupHandler.cs [hunk 1]
```diff
@@ -307,6 +307,13 @@ public bool Setup(IAlgorithm algorithm, IBrokerage brokerage, AlgorithmNodePacke
                 {
                     // populate the algorithm with the account's current holdings
                     var holdings = brokerage.GetAccountHoldings();
+
+                    // add options first to ensure raw data normalization mode is set on the equity underlyings
+                    holdings = holdings
+                        .Where(x => x.Type == SecurityType.Option)
+                        .Union(holdings.Where(x => x.Type != SecurityType.Option))
```
Comment (Martin-Molinero) [inline Engine/Setup/BrokerageSetupHandler.cs]: maybe instead of doing multiple operations, you could take advantage of the `OrderByDescending()` targeted at the `type`? Idem for bellow

Comment (StefanoRaggi) [reply Engine/Setup/BrokerageSetupHandler.cs]: ty, fixed
