### PR TITLE
Fixes options order crashing ReportGenerator

### LINKED ISSUE #4951: Report generation fails with null underlying for option orders
#### Expected Behavior
When running report generator using downloaded JSON results from a QuantConnect platform run backtest with options traded, report should be generated

#### Actual Behavior
Report generation errors with a null reference as it seems the underlying of the option is not being deserialized. Because a loaded option symbol has a null underlying reference it fails at SecurityService.cs line 131:

`Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at QuantConnect.Securities.SecurityService.CreateSecurity (QuantConnect.Symbol symbol, System.Collections.Generic.List`1[T] subscriptionDataConfigList, System.Decimal leverage, System.Boolean addToSymbolCache) [0x00272] in /home/ari/Development/projects/Lean/Common/Securities/SecurityService.cs:131 
  at QuantConnect.Securities.SecurityManager.CreateSecurity (QuantConnect.Symbol symbol, System.Collections.Generic.List`1[T] subscriptionDataConfigList, System.Decimal leverage, System.Boolean addToSymbolCache) [0x00001] in /home/ari/Development/projects/Lean/Common/Securities/SecurityManager.cs:302 
  at QuantConnect.Report.PortfolioLooperAlgorithm.FromOrders (System.Collections.Generic.IEnumerable`1[T] orders) [0x0006c] in /home/ari/Development/projects/Lean/Report/PortfolioLooper/PortfolioLooperAlgorithm.cs:45 
  at (wrapper remoting-invoke-with-check) QuantConnect.Report.PortfolioLooperAlgorithm.FromOrders(System.Collections.Generic.IEnumerable`1<QuantConnect.Orders.Order>)
  at QuantConnect.Report.PortfolioLooper..ctor (System.Double startingCash, System.Collections.Generic.List`1[T] orders, QuantConnect.Resolution resolution) [0x001ca] in /home/ari/Development/projects/Lean/Report/PortfolioLooper/PortfolioLooper.cs:122 
  at QuantConnect.Report.PortfolioLooper+<FromOrders>d__13.MoveNext () [0x00283] in /home/ari/Development/projects/Lean/Report/PortfolioLooper/PortfolioLooper.cs:270 
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in /builddir/build/BUILD/mono-6.12.0.90/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:1108 
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in /builddir/build/BUILD/mono-6.12.0.90/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:87 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /builddir/build/BUILD/mono-6.12.0.90/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30 
  at QuantConnect.Report.Report..ctor (System.String name, System.String description, System.String version, QuantConnect.Packets.BacktestResult backtest, QuantConnect.Packets.LiveResult live) [0x00080] in /home/ari/Development/projects/Lean/Report/Report.cs:50 
  at QuantConnect.Report.Program.Main (System.String[] args) [0x0012c] in /home/ari/Development/projects/Lean/Report/Program.cs:73 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at QuantConnect.Securities.SecurityService.CreateSecurity (QuantConnect.Symbol symbol, System.Collections.Generic.List`1[T] subscriptionDataConfigList, System.Decimal leverage, System.Boolean addToSymbolCache) [0x00272] in /home/ari/Development/projects/Lean/Common/Securities/SecurityService.cs:131 
  at QuantConnect.Securities.SecurityManager.CreateSecurity (QuantConnect.Symbol symbol, System.Collections.Generic.List`1[T] subscriptionDataConfigList, System.Decimal leverage, System.Boolean addToSymbolCache) [0x00001] in /home/ari/Development/projects/Lean/Common/Securities/SecurityManager.cs:302 
  at QuantConnect.Report.PortfolioLooperAlgorithm.FromOrders (System.Collections.Generic.IEnumerable`1[T] orders) [0x0006c] in /home/ari/Development/projects/Lean/Report/PortfolioLooper/PortfolioLooperAlgorithm.cs:45 
  at (wrapper remoting-invoke-with-check) QuantConnect.Report.PortfolioLooperAlgorithm.FromOrders(System.Collections.Generic.IEnumerable`1<QuantConnect.Orders.Order>)
  at QuantConnect.Report.PortfolioLooper..ctor (System.Double startingCash, System.Collections.Generic.List`1[T] orders, QuantConnect.Resolution resolution) [0x001ca] in /home/ari/Development/projects/Lean/Report/PortfolioLooper/PortfolioLooper.cs:122 
  at QuantConnect.Report.PortfolioLooper+<FromOrders>d__13.MoveNext () [0x00283] in /home/ari/Development/projects/Lean/Report/PortfolioLooper/PortfolioLooper.cs:270 
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in /builddir/build/BUILD/mono-6.12.0.90/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:1108 
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in /builddir/build/BUILD/mono-6.12.0.90/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:87 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /builddir/build/BUILD/mono-6.12.0.90/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30 
  at QuantConnect.Report.Report..ctor (System.String name, System.String description, System.String version, QuantConnect.Packets.BacktestResult backtest, QuantConnect.Packets.LiveResult live) [0x00080] in /home/ari/Development/projects/Lean/Report/Report.cs:50 
  at QuantConnect.Report.Program.Main (System.String[] args) [0x0012c] in /home/ari/Development/projects/Lean/Report/Program.cs:73 `

An example piece of relevant JSON downloaded from QuantConnect looks like:
`"Symbol": {
          "Value": "WAG   101016P00025000",
          "ID": "WAG 2YPXFKVWULF1I|WAG R735QTJ8XC9X",
          "Permtick": "WAG   101016P00025000",
          "Underlying": {
            "Value": "WAG",
            "ID": "WAG R735QTJ8XC9X",
            "Permtick": "WAG"
          }
        }`

#### Reproducing the Problem
Run a backtest that trades options (in my case I only traded options, and not the underlying, so this may be related) on QuantConnect, then download the JSON of the total results. Run the report generator on that file.

#### System Information
Linux/mono

#### Checklist
- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by gsalaz98**
#### Description

Fixes a crash in the Report Generator caused by an option order having no `Underlying` in its Symbol when constructed in the `OrderJsonConverter`

 Additionally, adds functionality to the Symbol constructor to create an underlying Symbol if the SID provided has an underlying SID.
#### Related Issue

Closes #4951 
#### Motivation and Context

Bug fixes, squash all bugs
#### Requires Documentation Change

No
#### How Has This Been Tested?

New unit tests
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Symbol.cs [hunk 1]
```diff
@@ -307,6 +307,10 @@ public Symbol(SecurityIdentifier sid, string value)
                 throw new ArgumentNullException(nameof(value));
             }
             ID = sid;
+            if (ID.HasUnderlying)
+            {
+                Underlying = new Symbol(ID.Underlying, ID.Underlying.Symbol);
```
Comment (Martin-Molinero) [inline Common/Symbol.cs:312]: Nice find!
This is exposing an interesting 'information duplication' case, the fact that the `Symbol Symbol.Underlying` isn't directly attached to it's `SecurityIdentifier ID.Underlying`, which means they could be different. With this change we should be covered since Symbol only has two constructors.

**Review by Martin-Molinero — APPROVED** [review]
