### PR TITLE
Bug 4925 daylight out of order bar

### LINKED ISSUE #4925: FillForwardEnumerator daylight savings creating out of order bar
#### Expected Behavior

- No `FillForwardEnumerator received data out of order`
#### Actual Behavior

- `FillForwardEnumerator received data out of order` due to fill forward `TradeBar` being emitted with time 9:30 after the next data point 8:33, believe due to the `daylightMovement`. 
#### Potential Solution

Review daylight savings adjustment logic. Add tests reproducing the issue.
#### Reproducing the Problem

```
public override void Initialize()
{
    SetStartDate(2008, 3, 7);
    SetEndDate(2008, 3, 10);
    AddEquity("SHY", Resolution.Minute);
    // just to make debugging easier, less subscriptions
    SetBenchmark(time => 1);
}
```
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AdalyatNazirov**
#### Description

Reverted PRs https://github.com/QuantConnect/Lean/pull/3708, https://github.com/QuantConnect/Lean/pull/4700

behind these changes a few main ideas:
1) In most cases in Lean we calculate `EndTime=Time + resolution`. it means that `EndTime` is built in the same TZ as `Time`, because simple arithmetic operation doesn't take into account TZ itself. It works for standard situation. But broken when it comes to specific days when we switch TZ to Daylight/Standard.

That's why both `potentialbarEndTime` and `next.EndTime` should be in the same TZ (Daylight/Standard). because of  `next.EndTime` is built in 'current TZ' we also need to build  `potentialbarEndTime` in 'current'. To do that  it's necessary to `RoundDown` origin day and then add interval, while those PRs rounded down the day + interval, which would not work for daily resolution because we missed the 2am of Sunday where the movement actually happens. In the https://github.com/QuantConnect/Lean/pull/4700 we tried to compensate that by adding `daylightMovement` but didn't worked for minute resolution on pre-market data

2) Usually `Time` and `EndTime`  are in the same TZ, but if we consider that specific day of Daylight movement, we can find that `Time` is one TZ, but `EndTime` in another. In `master` we ignore that, so ff'ed bar `Time` and `EndTime` are always from the same TZ, but it breaks 'next' step. To fix it we need apply their own TZ to `Time` and `EndTime`

There are a few examples (DataTimeZone = UTC-5; Exchange TimeZone = America/new York)

**Standard Time** 
00:00:00 => 1.00:00:00
image

**Daylight Time**
01:00:00 => 1.01:00:00
image

### **EDGE CASES**

**Standard => Daylight**
00:00:00 => 1.01:00:00
image

**Daylight => Standard**
020:00:00 => 1.19:00:00
image

Worth to mention that `NodaTime` consider 1 AM - 2 AM as interval _after_ daylight move, so it's sensitive for DataTZ and ExchangeTZ, for example

DataTZ = UTC; ExchangeTZ = America/New York
020:00:00 => 1.19:00:00

DataTZ = UTC-5; ExchangeTZ = America/New York
01:00:00 => 1.01:00:00

#### Related Issue

Closes #4925 

#### Motivation and Context

On minute resolution error was thrown for pre-market data `FillForwardEnumerator received data out of order`.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

- unit tests. Created a lot of different test cases for different Exchange and DataTimeZone values. Run it against master first; save results and then after fix. Fixed expected data due to changes. Some failed results listed below (left - master; right - branch)

- regression test for minute resolution checking first bar after daylight movement

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs [hunk 1]
```diff
@@ -1165,76 +1165,319 @@ public void FillForwardBarsForDifferentResolutions(Resolution resolution, Resolu
...
+
+                return new TestCaseData(list.ToArray());
+            });
+        }
+
+        [Test]
+        [TestCaseSource(nameof(DaylightSavingCases), new object[] { -5 })]
+        [TestCaseSource(nameof(DaylightSavingCases), new object[] { 0 })]
+        [TestCaseSource(nameof(DaylightSavingCases), new object[] { -3 })]
+        public void FillsForwardDaylightSavingTime(DateTime reference, SecurityExchange exchange, DateTimeZone dataTimeZone)
```
Comment (Martin-Molinero) [inline Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs:1193]: Nice tests 💯

**Review by Martin-Molinero — APPROVED** [review]

File: Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs [hunk 2]
```diff
@@ -1273,6 +1682,31 @@ public override void OnEndOfAlgorithm()
...
+                {
+                    var bar = data[_symbol] as QuoteBar;
+                    if (bar != null && bar.IsFillForward)
+                    {
+                        FillForwardBars.Add($"{bar.Time:yyyy.MM.dd H:m:s} - {bar.EndTime:yyyy.MM.dd H:m:s}");
+                    }
+                }
+            }
+        }
+
```
Comment (Martin-Molinero) [inline Tests/Engine/DataFeeds/Enumerators/FillForwardEnumeratorTests.cs:1709]: Nice test suite!

File: Engine/DataFeeds/Enumerators/FillForwardEnumerator.cs [hunk 3]
```diff
@@ -294,20 +278,53 @@ protected virtual bool RequiresFillForwardData(TimeSpan fillForwardResolution, B
...
+
+                // all above means, that all Time values, calculated using simple +/- operations
+                // sticks to original Time Zone, swallowing its own TZ and movement i.e.
+                // EndTime = Time + resolution, both Time and EndTime in the TZ of Time (Standard/Daylight)
+                // Time = EndTime - resolution, both Time and EndTime in the TZ of EndTime (Standard/Daylight)
+
+                // because of all above, we know that next.EndTime sticks to Time TZ,
+                // it means that we have to calculate potentialBadEndTime in the same TZ
+                // by adding interval in daily resolution we move to next day
+                // in order to track daylight movement need to round-down origin day (before + Interval)
```
Comment (Martin-Molinero) [inline Engine/DataFeeds/Enumerators/FillForwardEnumerator.cs:301]: Cool ✔️

**Review by Martin-Molinero — APPROVED** [review]
