### PR TITLE
Use data end time to timestamp fundalmental data dictionaries

### LINKED ISSUE #6325: GetFundamental is not Timestamped with EndTime
#### Expected Behavior
Data is timestamped with end-of-period time.

#### Actual Behavior
Data is timestamped with start-of-period time due to this implementation:
https://github.com/QuantConnect/Lean/blob/master/Research/QuantBook.cs#L846:L850

#### Potential Solution
Replace `Time` for `EndTime`.

#### Reproducing the Problem
```python
history = qb.History(tickers, start_date, end_date, Resolution.Daily)
ff = qb.GetFundamental(tickers, "MarketCap", start_date, end_date)
```
the timestamps do not match.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

Using end-of-period time to timestamp fundamental data dictionaries.

#### Related Issue

Closes #6325 

#### Motivation and Context

Match fundamentals timestamps with daily history requests timestamps.

#### How Has This Been Tested?

Unit tests

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Research/QuantBook.cs [hunk 1]
```diff
@@ -852,17 +852,19 @@ private object GetPropertyValue(object baseData, string fullName)
...
                         lock (data)
                         {
-                            if (!data.ContainsKey(enumerator.Current.Time))
+                            if (!data.ContainsKey(time))
                             {
-                                data[enumerator.Current.Time] = new DataDictionary<dynamic>(enumerator.Current.Time);
+                                data[time] = new DataDictionary<dynamic>(time);
                             }
-                            data[enumerator.Current.Time].Add(enumerator.Current.Symbol, dataPoint);
+                            data[time].Add(currentData.Symbol, dataPoint);
```
Comment (Martin-Molinero) [inline Research/QuantBook.cs:867]: Cool! Minor but we could use `TryGetValue` instead of the `ContainsKey` & `[]`

File: Tests/Research/QuantBookFundamentalTests.cs [hunk 2]
```diff
@@ -155,6 +161,32 @@ public void CSharpReturnNullTest(dynamic input)
...
+            var fundamental = (_qb.GetFundamental("AAPL", "", startDate, endDate) as IEnumerable<DataDictionary<dynamic>>).ToList();
+
+            var isEndDateOpen = security.Exchange.Hours.IsDateOpen(endDate);
+            var expectedFundamentalCount = isEndDateOpen ? history.Count + 1 : history.Count;
+            Assert.AreEqual(expectedFundamentalCount, fundamental.Count);
+
+            var historyTimes = history.Select(x => x.EndTime);
+            var fundamentalTimes = fundamental.Select(x => x.Time).SkipLast(isEndDateOpen ? 1 : 0);
+
+            CollectionAssert.AreEqual(historyTimes, fundamentalTimes);
```
Comment (Martin-Molinero) [inline Tests/Research/QuantBookFundamentalTests.cs:182]: Maybe can assert the expected count just to be sure they are not both empty 👍

**Review by Martin-Molinero — APPROVED** [review]
Thank you! Minor requests
