### PR TITLE
Fixes issue where BidPrice/AskPrice were not adjusted for Quote Ticks

### LINKED ISSUE #4788: Tick BidPrice and AskPrice are not adjusted for equities
#### Expected Behavior

BidPrice and AskPrice are adjusted, same as the Value of the Tick
#### Actual Behavior

BidPrice and AskPrice are not adjusted
#### Potential Solution

Find adjustment point and adjust BidPrice and AskPrice
#### Reproducing the Problem

This algorithm reproduces the problem on QC cloud. Also works locally if using IBM between 2013-10-07 and 2013-10-08

```python
class HorizontalModulatedCoil(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2020, 5, 1)
        self.SetEndDate(2020, 5, 2)
        self.aapl = self.AddEquity("AAPL", Resolution.Tick).Symbol
    def OnData(self, data):
        if not data.ContainsKey(self.aapl):
            return
        if self.Time >= datetime(2020, 5, 1, 10, 0, 0):
            # Prevents flooding of the console
            return
        for tick in data.Ticks[self.aapl]:
            if tick.BidPrice == 292.18:
                self.Debug(f"{self.Time} -- Price: {tick.Value} BidPrice: {tick.BidPrice}")
            if tick.AskPrice == 292.18:
                self.Debug(f"{self.Time} -- Price: {tick.Value} AskPrice: {tick.AskPrice}")
```
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by gsalaz98**
#### Description

Previously, ticks would have their prices (Tick.Value) adjusted whenever TickType == TickType.Quote, but would not have their BidPrice/AskPrice fields adjusted, thus potentially being orders of magnitude such as 4x from the actual Bid/Ask prices.

This commit applies the pricing scaling factor in a critical path where Ticks are adjusted to their scaled price. This issue only applied to Resolution.Tick && SecurityType.Equity data.

#### Related Issue

Closes #4788 
#### Motivation and Context

Data consistency and correctness
#### Requires Documentation Change

No
#### How Has This Been Tested?

New unit test, algorithm testing via debugger
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Extensions.cs [hunk 1]
```diff
@@ -2141,6 +2141,8 @@ public static BaseData Scale(this BaseData data, Func<decimal, decimal> factor)
                         if (securityType == SecurityType.Equity)
                         {
                             tick.Value = factor(tick.Value);
+                            tick.BidPrice = factor(tick.BidPrice);
+                            tick.AskPrice = factor(tick.AskPrice);
                         }
                         if (securityType == SecurityType.Option
```
Comment (Martin-Molinero) [inline Common/Extensions.cs:2147]: I think we could directly add `securityType == SecurityType.Equity` in the if bellow?

File: Tests/Common/Util/ExtensionsTests.cs [hunk 2]
```diff
@@ -1160,6 +1165,77 @@ public void GetsExerciseDirection(OptionRight right, bool isShort, OrderDirectio
...
+                    new LocalDiskMapFileProvider(),
+                    new LocalDiskFactorFileProvider(),
+                    (_) => {},
+                    false,
+                    new DataPermissionManager()));
+
+            algo.SetStartDate(DateTime.UtcNow.AddDays(-1));
+
+            var history = algo.History(new[] { Symbols.IBM }, new DateTime(2013, 10, 7), new DateTime(2013, 10, 8), Resolution.Tick).ToList();
+            Console.WriteLine(history.Count);
```
Comment (Martin-Molinero) [inline Tests/Common/Util/ExtensionsTests.cs:1216]: This guy needs to be disposed `ZipDataCacheProvider` and we should probably call `Exit` on the `FileSystemDataFeed` (maybe could use the `NullDataFeed` ?). Suggest we replace the `Console.WriteLine` for an assert on the history count

**Review by Martin-Molinero — CHANGES_REQUESTED** [review]
Nice catch! 👍 Leaving minor requests

**Review by Martin-Molinero — APPROVED** [review]
Sweet! 🍬
