### PR TITLE
Sets PYTHONPATH in CommonAlphaModelTests TestFixtureSetup

### LINKED ISSUE #2374: ModuleNotFoundError in python versions of alpha model units
#### Expected Behavior
Python versions of alpha model are imported successfully in units tests.

#### Actual Behavior
Unit tests cannot find python models in the python path.

#### Potential Solution
Append the modules location to the python path:
```csharp
var pythonPath = new DirectoryInfo("../../../Algorithm.Framework/Alphas");
Environment.SetEnvironmentVariable("PYTHONPATH", pythonPath.FullName);
```
#### Reproducing the Problem
Run alpha model unit tests (e.g.: `RsiAlphaModelTests`). It will failed with the message:
`Message: Python.Runtime.PythonException : ModuleNotFoundError : No module named 'RsiAlphaModel'`

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
Sets PYTHONPATH in `CommonAlphaModelTests` `TestFixtureSetup`.
- When the PYTHONPATH is explicitly set to include the location of the modules, python easily find and load them.

Fixing this issue also exposed a bug in `RsiAlphaModel`.
- The model was assuming that we could only add elements to the dictionary field if there was data in the history request which is not required.

#### Related Issue
Closes #2374 

#### Motivation and Context
Improve unit tests.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Unit tests.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Algorithm/Framework/Alphas/CommonAlphaModelTests.cs [hunk 1]
```diff
@@ -41,6 +42,9 @@ public abstract class CommonAlphaModelTests
         [TestFixtureSetUp]
         public void Initialize()
         {
+            var pythonPath = new DirectoryInfo("../../../Algorithm.Framework/Alphas");
+            Environment.SetEnvironmentVariable("PYTHONPATH", pythonPath.FullName);
+
```
Comment (StefanoRaggi) [inline Tests/Algorithm/Framework/Alphas/CommonAlphaModelTests.cs]: I think this should already be covered by the new `PythonSetup` class, which already sets the path for all models

Comment (AlexCatarino) [reply Tests/Algorithm/Framework/Alphas/CommonAlphaModelTests.cs]: Reverted the changes in that file and the issue is still gone.
