### PR TITLE
Fix infinite loop in `InsightsCollection.CopyTo`

### LINKED ISSUE #3168: JSON serialization of ordered InsightCollection causes stack overflow exception
#### Expected Behavior
Ordering an `InsightCollection` before serializing it works.

#### Actual Behavior
Ordering an `InsightCollection` and subsequently JSON-serializing it produces a stack overflow exception (VS reports it as that, the below is from the Terminal):

```
[ERROR] FATAL UNHANDLED EXCEPTION: at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter, object, System.Type) [0x00253] in :0, at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter, object, System.Type) [0x00000] in :0, at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (object, System.Type, Newtonsoft.Json.JsonSerializer) [0x00028] in :0, at Newtonsoft.Json.JsonConvert.SerializeObject (object, System.Type, Newtonsoft.Json.Formatting, Newtonsoft.Json.JsonSerializerSettings) [0x0000e] in :0, at Newtonsoft.Json.JsonConvert.SerializeObject (object, Newtonsoft.Json.Formatting, Newtonsoft.Json.JsonSerializerSettings) [0x00000] in :0, at Newtonsoft.Json.JsonConvert.SerializeObject (object, Newtonsoft.Json.Formatting) [0x00000] in :0, at QuantConnec
```

#### Potential Solution
Just ordering the object works, so it must be something that happens when during JSON serialization.

#### Reproducing the Problem
_Set `EqualWeightingPortfolioConstructionModel._insightCollection` to `public`._

```c#
using Newtonsoft.Json;

namespace QuantConnect.Algorithm.CSharp
{
    public class ParticleHorizontalProcessor : QCAlgorithm
    {
        public override void Initialize()
        {
            SetStartDate(2019, 5, 1);
            SetCash(100000);
            SetPortfolioConstruction(new EqualWeightingPortfolioConstructionModel());
            SetAlpha(new ConstantAlphaModel(InsightType.Price, InsightDirection.Up, TimeSpan.FromDays(1)));
            UniverseSettings.Resolution = Resolution.Hour;
            var symbols = new[] { QuantConnect.Symbol.Create("EURUSD", SecurityType.Forex, Market.Oanda) };
            SetUniverseSelection( new ManualUniverseSelectionModel(symbols) );
        }

        public override void OnEndOfAlgorithm()
        {
            var portConst = PortfolioConstruction as EqualWeightingPortfolioConstructionModel;
            var sorted = portConst._insightCollection.OrderBy( x => x.GeneratedTimeUtc );
            var test = JsonConvert.SerializeObject( sorted );
            Debug(test);
        }
    }
}
```

#### System Information
Happens on both QC terminal and Win x64.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by gsalaz98**
#### Description

Fixes infinite loop in call to `CopyTo` in order to allow list creation and serialization.

This fix may cause a performance degradation.
#### Related Issue

Closes #3168 
#### Motivation and Context

Allows for LINQ queries on `InsightCollection`
#### Requires Documentation Change

No
#### How Has This Been Tested?

Unable to be tested; Halting problem prevents testing of stack overflows
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Algorithm/Framework/Alphas/InsightCollection.cs [hunk 1]
```diff
@@ -103,7 +103,13 @@ public bool ContainsKey(Symbol symbol)
...
         public void CopyTo(Insight[] array, int arrayIndex)
         {
-            var copy = this.ToList();
+            // Avoid calling `ToList` on insights to avoid potential infinite loop (issue #3168)
+            var copy = new List<Insight>(Count);
+
+            foreach (var insight in this)
+            {
+                copy.Add(insight);
+            }
```
Comment (Martin-Molinero) [inline Common/Algorithm/Framework/Alphas/InsightCollection.cs]: Good catch!
I think it would be nice if we added a unit test that stacked overflowed before and now passes. Maybe could directly use `AddRange(this)`.

Comment (gsalaz98) [reply Common/Algorithm/Framework/Alphas/InsightCollection.cs]: I attempted to write a unit test for this bug, but unfortunately, didn't end up working out.

Here's the unit test I wrote (or at least what I remember of it):

```csharp
using System;
using System.Linq;
using NUnit.Framework;
using QuantConnect.Algorithm.Framework.Alphas;

namespace QuantConnect.Tests.Algorithm.Framework.Alphas
{
    [TestFixture]
    public class InsightCollectionTests
    {
        [Test]
        public static void InsightCollectionShouldBeAbleToBeConvertedToListWithoutStackOverflow()
        {
            var aapl = Symbol.Create("AAPL", SecurityType.Equity, "usa");
            var insightCollection = new InsightCollection();

            insightCollection.Add(new Insight(aapl, new TimeSpan(1, 0, 0, 0), InsightType.Price, InsightDirection.Up)
            {
                CloseTimeUtc = new DateTime(2019, 1, 1),
            });
            insightCollection.Add(new Insight(aapl, new TimeSpan(1, 0, 0, 0), InsightType.Volatility, InsightDirection.Up)
            {
                CloseTimeUtc = new DateTime(2019, 1, 2),
            });
            
            Assert.DoesNotThrow(() => insightCollection.OrderBy(x => x.GeneratedTimeUtc).ToList());
        }
    }
}
```

Stack overflows aren't able to be caught with traditional patterns (try and catch). I'd like your insight as to how we can test this if possible @Martin-Molinero . I don't know how this test would behave in CI if it fails by SO, so I'm trying to stay clear from that route for the meanwhile.

Comment (Martin-Molinero) [reply Common/Algorithm/Framework/Alphas/InsightCollection.cs]: The unit test looks good to me, stack overflows in `master` and passes in this `PR`.
ACK `AddRange`: right, it shouldn't use `this`! this works: `copy.AddRange(_insights.SelectMany(kvp => kvp.Value));`
Also I checked the `List` implementation and it uses `Array.Copy`, this seems to also work `Array.Copy((Array)list.ToArray(), 0, (Array)array, arrayIndex, list.Count);`

Comment (gsalaz98) [reply Common/Algorithm/Framework/Alphas/InsightCollection.cs]: I believe the method can be simplified to the following:
```csharp
public void CopyTo(Insight[] array, int arrayIndex)
{
    // Avoid calling `ToList` on insights to avoid potential infinite loop (issue #3168)
    Array.Copy(_insights.Values.ToArray(), 0, array, arrayIndex, Count);
}
```

Because `this.ToArray()` also causes a stack overflow, I believe we must source the data from within `_insights` if we are to get rid of the foreach loop.

I'll include the unit tests in the next commit. It may report bad information in CI if the test fails.

One last question: is there a reason to use `SelectMany` over just accessing the `Values` member of `_insights`?

Comment (Martin-Molinero) [reply Common/Algorithm/Framework/Alphas/InsightCollection.cs]: res `SelectMany`: I believe its required because `_insights` is a collection of `List<Insight>`.
I'm thinking we might want to add another unit test to verify the behavior of `CopyTo` is as expected
