### PR TITLE
Binance crypto futures fee models

### LINKED ISSUE #6856: Crypto Future Fee Model
#### Expected Behavior
CryptoFuture fee structure is different from crypto-spot.

#### Actual Behavior
We use the same maker/taker rates for CryptoFuture and Crypto.

#### Potential Solution
- Create new `BinanceFuturesFeeModel` to be used by `BinanceFuturesBrokerageModel.GetFeeModel` override
- Create new `BinanceCoinFuturesFeeModel` to be used by `BinanceCoinFuturesBrokerageModel.GetFeeModel` override
- For each apply maker/taker fees as specified by Binance https://www.binance.com/en/fee/futureFee. Maker and taker rate fees can be arguments and we default to tier 1
- Add unit tests for each

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

New fee models for Binance Futures and Binance Coin Futures.

Fees references:
- Binance futures: https://www.binance.com/en/fee/futureFee
- Binance Coin Futures: https://www.binance.com/en/fee/deliveryFee

#### Related Issue

Closes #6856 

#### How Has This Been Tested?

Unit tests

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by Martin-Molinero — COMMENTED** [review]
Nice! leaving a couple of minor comments 👍

File: Common/Securities/CryptoFuture/CryptoFutureMarginModel.cs [hunk 1]
```diff
@@ -16,6 +16,7 @@
 using System;
 using System.Linq;
 using QuantConnect.Orders;
+using QuantConnect.Securities.Option;
```
Comment (Martin-Molinero) [inline Common/Securities/CryptoFuture/CryptoFutureMarginModel.cs:19]: `using QuantConnect.Securities.Option;` we don't need this guy, same for `Common/Securities/CryptoFuture/CryptoFutureHolding.cs`

**Review by Martin-Molinero — APPROVED** [review]
Looks good! minor comment 👍
