### PR TITLE
Fix Beta calculation for non-daily algorithms

### LINKED ISSUE #3927: Beta Calculation Incorrect
The Beta Calculation in the strategy overview always shows low beta for every strategy even buy and hold the Benchmark. 

I think the issue stems from the way the overview is lining up the strategy and benchmark performance data. It seems the first entry of the benchmark data is duplicated meaning everything else is off by a day when comparing.

### PR DESCRIPTION
**Pull request by gsalaz98**
# ⚠️ Warning ⚠️ 

This commit breaks accurate calculations for algorithms that
only make use of `Daily` resolution data. Previously, because
the benchmark was added in Daily resolution in backtesting, any
algorithm that only made use of daily data would have an accurate
calculation for beta and various other statistics.

These changes serve to fix the statistics calculations of non-daily
resolution algorithms, with daily resolution to be revisited at a later
time.

Regression algorithm statistics and a few BacktestNodePacket test statistics have not been updated. They'll be updated once this PR is approved.

Also please note that a few tests should be failing. They are:

* Most regression tests
* QuantConnect.Tests.Common.Packets/BacktestNodePacketTests/ClearsOtherCashAmounts
* QuantConnect.Tests.Common.Packets/BacktestNodePacketTests/InitialCashAmountIsRespected
* QuantConnect.Tests.Common.Packets/BacktestNodePacketTests/JobDatesAreRespected
* QuantConnect.Tests.Engine.Results/BacktestingResultHandlerTests/BasicTemplateDailyAlgorithmSamplesNotMisalignedAbsolute
* QuantConnect.Tests.Engine.Results/BacktestingResultHandlerTests/ResolutionSwitchingAlgorithmSamplesNotMisalignedAbsolute
* QuantConnect.Tests.Engine.Results/BacktestingResultHandlerTests/SamplesNotMisalignedRelative("BasicTemplateDailyAlgorithm")
* QuantConnect.Tests.Engine.Results/BacktestingResultHandlerTests/SamplesNotMisalignedRelative("ResolutionSwitchingAlgorithm")

Any additional failing tests are most likely a new bug.
#### Description

 Refactors sampling strategy in AlgorithmManager loop

* Refactors AlgorithmManager loop
* Refactors StatisticsBuilder methods and strategy for series alignment
* Move sampling logic to the corresponding IResultHandler
* Changes benchmark resolution to Resolution.Hour
* Modifies IResultHandler to enable external sampling
* Adds BacktestResultHandler unit tests
* Adds ResolutionSwitchingAlgorithm to test misalignment
* Adds support to AlgorithmRunner to store algorithm IResultHandler
* Removed Sample[a-zA-Z]+ methods from IResultHandler definition
* Converted Sample[a-zA-Z]+ methods from public to protected
* Updated inheritors of BaseResultHandler to use new accessibility
modifiers
* Removes useless code in ResolutionSwitchingAlgorithm

#### Related Issue

Closes #3927 
#### Motivation and Context

Provide accurate statistics to end users. Cleans up AlgorithmManager code.
#### Requires Documentation Change

Encourage users to not use daily resolution if possible

#### How Has This Been Tested?

Unit tests, new unit tests
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/AlgorithmManager.cs [hunk 1]
```diff
@@ -728,10 +705,8 @@ public void Run(AlgorithmNodePacket job, IAlgorithm algorithm, ISynchronizer syn
             SetStatus(AlgorithmStatus.Completed);
 
             //Take final samples:
-            results.SampleRange(algorithm.GetChartUpdates());
-            results.SampleEquity(_previousTime, Math.Round(algorithm.Portfolio.TotalPortfolioValue, 4));
-            SampleBenchmark(results, backtestMode ? _previousTime.Date : _previousTime);
-            SamplePerformance(results, _previousTime.Date, force:true);
+            results.Sample(previousTime, force: true);
```
Comment (Martin-Molinero) [inline Engine/AlgorithmManager.cs]: Why use `previousTime` here? Since we are outside the streaming loop at this stage, wouldn't both be equals? Maybe we can join `time` in the loop with this `previousTime` outside the loop, into a single global `time`?

File: Engine/Results/BacktestingResultHandler.cs [hunk 2]
```diff
@@ -54,6 +55,9 @@ public class BacktestingResultHandler : BaseResultsHandler, IResultHandler
         private bool _processingFinalPacket;
         private readonly HashSet<string> _chartSeriesExceededDataPoints;
 
+        protected decimal _closingPortfolioValue;
+        protected DateTime _previousTime;
```
Comment (Martin-Molinero) [inline Engine/Results/BacktestingResultHandler.cs]: We could move these into the `BaseResultsHandler`? Maybe to be more precise, could rename to `_previousUtcSampleTime`/`_dailyPortfolioValue`

nit - `using QuantConnect.Lean.Engine.DataFeeds;` not required

File: Engine/Results/LiveTradingResultHandler.cs [hunk 3]
```diff
@@ -1062,6 +1066,43 @@ protected virtual string CreateSafeChartName(string chartName)
             return Uri.EscapeDataString(chartName);
         }
 
+        /// <summary>
+        /// Samples benchmark continuously, and on date change, samples performance and portfolio equity
+        /// </summary>
+        /// <param name="time">Current time step of the AlgorithmManager loop</param>
+        /// <param name="force">Forces processing of equity and performance if true</param>
+        public virtual void Sample(DateTime time, bool force = false)
```
Comment (Martin-Molinero) [inline Engine/Results/LiveTradingResultHandler.cs]: Seems both live and backtesting implementations are very similar, can we join them and place it into the `BaseResultsHandler`? I think the difference is that Live is sampling the `Benchmark` on each call?

File: Common/Statistics/StatisticsBuilder.cs [hunk 4]
```diff
@@ -265,64 +269,45 @@ private static IEnumerable<PeriodRange> GetPeriodRanges(int periodMonths, DateTi
...
-                listPerformance.Add(0);
-                Log.Trace("StatisticsBuilder.EnsureSameLength(): Padded Performance");
-            }
-            while (listPerformance.Count > listBenchmark.Count)
-            {
-                listBenchmark.Add(0);
-                Log.Trace("StatisticsBuilder.EnsureSameLength(): Padded Benchmark");
-            }
+            // GroupBy(...) is guaranteed to preserve the order the elements are in.
+            // See http://msdn.microsoft.com/en-us/library/bb534501 for more information.
```
Comment (Martin-Molinero) [inline Common/Statistics/StatisticsBuilder.cs]: Nice 👍

File: Common/Statistics/StatisticsBuilder.cs [hunk 5]
```diff
@@ -93,23 +93,28 @@ public static class StatisticsBuilder
...
-            // so we add missing dates with zero value
-            var missingPerformanceDates = benchmark.Keys.Where(x => !performance.ContainsKey(x));
-            foreach (var date in missingPerformanceDates)
+            // In very rare circumstances, we might have multiple entries for a single day in backtesting.
+            // These multiple entries will all be located at the end of the `pointsBenchmark` and `pointsPerformance`
+            // collections, since we force sample at the end of the algorithm.
+            // For good measure and to put any alignment issues to rest, let's resample both collections
+            // to daily resolution just in case.
+            var benchmark = ResampleDaily(ChartPointToDictionary(pointsBenchmark, fromDate, toDate));
+            var performance = ResampleDaily(ChartPointToDictionary(pointsPerformance, fromDate, toDate));
```
Comment (Martin-Molinero) [inline Common/Statistics/StatisticsBuilder.cs]: Nice 👍

File: Tests/Engine/Results/BacktestingResultHandlerTests.cs [hunk 6]
```diff
@@ -0,0 +1,391 @@
...
+using System;
+using System.Collections.Generic;
+using System.Linq;
+
+namespace QuantConnect.Tests.Engine.Results
+{
+    [TestFixture]
+    public class BacktestingResultHandlerTests
+    {
+        private Dictionary<string, BacktestingResultHandler> _resultsCache = new Dictionary<string, BacktestingResultHandler>();
```
Comment (Martin-Molinero) [inline Tests/Engine/Results/BacktestingResultHandlerTests.cs]: If we are just consuming the `Charts`, I'd suggest for us to just store them instead, if we need more in the future we can add it too

File: Tests/AlgorithmRunner.cs [hunk 7]
```diff
@@ -44,6 +44,12 @@ namespace QuantConnect.Tests
     /// </summary>
     public static class AlgorithmRunner
     {
+        /// <summary>
+        /// Dictionary used to store algorithm <see cref="BacktestingResultHandler"/> instances keyed by the algorithm's <see cref="Language"/>
+        /// </summary>
+        public static Dictionary<Language, Dictionary<string, BacktestingResultHandler>> AlgorithmResults = new Dictionary<Language, Dictionary<string, BacktestingResultHandler>>();
```
Comment (Martin-Molinero) [inline Tests/AlgorithmRunner.cs]: I think this isn't required? Since `BacktestingResultHandlerTests` has his own cache? Don't think we can really trust a global cache for results because for example start and end dates could change between executions

File: Tests/Engine/Results/BacktestingResultHandlerTests.cs [hunk 8]
```diff
@@ -0,0 +1,391 @@
...
+
+        [TestCase(nameof(BasicTemplateAlgorithm))]
+        [TestCase(nameof(BasicTemplateDailyAlgorithm))]
+        [TestCase(nameof(ResolutionSwitchingAlgorithm))]
+        public void SamplesNotMisalignedRelative(string algorithm)
+        {
+            var backtestResults = GetResults(algorithm, new DateTime(2013, 10, 7), new DateTime(2013, 10, 11));
+            var benchmarkSeries = backtestResults.Charts["Benchmark"].Series["Benchmark"];
+            var equitySeries = backtestResults.Charts["Strategy Equity"].Series["Equity"];
+            var performanceSeries = backtestResults.Charts["Strategy Equity"].Series["Daily Performance"];
```
Comment (Martin-Molinero) [inline Tests/Engine/Results/BacktestingResultHandlerTests.cs]: I think we are also missing tests that go through the code paths in `StatisticsBuilder`, where part of the changes took place? Maybe simpler unit tests, just for the `StatisticsBuilder`, where for example we can assert it throws if given "misaligned values", it resamples daily

File: Tests/AlgorithmRunner.cs (hunk 7 above)
Comment (gsalaz98) [reply Tests/AlgorithmRunner.cs]: We use it to extract the BacktestingResultHandler from the AlgorithmRunner and load it into the BacktestingResultHandlerTests. It will overwrite any existing value (if there is one). The only caching we do is localized within the result handler test fixture.

File: Engine/Results/LiveTradingResultHandler.cs (hunk 3 above)
Comment (gsalaz98) [reply Engine/Results/LiveTradingResultHandler.cs]: Personally, I think it's best that each `Sample` method is implemented separately since they have their own concerns with how they're sampling. Mixing these concerns might make us reliant on specific base class behavior. 

I'll talk to you more about this, would like to know what your thoughts are 👍

Comment (gsalaz98) [reply Engine/Results/LiveTradingResultHandler.cs]: Update: we looked into addressing this review, but we concluded that it would require additional effort outside the scope of this PR.

**Comment by jaredbroad** [comment]
Closing as tests still not passing. Please open when ready for review.

**Comment by gsalaz98** [comment]
I've gone ahead and changed the existing tests so that they are passing. 

There were a few that couldn't be modified due to the nature of the test, but have been ignored with a message linking to this PR. They are:
* `SamplesNotMisalignedRelative("BasicTemplateDailyAlgorithm")`
* `SamplesNotMisalignedRelative("ResolutionSwitchingAlgorithm")`

I've also addressed Martin's review and updated regression test statistics.

File: Tests/Engine/Results/BacktestingResultHandlerTests.cs [hunk 9]
```diff
@@ -27,19 +28,21 @@ namespace QuantConnect.Tests.Engine.Results
     [TestFixture]
     public class BacktestingResultHandlerTests
     {
-        private Dictionary<string, BacktestingResultHandler> _resultsCache = new Dictionary<string, BacktestingResultHandler>();
+        private object _lock = new object();
```
Comment (Martin-Molinero) [inline Tests/Engine/Results/BacktestingResultHandlerTests.cs]: Why is this lock required?

File: Engine/Results/BaseResultsHandler.cs [hunk 10]
```diff
@@ -106,6 +106,16 @@ public abstract class BaseResultsHandler
...
 
+        /// <summary>
+        /// Closing portfolio value. Used to calculate daily performance.
+        /// </summary>
+        protected decimal _dailyPortfolioValue;
+
+        /// <summary>
+        /// Last time the <see cref="IResultHandler.Sample(DateTime, bool)"/> method was called in UTC
+        /// </summary>
+        protected DateTime _previousUtcSampleTime;
```
Comment (Martin-Molinero) [inline Engine/Results/BaseResultsHandler.cs]: nit - since they are now `protected` they should be renamed to `DailyPortfolioValue` and `PreviousUtcSampleTime`

File: Tests/Common/Statistics/StatisticsBuilderTests.cs [hunk 11]
```diff
@@ -0,0 +1,130 @@
...
+
+using System;
+using System.Collections.Generic;
+using NUnit.Framework;
+using QuantConnect.Statistics;
+
+namespace QuantConnect.Tests.Common.Statistics
+{
+    [TestFixture]
+    public class StatisticsBuilderTests
```
Comment (Martin-Molinero) [inline Tests/Common/Statistics/StatisticsBuilderTests.cs]: Nice 👍

File: Tests/Engine/Results/BacktestingResultHandlerTests.cs [hunk 12]
```diff
@@ -0,0 +1,396 @@
...
+                var results = AlgorithmRunner.AlgorithmResults[Language.CSharp][algorithm];
+                AlgorithmRunner.AlgorithmResults[Language.CSharp].Remove(algorithm);
+
+                return results;
+            }
+        }
+
+        [TestCase(nameof(BasicTemplateAlgorithm))]
+        [TestCase(nameof(BasicTemplateDailyAlgorithm), Ignore=true, IgnoreReason="Failing. Please see PR for more information: https://github.com/QuantConnect/Lean/pull/4003")]
+        [TestCase(nameof(ResolutionSwitchingAlgorithm), Ignore=true, IgnoreReason="Failing. Please see PR for more information: https://github.com/QuantConnect/Lean/pull/4003")]
```
Comment (Martin-Molinero) [inline Tests/Engine/Results/BacktestingResultHandlerTests.cs]: I think these tests shouldn't be ignored?

File: Tests/Engine/Results/BacktestingResultHandlerTests.cs [hunk 13]
```diff
@@ -0,0 +1,396 @@
...
+
+            Assert.AreEqual(new DateTime(2013, 10, 7), performance.FirstKey().Date);
+            Assert.AreEqual(new DateTime(2013, 10, 11), performance.LastKey().Date);
+            Assert.AreEqual(5, performance.ValueCount);
+            Assert.AreEqual(5, performance.KeyCount);
+            Assert.AreEqual(0.0, performance.GetAt(0));
+            Assert.AreEqual(0.0, performance.GetAt(1));
+            Assert.AreEqual(Math.Round(-0.01148770, 6), Math.Round(performance.GetAt(2), 6));
+            Assert.AreEqual(Math.Round(0.011161310, 6), Math.Round(performance.GetAt(3), 6));
+            // Unknown value should go here.
```
Comment (Martin-Molinero) [inline Tests/Engine/Results/BacktestingResultHandlerTests.cs]: nit - this comment seems off?

File: Tests/AlgorithmRunner.cs (hunk 7 above)
Comment (gsalaz98) [reply Tests/AlgorithmRunner.cs]: I don't think so. We still need a way to get the BacktestingResultHandler out of the AlgorithmRunner call.

Comment (Martin-Molinero) [reply Tests/AlgorithmRunner.cs]: Maybe we can create a custom class which holds the `LeanEngineAlgorithmHandlers`, the `AlgorithmManager` and return that instead 🤔

File: Engine/DataFeeds/UniverseSelection.cs [hunk 14]
```diff
@@ -381,7 +381,7 @@ public bool AddPendingInternalDataFeeds(DateTime utcStart)
 
                     var dataConfig = _algorithm.SubscriptionManager.SubscriptionDataConfigService.Add(
                         securityBenchmark.Security.Symbol,
-                        _algorithm.LiveMode ? Resolution.Minute : Resolution.Daily,
+                        _algorithm.LiveMode ? Resolution.Minute : Resolution.Hour,
```
Comment (jaredbroad) [inline Engine/DataFeeds/UniverseSelection.cs]: 127 files changed due to `+2 char; -2 char`....

**Comment by jaredbroad** [comment]
Congrats @Martin-Molinero @gsalaz98
