### PR TITLE
Exclude warmup period from sampling data

### LINKED ISSUE #2279: CAGR Formula Includes Warmup
#### Expected Behavior
CAGR / Statistics should include tradable period. Warm up is essentially a history request and shouldn't impact the statistics results -- or potentially even the charting period.

#### Actual Behavior
Charts flatline during warm up (because you're not allowed to trade) and the statistics skewed because they use the equity period for the years calculation.

#### Potential Solution
 - Stop plotting of the equity chart during the warm up period. This would fix both the skewed statistics and the weird looking charts.
https://github.com/QuantConnect/Lean/blob/master/Common/Statistics/Statistics.cs#L206

#### Reproducing the Problem
```
public class BasicTemplateAlgorithm : QCAlgorithm
{
    private Symbol _spy = QuantConnect.Symbol.Create("SPY", SecurityType.Equity, Market.USA);
    public override void Initialize()
    {
        SetStartDate(2010, 07, 18); 
        SetEndDate(DateTime.Now - TimeSpan.FromDays(1)); 
        SetCash(100000); 
        SetWarmup(1000); 
        AddEquity("SPY", Resolution.Daily); 
    }
 
    public override void OnData(Slice data)
    {
        if (IsWarmingUp) return;
        if (!Portfolio.Invested)
        {
            SetHoldings(_spy, 1);
            Debug("Purchased Stock");
        }
    }
}
```
image

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
Do not add samples to equity and benchmark charts during warm up.

#### Related Issue
Closes #2279

#### Motivation and Context
Get correct and consistent statistics. When we add samples to the equity and benchmark charts during the warm up, the statistics calculations include the warm up time.
Also, do not show warm up flat line when plotting the equity curve.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Algorithm provided in issue #2279. 
Results with and without `SetCash(100000);` match.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/Results/BacktestingResultHandler.cs [hunk 1]
```diff
@@ -642,6 +642,12 @@ public void RuntimeError(string message, string stacktrace = "")
         /// <param name="value">Value for the chart sample.</param>
         public void Sample(string chartName, string seriesName, int seriesIndex, SeriesType seriesType, DateTime time, decimal value, string unit = "$")
         {
+            // Sampling during warming up period skews statistics
+            if (_algorithm.IsWarmingUp)
```
Comment (mchandschuh) [inline Engine/Results/BacktestingResultHandler.cs]: this change didn't impact the regression statistics? If not, then I question the assumption that sampling during warm up skews statistics.

Comment (AlexCatarino) [reply Engine/Results/BacktestingResultHandler.cs]: It didn't. 
We have three types of algorithm with warm up:
1. Those that are not regression algorithm;
2. Those that do not have trades;
3. Those that warm up period is less than one day.
So the regression tests didn't catch the change.

Comment (mchandschuh) [reply Engine/Results/BacktestingResultHandler.cs]: Let's add a regression test whose statistics change because of this PR -- confirm by running it on master and observing different statistics than on this PR's branch.
