### PR TITLE
Fix IB Forex zero conversion rates

### LINKED ISSUE #3811: Conversion rates not available for some Forex currencies with IB
#### Expected Behavior
Conversion rates for valid Forex pairs should always be available.

#### Actual Behavior
Conversion rates for a few currencies such as `SGD` and `HUF` cannot be set when deploying to the IB brokerage.

#### Potential Solution
The default **"market"** for IB Forex symbols is currently set to `Market.FXCM`.
As already mentioned in #3731, Oanda supports many more FX pairs than FXCM, so the solution could be to update the IB brokerage and brokerage model to use `Market.Oanda` instead of `Market.FXCM`.

#### Reproducing the Problem
- Deploy any algorithm to an IB account with some cash in `SGD`.
- At cash sync time -- or simply calling this method:
``` C#
Portfolio.CashBook.ConvertToAccountCurrency(100, "SGD")
```
the algorithm will be terminated with the following error:
```
System.ArgumentException: The conversion rate for SGD is not available.
```
This happens because there is no `USDSGD` symbol available with the FXCM market and the conversion rate for `SGD` is zero.

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
- Updated `InteractiveBrokersBrokerage` and `InteractiveBrokersBrokerageModel` to use `Market.Oanda` instead of `Market.FXCM` when generating Forex symbols.
- Fixed a bug where the default brokerage model was being cached in the  `CurrencySubscriptionDataConfigManager` instead of the actual brokerage model set in the algorithm.

#### Related Issue
Closes #3811 

#### Motivation and Context
- Algorithm runtime error at cash sync time with algorithm deployed to IB with `SGD` or `HUF` cash in the account.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
- Converted some cash to SGD in the IB account
- Verified that the conversion rate is zero and the exception is thrown with current `master` code
- Verified that the conversion rate is non-zero and no exception is thrown using the PR code

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs [hunk 1]
```diff
@@ -2479,7 +2479,7 @@ private bool CanSubscribe(Symbol symbol)
 
             return
                 (securityType == SecurityType.Equity && market == Market.USA) ||
-                (securityType == SecurityType.Forex && market == Market.FXCM) ||
+                (securityType == SecurityType.Forex && market == Market.Oanda) ||
                 (securityType == SecurityType.Option && market == Market.USA) ||
                 (securityType == SecurityType.Future);
```
Comment (Martin-Molinero) [inline Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs]: Maybe to avoid the duplication, could we use the `InteractiveBrokersBrokerageModel.DefaultMarketMap` directly for these checks and the one above (L2176)?

File: Tests/QuantConnect.Tests.csproj [hunk 2]
```diff
@@ -756,7 +756,7 @@
       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
     </Content>
     <Content Include="TestData\FredVixData.json">
-      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
+      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
```
Comment (Martin-Molinero) [inline Tests/QuantConnect.Tests.csproj]: Nice one 👍

File: Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs (hunk 1 above)
Comment (StefanoRaggi) [reply Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs]: Updated `MapSymbol` to reuse the `DefaultMarketMap`, but I would leave `Subscribe` as is for a few reasons:
- CFD trading with IB is not officially supported/tested
- With futures we are currently allowing all markets (will probably have to get back to this when we'll start addressing international markets)
- `Subscribe` is only called when deploying with the IB feed (but not with the QC feed)
