### PR TITLE
Wraps Slice Object with PythonSlice for Python Framework Algorithms

### LINKED ISSUE #3737: Slice Object is not Wrapped for OnFrameworkData
#### Expected Behavior
Like `OnData`, the Slice object in `OnFrameworkData` should be wrapped by `PythonSlice` when custom data is present.

#### Actual Behavior
`Slice` object is not wrapped by `PythonSlice` causing runtime exceptions:
```
System.Exception: ArgumentException : Object of type 'System.RuntimeType' cannot be converted to type 'QuantConnect.Symbol'.
```
#### Potential Solution
In `AlgorithmPythonWrapper.cs`:
```csharp
        public void OnFrameworkData(Slice slice)
        {
            using (Py.GIL())
            {
                _algorithm.OnFrameworkData(SubscriptionManager.HasCustomData ? new PythonSlice(slice) : slice);
            }
        }
```
#### Reproducing the Problem
```python
class NadionDynamicShield(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2019, 3, 1)
        self.SetEndDate(2019, 7, 4)
        self.SetCash(100000)  # Set Strategy Cash
        # self.AddEquity("SPY", Resolution.Minute)
        self.AddAlpha(SmartInsiderAlphaModel())

        symbols = [ Symbol.Create("IBM", SecurityType.Equity, Market.USA) ]

        # set algorithm framework models
        self.SetUniverseSelection(ManualUniverseSelectionModel(symbols))

from QuantConnect.Data.Custom.SmartInsider import *
class SmartInsiderAlphaModel:
    
    def Update(self, algorithm, data):
        insights = []
        
        intentions = data.Get(SmartInsiderIntention)
            
        return insights
    
    def OnSecuritiesChanged(self, algorithm, changes):
        for security in changes.AddedSecurities:
            if security.Type == SecurityType.Equity:
                intention = algorithm.AddData(SmartInsiderIntention, security.Symbol).Symbol
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
Wraps `Slice` object with `PythonSlice` for Python framework algorithms when alternative/custom data is present.

#### Related Issue
Closes #3737 

#### Motivation and Context
Bug fix

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Ran backtest in QC cloud using the algorithm from #3737 . 

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: AlgorithmFactory/Python/Wrappers/AlgorithmPythonWrapper.cs [hunk 1]
```diff
@@ -558,7 +558,20 @@ public void OnData(Slice slice)
...
+            if (SubscriptionManager.HasCustomData)
+            {
+                using (Py.GIL())
+                {
+                    _algorithm.OnFrameworkData(new PythonSlice(slice));
+                }
+            }
+            else
+            {
+                _baseAlgorithm.OnFrameworkData(slice);
```
Comment (Martin-Molinero) [inline AlgorithmFactory/Python/Wrappers/AlgorithmPythonWrapper.cs]: Wondering why one is `_algorithm.OnFrameworkData` and the other `_baseAlgorithm.OnFrameworkData`? Might be cleaner if it were 1 liner `SubscriptionManager.HasCustomData ? new PythonSlice(slice) : slice`

Comment (AlexCatarino) [reply AlgorithmFactory/Python/Wrappers/AlgorithmPythonWrapper.cs]: In my version 1.0, I implemented it line `OnData`.
However, if we don't have custom data, we don't need to use the Py.GIL lock.
