### PR TITLE
Fixes EquityFillModel.FillModel

### LINKED ISSUE #6973: Review Fill Model: Limit Fill
#### Expected Behavior
[Limit Orders](https://www.interactivebrokers.com/en/index.php?f=593):

>Step 1 – Enter a Limit Buy Order
>XYZ stock has a current Ask price of 34.00 and you want to use a Limit order to buy 100 shares when the market price falls to 33.50.
>You create the Limit order as shown above.
>Step 2 – Order Transmitted, Market Price Begins to Fall
>As soon as you transmit your Limit order, the market price of XYZ stock begins to fall.
>Step 3 – Market Price Falls to Limit Price, Order Filled
>The market price of XYZ continues to fall until it touches your Limit Price of 33.50. Your order for 100 shares is filled.
>where the market price is the market offer.

#### Actual Behavior
`FillModel.LimitFill` uses **quote** data to trigger the order.

#### Potential Solution
Remove the `FillModel.GetPrices` logic and write the `LimitFill` method to use `Tick.Trade` or `TradeBar` properties. We need to create unit tests that cover all scenarios and security types. For instance, Forex and CFD don't have trade data.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
Use `Tick` with `TickType.Trade` or `TradeBar` information to fill limit orders.

- Adds Unit Tests:
The `LimitFill` method should not fill using `QuoteBar` or `Tick` with `TickType.Quote` type.
Adds missing test for tick data (`TickType.Trade`).

- Update Regression Test Expected Statistics:
The regression tests changed because of different fills.
The `ExtendedMarketTradingRegressionAlgorithm` has different number of trades because of an extra fill on the 4th order generated by TradeBar with a Low lower than than the QuoteBar.Ask Low:

> 20230222 13:56:24.251 TRACE:: Log: Time: 10/10/2013 12:01:00 OrderID: 4 EventID: 2 Symbol: SPY Status: Filled Quantity: 10 FillQuantity: 10 FillPrice: 143.8998 USD

> asset.Cache.GetData<QuoteBar>().ToString()
"SPY: Bid: O: 144.2457 Bid: H: 144.2629 Bid: **L: 144.2457** Bid: C: 144.2629 Ask: O: 144.2543 Ask: H: 144.2889 Ask: **L: 144.2543** Ask: C: 144.2889 "

> asset.Cache.GetData<TradeBar>().ToString()
"SPY: O: 144.2543 H: 144.4532 **L: 143.4156** C: 144.2716 V: 75423"

#### Related Issue
Closes #6973

#### Motivation and Context
Fix modeling bug.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
New unit tests exposing the bug.
Regression tests.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Orders/Fills/EquityFillModel.cs [hunk 1]
```diff
@@ -350,37 +350,64 @@ public override OrderEvent LimitFill(Security asset, LimitOrder order)
...
+                    if (tradeLow < order.LimitPrice)
                     {
                         //Set order fill:
                         fill.Status = OrderStatus.Filled;
                         // fill at the worse price this bar or the limit price, this allows far out of the money limits
                         // to be executed properly
-                        fill.FillPrice = Math.Min(prices.High, order.LimitPrice);
+                        fill.FillPrice = Math.Min(tradeHigh, order.LimitPrice);
                         // assume the order completely filled
                         fill.FillQuantity = order.Quantity;
```
Comment (jaredbroad) [inline Common/Orders/Fills/EquityFillModel.cs:400]: Please add TODO: Add separate DepthLimited fill partial order quantities based on tick quantity / bar.Volume available.

**Review by Martin-Molinero — APPROVED** [review]
