### PR TITLE
Linux PyCharm Docker Debugger Fix

### LINKED ISSUE #5070: PyCharm Debug in Container Not Working in Linux
#### Expected Behavior

Lean running in Docker container can successfully connect to PyCharm Debug Server on Local Machine

#### Actual Behavior

Connection is refused.
```
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/_pydevd_bundle/pydevd_comm.py", line 456, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Could not connect to host.docker.internal: 6000
```

#### Potential Solution

Unsure as to what is the cause of this issue. This setup works fine in Windows 10. Would be interested in seeing others test this.

#### Reproducing the Problem

Set config to a Python algorithm and follow the steps in PyCharm readme (.idea/readme.md) and attempt to debug your algorithm running in the container

#### System Information

Ubuntu 20.04

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

Use docker --add-host command to map the host ip to host.docker.internal to make it operate the same way that windows does.

#### Related Issue

Closes #5070

#### Motivation and Context

Linux Docker does not support host.docker.internal so the container was unable to connect to pycharms debugger. Now with this change it can resolve the address and connect to the host.

There is some mention in docker/for-linux repo that soon it should support it some manner but for now this works.

#### Requires Documentation Change

n/a

#### How Has This Been Tested?

Working in Ubuntu 20.04

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: run_docker.sh [hunk 1]
```diff
@@ -105,7 +105,11 @@ COMMAND="docker run --rm \
     -v $RESULTS_DIR:/Results \
     --name $CONTAINER_NAME \
     -p 5678:5678 \
-    --expose 6000 --add-host=host.docker.internal:$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+') "
+    --expose 6000 "
+
+if [[ "$(uname)" == "Linux" ]]; then
+  COMMAND+="--add-host=host.docker.internal:$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+') "
```
Comment (Martin-Molinero) [inline run_docker.sh:111]: This is to avoid setting the `host.docker.internal` which works for MacOS

**Review by Martin-Molinero — APPROVED** [review]
