### PR TITLE
bug-1710-KaikoDataConverter stops processing if there are unexpected files 

### LINKED ISSUE #1710: KaikoDataConverter stops if there are other files than zipped data in destiantion folder.
#### Expected Behavior

The Kaiko converter should convert all available tick raw data into all resolutions.  

#### Actual Behavior

If there is a file other than a zipped in some of the target variable, then it throws an unhanded error and stops the processing.

#### Potential Solution

Processing only supported zipped files.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ ] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Jay-Jay-D**
#### Description

Only processing supported zipped data files.

Also some handling error in case of corrupted raw data file.

#### Related Issue

Fixed #1710 

#### Motivation and Context

It 

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/ect)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: ToolBox/KaikoDataConverter/Program.cs [hunk 1]
```diff
@@ -87,7 +96,7 @@ private static void AggregateTicksInAllResolutions(string market, TickType tickT
                 var symbolDirectoryInfo = new DirectoryInfo(tickDirectory);
                 var symbol = Symbol.Create(symbolDirectoryInfo.Name, SecurityType.Crypto, market);
 
-                foreach (var tickDateFile in Directory.EnumerateFiles(symbolDirectoryInfo.FullName))
+                foreach (var tickDateFile in Directory.EnumerateFiles(symbolDirectoryInfo.FullName, "*.zip"))
```
Comment (jaredbroad) [inline ToolBox/KaikoDataConverter/Program.cs]: This can still fail too; please also try catch inside this foreach -- e.g. corrupt zip.
