### PR TITLE
Do not terminate algorithm for exceptions in GDAX Fill Monitor

### LINKED ISSUE #4909: Exception in GDAX Fill Monitor causes algorithm termination
#### Expected Behavior
- An exception thrown in the Fill Monitor task should not terminate the algorithm

#### Actual Behavior
- An exception thrown in the Fill Monitor task terminates the algorithm (Runtime error)

#### Potential Solution
- Emit a `BrokerageMessageType.Warning` instead of BrokerageMessageType.Error

#### Reproducing the Problem
- An error in the fill monitor is usually caused by a failed REST API call (`/fills` endpoint)

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
- An exception in the GDAX Fill Monitor no longer terminates the algorithm

#### Related Issue
Closes #4909 

#### Motivation and Context
- Occasional API call failures should not terminate a live algorithm

#### Requires Documentation Change
No.

#### How Has This Been Tested?
n/a

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Brokerages/GDAX/GDAXBrokerage.Messaging.cs [hunk 1]
```diff
@@ -560,7 +560,7 @@ private void FillMonitorAction()
             }
             catch (Exception exception)
             {
-                OnMessage(new BrokerageMessageEvent(BrokerageMessageType.Error, -1, exception.Message));
+                OnMessage(new BrokerageMessageEvent(BrokerageMessageType.Warning, -1, exception.Message));
```
Comment (Martin-Molinero) [inline Brokerages/GDAX/GDAXBrokerage.Messaging.cs:563]: Believe the monitoring task still stop running though? Maybe instead of `throw new Exception($"GDAXBrokerage.FillMonitorAction()....` above we could directly trigger this `Warning` message, not throw and continue, so it keeps running. And if there is another unexpected exception we **do** emit a `Error` message type here

**Review by Martin-Molinero — APPROVED** [review]
