### PR TITLE
 Fixes InsightDirection.Flat allocation in EqualWeightingPortfolioConstructionModel

### LINKED ISSUE #2327: EqualWeightingPortfolioConstructionModel Flat Allocations
#### Expected Behavior
When alpha model assigns a `Flat` insight; the resources for the allocation should be freed up and reallocated to the other `Up` or `Down` insights in portfolio.

#### Actual Behavior
`Flat` retains an allocation of the portfolio.

#### Potential Solution
`activeSymbols = all insights Up + Down who aren't expired.`
`percent = 1 / activeSymbols`
[C#](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Framework/Portfolio/EqualWeightingPortfolioConstructionModel.cs#L69) and [Python](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Framework/Portfolio/EqualWeightingPortfolioConstructionModel.py#L55) both have same implementation issue.

#### Reproducing the Problem
https://www.quantconnect.com/forum/discussion/4302/alpha-framework-does-not-buy-and-sell-when-i-would-expect-based-on-my-generated-insights/p1

Run an algorithm with flat allocations.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
The allocation should be calculated for symbols which last insights are not `InsightDirection.Flat`. For example, if the last insight of SPY and of IBM are Up, and of AIG is flat, then 50% of equity should be allocated in SPY, 50% in IBM and 0% in AIG. Before this fix, we would have 33% SPY, 33%, IBM and 0% AIG.

#### Related Issue
Closes #2327 

#### Motivation and Context
Fix and improve framework models.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Ran a backtest with the `VolumeWeightedAveragePriceExecutionModelRegressionAlgorithm` and modified `RsiAlphaModel` to emit `InsightDirection.Flat` when `State.Middle`.
Note: Lean doesn't have an alpha model that emits an insight with direction of `InsightDirection.Flat`.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by jaredbroad** [comment]
Pending unit tests

File: Algorithm.Framework/Portfolio/EqualWeightingPortfolioConstructionModel.cs [hunk 1]
```diff
@@ -55,26 +55,24 @@ public override IEnumerable<IPortfolioTarget> CreateTargets(QCAlgorithmFramework
...
 
-            // Get symbols that have emit insights, are still in the universe, and insigths haven't expired
-            var symbols = _insightCollection
-                .Where(x => x.CloseTimeUtc > algorithm.UtcTime)
-                .Select(x => x.Symbol).Distinct().ToList();
+            // Get last insight that haven't expired of each symbol that is still in the universe
+            var activeInsights = (from insight in _insightCollection
+                                  group insight by insight.Symbol into g
+                                  where g.LastOrDefault().CloseTimeUtc > algorithm.UtcTime
+                                  select g.LastOrDefault()).ToList();
```
Comment (mchandschuh) [inline Algorithm.Framework/Portfolio/EqualWeightingPortfolioConstructionModel.cs]: We could be losing insights here. Maybe a better option is to sort by generated time and then grabbing the 'last' isn't arbitrary -- we would simply be grabbing the most recent insight.
