### PR TITLE
Detect unsupported option style in option price model

### LINKED ISSUE #4520: Greeks Always 0 With BlackScholes and Integral Price Models
#### Expected Behavior

All price models should return non-zero greek values.

#### Actual Behavior

BlachScholes and Integral models return zero-value greeks.

#### Potential Solution

Possibly an issue with QuantLib library.

#### Reproducing the Problem

View the logs of [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_56b78eff244f704a058e7cb6ef38055d.html).

#### System Information

Run in the QC web terminal. Windows 10.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

When using a `QLOptionPriceModel` for an unsupported option style (like `BlackScholes` or `Integral` for an American style option), price estimation and greeks calculation by QLNet fails by throwing an exception. In this case, option price calculation was defaulting to 0 (which lead to greeks having an invalid value of 0) instead of detecting and communicating the issue. Now the unsupported option style is detected and communicated. On the other hand, using `BlackScholes` or `Integral` for European style options does calculate valid greeks.

#### Related Issue

Closes #4520 

#### Motivation and Context

Using `QLOptionPriceModel` for an unsupported option style (like `BlackScholes` or `Integral` for an American style option) was defaulting option price estimation to 0 and by extension assigning 0 to greeks. Ideally, the problem is detected and communicated.

#### Requires Documentation Change

This issue does not require documentation changes.

#### How Has This Been Tested?

- Asserting that option price evaluation (`OptionPriceModel.Evaluate()`) throws for an unsuported option style (like `BlackScholes` for American style options).
- Asserting that option price evaluation (`OptionPriceModel.Evaluate()`) does not throws for a suported option style (like `BlackScholes` for European style options).

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Securities/Option/OptionPriceModels.cs [hunk 1]
```diff
@@ -110,11 +114,12 @@ public static IOptionPriceModel Integral()
...
                                            _underlyingVolEstimator,
                                            _riskFreeRateEstimator,
-                                           _dividendYieldEstimator);
+                                           _dividendYieldEstimator,
+                                           new[] { OptionStyle.European });
         }
 
         /// <summary>
-        /// Pricing engine for European options using finite-differences. 
+        /// Pricing engine for European options using finite-differences.
```
Comment (AlexCatarino) [inline Common/Securities/Option/OptionPriceModels.cs:122]: Could you please update the method description/summary too? `CrankNicolsonFD` support both `American` and `European` option according to the `allowedOptionStyles` 15 lines below. I think we should add this information "for European", "for American", "for both American and European" in all descriptions/summary.

**Review by Martin-Molinero — APPROVED** [review]
Nice! Minor comments passed through slack

**Review by Martin-Molinero — APPROVED** [review]

**Review by Martin-Molinero — APPROVED** [review]
