### PR TITLE
Exclude expired options from IB GetAccountHoldings

### LINKED ISSUE #3728: Options with IB in Live Mode: "No security definition has been found for the request"
#### Expected Behavior
Have enough information about to understand the reason of IB's message: "No security definition has been found for the request". 

#### Actual Behavior
Current message is not enough.

#### Potential Solution
Add better logging info.

#### Reproducing the Problem
Live algorithm trading options near expiration.
```
2019-09-20T20:12:52.9162610Z TRACE:: BrokerageSetupHandler.Setup(): Has existing holding: BHP   190920C00055000: 20 @ $2.417938 - Market: $0.0000044 - Conversion: 
2019-09-20T20:12:52.9163080Z TRACE:: BrokerageSetupHandler.Setup(): Adding unrequested security: BHP   190920C00055000
2019-09-20T20:12:52.9165940Z TRACE:: BrokerageSetupHandler.Setup(): Has existing holding: BHP   190920C00052500: 20 @ $1.654929 - Market: $0.00060135 - Conversion: 
2019-09-20T20:12:52.9166400Z TRACE:: BrokerageSetupHandler.Setup(): Adding unrequested security: BHP   190920C00052500 
```
```
2019-09-20T20:12:58.9238550Z TRACE:: InteractiveBrokersBrokerage.HandleError(): RequestId: 2 ErrorCode: 200 - No security definition has been found for the request. Origin: GetContractDetails: OPT BHP USD Smart 
```
#### System Information
QC Cloud.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
- The `InteractiveBrokersBrokerage.GetAccountHoldings()` method has been updated to filter out expired option holdings returned by IB.

#### Related Issue
Closes #3728 

#### Motivation and Context
Runtime error when deploying an algorithm to IB account with expired option holdings:
```
ErrorCode: 200 - No security definition has been found for the request.
```

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Live algorithm with IB + new unit tests.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs [hunk 1]
```diff
@@ -501,7 +502,11 @@ public override List<Holding> GetAccountHoldings()
                 Connect();
             }
 
-            var holdings = _accountData.AccountHoldings.Select(x => ObjectActivator.Clone(x.Value)).Where(x => x.Quantity != 0).ToList();
+            var utcNow = DateTime.UtcNow;
+            var holdings = _accountData.AccountHoldings
+                .Select(x => ObjectActivator.Clone(x.Value))
+                .Where(x => x.Quantity != 0 && !OptionSymbol.IsOptionContractExpired(x.Symbol, utcNow))
```
Comment (Martin-Molinero) [inline Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs]: Maybe we could add a log letting the user now we are filtering out these expired option holdings
