### PR TITLE
Bug 4600 brokerage unsubscribe symbol granular

### LINKED ISSUE #4600: Brokerages Unsubscribe interrupt listening symbol even there are other subscriptions
#### Expected Behavior

Need more accurate Unsubscribe implementation that doesn't harm other existing Subscriptions

#### Actual Behavior

Brokerage implementation  stop listening Symbol once `Unsubscribe` is called, even there are more subscriptions for that symbol

#### Potential Solution

Refactor existing brokerages implementation and remove only corresponding subscription. It's important to know that different brokerages behaves differently and can listed different channels for Quote/Trade bars

#### Reproducing the Problem

To understand the problem we can Subscribe twise for the same symbol (Quote and Trade bars, or different resolution) and then remove one of them.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AdalyatNazirov**
#### Description

Fix broekrage Subscribe/Unsubscribe methods to be more accurate and subscribe/unsubscribe proper channels 

#### Related Issue

Closes #4600 

also fixed
- bitfixed public channel unsubscribe command spelling ('channelId' => 'chanId')
- bitfinex unsubscribe logic (unsubscribed from all channels from current websocket)
- GDAX unsubscribe - unsubscribe from specific channels rather than entire list

#### Motivation and Context

Current implementation relies on Symbol, but since we refactored IDataQueueHandler we need to change it dependent on SubsctiptionConfigData not only Symbol

#### How Has This Been Tested?

Manual testing
Unit tests

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Brokerages/BaseWebsocketsBrokerage.cs [hunk 1]
```diff
@@ -71,6 +67,8 @@ public abstract class BaseWebsocketsBrokerage : Brokerage
         private readonly object _lockerConnectionMonitor = new object();
         private volatile bool _connectionLost;
         private const int _connectionTimeout = 30000;
+
+        protected DataQueueHandlerSubscriptionManager _subscriptionManager;
```
Comment (Martin-Molinero) [inline Brokerages/BaseWebsocketsBrokerage.cs:71]: code style nit - missing xml docs and should be renamed to `SubscriptionManager`

File: Brokerages/Bitfinex/BitfinexBrokerage.Messaging.cs [hunk 2]
```diff
@@ -131,40 +130,8 @@ public void SubscribeAuth()
...
-        private void Unsubscribe(IEnumerable<Symbol> symbols)
-        {
-            foreach (var symbol in symbols)
-            {
-                _subscriptionManager.Unsubscribe(symbol);
 
-                Log.Trace($"BitfinexBrokerage.Unsubscribe(): Sent unsubscribe for {symbol.Value}.");
-            }
-        }
+        public override void Subscribe(IEnumerable<Symbol> symbols) { }
```
Comment (Martin-Molinero) [inline Brokerages/Bitfinex/BitfinexBrokerage.Messaging.cs:134]: We should add a comment of why this isn't required, and wasn't used in master either, same for `GetSubscribed`

File: Brokerages/Fxcm/FxcmBrokerage.DataQueueHandler.cs [hunk 3]
```diff
@@ -61,18 +64,16 @@ public IEnumerator<BaseData> Subscribe(SubscriptionDataConfig dataConfig, EventH
...
+        /// <param name="tickType">Type of tick data</param>
+        private bool Subscribe(IEnumerable<Symbol> symbols, TickType tickType)
         {
-            var symbolsToSubscribe = (from symbol in symbols 
-                                      where !_subscribedSymbols.Contains(symbol) && CanSubscribe(symbol)
-                                      select symbol).ToList();
-            if (symbolsToSubscribe.Count == 0)
-                return;
+            if (symbols.Any())
+                return false;
```
Comment (Martin-Molinero) [inline Brokerages/Fxcm/FxcmBrokerage.DataQueueHandler.cs:71]: This should be `!symbols.Any()`? not sure this is a possible case though? Same for `Unsubscribe`

File: Brokerages/Fxcm/FxcmBrokerage.cs [hunk 4]
```diff
@@ -115,6 +116,11 @@ public FxcmBrokerage(IOrderProvider orderProvider, ISecurityProvider securityPro
             _password = password;
             _accountId = accountId;
 
+            _subscriptionManager = new EventBasedDataQueueHandlerSubscriptionManager();
+            _subscriptionManager.SubscribeImpl += Subscribe;
+            _subscriptionManager.UnsubscribeImpl += Unsubscribe;
+            _subscriptionManager.GetChannelName += (t) => "quote";
```
Comment (Martin-Molinero) [inline Brokerages/Fxcm/FxcmBrokerage.cs:122]: Seems that `GetChannelName` would be better as an argument for `EventBasedDataQueueHandlerSubscriptionManager` constructor, don't think it would work without it?

File: Brokerages/GDAX/GDAXBrokerage.Messaging.cs [hunk 5]
```diff
@@ -558,5 +581,21 @@ private void FillMonitorAction()
 
             Log.Trace("GDAXBrokerage.FillMonitorAction(): task ended");
         }
+
+        /// <summary>
+        /// Checks if this brokerage supports the specified symbol
+        /// </summary>
+        /// <param name="symbol">The symbol</param>
+        /// <returns>returns true if brokerage supports the specified symbol; otherwise false</returns>
+        public bool CanSubscribe(Symbol symbol)
```
Comment (Martin-Molinero) [inline Brokerages/GDAX/GDAXBrokerage.Messaging.cs:590]: nit - Think this method can be private?

File: Brokerages/GDAX/GDAXBrokerage.Messaging.cs [hunk 6]
```diff
@@ -497,12 +503,29 @@ private bool IsSubscribeAvailable(Symbol symbol)
...
+        public bool Unsubscribe(IEnumerable<Symbol> symbols, TickType tickType)
         {
             if (WebSocket.IsOpen)
             {
-                WebSocket.Send(JsonConvert.SerializeObject(new { type = "unsubscribe", channels = ChannelNames }));
+                var products = symbols
+                    .Select(s => s.Value.Substring(0, 3) + "-" + s.Value.Substring(3))
+                    .ToArray();
+
+                if (products.Length == 0)
```
Comment (Martin-Molinero) [inline Brokerages/GDAX/GDAXBrokerage.Messaging.cs:514]: Don't think this could happen either?

File: Brokerages/GDAX/GDAXBrokerage.Messaging.cs [hunk 7]
```diff
@@ -380,19 +380,24 @@ private void EmitTradeTick(Messages.Matched message)
             });
         }
 
+        /// <summary>
+        /// Creates websocket message subscriptions for the supplied symbols
+        /// </summary>
+        protected bool Subscribe(IEnumerable<Symbol> symbols, TickType tickType)
```
Comment (Martin-Molinero) [inline Brokerages/GDAX/GDAXBrokerage.Messaging.cs:386]: I think that if `TickType` doesn't apply for this IDQH (for all similar cases) let's just not use it and drop it at the `subscriptionManager.Un/SubscribeImpl +=` level, will make the methods cleaner

File: Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs [hunk 8]
```diff
@@ -247,6 +248,11 @@ public InteractiveBrokersBrokerage(IAlgorithm algorithm, IOrderProvider orderPro
             _port = port;
             _agentDescription = agentDescription;
 
+            _subscriptionManager = new EventBasedDataQueueHandlerSubscriptionManager();
+            _subscriptionManager.SubscribeImpl += Subscribe;
+            _subscriptionManager.UnsubscribeImpl += Unsubscribe;
```
Comment (Martin-Molinero) [inline Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs:253]: `EventBasedDataQueueHandlerSubscriptionManager` is pretty cool! 👍

File: Brokerages/GDAX/GDAXDataQueueHandler.cs [hunk 9]
```diff
@@ -35,6 +36,12 @@ public class GDAXDataQueueHandler : GDAXBrokerage, IDataQueueHandler
             IPriceProvider priceProvider, IDataAggregator aggregator)
             : base(wssUrl, websocket, restClient, apiKey, apiSecret, passPhrase, algorithm, priceProvider, aggregator)
         {
+            var subscriptionManager = new EventBasedDataQueueHandlerSubscriptionManager();
```
Comment (Martin-Molinero) [inline Brokerages/GDAX/GDAXDataQueueHandler.cs:39]: Think here we have base `protected DataQueueHandlerSubscriptionManager _subscriptionManager` from `BaseWebsocketsBrokerage` ?

File: Brokerages/Oanda/OandaRestApiBase.cs [hunk 10]
```diff
@@ -143,6 +148,20 @@ protected OandaRestApiBase(OandaSymbolMapper symbolMapper, IOrderProvider orderP
             AccountId = accountId;
             Agent = agent;
             Aggregator = aggregator;
+            _subscriptionManager = new EventBasedDataQueueHandlerSubscriptionManager();
+            _subscriptionManager.SubscribeImpl += (s, t) =>
+            {
+                Log.Trace("OandaBrokerage.Subscribe(): {0}", string.Join(",", s.Select(x => x.Value)));
```
Comment (Martin-Molinero) [inline Brokerages/Oanda/OandaRestApiBase.cs:154]: Maybe we should we move the `Subscribe/Unsubscribe` logs into the base `DataQueueHandlerSubscriptionManager` and remove it from the different consumers, so we normalize & centralize behavior regarding it

File: Brokerages/Oanda/OandaRestApiBase.cs [hunk 11]
```diff
@@ -347,110 +366,35 @@ public void SetJob(LiveNodePacket job)
...
         /// </summary>
         private void ProcessSubscriptionRequest()
         {
-            if (_subscriptionsPending) return;
+            if (_refreshDelay.Enabled) _refreshDelay.Stop();
+            _refreshDelay.DisposeSafely();
+            _refreshDelay = new Timer(SubscribeDelay.TotalMilliseconds);
+            _refreshDelay.Elapsed += (sender, args) =>
+            {
+                var symbolsToSubscribe = SubscribedSymbols;
```
Comment (Martin-Molinero) [inline Brokerages/Oanda/OandaRestApiBase.cs:389]: Not sure about this `timer`, seems there are race conditions, 🤔, we should probably have a single task started in the constructor which monitors an event that we trigger here and has to take the `lock (LockerSubscriptions)`

File: Brokerages/Tradier/TradierBrokerage.DataQueueHandler.cs [hunk 12]
```diff
@@ -43,9 +43,10 @@ public partial class TradierBrokerage
         private bool _disconnect;
         private volatile bool _refresh = true;
         private Timer _refreshDelay = new Timer();
-        private readonly ConcurrentDictionary<Symbol, string> _subscriptions = new ConcurrentDictionary<Symbol, string>();
         private Stream _tradierStream;
 
+        public IEnumerable<Symbol> Subscriptions => _subscriptionManager.GetSubscribedSymbols();
```
Comment (Martin-Molinero) [inline Brokerages/Tradier/TradierBrokerage.DataQueueHandler.cs:48]: Not sure we need this public property?

File: Common/Data/DataQueueHandlerSubscriptionManager.cs [hunk 13]
```diff
@@ -0,0 +1,150 @@
...
+{
+    /// <summary>
+    /// Count number of subscribers for each channel (Symbol, Socket) pair
+    /// </summary>
+    public abstract class DataQueueHandlerSubscriptionManager
+    {
+        /// <summary>
+        /// Counter
+        /// </summary>
+        protected ConcurrentDictionary<Channel, int> _subscribersByChannel = new ConcurrentDictionary<Channel, int>();
```
Comment (Martin-Molinero) [inline Common/Data/DataQueueHandlerSubscriptionManager.cs:33]: nit - code style, protected are upper case

File: ToolBox/IEX/IEXDataQueueHandler.cs [hunk 14]
```diff
@@ -68,6 +71,21 @@ public IEXDataQueueHandler() : this(true)
...
+                return true;
+            };
+
+            _subscriptionManager.UnsubscribeImpl += (s, t) =>
+            {
+                Unsubscribe(s);
+                return true;
+            };
+
+            _subscriptionManager.GetChannelName += (t) => "quote-trade";
```
Comment (Martin-Molinero) [inline ToolBox/IEX/IEXDataQueueHandler.cs:87]: In these cases where the channel is unique and unimportant, maybe we could define a `static string Channel.Single` or something similar? I think it will make it clearer

**Review by Martin-Molinero — CHANGES_REQUESTED** [review]
Nice work! Sweet improvement 👍
Leaving some concerns and minor comments

File: Brokerages/BaseWebsocketsBrokerage.cs (hunk 1 above)
Comment (AdalyatNazirov) [reply Brokerages/BaseWebsocketsBrokerage.cs:71]: done

File: Brokerages/Fxcm/FxcmBrokerage.DataQueueHandler.cs (hunk 3 above)
Comment (AdalyatNazirov) [reply Brokerages/Fxcm/FxcmBrokerage.DataQueueHandler.cs:71]: done

File: Brokerages/Bitfinex/BitfinexBrokerage.Messaging.cs (hunk 2 above)
Comment (AdalyatNazirov) [reply Brokerages/Bitfinex/BitfinexBrokerage.Messaging.cs:134]: done

File: Brokerages/GDAX/GDAXBrokerage.Messaging.cs (hunk 5 above)
Comment (AdalyatNazirov) [reply Brokerages/GDAX/GDAXBrokerage.Messaging.cs:590]: moved to `GDAXDataQueueHandler`, and now it can be private.
done

File: Brokerages/GDAX/GDAXBrokerage.Messaging.cs (hunk 6 above)
Comment (AdalyatNazirov) [reply Brokerages/GDAX/GDAXBrokerage.Messaging.cs:514]: done

File: Common/Data/DataQueueHandlerSubscriptionManager.cs (hunk 13 above)
Comment (AdalyatNazirov) [reply Common/Data/DataQueueHandlerSubscriptionManager.cs:33]: done

File: Brokerages/Fxcm/FxcmBrokerage.cs (hunk 4 above)
Comment (AdalyatNazirov) [reply Brokerages/Fxcm/FxcmBrokerage.cs:122]: agree, done

File: Brokerages/GDAX/GDAXDataQueueHandler.cs (hunk 9 above)
Comment (AdalyatNazirov) [reply Brokerages/GDAX/GDAXDataQueueHandler.cs:39]: yeah. exactly. and it's assigned right there :)

File: Brokerages/Oanda/OandaRestApiBase.cs (hunk 10 above)
Comment (AdalyatNazirov) [reply Brokerages/Oanda/OandaRestApiBase.cs:154]: agree. done

File: Brokerages/Tradier/TradierBrokerage.DataQueueHandler.cs (hunk 12 above)
Comment (AdalyatNazirov) [reply Brokerages/Tradier/TradierBrokerage.DataQueueHandler.cs:48]: It's used for new update ticker list and recreate session

File: ToolBox/IEX/IEXDataQueueHandler.cs (hunk 14 above)
Comment (AdalyatNazirov) [reply ToolBox/IEX/IEXDataQueueHandler.cs]: done

File: Brokerages/GDAX/GDAXDataQueueHandler.cs (hunk 9 above)
Comment (Martin-Molinero) [reply Brokerages/GDAX/GDAXDataQueueHandler.cs:39]: oh 😅 I see it now, confusing, same thought for `PolygonDataQueueHandler`. I'd suggest directly setting the final property from the start, but it's okay like this too

File: Common/Data/Channel.cs [hunk 15]
```diff
@@ -0,0 +1,105 @@
...
+                hash = (hash * 16777619) ^ Name.GetHashCode();
+                hash = (hash * 16777619) ^ Symbol.GetHashCode();
+                return hash;
+            }
+        }
+
+        /// <summary>
+        /// Represents an internal channel name for all brokerage channels in case we don't differentiate them
+        /// </summary>
+        public static string Single = "common";
```
Comment (Martin-Molinero) [inline Common/Data/Channel.cs:103]: nit - following code style this guy should be at the top of this class

File: Common/Data/DataQueueHandlerSubscriptionManager.cs [hunk 16]
```diff
@@ -0,0 +1,150 @@
...
+            return new Channel(
+                ChannelNameFromTickType(tickType),
+                symbol);
+        }
+
+        /// <summary>
+        /// Returns subscribed symbols
+        /// </summary>
+        /// <returns>list of <see cref="Symbol"/> currently subscribed</returns>
+        public IEnumerable<Symbol> GetSubscribedSymbols()
```
Comment (Martin-Molinero) [inline Common/Data/DataQueueHandlerSubscriptionManager.cs:143]: nit - `public` methods should be before `private/protected` ones, same for `IsSubscribed`

File: ToolBox/Polygon/PolygonWebSocketClientWrapper.cs [hunk 17]
```diff
@@ -61,41 +61,36 @@ public PolygonWebSocketClientWrapper(string apiKey, ISymbolMapper symbolMapper,
...
+                return;
             }
 
-            // quotes
             Send(JsonConvert.SerializeObject(
                 new
                 {
                     action = subscribe ? "subscribe" : "unsubscribe",
-                    @params = $"{GetSubscriptionPrefix(symbol.SecurityType, TickType.Quote)}.{ticker}"
+                    @params = $"{GetSubscriptionPrefix(symbol.SecurityType, tickType)}.{ticker}"
```
Comment (Martin-Molinero) [inline ToolBox/Polygon/PolygonWebSocketClientWrapper.cs:93]: Nice consolidation! 👍

File: Brokerages/Bitfinex/BitfinexSubscriptionManager.cs [hunk 18]
```diff
@@ -94,64 +123,92 @@ public void Subscribe(Symbol symbol)
...
                             {
-                                foreach (var channel in channels)
+                                Channel channel = new Channel(channelName, symbol);
+                                List<Channel> channels;
+                                if (_channelsByWebSocket.TryGetValue(webSocket, out channels) && channels.Contains(channel))
                                 {
-                                    UnsubscribeChannel(webSocket, channel.ChannelId);
+                                    UnsubscribeChannel(webSocket, channel);
+
+                                    if (_onUnsubscribeEvent.WaitOne(TimeSpan.FromSeconds(30)))
```
Comment (Martin-Molinero) [inline Brokerages/Bitfinex/BitfinexSubscriptionManager.cs:150]: Believe `_onUnsubscribeEvent.WaitOne` will always timeout, we are taking the `_locker` here and the path setting `_onUnsubscribeEvent` needs the lock too. Is there a reason to need this `_onUnsubscribeEvent`? If not I'd suggest removing it, the simpler the merrier

File: Brokerages/Tradier/TradierBrokerage.DataQueueHandler.cs (hunk 12 above)
Comment (Martin-Molinero) [reply Brokerages/Tradier/TradierBrokerage.DataQueueHandler.cs:48]: > It's used for new update ticker list and recreate session

But that's all within the same class (even if partial), so it can be made private?

**Review by Martin-Molinero — CHANGES_REQUESTED** [review]

**Review by Martin-Molinero — APPROVED** [review]
