### PR TITLE
Mark delisted securities as not tradable

### LINKED ISSUE #1917: Security.IsTradable is never updated from true to false
#### Expected Behavior
The `Security.IsTradable` property should be set to `false` when a security is delisted or, more generally, whenever we stop receiving price data, such as when removed from data feed (or end of subscription).

#### Actual Behavior
The `Security.IsTradable` property is never updated from `true` to `false`.
This property only has an initial value of `false` for canonical symbols and internal feeds.

#### Potential Solution
n/a

#### Reproducing the Problem
After a security is delisted, the `IsTradable` property still has a value of `true`.

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by mchandschuh**
#### Description

Flip tradable flag when a security is delisted.
Prevent delisted securities from being selected via universe selection and always allow them to be removed.
Add regression test for delisted/tradable flags.
Add Security.IsDelisted to flag.

#### Related Issue

Fixes #1917 

#### Motivation and Context

Tradable flag should be kept up to date and be correct.

#### Requires Documentation Change

No.

#### How Has This Been Tested?

Ran locally and added regression test to cover the changes.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/ect)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/RegressionTests.cs [hunk 1]
```diff
@@ -1084,7 +1107,6 @@ private static TestCaseData[] GetRegressionTestParameters()
                 new AlgorithmStatisticsTestParameters("ScheduledUniverseSelectionModelRegressionAlgorithm", scheduledUniverseSelectionModelRegressionAlgorithmStatistics, Language.CSharp),
                 new AlgorithmStatisticsTestParameters("PairsTradingAlphaModelFrameworkAlgorithm", pairsTradingAlphaModelFrameworkAlgorithmStatistics, Language.CSharp),
                 new AlgorithmStatisticsTestParameters("TimeInForceAlgorithm", timeInForceAlgorithmStatistics, Language.CSharp),
-                new AlgorithmStatisticsTestParameters("SectorExposureRiskFrameworkAlgorithm", sectorExposureRiskFrameworkAlgorithmStatistics, Language.CSharp),
```
Comment (StefanoRaggi) [inline Tests/RegressionTests.cs]: Was this removal intentional?
Also the new `DelistingEventsAlgorithm` should be added here?
