### PR TITLE
Fix TradingEconomicsCalendar.Symbol serialization

### LINKED ISSUE #4231: TradingEconomicsCalendar.Symbol is not being serialized/deserialized
#### Expected Behavior
The `Symbol` property should be serialized/deserialized correctly.

#### Actual Behavior
The `Symbol` property is not serialized.

#### Potential Solution
n/a

#### Reproducing the Problem
This unit test fails on the last assert:
``` C#
        [Test]
        public void SerializeRoundTrip()
        {
            var settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All };

            var time = new DateTime(2020, 3, 20, 14, 0, 0);
            var symbol = Symbol.CreateBase(
                typeof(TradingEconomicsCalendar),
                Symbol.Create(
                    TradingEconomics.Calendar.UnitedStates.ExistingHomeSales,
                    SecurityType.Base,
                    QuantConnect.Market.USA),
                QuantConnect.Market.USA);

            var item = new TradingEconomicsCalendar
            {
                Country = "United States",
                Category = "Existing Home Sales",
                Importance = TradingEconomicsImportance.Medium,
                Event = "existing home sales",
                Actual = 5770000m,
                Previous = 5460000m,
                LastUpdate = time,
                EndTime = time,
                Symbol = symbol,
            };

            var serialized = JsonConvert.SerializeObject(item, settings);
            var deserialized = JsonConvert.DeserializeObject<TradingEconomicsCalendar>(serialized, settings);

            Assert.AreEqual("United States", deserialized.Country);
            Assert.AreEqual("Existing Home Sales", deserialized.Category);
            Assert.AreEqual(TradingEconomicsImportance.Medium, deserialized.Importance);
            Assert.AreEqual(5770000m, deserialized.Actual);
            Assert.AreEqual(5460000m, deserialized.Previous);
            Assert.AreEqual(time, deserialized.LastUpdate);
            Assert.AreEqual(time, deserialized.Time);
            Assert.AreEqual(time, deserialized.EndTime);
            Assert.AreEqual(symbol, deserialized.Symbol);
        }
```

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
- Updates the `TradingEconomicsCalendar` class to enable round-trip serialization

#### Related Issue
Closes #4231 

#### Motivation and Context
- The `Symbol` property is not serialized.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
New unit test.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Data/Custom/TradingEconomicsTests.cs [hunk 1]
```diff
@@ -385,5 +385,46 @@ public void DecimalIsParsedCorrectly(string value, double? expected, bool inPerc
...
             Assert.AreEqual((decimal?)expected, TradingEconomicsCalendar.ParseDecimal(value, inPercentage));
         }
+
+        [Test]
+        public void SerializeRoundTrip()
+        {
+            var settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All };
+
+            var time = new DateTime(2020, 3, 20, 14, 0, 0);
+            var symbol = Symbol.CreateBase(
```
Comment (gsalaz98) [inline Tests/Common/Data/Custom/TradingEconomicsTests.cs]: The call to `Symbol.CreateBase` isn't necessary, since we don't have underlying `Symbol`s for this kind of custom data.

Do this instead: 
```
Symbol.Create(
    TradingEconomics.Calendar.UnitedStates.ExistingHomeSales,
    SecurityType.Base,
    Market.USA,
    baseDataType: typeof(TradingEconomicsCalendar)
);
```

File: Common/Data/Custom/TradingEconomics/TradingEconomicsCalendar.cs [hunk 2]
```diff
@@ -185,10 +185,10 @@ public string EventRaw
         public string Ticker { get; set; }
 
         /// <summary>
-        /// Unique symbol used by Trading Economics
+        /// The LEAN symbol
         /// </summary>
-        [JsonProperty(PropertyName = "Symbol")]
-        public string TESymbol { get; set; }
+        [JsonProperty(PropertyName = "Symbol"), JsonConverter(typeof(TradingEconomicsSymbolJsonConverter))]
+        public new Symbol Symbol { get; set; }
```
Comment (gsalaz98) [inline Common/Data/Custom/TradingEconomics/TradingEconomicsCalendar.cs]: Let's remove the Symbol member hiding. It can potentially be problematic if we upcast to BaseData: https://dotnetfiddle.net/P5gaVC 

The rest of the changes are okay. Let's just make sure to make the `ProcessAPIResponse` method convert the API "Symbol" property to null by doing: `rawData["Symbol"] = null`

File: Common/Data/Custom/TradingEconomics/TradingEconomicsSymbolJsonConverter.cs [hunk 3]
```diff
@@ -0,0 +1,46 @@
+﻿/*
```
Comment (gsalaz98) [inline Common/Data/Custom/TradingEconomics/TradingEconomicsSymbolJsonConverter.cs]: We can delete this altogether with the making of "Symbol" API response null 👍

File: Common/Data/Custom/TradingEconomics/TradingEconomicsCalendar.cs (hunk 2 above)
Comment (StefanoRaggi) [reply Common/Data/Custom/TradingEconomics/TradingEconomicsCalendar.cs]: `((JObject)rawData).Remove("Symbol")` did the trick 😃
