### PR TITLE
Fixes EquityFillModel.StopMarketFill

### LINKED ISSUE #6972: Review Fill Model: Stop Market Fill
#### Expected Behavior
[Stop Market](https://www1.interactivebrokers.com/en/index.php?f=609)

A Stop order is an instruction to submit a buy or sell market order if and when the user-specified stop trigger price is attained or penetrated. A Stop order is not guaranteed a specific execution price and may execute significantly away from its stop price. A Sell Stop order is always placed below the current market price and is typically used to limit a loss or protect a profit on a long stock position. A Buy Stop order is always placed above the current market price. It is typically used to limit a loss or help protect a profit on a short sale.

#### Actual Behavior
`FillModel.StopMarketFill` uses **quote** data to trigger the order.

#### Potential Solution
Remove the `FillModel.GetPrices` logic and write the `StopMarketFill` method to use `Tick.Trade` or `TradeBar` properties. We need to create unit tests that cover all scenarios and security types. For instance, Forex and CFD don't have trade data.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
These unit tests cover new scenarios:
- Cannot trigger on quote data (QuoteBar or TickRype.Quote);
- Adds missing test for tick data (TickType.Trade)
- Unfavorable gap (see #4545)
 
Fixes EquityFillModel StopMarketFill
- Use the entire tick history to find the trigger price
- Fill price is the stop price, unless there is an unfavorable gap.

Update Regression Tests
- All regression tests keep the total trades. The difference are due to the time that the stop market orders are triggered and the prices that are filled. The `StopLossOnOrderEventRegressionAlgorithm` and the `UpdateOrderRegressionAlgorithm` observe the unfavorable gap case.

Capture

#### Related Issue
Closes #6972 and #4545

#### Motivation and Context
Improve modeling.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Old and new unit tests.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Orders/Fills/EquityFillModel.cs [hunk 1]
```diff
@@ -183,58 +184,113 @@ public override OrderEvent MarketFill(Security asset, MarketOrder order)
...
+                {
+                    tradeOpen = tradeBar.Open;
+                    tradeHigh = tradeBar.High;
+                    tradeLow = tradeBar.Low;
+                    endTimeUtc = tradeBar.EndTime.ConvertToUtc(asset.Exchange.TimeZone);
+                }
+            }
+
+            // Do not fill on stale data
+            if (endTimeUtc <= order.Time) return fill;
```
Comment (Martin-Molinero) [inline Common/Orders/Fills/EquityFillModel.cs:253]: I think we can eventually move all this logic above to a shared method given it's being reused, can be in it's own PR with no behavior change 👍

File: Common/Messages/Messages.Orders.Fills.cs [hunk 2]
```diff
@@ -132,6 +132,13 @@ public static string FilledWithTradeBarData(Securities.Security security, TradeB
                 return Invariant($@"Warning: No quote information available at {tradeBar.EndTime.ToStringInvariant()} {
                     security.Exchange.TimeZone}, order filled using TradeBar data");
             }
+
+            [MethodImpl(MethodImplOptions.AggressiveInlining)]
+            public static string FilledWithOpenDueToUnfavorableGap(Securities.Security security, decimal open, DateTime endTimeUtc)
+            {
+                var endTime = endTimeUtc.ConvertFromUtc(security.Exchange.TimeZone).ToStringInvariant();
+                return Invariant($@"Warning: Due to an unfavorable gap at {endTime} {security.Exchange.TimeZone}, order filled using the open price ({open})");
```
Comment (jaredbroad) [inline Common/Messages/Messages.Orders.Fills.cs:140]: Please remove "Warning:"

File: Common/Orders/Fills/EquityFillModel.cs [hunk 3]
```diff
@@ -183,58 +184,113 @@ public override OrderEvent MarketFill(Security asset, MarketOrder order)
...
 
-            // do not fill on stale data
-            if (pricesEndTime <= order.Time) return fill;
+            var subscribedTypes = GetSubscribedTypes(asset);
 
-            //Calculate the model slippage: e.g. 0.01c
-            var slip = asset.SlippageModel.GetSlippageApproximation(asset, order);
+            if (subscribedTypes.Contains(typeof(Tick)))
+            {
+                var trades = asset.Cache.GetAll<Tick>().Where(x => x.TickType == TickType.Trade && x.Price > 0);
```
Comment (jaredbroad) [inline Common/Orders/Fills/EquityFillModel.cs:229]: When is price 0?

File: Common/Orders/Fills/EquityFillModel.cs [hunk 4]
```diff
@@ -183,58 +184,113 @@ public override OrderEvent MarketFill(Security asset, MarketOrder order)
...
-            // make sure the exchange is open/normal market hours before filling
+            // Make sure the exchange is open/normal market hours before filling
             if (!IsExchangeOpen(asset, false)) return fill;
 
-            //Get the range of prices in the last bar:
-            var prices = GetPricesCheckingPythonWrapper(asset, order.Direction);
-            var pricesEndTime = prices.EndTime.ConvertToUtc(asset.Exchange.TimeZone);
+            // Get the range of prices in the last bar:
+            var tradeOpen = 0m;
+            var tradeHigh = 0m;
```
Comment (jaredbroad) [inline Common/Orders/Fills/EquityFillModel.cs:221]: Normally this is tradeLow = Decimal.MaxValue, tradeHigh = Decimal.MinValue for the initial state.

**Review by jaredbroad — CHANGES_REQUESTED** [review]
Minor comments

File: Common/Orders/Fills/EquityFillModel.cs [hunk 5]
```diff
@@ -218,21 +218,21 @@ public override OrderEvent StopMarketFill(Security asset, StopMarketOrder order)
...
-            var tradeLow = 0m;
+            var tradeHigh = decimal.MinValue;
+            var tradeLow = decimal.MaxValue;
             var endTimeUtc = DateTime.MinValue;
 
             var subscribedTypes = GetSubscribedTypes(asset);
 
             if (subscribedTypes.Contains(typeof(Tick)))
             {
-                var trades = asset.Cache.GetAll<Tick>().Where(x => x.TickType == TickType.Trade && x.Price > 0);
```
[the remark this answers is not in the document]
Comment (AlexCatarino) [reply Common/Orders/Fills/EquityFillModel.cs]: I propose we remove `&& x.Price > 0` in the PR to address this request:
https://github.com/QuantConnect/Lean/pull/7042#discussion_r1127852198

**Review by jaredbroad — APPROVED** [review]
