### PR TITLE
Expand Filtering of Contracts by type to Futures

### LINKED ISSUE #4725: Exclude Weekly Futures By Default
#### Expected Behavior
Like options, futures' contracts should not include weekly contracts that would be requested by `IncludeWeeklys()` method.

#### Actual Behavior
Weeklies are included by default and there no API method to remove them.

#### Potential Solution
Implement `IncludeWeeklys()`.

#### Reproducing the Problem
In live mode, we got `VX30U20` (for ref., `VX23U20` is the standard contract):
> 2020-09-14T13:40:50.2704570Z TRACE:: Brokerage.OnMessage(): Information - Code: 10197 - No market data during competing live session. Origin: Subscribe: VX30U20 (FUT VIX USD CFE)

which is a weekly contract.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

- Support filtering Future contracts by Standard or Weeklys
- Combine core filtering logic of Options and Futures contracts into new base class `ContractSecurityFilterUniverse<T>` to reduce code duplication
- Addition of tests to verify correct behaviour of filters

#### Related Issue

Closes #4725 

#### Motivation and Context

Just as with Options we expect Futures to only include standard contracts by default. This PR implements the functionality to filter out these contracts with the same interface as OptionFilterUniverse, (i.e. .IncludeWeeklys(), WeeklysOnly). Now by default (just like Options) Futures contracts will not include weeklys, you must use the filter functions above to allow them through the filter.

Also upon inspection it was clear that both filter setups (OptionsFilterUniverse & FutureFilterUniverse) were basically exactly the same except a couple of unique filters. So instead of expanding the duplication of code I combined their core logic into a shared base class and then left the unique functions for implementation in their respective classes. 

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

- Test built to cover case of filtering out weeklys, standards, and neither 
- Test for symbols without an expiry function (flags as standard by default**) 
- Ran Live Paper Trading through IB to observe the Weekly contracts for "VX" being filtered out as described in #4725 
- Will test in the cloud

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Securities/ContractSecurityFilterUniverse.cs [hunk 1]
```diff
@@ -0,0 +1,295 @@
...
+        {
+            get
+            {
+                // underlying value changes over time, so accessing it makes universe dynamic
+                _isDynamic = true;
+                return _underlying;
+            }
+        }
+
+        protected BaseData _underlying;
```
Comment (Martin-Molinero) [inline Common/Securities/ContractSecurityFilterUniverse.cs:64]: nit - code style protected should be `Underlying` and have xml docs
We should place privates first, later protected and finally public properties/fields

File: Common/Securities/ContractSecurityFilterUniverse.cs [hunk 2]
```diff
@@ -0,0 +1,295 @@
...
+
+        /// <summary>
+        /// True if the universe is dynamic and filter needs to be reapplied
+        /// </summary>
+        public bool IsDynamic => _isDynamic;
+
+        //TODO: Naming Conventions
+        internal bool _isDynamic;
+        protected Type _type = Type.Standard;
```
Comment (Martin-Molinero) [inline Common/Securities/ContractSecurityFilterUniverse.cs:73]: Let's address the `TODO:` 😛 . Suggest we also rename `_type`. We might add a `remarks` to the `internal` type fields noting they are internal so that the extension methods can access them

File: Common/Securities/Future/FutureFilterUniverse.cs [hunk 3]
```diff
@@ -19,40 +19,16 @@
...
-            {
-                return _isDynamic;
-            }
-        }
-
-        internal bool _isDynamic;
-
         /// <summary>
         /// Constructs FutureFilterUniverse
         /// </summary>
```
Comment (Martin-Molinero) [inline Common/Securities/Future/FutureFilterUniverse.cs:34]: I think it would be nice if this constructor should be calling the base one and not setting those fields here?

File: Common/Securities/Future/FutureFilterUniverse.cs [hunk 4]
```diff
@@ -154,54 +58,6 @@ public FutureFilterUniverse ExpirationCycle(int[] months)
             var monthHashSet = months.ToHashSet();
             return this.Where(x => monthHashSet.Contains(x.ID.Date.Month));
```
Comment (Martin-Molinero) [inline Common/Securities/Future/FutureFilterUniverse.cs:59]: nit - Let's please add the missing documentation for this method

File: Common/Securities/ContractSecurityFilterUniverse.cs [hunk 5]
```diff
@@ -0,0 +1,295 @@
...
+            _underlying = underlying;
+            _type = Type.Standard;
+            _isDynamic = false;
+        }
+
+        /// <summary>
+        /// Includes universe of non-standard weeklys contracts (if any) into selection
+        /// </summary>
+        /// <returns></returns>
+        public T IncludeWeeklys()
```
Comment (Martin-Molinero) [inline Common/Securities/ContractSecurityFilterUniverse.cs:97]: Let's rereview the `xml` documentation of these classes and make sure it's all covered 👍

File: Tests/Common/Securities/FutureFilterTests.cs [hunk 6]
```diff
@@ -61,6 +61,93 @@ public void FiltersExpiryRange()
             Assert.AreEqual(symbols[7], filtered[4]);
         }
 
+        [Test]
+        public void FiltersOutWeeklys()
```
Comment (Martin-Molinero) [inline Tests/Common/Securities/FutureFilterTests.cs:65]: Sweet tests! 💯 
nit - maybe we should add `ByDefault` to the test name

File: Common/Securities/Future/FutureSymbol.cs [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+    {
+        /// <summary>
+        /// Returns true if the option is a standard contract that expires 3rd Friday of the month
+        /// </summary>
+        /// <param name="symbol">Future symbol</param>
+        /// <returns></returns>
+        public static bool IsStandard(Symbol symbol)
+        {
+            var date = symbol.ID.Date;
+            var symbolToCheck = symbol.HasUnderlying ? symbol.Underlying : symbol;
```
Comment (Martin-Molinero) [inline Common/Securities/Future/FutureSymbol.cs:34]: Wonder in which case is this required `symbol.HasUnderlying ? symbol.Underlying : symbol` wouldn't really expect there to be an underlying symbol for the future?

File: Common/Securities/Future/FutureSymbol.cs [hunk 8]
```diff
@@ -0,0 +1,68 @@
...
+                var standardDate = expiryFunction(date);
+
+                // If the date on this symbol and the nearest standard date are equal then it is a standard contract
+                if (date == standardDate)
+                {
+                    return true;
+                }
+
+                // Date is non-standard, return false
+                return false;
```
Comment (Martin-Molinero) [inline Common/Securities/Future/FutureSymbol.cs:49]: nit - could directly `return date == standardDate`
nit - maybe we could rename `date` to something like `contractExpirationDate`?

File: Common/Securities/Future/FutureSymbol.cs [hunk 9]
```diff
@@ -0,0 +1,68 @@
...
+            }
+            catch
+            {
+                Log.Error($"Could not find standard date for {symbolToCheck}, will be classified as weekly (non-standard)");
+                return false;
```
Comment (Martin-Molinero) [inline Common/Securities/Future/FutureSymbol.cs:54]: Suggest by default we return true here, else since by default we filter weeklys we would filter out all contracts?

**Review by Martin-Molinero — COMMENTED** [review]
Nice work 👍 great consolidation
Leaving some nit/style comments

File: Common/Securities/Future/FutureSymbol.cs (hunk 9 above)
Comment (C-SELLERS) [reply Common/Securities/Future/FutureSymbol.cs:54]: Definitely, I wasn't to sure how we wanted that to operate but it makes sense to keep the contract in if we can't verify its non-standard

>** Do we want symbols that are found to not have an expiry function to be flagged as non-standard???

File: Common/Securities/ContractSecurityFilterUniverse.cs [hunk 10]
```diff
@@ -0,0 +1,340 @@
...
+                }
+            }).ToList();
+
+            return (T) this;
+        }
+
+        /// <summary>
+        /// Refreshes this filter universe
+        /// </summary>
+        /// <param name="allSymbols">All the options contract symbols</param>
```
Comment (C-SELLERS) [inline Common/Securities/ContractSecurityFilterUniverse.cs:158]: Fix documentation

**Review by C-SELLERS — COMMENTED** [review]
One thing I missed and I think we are good to go

File: Common/Securities/Future/FutureSymbol.cs [hunk 11]
```diff
@@ -0,0 +1,61 @@
...
+            var contractExpirationDate = symbol.ID.Date;
+
+            try
+            {
+                // Use our FutureExpiryFunctions to determine standard contracts dates.
+                var expiryFunction = FuturesExpiryFunctions.FuturesExpiryFunction(symbol);
+                var standardExpirationDate = expiryFunction(contractExpirationDate);
+
+                // Return true if the dates match
+                return contractExpirationDate == standardExpirationDate;
```
Comment (Martin-Molinero) [inline Common/Securities/Future/FutureSymbol.cs:42]: Suggest we compare the `Date` component here, `expiryFunction` might return the hour component, but for example I believe IB won't (see https://github.com/QuantConnect/Lean/blob/master/Brokerages/InteractiveBrokers/InteractiveBrokersBrokerage.cs#L2229). Let's give this case a live test too to be on the safe side👍

**Review by Martin-Molinero — COMMENTED** [review]
Sweet 👍 just one last minor comment

File: Common/Securities/Future/FutureSymbol.cs (hunk 11 above)
Comment (C-SELLERS) [reply Common/Securities/Future/FutureSymbol.cs:42]: Good idea! I did run it through a live test with IB and saw the weeklys get filtered out so can confirm it works and there was no issue with the full DateTime comparison. But using the date component is probably a safer bet!

Comment (C-SELLERS) [reply Common/Securities/Future/FutureSymbol.cs]: Made the change, testing IB again to confirm behaviour!

Comment (C-SELLERS) [reply Common/Securities/Future/FutureSymbol.cs]: You were correct! The time components of the DateTimes did not match up so it is for the best that we use the `Date` component.

**Review by Martin-Molinero — APPROVED** [review]
🚀

File: Tests/Engine/DataFeeds/LiveTradingDataFeedTests.cs [hunk 12]
```diff
@@ -2023,7 +2023,7 @@ public void HandlesFutureAndOptionChainUniverse(SecurityType securityType)
             else if (securityType == SecurityType.Future)
             {
                 var future = algorithm.AddFuture(Futures.Indices.SP500EMini, Resolution.Minute);
-                future.SetFilter(x => x);
+                future.SetFilter(x => x.IncludeWeeklys());
```
Comment (jaredbroad) [inline Tests/Engine/DataFeeds/LiveTradingDataFeedTests.cs:2026]: Can you please show the impact on the total count of contracts from this change?

**Review by jaredbroad — APPROVED** [review]

File: Tests/Engine/DataFeeds/LiveTradingDataFeedTests.cs (hunk 12 above)
Comment (C-SELLERS) [reply Tests/Engine/DataFeeds/LiveTradingDataFeedTests.cs:2026]: Total count of contracts is the same! 2 in 2 out!

The reason this was adjusted is the contract dates for ES we created are as follows:
12/19/19
3/19/20

But the standard contracts for those months are:
12/20/19
3/20/20

See [here](https://www.barchart.com/futures/quotes/ESZ20/historical-prices) for verification. 

Without the IncludeWeeklys() function on the filter those two dates get filtered out!
