### PR TITLE
Accounting for the position quantity in margin requirements

### LINKED ISSUE #7153: Cannot liquidate part of an option strategy naked short position
#### Expected Behavior

When holding a naked short position for an option strategy, the algorithm is able to liquidate part of that position.

#### Actual Behavior

When holding a naked short position for an option strategy (say `group quantity=-5`), the algorithm is not able to place a reverting order to liquidate part of the position (`quantity < |strategyQuantity|`. E.g. `quantity = 4` in this case).

#### Potential Solution

A potential hint: look into the `PositionGroupBuyingPowerModel`, specifically into how the available and delta buying power are calculated in [`HasSufficientBuyingPowerForOrder`](https://github.com/QuantConnect/Lean/blob/4d3211957631e085fe299c8452c794c180a4f165/Common/Securities/Positions/PositionGroupBuyingPowerModel.cs#L142), which is used by the transaction handler to check where an order can be submitted and filled. The condition `deltaBuyingPower <= availableBuyingPower` is not met for this cases, resulting in unsufficient buying power.

#### Reproducing the Problem

Run this algorithm:

```python
import itertools

class SleepyTanMule(QCAlgorithm):

    def Initialize(self):        
        self.SetStartDate(2015, 12, 24)
        self.SetEndDate(2015, 12, 24)
        self.SetCash(150000)
        
        equity = self.AddEquity("GOOG", leverage=4)
        option = self.AddOption(equity.Symbol)
        self._optionSymbol = option.Symbol

        option.SetFilter(lambda u: u.Strikes(-2, +2).Expiration(0, 180))

    def OnData(self, data):
        if not self.Portfolio.Invested:
            for chain in data.OptionChains.Values:
                callContracts = [contract for contract in chain if contract.Right == OptionRight.Call]
                callContracts = [(key, list(group)) for key, group in itertools.groupby(callContracts, key=lambda x: x.Expiry)]
                callContracts.sort(key=lambda x: x[0])
                callContracts = callContracts[0][1]
                callContracts.sort(key=lambda x: x.Strike)

                if len(callContracts) < 3:
                    break

                expiry = callContracts[0].Expiry
                lowerStrike = callContracts[0].Strike
                middleStrike = callContracts[1].Strike
                higherStrike = callContracts[2].Strike

                self._optionStrategy = OptionStrategies.Straddle(self._optionSymbol, higherStrike, expiry)

                self._strategyQuantity = -5
                self.Order(self._optionStrategy, self._strategyQuantity)  
        else:
            self.Order(self._optionStrategy, abs(self._strategyQuantity) - 1)
```

Se the orders and logs:

image

#### System Information

Local environment in Windows 11 and QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

When shorting options and options strategies with no initial holdings, the margin buying power model allowed us to short too many contracts, making us go avobe the available margin. This is because it was using the existing security holdings to calculate the margin requirements for any existing or potential position.

This fixes this by pssing the actual quantity down to the margin requirement calculation method.

- Quantity is reduced in initial orders when there are no holdings, because the models where allowing highier quantities than actually margin was available for. For some algorithms, the order quantities were reduced to match this, as well as cash was increased for some others for them to be able to hold the positions.
- Note about `Algorithm.CSharp/OptionChainConsistencyRegressionAlgorithm.cs`: the orders list hash changed. The reason is the following: this algorithm runs for a single day, placing a market order and then liquidating it on market close. Right after that, the condition `!Portfolio.Invested` is true again, so the orders are placed again but never filled because the algorithm is completed. The last MOC order is invalidated with this changes because of insufficient buying power, hence the hash change.

##### Shorting options outside of margin in IB for validation

image
image

#### Related Issue

Closes #7153 

#### How Has This Been Tested?

Unit tests, regression algorithm.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Common/Securities/OptionMarginBuyingPowerModelTests.cs [hunk 1]
```diff
@@ -412,31 +412,26 @@ public void NonAccountCurrency_GetBuyingPower(decimal nonAccountCurrencyCash)
...
+        [TestCase(-2, 838, 0.40)] // Short to Long (-2 + 838 = 836)
+        [TestCase(2, 834, 0.40)] // Long To Longer (2 + 834 = 836)
 
         // ~0.04% Target (~400). This is below the needed margin for one unit. We end up at 0 holdings for all cases.
-        [TestCase(-31, 31, 0.0004)] // Short to Long (-31 + 31 = 0)
         [TestCase(0, 0, 0.0004)] // Open Long (0 + 0 = 0)
-        [TestCase(31, -31, 0.0004)] // Long To Longer (31 + -31 = 0)
+        [TestCase(-2, 2, 0.0004)] // Short to Long (-2 + 2 = 0)
+        [TestCase(2, -2, 0.0004)] // Long To Longer (2 + -2 = 0)
         public void CallOTM_MarginRequirement(int startingHoldings, int expectedOrderSize, decimal targetPercentage)
```
Comment (Martin-Molinero) [inline Tests/Common/Securities/OptionMarginBuyingPowerModelTests.cs:435]: Nice! ✨

File: Tests/Common/Securities/OptionStrategyPositionGroupBuyingPowerModelTests.cs [hunk 2]
```diff
@@ -0,0 +1,224 @@
...
+            );
+            _putOption.Underlying = _equity;
+
+            _portfolio.Securities.Add(_equity.Symbol, _equity);
+            _portfolio.Securities.Add(_callOption.Symbol, _callOption);
+            _portfolio.Securities.Add(_putOption.Symbol, _putOption);
+        }
+
+        [Test]
+        public void TestHasSufficientBuyingPower([Values] bool withInitialHoldings)
```
Comment (Martin-Molinero) [inline Tests/Common/Securities/OptionStrategyPositionGroupBuyingPowerModelTests.cs:101]: cool!

**Review by Martin-Molinero — APPROVED** [review]
