### PR TITLE
Replace WebSocketSharp with System.Net.WebSockets in GDAXBrokerage

### LINKED ISSUE #4324: Overflow exception and Websocket reconnect failing with Coinbase Pro
#### Expected Behavior
Websocket connection to Coinbase Pro stays reasonably stable.

#### Actual Behavior
Recently the websocket connection became much more unstable as compared to the average behaviour over the past few months.

If a websocket connection is disrupted, reconnection does not happen and LEAN exits within about 15 min or so.

In the past, reconnection happened normally after 1-2 attemps. Currently, it fails repeatedly. A rare case of reconnection happening before LEAN exits has the following log:

```
20200421 16:11:25.786 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 60, Sample: 61, App: 287, CurrentTimeStepElapsed: 00:00.000
20200421 16:12:26.422 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 59, Sample: 57, App: 277, CurrentTimeStepElapsed: 00:00.000
20200421 16:13:27.128 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 60, Sample: 65, App: 284, CurrentTimeStepElapsed: 00:00.000

20200421 16:13:58.800 Trace:: WebSocket.<startReceiving>b__170_2(): System.StackOverflowException: The requested operation caused a stack overflow.
  at Mono.Net.Security.AsyncProtocolRequest.InnerRead (System.Threading.CancellationToken cancellationToken) <0x41513790 + 0x00007> in <a360a10e096b4659a9142a244dda
ea3e>:0
  at Mono.Net.Security.AsyncProtocolRequest+<ProcessOperation>d__24.MoveNext () [0x0002f] in <a360a10e096b4659a9142a244ddaea3e>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <b0e1ad7573a24fd5a9f2af9595e677e7>:0
  at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x0002b] in <a360a10e096b4659a9142a244ddaea3e>:
0
  at Mono.Net.Security.AsyncProtocolRequest+<StartOperation>d__23.MoveNext () [0x0002a] in <a360a10e096b4659a9142a244ddaea3e>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <b0e1ad7573a24fd5a9f2af9595e6
77e7>:0
  at Mono.Net.Security.AsyncProtocolRequest.StartOperation (System.Threading.CancellationToken cancellationToken) [0x0002b] in <a360a10e096b4659a9142a244ddaea3e>:0
  at Mono.Net.Security.MobileAuthenticatedStream+<StartOperation>d__58.MoveNext () [0x000b4] in <a360a10e096b4659a9142a244ddaea3e>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <b0e1ad7573a24fd5a9f2af9595e6
77e7>:0
  at Mono.Net.Security.MobileAuthenticatedStream.StartOperation (Mono.Net.Security.MobileAuthenticatedStream+OperationType type, Mono.Net.Security.AsyncProtocolRequ
est asyncRequest, System.Threading.CancellationToken cancellationToken) [0x0003b] in <a360a10e096b4659a9142a244ddaea3e>:0
  at Mono.Net.Security.MobileAuthenticatedStream.BeginRead (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.AsyncCallback asyncCallback, Syste
m.Object asyncState) [0x00013] in <a360a10e096b4659a9142a244ddaea3e>:0
  at System.Net.Security.SslStream.BeginRead (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.AsyncCallback asyncCallback, System.Object async
State) [0x00006] in <a360a10e096b4659a9142a244ddaea3e>:0
  at WebSocketSharp.Ext.ReadBytesAsync (System.IO.Stream stream, System.Int32 length, System.Action`1[T] completed, System.Action`1[T] error) [0x0005c] in <1fc1e12f
21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame.readHeaderAsync (System.IO.Stream stream, System.Action`1[T] completed, System.Action`1[T] error) [0x0000e] in <1fc1e12f21eb4681a
a69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame.ReadFrameAsync (System.IO.Stream stream, System.Boolean unmask, System.Action`1[T] completed, System.Action`1[T] error) [0x00023]
 in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocket+<>c__DisplayClass170_0.<startReceiving>b__0 () [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocket+<>c__DisplayClass170_0.<startReceiving>b__1 (WebSocketSharp.WebSocketFrame frame) [0x00044] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__3 (WebSocketSharp.WebSocketFrame frame3) [0x00012] in <1fc1e12f21eb4681aa69c484f58d0121>
:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass77_0.<readPayloadDataAsync>b__0 (System.Byte[] bytes) [0x00035] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.Ext+<>c__DisplayClass54_0.<ReadBytesAsync>b__0 (System.IAsyncResult ar) [0x0009e] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at System.Threading.Tasks.TaskToApm.Begin (System.Threading.Tasks.Task task, System.AsyncCallback callback, System.Object state) [0x00014] in <b0e1ad7573a24fd5a9f
2af9595e677e7>:0
  at Mono.Net.Security.MobileAuthenticatedStream.BeginRead (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.AsyncCallback asyncCallback, Syste
m.Object asyncState) [0x00018] in <a360a10e096b4659a9142a244ddaea3e>:0
  at System.Net.Security.SslStream.BeginRead (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.AsyncCallback asyncCallback, System.Object async
State) [0x00006] in <a360a10e096b4659a9142a244ddaea3e>:0
  at WebSocketSharp.Ext.ReadBytesAsync (System.IO.Stream stream, System.Int32 length, System.Action`1[T] completed, System.Action`1[T] error) [0x0005c] in <1fc1e12f
21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame.readPayloadDataAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, System.Action`1
[T] error) [0x00097] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__2 (WebSocketSharp.WebSocketFrame frame2) [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>
:0
  at WebSocketSharp.WebSocketFrame.readMaskingKeyAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, System.Action`1[
T] error) [0x0004a] in <1fc1e12f21eb4681aa69c484f58d0121>:0




  at Mono.Net.Security.MobileAuthenticatedStream.BeginRead (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.AsyncCallback asyncCallback, Syste
m.Object asyncState) [0x00018] in <a360a10e096b4659a9142a244ddaea3e>:0
  at System.Net.Security.SslStream.BeginRead (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.AsyncCallback asyncCallback, System.Object async
State) [0x00006] in <a360a10e096b4659a9142a244ddaea3e>:0
  at WebSocketSharp.Ext.ReadBytesAsync (System.IO.Stream stream, System.Int32 length, System.Action`1[T] completed, System.Action`1[T] error) [0x0005c] in <1fc1e12f
21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame.readPayloadDataAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, System.Action`1
[T] error) [0x00097] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__2 (WebSocketSharp.WebSocketFrame frame2) [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>
:0
  at WebSocketSharp.WebSocketFrame.readMaskingKeyAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, System.Action`1[
T] error) [0x0004a] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__1 (WebSocketSharp.WebSocketFrame frame1) [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>
:0
  at WebSocketSharp.WebSocketFrame.readExtendedPayloadLengthAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, Syste
m.Action`1[T] error) [0x00044] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__0 (WebSocketSharp.WebSocketFrame frame) [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>:
0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass73_0.<readHeaderAsync>b__0 (System.Byte[] bytes) [0x0000c] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.Ext+<>c__DisplayClass54_0.<ReadBytesAsync>b__0 (System.IAsyncResult ar) [0x0009e] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at System.Threading.Tasks.TaskToApm.Begin (System.Threading.Tasks.Task task, System.AsyncCallback callback, System.Object state) [0x00014] in <b0e1ad7573a24fd5a9f
2af9595e677e7>:0
  at Mono.Net.Security.MobileAuthenticatedStream.BeginRead (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.AsyncCallback asyncCallback, Syste
m.Object asyncState) [0x00018] in <a360a10e096b4659a9142a244ddaea3e>:0
  at System.Net.Security.SslStream.BeginRead (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.AsyncCallback asyncCallback, System.Object async
State) [0x00006] in <a360a10e096b4659a9142a244ddaea3e>:0
  at WebSocketSharp.Ext.ReadBytesAsync (System.IO.Stream stream, System.Int32 length, System.Action`1[T] completed, System.Action`1[T] error) [0x0005c] in <1fc1e12f
21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame.readHeaderAsync (System.IO.Stream stream, System.Action`1[T] completed, System.Action`1[T] error) [0x0000e] in <1fc1e12f21eb4681a
a69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame.ReadFrameAsync (System.IO.Stream stream, System.Boolean unmask, System.Action`1[T] completed, System.Action`1[T] error) [0x00023]
 in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocket+<>c__DisplayClass170_0.<startReceiving>b__0 () [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocket+<>c__DisplayClass170_0.<startReceiving>b__1 (WebSocketSharp.WebSocketFrame frame) [0x00044] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__3 (WebSocketSharp.WebSocketFrame frame3) [0x00012] in <1fc1e12f21eb4681aa69c484f58d0121>
:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass77_0.<readPayloadDataAsync>b__0 (System.Byte[] bytes) [0x00035] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.Ext+<>c__DisplayClass54_0.<ReadBytesAsync>b__0 (System.IAsyncResult ar) [0x0009e] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at System.Threading.Tasks.TaskToApm.Begin (System.Threading.Tasks.Task task, System.AsyncCallback callback, System.Object state) [0x00014] in <b0e1ad7573a24fd5a9f
2af9595e677e7>:0
  at Mono.Net.Security.MobileAuthenticatedStream.BeginRead (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.AsyncCallback asyncCallback, Syste
m.Object asyncState) [0x00018] in <a360a10e096b4659a9142a244ddaea3e>:0
  at System.Net.Security.SslStream.BeginRead (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.AsyncCallback asyncCallback, System.Object async
State) [0x00006] in <a360a10e096b4659a9142a244ddaea3e>:0
  at WebSocketSharp.Ext.ReadBytesAsync (System.IO.Stream stream, System.Int32 length, System.Action`1[T] completed, System.Action`1[T] error) [0x0005c] in <1fc1e12f
21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame.readPayloadDataAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, System.Action`1
[T] error) [0x00097] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__2 (WebSocketSharp.WebSocketFrame frame2) [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>
:0
  at WebSocketSharp.WebSocketFrame.readMaskingKeyAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, System.Action`1[
T] error) [0x0004a] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__1 (WebSocketSharp.WebSocketFrame frame1) [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>
:0
  at WebSocketSharp.WebSocketFrame.readExtendedPayloadLengthAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, Syste
m.Action`1[T] error) [0x00044] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__0 (WebSocketSharp.WebSocketFrame frame) [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>:
0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass73_0.<readHeaderAsync>b__0 (System.Byte[] bytes) [0x0000c] in <1fc1e12f21eb4681aa69c484f58d0121>:0

                                                                                                                                                        
(repeats over several 100s kB of log)


  at WebSocketSharp.Ext.ReadBytesAsync (System.IO.Stream stream, System.Int32 length, System.Action`1[T] completed, System.Action`1[T] error) [0x0005c] in <1fc1e12f
21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame.readPayloadDataAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, System.Action`1
[T] error) [0x00097] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__2 (WebSocketSharp.WebSocketFrame frame2) [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>
:0
  at WebSocketSharp.WebSocketFrame.readMaskingKeyAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, System.Action`1[
T] error) [0x0004a] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__1 (WebSocketSharp.WebSocketFrame frame1) [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>
:0
  at WebSocketSharp.WebSocketFrame.readExtendedPayloadLengthAsync (System.IO.Stream stream, WebSocketSharp.WebSocketFrame frame, System.Action`1[T] completed, Syste
m.Action`1[T] error) [0x00044] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass82_0.<ReadFrameAsync>b__0 (WebSocketSharp.WebSocketFrame frame) [0x00000] in <1fc1e12f21eb4681aa69c484f58d0121>:
0
  at WebSocketSharp.WebSocketFrame+<>c__DisplayClass73_0.<readHeaderAsync>b__0 (System.Byte[] bytes) [0x0000c] in <1fc1e12f21eb4681aa69c484f58d0121>:0
  at WebSocketSharp.Ext+<>c__DisplayClass54_0.<ReadBytesAsync>b__0 (System.IAsyncResult ar) [0x0009e] in <1fc1e12f21eb4681aa69c484f58d0121>:0
20200421 16:13:58.815 Trace:: WebSocketWrapper.OnClose(): Connection closed (IsOpen:False, ReadyState:Closed, Code:1006, Reason:An exception has occurred while rece
iving., WasClean:False): wss://ws-feed.pro.coinbase.com
20200421 16:15:34.604 Trace:: Brokerage.OnMessage(): Disconnect - Code: Disconnect - Connection with server lost. This could be because of internet connectivity iss
ues.
20200421 16:15:34.604 Trace:: DefaultBrokerageMessageHandler.Handle(): Disconnected.
20200421 16:15:34.605 Trace:: DefaultBrokerageMessageHandler.Handle(): Disconnect when exchanges are open, trying to reconnect for 15 minutes.
20200421 16:15:44.605 Trace:: BaseWebsocketsBrokerage(): Reconnecting... IsConnected: False
20200421 16:15:44.796 Trace:: WebSocketWrapper.OnOpen(): Connection opened (IsOpen:True, ReadyState:Open): wss://ws-feed.pro.coinbase.com
20200421 16:15:44.797 Trace:: GDAXBrokerage.Subscribe: Sent subscribe.
20200421 16:15:55.436 Trace:: Brokerage.OnMessage(): Reconnect - Code: Reconnect - Connection with server restored.
20200421 16:15:55.436 Trace:: DefaultBrokerageMessageHandler.Handle(): Reconnected.
20200421 16:16:28.584 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 59, Sample: 59, App: 278, CurrentTimeStepElapsed: 00:00.000
20200421 16:17:29.394 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 59, Sample: 60, App: 279, CurrentTimeStepElapsed: 00:00.000
```

#### Potential Solution
The issue seems to have started after a recent commit from this PR:
https://github.com/QuantConnect/Lean/pull/4317

Perhaps check the reconnection attempt logic and what causes the overflow?

#### Reproducing the Problem

Keep LEAN connected to GDAX live and subscribe to a trading pair with 1 min resolution. Observe what happens after the websocket connection is disrupted.

#### System Information
Lean running in a Docker container following DockerLeanFoundation.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
- Added new `WebSocketClientWrapper` class based on `System.Net.WebSockets.ClientWebSocket`
- Replaced usage of `WebSocketWrapper` with `WebSocketClientWrapper` in `GDAXBrokerage`

#### Related Issue
Closes #4324 

#### Motivation and Context
- Stability of brokerage implementation

#### Requires Documentation Change
No.

#### How Has This Been Tested?
- Local testing in both Windows and Linux/Docker + cloud testing

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Brokerages/WebSocketClientWrapper.cs [hunk 1]
```diff
@@ -0,0 +1,265 @@
...
+        }
+
+        /// <summary>
+        /// Wraps Connect method
+        /// </summary>
+        public void Connect()
+        {
+            lock (_locker)
+            {
+                if (!IsOpen)
```
Comment (Martin-Molinero) [inline Brokerages/WebSocketClientWrapper.cs:76]: I think we should be checking if `_taskConnect` is already running or maybe `_cts` is null or `canceled`, so two consecutive calls to `Connect()` don't start two clients and tasks, because there can be a time gap between calling `Connect()` and `IsOpen` being true

File: Brokerages/WebSocketClientWrapper.cs [hunk 2]
```diff
@@ -0,0 +1,265 @@
...
+        /// </summary>
+        public void Close()
+        {
+            try
+            {
+                _client?.CloseOutputAsync(WebSocketCloseStatus.NormalClosure, "", _cts.Token).SynchronouslyAwaitTask();
+
+                _cts?.Cancel();
+
+                _taskConnect?.Wait();
```
Comment (Martin-Molinero) [inline Brokerages/WebSocketClientWrapper.cs:119]: Maybe wait with a timeout just in case?

File: Brokerages/WebSocketClientWrapper.cs [hunk 3]
```diff
@@ -0,0 +1,265 @@
...
+
+                    while ((_client.State == WebSocketState.Open || _client.State == WebSocketState.CloseSent) &&
+                        !connectionCts.IsCancellationRequested)
+                    {
+                        var messageData = await ReceiveMessage(_client, connectionCts.Token);
+
+                        if (messageData.MessageType == WebSocketMessageType.Close)
+                        {
+                            Log.Trace("WebSocketClientWrapper.HandleConnection(): WebSocketMessageType.Close");
+                            return;
```
Comment (Martin-Molinero) [inline Brokerages/WebSocketClientWrapper.cs:212]: Should we call `OnClose()` here? The wrapping task will try to reconnect, that's expected?

Comment (StefanoRaggi) [reply Brokerages/WebSocketClientWrapper.cs:204]: > Should we call `OnClose()` here?

This message should be received by the client as a response to the Close request on L105,
OnClose should be called after the close handshake is completed on L120

> The wrapping task will try to reconnect, that's expected?

Correct
