### PR TITLE
Fixes issue in SmartInsider where we could not choose where the final processed directory is

### LINKED ISSUE #3613: Smart Insider Assumes Destination Directory Contains Processed Files
#### Expected Behavior

Be able to define where to look for processed files
#### Actual Behavior

Destination directory is assumed to be the location of the processed files
#### Potential Solution

Add functionality for selecting processed files directory
#### Reproducing the Problem

Run the Smart Insider converter
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by gsalaz98**
#### Description

Enables the ability to choose the source directory for the processed files
#### Related Issue

Closes #3613 
#### Motivation and Context

Ensure data integrity and consistency
#### Requires Documentation Change

Yes - ToolBox configuration has been updated
#### How Has This Been Tested?

Offline local testing
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: ToolBox/SmartInsider/SmartInsiderProgram.cs [hunk 1]
```diff
@@ -23,9 +23,19 @@ public static class SmartInsiderProgram
...
         /// Converts Smart Insider data
         /// </summary>
-        public static void SmartInsiderConverter(DateTime date, string sourceDirectory, string destinationDirectory)
+        public static void SmartInsiderConverter(DateTime date, string sourceDirectory, string destinationDirectory, string processedFileDirectory = null)
         {
-            var converter = new SmartInsiderConverter(new DirectoryInfo(sourceDirectory), new DirectoryInfo(destinationDirectory));
+            // Default to the Data Folder Smart Insider data directory if no argument is passed
+            if (string.IsNullOrEmpty(processedFileDirectory))
+            {
+                processedFileDirectory = Path.Combine(Globals.DataFolder, "alternative", "smartinsider");
```
Comment (Martin-Molinero) [inline ToolBox/SmartInsider/SmartInsiderProgram.cs]: Isn't this default value already handled by the caller using `GetParameterOrDefault()`?

File: ToolBox/SmartInsider/SmartInsiderConverter.cs [hunk 2]
```diff
@@ -240,12 +243,13 @@ private void WriteToFile<T>(DirectoryInfo destinationDirectory, Dictionary<strin
...
                 var finalFile = new FileInfo(Path.Combine(destinationDirectory.FullName, $"{ticker}.tsv"));
+                var processedFile = new FileInfo(Path.Combine(_processedFilesDirectory.FullName, destinationDirectory.Name, $"{ticker}.tsv"));
                 var fileContents = new List<T>();
 
-                if (finalFile.Exists)
+                if (processedFile.Exists)
                 {
                     Log.Trace($"SmartInsiderConverter.WriteToFile(): Writing to existing file: {finalFile.FullName}");
-                    fileContents = File.ReadAllLines(finalFile.FullName)
+                    fileContents = File.ReadAllLines(processedFile.FullName)
```
Comment (Martin-Molinero) [inline ToolBox/SmartInsider/SmartInsiderConverter.cs]: Not sure I follow how this works, are the logs at 251 and 258 now outdated?
`processedFile` is the combination of `_processedFilesDirectory.FullName` and `destinationDirectory.Name`?

File: ToolBox/SmartInsider/SmartInsiderConverter.cs [hunk 3]
```diff
@@ -31,17 +30,21 @@ public class SmartInsiderConverter
...
         private readonly DirectoryInfo _destinationDirectory;
+        private readonly DirectoryInfo _processedFilesDirectory;
+
         private readonly MapFileResolver _mapFileResolver;
 
         /// <summary>
         /// Creates an instance of the converter
         /// </summary>
         /// <param name="sourceFile"></param>
         /// <param name="destinationFile"></param>
```
Comment (Martin-Molinero) [inline ToolBox/SmartInsider/SmartInsiderConverter.cs]: Documentation is outdated

File: ToolBox/SmartInsider/SmartInsiderConverter.cs (hunk 2 above)
Comment (gsalaz98) [reply ToolBox/SmartInsider/SmartInsiderConverter.cs]: `destinationDirectory.Name` gets the `transactions` or `intentions` part of the path, so that we know where to load up the existing files from.

File: ToolBox/SmartInsider/SmartInsiderProgram.cs (hunk 1 above)
Comment (gsalaz98) [reply ToolBox/SmartInsider/SmartInsiderProgram.cs]: We need to set a default for external callers of this method

File: ToolBox/Program.cs [hunk 4]
```diff
@@ -261,7 +261,8 @@ public static void Main(string[] args)
                         SmartInsiderProgram.SmartInsiderConverter(
                             DateTime.ParseExact(GetParameterOrExit(optionsObject, "date"), "yyyyMMdd", CultureInfo.InvariantCulture),
                             GetParameterOrExit(optionsObject, "source-dir"),
-                            GetParameterOrExit(optionsObject, "destination-dir"));
+                            GetParameterOrExit(optionsObject, "destination-dir"),
+                            GetParameterOrDefault(optionsObject, "source-meta-dir", Path.Combine(Globals.DataFolder, "alternative", "smartinsider")));
```
Comment (Martin-Molinero) [inline ToolBox/Program.cs]: Maybe could send in `null` here, to avoid default value duplication with the implementation at `SmartInsiderConverter`?

File: ToolBox/SmartInsider/SmartInsiderConverter.cs (hunk 2 above)
Comment (Martin-Molinero) [reply ToolBox/SmartInsider/SmartInsiderConverter.cs]: thanks for the updated docs - The log at 252 seems to supposed that the `finalFile` is the same as the `processedFile` which isn't the case anymore?

File: ToolBox/Program.cs (hunk 4 above)
Comment (gsalaz98) [reply ToolBox/Program.cs]: Good idea 👍

File: ToolBox/SmartInsider/SmartInsiderConverter.cs (hunk 2 above)
Comment (gsalaz98) [reply ToolBox/SmartInsider/SmartInsiderConverter.cs]: I believe it makes sense to keep the logs as-is so that we can differentiate whether we're writing to a new file, or an existing file. Maybe some rewording of that log message would be ideal for further clarity.
