### PR TITLE
Use given selector on indicator warm up

### LINKED ISSUE #6701: EnableAutomaticIndicatorWarmUp doesn't warm up with the selector
#### Expected Behavior

If we set `EnableAutomaticIndicatorWarmUp`, the indicator is warmed up with the selector data point. 

#### Actual Behavior

If we set `EnableAutomaticIndicatorWarmUp`, the indicator is warmed up with the close price.

#### Potential Solution

In **QCAlgorithm.Indicators.cs**, change each
```
WarmUpIndicator(symbol, indicator, resolution);
```
to
```
WarmUpIndicator(symbol, indicator, resolution, selector);
```

#### Reproducing the Problem

https://www.quantconnect.com/terminal/processCache/?request=embedded_backtest_f90578f3a1e54d7170fdbf9f1cc65911.html

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by jhonabreul**
#### Description

Use the given selector when warming indicator up in `QCAlgorithm`  indicator methods

#### Related Issue

Closes #6701 

#### Motivation and Context

`QCAlgorithm`  indicator methods were not using the given selector for warm up

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

Unit tests

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Algorithm/QCAlgorithm.Indicators.cs [hunk 1]
```diff
@@ -528,13 +437,8 @@ public DeMarkerIndicator DEM(Symbol symbol, int period, MovingAverageType type,
...
             var deMarkerIndicator = new DeMarkerIndicator(name, period, type);
-            RegisterIndicator(symbol, deMarkerIndicator, resolution, selector);
-
-            if (EnableAutomaticIndicatorWarmUp)
-            {
-                WarmUpIndicator(symbol, deMarkerIndicator, resolution);
-            }
-
+            InitializeIndicator(symbol, deMarkerIndicator, resolution, selector);
+        https://github.com/QuantConnect/Lean/compare/master...jhonabreul:bug-6701-use-selector-on-warmup
```
Comment (Martin-Molinero) [inline Algorithm/QCAlgorithm.Indicators.cs:441]: typo 😁

**Review by Martin-Molinero — APPROVED** [review]
