### PR TITLE
Fix QuantBook failing unit tests

### LINKED ISSUE #2489: QuantBook unit tests are excluded and failing
#### Expected Behavior
Unit tests should be passing.

#### Actual Behavior
The `QuantBook` unit tests are currently excluded from Travis build and are failing locally.

#### Potential Solution
Add the `Jupyter/RegressionScripts` folder in `PythonSetup.Setup` and add this line in the `QuantBook` constructor:
``` C#
 SubscriptionManager.SetDataManager(new DataManager());
```

#### Reproducing the Problem
Run unit tests locally.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### LINKED ISSUE #2499: MarketHoursDatabase keep data base across unit tests
#### Expected Behavior
`MarketHoursDatabase.Entry` added in a particular unit test should not be used by another test in another class.

#### Actual Behavior
After we run `SecurityManagerTests`, a `Entry` created for SPY set as `AlwaysOpen` is erroneously used by `SecurityQuantBookHistoryTests` resulting on history request with wrong start date/time.

#### Potential Solution
Implement a `Reset` method in `MarketHoursDatabase` and call it with a method with the '[TearDown]` attribute in `SecurityManagerTests`

#### Reproducing the Problem
Run `SecurityManagerTests` and `SecurityQuantBookHistoryTests` in sequence: 
Test SecurityQuantBookHistoryTests(2013,10,11,Equity,"SPY") fails.

#### System Information
Locally in Win10 and Travis.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
The `QuantBook` failing unit tests have been fixed.

Thanks to @AlexCatarino for finding the market hours database issue.

#### Related Issue
Closes #2489 
Closes #2499 

#### Motivation and Context
Failing unit tests.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Unit tests.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Securities/MarketHoursDatabase.cs [hunk 1]
```diff
@@ -91,6 +91,19 @@ public DateTimeZone GetDataTimeZone(string market, Symbol symbol, SecurityType s
...
+        /// <summary>
+        /// Resets the market hours database, forcing a reload when reused.
+        /// Called in tests where multiple algorithms are run sequentially,
+        /// and we need to guarantee that every test starts with the same environment.
+        /// </summary>
+        public static void Reset()
+        {
+            lock (DataFolderMarketHoursDatabaseLock)
+            {
+                _dataFolderMarketHoursDatabase = null;
```
Comment (mchandschuh) [inline Common/Securities/MarketHoursDatabase.cs]: The horrors of statics! not for now, but a later refactoring would be to remove these statics and the symbol properties statics and convert them into provides (similar to map/factor file) -- benefit would be could define a `GitHubMarketHoursDatabaseProvider` which fetches the file from github (same with symbol properties)!

File: Tests/Common/Securities/SecurityManagerTests.cs [hunk 2]
```diff
@@ -38,9 +38,11 @@ public class SecurityManagerTests
         private SymbolPropertiesDatabase _symbolPropertiesDatabase;
         private ISecurityInitializer _securityInitializer;
 
-        [TestFixtureSetUp]
+        [SetUp]
```
Comment (mchandschuh) [inline Tests/Common/Securities/SecurityManagerTests.cs]: 👍

File: Tests/Jupyter/QuantBookIndicatorsTests.cs [hunk 3]
```diff
@@ -16,20 +16,21 @@
...
     public class QuantBookIndicatorsTests
     {
         dynamic _module;
 
         [TestFixtureSetUp]
         public void Setup()
         {
-            var pythonPath = new DirectoryInfo("Jupyter/RegressionScripts");
-            Environment.SetEnvironmentVariable("PYTHONPATH", pythonPath.FullName);
+            SymbolCache.Clear();
```
Comment (mchandschuh) [inline Tests/Jupyter/QuantBookIndicatorsTests.cs]: not for now, but next time, I think there may be a way to do a global test clean up function, after each test we should be resetting all static state so the test starts clean
