### PR TITLE
Fix non-deterministic query in QCAlgorithm.GetSubscription

### LINKED ISSUE #2119: BasicTemplateCryptoAlgorithm regression failing
#### Expected Behavior
`BasicTemplateCryptoAlgorithm` backtest should always return the same results.

#### Actual Behavior
`BasicTemplateCryptoAlgorithm` returns different results for a backtest with the Test runner vs LEAN launcher.

#### Reproducing the Problem
Run the `BasicTemplateCryptoAlgorithm` with LEAN launcher: **10 trades** (correct)
Run the `BasicTemplateCryptoAlgorithm` with Test runner: **5 trades** (incorrect)

#### System Information
Windows 10

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
`QCAlgorithm.GetSubscription` now searches for the first matching subscription in an enumerable sorted by `Symbol` and `TickType`.

#### Related Issue
Closes #2119 

#### Motivation and Context
`BasicTemplateCryptoAlgorithm` is returning different results for a backtest with the Test runner vs LEAN launcher.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
`BasicTemplateCryptoAlgorithm` is now consistently returning the same results.
Previously, when running in the test runner, the last 5 orders were never submitted because the EMA values were always zero (due to the wrong consolidators being selected).

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/ect)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Algorithm/QCAlgorithm.Indicators.cs [hunk 1]
```diff
@@ -1332,12 +1332,17 @@ public SubscriptionDataConfig GetSubscription(Symbol symbol, TickType? tickType)
             SubscriptionDataConfig subscription;
             try
             {
+                // deterministic ordering is required here
+                var subscriptions = SubscriptionManager.Subscriptions
+                    .OrderBy(x => x.Symbol)
+                    .ThenBy(x => x.TickType);
```
Comment (mchandschuh) [inline Algorithm/QCAlgorithm.Indicators.cs]: since we're filtering by `symbol` below, I don't think we need to perform an order by based on symbol. Please test removing the order by symbol to see if it still works as expected

Comment (StefanoRaggi) [reply Algorithm/QCAlgorithm.Indicators.cs]: You're right, order by symbol is not needed. Updated PR

File: Algorithm/QCAlgorithm.Indicators.cs [hunk 2]
```diff
@@ -1332,12 +1332,15 @@ public SubscriptionDataConfig GetSubscription(Symbol symbol, TickType? tickType)
             SubscriptionDataConfig subscription;
             try
             {
+                // deterministic ordering is required here
+                var subscriptions = SubscriptionManager.Subscriptions.OrderBy(x => x.TickType);
```
Comment (Martin-Molinero) [inline Algorithm/QCAlgorithm.Indicators.cs]: I wonder if it would be more performant to filter first by (x => x.Symbol == symbol). I image it will probably depend on each case.

**Comment by jaredbroad** [comment]
This was a bad one. Do we know how it arrived & (other than regression) how to prevent it in the future?
