### PR TITLE
Warm up EmaCrossAlphaModel indicators

### LINKED ISSUE #6167: Update EmaCrossAlphaModel to Warm Up Indicator
#### Expected Behavior
The `EmaCrossAlphaModel` is not warming up its indicators.

#### Actual Behavior
All indicators are warmed up as soon as possible.

#### Potential Solution
Add
```csharp
algorithm.WarmUpIndicator(added.Symbol, fast, _resolution);
algorithm.WarmUpIndicator(added.Symbol, slow, _resolution);
```
at lines 107 and 108 of `EmaCrossAlphaModel.cs` and change to `EmaCrossAlphaModel.py`

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Marinovsky**
#### Description

- Warm up `EmaCrossAlphaModel.cs` and `EmaCrossAlphaModel.py` indicators
- Add unit tests to check the behavior is the expected one
- Fix regression test `CompositeAlphaModelFrameworkAlgorithm.cs`. It turns out the period from the start and end date was less than the default period given to the indicators in the EmeCrossAlphaModel, then those indicators were never ready so `Update()` method never returned an insight. Then, when the indicators of EmaCrossAlpha model were warmed up, the statistics of the regression algorithm changed.
#### Related Issue

Closes #6167
#### Motivation and Context

With this change users will be able to use default EmaCrossAlphaModel even when the period of time between the start and end date is less than the period of time of the fast or slow EMA indicators
#### Requires Documentation Change

This change does not require an update to documentation
#### How Has This Been Tested?

There was created EmaCrossAlpha models in C# and Python and then asserted their indicators were already warmed up when changes are done
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Algorithm.Framework/Alphas/EmaCrossAlphaModel.cs [hunk 1]
```diff
@@ -104,6 +104,8 @@ public override void OnSecuritiesChanged(QCAlgorithm algorithm, SecurityChanges
                     // create fast/slow EMAs
                     var fast = algorithm.EMA(added.Symbol, _fastPeriod, _resolution);
                     var slow = algorithm.EMA(added.Symbol, _slowPeriod, _resolution);
```
Comment (AlexCatarino) [inline Algorithm.Framework/Alphas/EmaCrossAlphaModel.cs:106]: The indicators need to be created by their constructor and registered to a consolidator, so we can remove the subscription to the consolidator when the security is removed.

**Review by AlexCatarino — CHANGES_REQUESTED** [review]
Thank you for the update, @Marinovsky.
I am requesting a change to improve the algorithm speed that uses this Alpha. If we don't remove the consolidators that are created under the hood when we use a helper method such as `EMA`, the algorithm manager will have a lot of unused consolidators to update.

**Review by AlexCatarino — APPROVED** [review]

**Review by Martin-Molinero — CHANGES_REQUESTED** [review]
Thanks for the fixes! 💯 Leaving a few minor requests

**Review by Martin-Molinero — APPROVED** [review]
