### PR TITLE
TryParsePath ignores DateTime

### LINKED ISSUE #7850: TryParsePath ignores DateTime generating incorrect symbol
#### Expected Behavior

Input: 
```
var key = ".../equity/usa/minute/goog/20130102_quote.zip";
LeanData.TryParsePath(key, out var symbol, ...);
```
**Output**: "GOOGL" security.

#### Actual Behavior

```
var key = ".../equity/usa/minute/goog/20130102_quote.zip";
LeanData.TryParsePath(key, out var symbol, ...);
```
**Output**: It always returns "GOOCV" security (**no matter the date**).

#### Potential Solution

When `TryParsePath` create new Symbol, it may to consider date in path to get right `MapFile`.

#### Reproducing the Problem

Run specific test: https://github.com/QuantConnect/Lean/pull/7845/commits/1b12ece772922a0618deb3d1520ee3b1c879377a

#### System Information

OS: Windows 10 x64
test: run on x64 CPU
IDE: Visual Studio 2022

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Romazes**
#### Description

The current implementation in `TryParsePath()` overlooks the parsed Date component. Consequently, when parsing a path like `"equity/usa/minute/spwr/20071223_trade.zip"`, the Date portion (`20071223`, representing December 23, 2007) is ignored. This oversight leads to incorrect `Symbol` generation from _map files_.

#### Related Issue

Closes #7850

#### Motivation and Context

By incorporating the Date into the parsing logic, the algorithm can accurately generate symbols from map files, ensuring correctness in symbol creation.

#### Requires Documentation Change

N/A
#### How Has This Been Tested?

To ensure the reliability and effectiveness of this fix, comprehensive testing has been conducted. This includes:
- Unit tests: New unit tests have been added to cover scenarios where the parsed Date is essential for symbol creation. These tests verify that the `TryParsePath()` method correctly handles Date parsing and generates accurate symbols.
- Integration tests: Existing integration tests have been expanded to incorporate cases where the Date component is significant. Through integration testing, the behavior of the code in real-world scenarios is validated.
- Manual testing: Various sample data sets have been employed to manually validate the functionality of the modified `TryParsePath()` method. This manual testing ensures that the fix performs as expected across different input scenarios and edge cases.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Util/LeanData.cs [hunk 1]
```diff
@@ -1222,6 +1222,37 @@ public static bool TryParsePath(string fileName, out Symbol symbol, out DateTime
...
+        /// market: usa
+        /// mappingResolveDate: 2007/12/23
+        /// </code>
+        /// </example>
+        private static Symbol CreateSymbol(string ticker, SecurityType securityType, string market, Type dataType, DateTime mappingResolveDate = default)
+        {
+            if (mappingResolveDate != default && (securityType == SecurityType.Equity || securityType == SecurityType.Option))
+            {
+                var symbol = new Symbol(SecurityIdentifier.GenerateEquity(ticker, market, mappingResolveDate: mappingResolveDate), ticker);
+                return securityType == SecurityType.Option ? Symbol.CreateCanonicalOption(symbol) : symbol;
```
Comment (Martin-Molinero) [inline Common/Util/LeanData.cs:1248]: Nice! 🙌  thank you 👍

**Review by Martin-Molinero — APPROVED** [review]
