### PR TITLE
Stop Emitting Insights on Delisted Securities

### LINKED ISSUE #4877: Do Not Emit Insights of Delisted Securities
#### Expected Behavior
Do not emit insights of delisted securities.

#### Actual Behavior
It's possible to emit insights of delisted securities

#### Potential Solution
N/A

#### Reproducing the Problem
```python
class ARQLInvalidInsightAlgorithm(QCAlgorithm):
    def Initialize(self):
        self.SetCash(1000000)
        self.SetStartDate(2015, 1, 1)
        self.SetBrokerageModel(BrokerageName.AlphaStreams)
        self.AddEquity("SPY", Resolution.Daily)
        self.symbol = self.AddEquity("ARQL", Resolution.Daily).Symbol
        
    def OnData (self, Data):
        self.EmitInsights(Insight.Price(self.symbol, timedelta(1), InsightDirection.Up))
```
ARQL was delisted on 20200116 and this algorithm keeps emitting insights after that date.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

In the `QCAlgorithm` layer I added a check to verify that all insights are valid before allowing they to be emitted.
 
#### Related Issue

Closes #4877 

#### Motivation and Context

Before you could emit insights for delisted securities, now I check all the pending insights securities to see if they are still listed, if not I remove it from the insights list that will be processed and post an error in the log.

#### Requires Documentation Change

N/A

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Algorithm/QCAlgorithm.Framework.cs [hunk 1]
```diff
@@ -382,6 +383,22 @@ public void EmitInsights(params Insight[] insights)
                 return;
             }
 
+            // Verify insights are valid
+            var validInsights = new List<Insight>();
+            foreach(var insight in insights){
+                if (Securities[insight.Symbol].IsDelisted)
+                {
+                    Error($"QCAlgorithm.EmitInsights(): Cannot emit insight for delisted security {insight.Symbol}");
```
Comment (AlexCatarino) [inline Algorithm/QCAlgorithm.Framework.cs:391]: Calling `Error` will add the message to the user log and consume his quota, and it can also be a repetitive annoying message. Perhaps we should find a solution that only logs once for the first time it happens just to let the user know that the `Insight` was discarded.

Comment (C-SELLERS) [reply Algorithm/QCAlgorithm.Framework.cs]: I went ahead and changed the logic to post one warning, informing the user that they will be discarded

File: Algorithm/QCAlgorithm.Framework.cs [hunk 2]
```diff
@@ -382,6 +384,26 @@ public void EmitInsights(params Insight[] insights)
...
             }
 
+            // Verify insights are valid
+            var validInsights = new List<Insight>();
+            foreach(var insight in insights){
+                if (Securities[insight.Symbol].IsDelisted)
+                {
+                    if (!_isEmitDelistedInsightWarningSent)
+                    {
+                        Error($"QCAlgorithm.EmitInsights(): Warning: cannot emit insights for delisted securities, these will be discarded");
```
Comment (Martin-Molinero) [inline Algorithm/QCAlgorithm.Framework.cs:394]: Cool! 👍 
We are missing to cover the insight emitted by the alpha too, see `public void OnFrameworkData(Slice slice)`. 
Suggest we create a method that performs this loop and `InitializeInsightFields` at the same time, returning an array, so we don't iterate twice over the insights. `OnInsightsGenerated` should also take an array of insights. And we call this new method in both locations.
We should add a regression test covering these two cases too

File: Algorithm/QCAlgorithm.Framework.cs [hunk 3]
```diff
@@ -394,7 +398,35 @@ public void EmitInsights(params Insight[] insights)
...
+        /// <summary>
+        /// 
+        /// </summary>
+        /// <param name="insights"></param>
+        /// <returns></returns>
+        private Insight[] InitializeInsights(Insight[] insights)
+        {
+            // Verify insights are valid and initialize their fields
+            var validInsights = new List<Insight>();
+            foreach (var insight in insights)
```
Comment (Martin-Molinero) [inline Algorithm/QCAlgorithm.Framework.cs:413]: Cool!
This is very sensitive to performance since it's executed for each insight, suggest we do the following:
- using a simple `for(var i = 0;..)` loop, so that we do not create the enumerator using linq.
- avoid creating the list unless there is at least 1 delisted security which we should remove, so in 99.9% of the cases we do not create a new collection at all, we return provided `Insight[]`
- let's make `OnInsightsGenerated` take an `Insight[]` and avoid the `ToArray` call he has internally

nit - missing XML docs

File: Tests/Algorithm/Framework/QCAlgorithmFrameworkTests.cs [hunk 4]
```diff
@@ -71,6 +71,45 @@ public void SetsInsightGeneratedAndCloseTimes()
...
+            security.IsDelisted = true;
+
+            // Trigger Alpha to emit insight
+            algorithm.OnFrameworkData(new Slice(new DateTime(2000, 01, 01), new List<BaseData>() { tick }));
+
+            // Manually emit insight
+            algorithm.EmitInsights(Insight.Price(Symbols.SPY, TimeSpan.FromDays(1), InsightDirection.Up, .5, .75));
+
+            // Should be zero because security is delisted
+            Assert.AreEqual(0, actualInsights.Count);
```
Comment (Martin-Molinero) [inline Tests/Algorithm/Framework/QCAlgorithmFrameworkTests.cs:110]: Cool! Maybe we can make `security.IsDelisted = true;` the bool a argument for the test so we assert the count is 2 for when delisted is `false`

**Review by Martin-Molinero — COMMENTED** [review]
Nice! almost there, some minor request

File: Tests/Algorithm/Framework/QCAlgorithmFrameworkTests.cs (hunk 4 above)
Comment (C-SELLERS) [reply Tests/Algorithm/Framework/QCAlgorithmFrameworkTests.cs]: Gotcha, made it two test cases one for delisted one for not

File: Algorithm/QCAlgorithm.Framework.cs (hunk 3 above)
Comment (C-SELLERS) [reply Algorithm/QCAlgorithm.Framework.cs]: Gotcha!

**Review by AlexCatarino — APPROVED** [review]

**Review by Martin-Molinero — APPROVED** [review]
Sweet! 🍬
