### PR TITLE
Tradier Options History Support

### LINKED ISSUE #5909: Tradier Options Support - History
#### Expected Behavior

- Tradier supports options completely
#### Actual Behavior

- Tradier does not support option history requests which are supported by the API
#### Potential Solution

- Implement option support
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by C-SELLERS**
#### Description

Modify Tradier Brokerage to support history request of options

#### Related Issue

Closes #5909 

#### Motivation and Context

Options history is support by their api so with a few adjustments Lean can also support it 

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

Unit test included to pull option history 

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Tests/Brokerages/Tradier/TradierBrokerageHistoryProviderTests.cs [hunk 1]
```diff
@@ -53,51 +60,23 @@ private static TestCaseData[] TestParameters
...
-                var accountId = Config.Get("tradier-account-id");
-                var accessToken = Config.Get("tradier-access-token");
-
-                var brokerage = new TradierBrokerage(null, null, null, null, useSandbox, accountId, accessToken);
-
+            {   
                 var now = DateTime.UtcNow;
+                var request = new HistoryRequest(now.Add(-period),
+                    now,
+                    typeof(QuoteBar),
```
Comment (Martin-Molinero) [inline Tests/Brokerages/Tradier/TradierBrokerageHistoryProviderTests.cs:67]: `Tradier` only returns TradeBars really? think should probably return empty when requested quoteBars

File: Tests/Brokerages/Tradier/TradierBrokerageHistoryProviderTests.cs [hunk 2]
```diff
@@ -109,5 +88,61 @@ public void GetsHistory(Symbol symbol, Resolution resolution, TimeSpan period, b
                 Assert.DoesNotThrow(test);
             }
         }
+    
+        [Test]
+        public void GetsOptionHistory(){
```
Comment (Martin-Molinero) [inline Tests/Brokerages/Tradier/TradierBrokerageHistoryProviderTests.cs:93]: Cool! Think would be nice to see different resolution as `TestCase`

**Review by Martin-Molinero — APPROVED** [review]
Cool! minor comments

**Review by Martin-Molinero — APPROVED** [review]
