### PR TITLE
Fix AddSecurity not adding security with same ticker but different market

### LINKED ISSUE #3124: AddSecurity does not add security with same ticker but different market
#### Expected Behavior
`AddSecurity` should be able to add multiple securities with the same ticker but different markets.

#### Actual Behavior
Only the first security with the same given ticker is added to the `Securities` collection.

#### Potential Solution
Update `AddSecurity` to check if the symbol returned by `SecurityCache.TryGetSymbol` has the same market.

#### Reproducing the Problem
This is a failing unit test, added in `AlgorithmSetBrokerageTests.cs`:
``` C#
        [Test]
        public void AddForexCanAddWithSameTickerAndDifferentMarket()
        {
            _algo.AddForex("EURUSD", Resolution.Minute, Market.FXCM);
            _algo.AddForex("EURUSD", Resolution.Minute, Market.Oanda);

            Assert.AreEqual(2, _algo.Securities.Count);
        }
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
The `QCAlgorithm.AddSecurity` method has been updated to support adding multiple assets with the same ticker but with different markets. 
Both the generic version (called by `AddEquity`, `AddForex`, `AddCrypto`, etc.) and the non-generic version have been updated, as well as the `AddFuture` and `AddOption` methods.

#### Related Issue
Closes #3124 

#### Motivation and Context
Unable to add multiple assets with the same ticker but with different markets. 

#### Requires Documentation Change
No.

#### How Has This Been Tested?
1. New unit tests included
2. The following algorithm has been deployed to Oanda in the cloud and it is receiving live data from both Oanda and FXCM for the EURUSD symbol:
``` C#
    public class TestAddSecuritySameTickerDifferentMarkets : QCAlgorithm
    {
        public override void Initialize()
        {
            SetStartDate(2018, 10, 23);
            SetCash(100000);
            
            AddForex("EURUSD", Resolution.Minute, Market.Oanda);
            AddForex("EURUSD", Resolution.Minute, Market.FXCM);
        }

        public override void OnData(Slice data)
        {
            foreach (var kvp in data.QuoteBars)
            {
                Debug($"{Time} - {kvp.Key.ID.ToString()} - {kvp.Value.Close}");
            }
        }
    }
```

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Algorithm/QCAlgorithm.cs [hunk 1]
```diff
@@ -1442,7 +1442,7 @@ public Security AddSecurity(SecurityType securityType, string symbol, Resolution
                 }
 
                 Symbol symbolObject;
-                if (!SymbolCache.TryGetSymbol(symbol, out symbolObject))
+                if (!SymbolCache.TryGetSymbol(symbol, out symbolObject) || symbolObject.ID.Market != market)
```
Comment (jaredbroad) [inline Algorithm/QCAlgorithm.cs]: While here please rename symbol variable to `ticker` and add security type check to future proof it. Tiny chance of 2 colliding USA ticker names.
