### PR TITLE
GDAXDownloader : save data int the right ticker name

### LINKED ISSUE #4798: GDAXDownloader don't save the data in the right ticker folder
## Expected Behavior

When downloading history for the BTCUSD pair on GDAX, I expect to see the data saved in the btcusd folder in order to be used for backtesting.

#### Actual Behavior

The GDAX/Coinbase history ask to provide the ticker name BTC-USD and not BTCUSD.
This result in saving the data in the folder btc-usd so to be able to use those data we have to manually move them in the correct ticker folder named btcusd.

#### Potential Solution

Map the tickers used on the exchange with the "tickers" used to get the history 

#### Reproducing the Problem

Download any data for the ticker BTC-USD the data will end in the btc-usd folder

#### System Information

MacOS Catalina 10.15.7

#### Checklist
- [X] I have completely filled out this template
- [ X I have confirmed that this issue exists on the current `master` branch
- [ X I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by nazbrok**
#### Description

The GDAXDownloader actually don't save the data in the right ticker folder.
Because of the way GDAX api is written, we have to request data for BTC-USD and not BTCUSD. The result is the data will be save in the btc-usd folder but Lean won't use it because it will try to load the data from the BTCUSD folder.

#### Related Issue

Fixes #4798 

#### Motivation and Context

When I download historical data from GDAX, I can't automatically used them, I have to move the data in the right folder name otherwise Lean won't find them.

#### Requires Documentation Change

The ticker name to use to call GDAXDownloader is now the same ticker we use in the application.
I could have do the mapping the other way to have no breaking change but I found it was confusing to request data for a different ticker. That way we are consistent.

#### How Has This Been Tested?

I requested historical data for gdax and the data is now saved in the right ticker folder.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [X ] My code follows the code style of this project.
- [X] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [X] All new and existing tests passed.
- [X] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Comment by Martin-Molinero** [comment]
Hey @nazbrok! Thanks for the fix, I believe you should be able to rebase on top of PR https://github.com/QuantConnect/Lean/pull/4741/files where we are adding the `SymbolPropertiesDatabaseSymbolMapper` and directly use him, so we don't need to duplicate the mapping of GDAX symbols?

**Comment by nazbrok** [comment]
Hi @Martin-Molinero , sure will do.

**Comment by nazbrok** [comment]
Hi @Martin-Molinero.
I am not so much used to git so I hope it's ok the way I did it.
I think the PR should now target the branch https://github.com/QuantConnect/Lean/tree/bug-4723-gdax-symbol-mapping but I can't edit it. Should I create or new one or can you edit it ?

File: ToolBox/GDAXDownloader/GDAXDownloaderProgram.cs [hunk 1]
```diff
@@ -44,19 +45,25 @@ public static void GDAXDownloader(IList<string> tickers, string resolution, Date
...
                 foreach (var ticker in tickers)
                 {
+                    // create symbols for lean and brokerage
+                    var leanSymbolObject = Symbol.Create(ticker, SecurityType.Crypto, market);
+                    var brokerageSymbolObject = Symbol.Create(mapper.GetBrokerageSymbol(leanSymbolObject), SecurityType.Crypto, market);
+
                     // Download the data
-                    var symbolObject = Symbol.Create(ticker, SecurityType.Crypto, market);
-                    var data = downloader.Get(symbolMapper.GetGDAXDownloadSymbol(symbolObject), castResolution, fromDate, toDate);
+                    var data = downloader.Get(brokerageSymbolObject, castResolution, fromDate, toDate);
```
Comment (Martin-Molinero) [inline ToolBox/GDAXDownloader/GDAXDownloaderProgram.cs:63]: Generally, there isn't a `brokerageSymbolObject` but a brokerage ticker as shown in the `ISymbolMapper` interface and the 'services' it provides. Seems to me the `GDAXDownloader` should own the mapper internally, instead of relying on the caller doing the right thing, and we avoid the need of a `brokerageSymbolObject`

**Review by Martin-Molinero — COMMENTED** [review]
Rebase looks okay ty! 👍 Leaving just one last tweak request

File: ToolBox/GDAXDownloader/GDAXDownloaderProgram.cs (hunk 1 above)
Comment (nazbrok) [reply ToolBox/GDAXDownloader/GDAXDownloaderProgram.cs]: make sense. updated

**Review by Martin-Molinero — APPROVED** [review]
Nice 👍, will merge after https://github.com/QuantConnect/Lean/pull/4741
