### PR TITLE
Fixes Bitfinex Brokerage history call bug

### LINKED ISSUE #5173: Indicator warmup broken on Bitfinex Brokerage API
I am reopening  #5119  as it's not yet fixed 

#### Expected Behavior

Framework is expected upon initialization to  request Bitfinex's API for historical OHLVC data and warm up itself .

#### Actual Behavior

It's not warming up itself from API and waits for incoming data to build the indicators. 

#### Potential Solution

The warm up function should properly format Start/End dates of the request for warmup . As Now it shows 

```
20210106 01:52:49.373 Trace:: Brokerage.OnMessage(): Warning - Code: InvalidEndTime - The history request's end date is not a full multiple of a resolution. Bitfinex API only allows to support trade bar history requests. The start and end dates of a such request are expected to match exactly with the beginning of the first bar and ending of the last

```

#### Reproducing the Problem

Run the latest  LEAN on any linux machine in docker with ANY  Python algorithm. 

In #5119 I have provided simple algo you can try 

#### System Information

I have run the Lean framework in Docker on Ubuntu machine 

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

Full log 

```
20210106 01:52:38.864 Trace:: Using /Lean/Launcher/config.json as configuration file
20210106 01:52:38.997 Trace:: Config.GetValue(): debug-mode - Using default value: False
20210106 01:52:38.998 Trace:: Config.Get(): Configuration key not found. Key: plugin-directory - Using default value: 
20210106 01:52:38.999 Trace:: Config.Get(): Configuration key not found. Key: composer-dll-directory - Using default value: /Lean/Launcher/bin/Debug/
20210106 01:52:39.106 Trace:: Python for .NET Assembly: Python.Runtime, Version=1.0.5.30, Culture=neutral, PublicKeyToken=null
20210106 01:52:39.132 Trace:: Python for .NET Assembly: nPython, Version=1.0.5.30, Culture=neutral, PublicKeyToken=null
20210106 01:52:39.235 Trace:: Config.Get(): Configuration key not found. Key: data-directory - Using default value: ../../../Data/
20210106 01:52:39.247 Trace:: Config.Get(): Configuration key not found. Key: version-id - Using default value: 
20210106 01:52:39.247 Trace:: Config.Get(): Configuration key not found. Key: cache-location - Using default value: /Data
20210106 01:52:39.248 Trace:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.4.0.0 Mode: DEBUG (64bit)
20210106 01:52:39.251 Trace:: Engine.Main(): Started 1:52 AM
20210106 01:52:39.258 Trace:: Config.GetValue(): job-project-id - Using default value: 0
20210106 01:52:39.265 Trace:: Config.GetValue(): regression-update-statistics - Using default value: False
20210106 01:52:39.266 Trace:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value: LocalLeanManager
20210106 01:52:39.323 Trace:: JobQueue.NextJob(): Selected ../../../Algorithm.Python/CryptoAlgorithm.py
20210106 01:52:39.332 Trace:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
20210106 01:52:39.332 Trace:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
20210106 01:52:39.332 Trace:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
20210106 01:52:39.335 Trace:: Config.Get(): Configuration key not found. Key: algorithm-id - Using default value: CryptoAlgorithm
20210106 01:52:45.486 Trace:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
20210106 01:52:45.490 Trace:: Config.GetValue(): streamed-chart-limit - Using default value: 12
20210106 01:52:45.490 Trace:: Config.GetValue(): streamed-chart-group-size - Using default value: 3
20210106 01:52:45.504 Trace:: Config.Get(): Configuration key not found. Key: object-store-root - Using default value: ./storage
20210106 01:52:45.506 Trace:: Config.GetValue(): ignore-version-checks - Using default value: False
20210106 01:52:45.507 Trace:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
20210106 01:52:45.510 Trace:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
20210106 01:52:45.513 Trace:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
20210106 01:52:45.517 Trace:: Config.GetValue(): consumer-batching-timeout-ms - Using default value: 0
20210106 01:52:46.008 Trace:: PythonInitializer.Initialize(): start...
PythonEngine.Initialize(): Runtime.Initialize()...
Runtime.Initialize(): Py_Initialize...
Runtime.Initialize(): PyEval_InitThreads...
Runtime.Initialize(): Initialize types...
Runtime.Initialize(): Initialize types end.
Runtime.Initialize(): AssemblyManager.Initialize()...
Runtime.Initialize(): AssemblyManager.UpdatePath()...
PythonEngine.Initialize(): register atexit callback...
PythonEngine.Initialize(): GetCLRModule()...
PythonEngine.Initialize(): clr GetManifestResourceStream...
20210106 01:52:46.732 Trace:: PythonInitializer.Initialize(): ended
20210106 01:52:46.738 Trace:: AlgorithmPythonWrapper(): Python version 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:25:33) 
[GCC 7.3.0]: Importing python module CryptoAlgorithm
20210106 01:52:47.634 Trace:: AlgorithmPythonWrapper(): Creating IAlgorithm instance.
20210106 01:52:48.131 Trace:: Config.GetValue(): mute-python-library-logging - Using default value: True
20210106 01:52:48.201 Trace:: LocalObjectStore.Initialize(): Storage Root: /Lean/Launcher/bin/Debug/storage/QCAlgorithm
20210106 01:52:48.202 Trace:: LiveTradingDataFeed.GetDataChannelProvider(): will use DataChannelProvider
20210106 01:52:48.529 Trace:: LiveTradingDataFeed.GetDataQueueHandler(): will use BitfinexBrokerage
20210106 01:52:48.532 ERROR:: LiveTradingResultHandler.Update(): Algorithm not yet initialized.
20210106 01:52:48.532 Trace:: BaseDataExchange(CustomDataExchange) Starting...
20210106 01:52:48.535 Trace:: BaseWebSocketsBrokerage.Connect(): Connecting...
20210106 01:52:48.536 Trace:: WebSocketClientWrapper connection task started: wss://api.bitfinex.com/ws/2
20210106 01:52:48.539 Trace:: WebSocketClientWrapper.HandleConnection(wss://api.bitfinex.com/ws/2): Connecting...
20210106 01:52:48.713 Trace:: WebSocketClientWrapper.OnOpen(): Connection opened (IsOpen:True, State:Open): wss://api.bitfinex.com/ws/2
20210106 01:52:48.713 Trace:: BaseWebsocketsBrokerage(): WebSocket.Open. Subscribing
20210106 01:52:48.728 Trace:: BitfinexBrokerage.SubscribeAuth(): Sent authentication request.
20210106 01:52:48.733 Trace:: LiveTradingResultHandler.SendStatusUpdate(): status: 'LoggingIn'.  Logging into brokerage...
20210106 01:52:48.733 Trace:: BrokerageSetupHandler.Setup(): Connecting to brokerage...
20210106 01:52:48.734 Trace:: BrokerageSetupHandler.Setup(): Bitfinex account base currency: USD
20210106 01:52:48.734 Trace:: BrokerageSetupHandler.Setup(): Initializing algorithm...
20210106 01:52:48.734 Trace:: LiveTradingResultHandler.SendStatusUpdate(): status: 'Initializing'.  Initializing algorithm...
20210106 01:52:48.739 Trace:: Config.Get(): Configuration key not found. Key: security-data-feeds - Using default value: 
20210106 01:52:48.764 Trace:: BitfinexWebsocketsBrokerage.OnMessage: Subscribing to authenticated channels succeed
20210106 01:52:48.885 Trace:: BrokerageSetupHandler.Setup(): Fetching cash balance from brokerage...
20210106 01:52:49.160 Trace:: BrokerageSetupHandler.Setup(): Setting USD cash to 1.49645876922358
20210106 01:52:49.161 Trace:: BrokerageSetupHandler.Setup(): Fetching open orders from brokerage...
20210106 01:52:49.216 Trace:: BrokerageSetupHandler.Setup(): Fetching holdings from brokerage...
20210106 01:52:49.300 Trace:: LiveTradingDataFeed.CreateUniverseSubscription(): Creating user defined universe: QC-UNIVERSE-USERDEFINED-BITFINEX-CRYPTO E3
20210106 01:52:49.304 Trace:: DataManager.AddSubscription(): Added QC-UNIVERSE-USERDEFINED-BITFINEX-CRYPTO,QC-UNIVERSE-USERDEFINED-BITFINEX-CRYPTO,Minute,TradeBar,Trade,Adjusted,Internal. Start: 1/6/2021 1:52:48 AM. End: 12/31/2050 12:00:00 AM
20210106 01:52:49.319 Trace:: Brokerage.OnMessage(): Warning - Code: InvalidEndTime - The history request's end date is not a full multiple of a resolution. Bitfinex API only allows to support trade bar history requests. The start and end dates of a such request are expected to match exactly with the beginning of the first bar and ending of the last
20210106 01:52:49.322 Trace:: BaseSetupHandler.SetupCurrencyConversions():
Symbol      Quantity    Conversion = Value in USD
USD: $           1.50 @       1.00 = $1.50
BTC: ฿           0.00 @       0.00 = $0
-------------------------------------------------
CashBook Total Value:                $1.50

20210106 01:52:49.326 Trace:: JOB HANDLERS: 
20210106 01:52:49.326 Trace::          DataFeed:     QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed
20210106 01:52:49.326 Trace::          Setup:        QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler
20210106 01:52:49.326 Trace::          RealTime:     QuantConnect.Lean.Engine.RealTime.LiveTradingRealTimeHandler
20210106 01:52:49.326 Trace::          Results:      QuantConnect.Lean.Engine.Results.LiveTradingResultHandler
20210106 01:52:49.326 Trace::          Transactions: QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler
20210106 01:52:49.326 Trace::          Alpha:        QuantConnect.Lean.Engine.Alphas.DefaultAlphaHandler
20210106 01:52:49.326 Trace::          ObjectStore:  QuantConnect.Lean.Engine.Storage.LocalObjectStore
20210106 01:52:49.326 Trace::          History Provider:     QuantConnect.Lean.Engine.HistoricalData.BrokerageHistoryProvider
20210106 01:52:49.326 Trace::          Brokerage:      QuantConnect.Brokerages.Bitfinex.BitfinexBrokerage
20210106 01:52:49.337 Trace:: LiveTradingRealTimeHandler.RefreshMarketHoursToday(Crypto): Market hours set: Symbol: BTCUSD Tuesday: Market: 00:00:00-1.00:00:00 | Market: 00:00:00-1.00:00:00 (UTC)
20210106 01:52:49.348 Trace:: LiveTradingResultHandler.SendStatusUpdate(): status: 'Running'. 
20210106 01:52:49.357 Trace:: AlgorithmManager.Run(): Begin DataStream - Start: 1/5/2021 12:00:00 AM Stop: 12/31/2050 12:00:00 AM
20210106 01:52:49.361 Trace:: ProcessVolatilityHistoryRequirements(): Updating volatility models with historical data...
20210106 01:52:49.362 Trace:: ProcessVolatilityHistoryRequirements(): finished.
20210106 01:52:49.373 Trace:: AlgorithmManager.Stream(): WarmupHistoryRequest: BTCUSD: Start: 12/31/2020 5:10:00 PM End: 1/6/2021 1:52:48 AM Resolution: Minute
20210106 01:52:49.373 Trace:: Brokerage.OnMessage(): Warning - Code: InvalidEndTime - The history request's end date is not a full multiple of a resolution. Bitfinex API only allows to support trade bar history requests. The start and end dates of a such request are expected to match exactly with the beginning of the first bar and ending of the last
20210106 01:52:49.403 Trace:: Debug: Launching analysis for CryptoAlgorithm with LEAN Engine v2.4.0.0
20210106 01:52:50.029 Trace:: WebSocketClientWrapper connection task started: wss://api.bitfinex.com/ws/2
20210106 01:52:50.029 Trace:: WebSocketClientWrapper.HandleConnection(wss://api.bitfinex.com/ws/2): Connecting...
20210106 01:52:50.168 Trace:: WebSocketClientWrapper.OnOpen(): Connection opened (IsOpen:True, State:Open): wss://api.bitfinex.com/ws/2
20210106 01:52:50.173 Trace:: BitfinexSubscriptionManager.GetFreeWebSocket(): New websocket added: Hashcode: 1178891180, WebSocket connections: 1
20210106 01:52:50.178 Trace:: BitfinexBrokerage.Subscribe(): Sent subscribe for BTCUSD/Trade.
20210106 01:52:50.209 Trace:: BitfinexSubscriptionManager.OnSubscribe(): Channel subscribed: Id:451698 BTCUSD/trades
20210106 01:52:50.213 Trace:: DataManager.AddSubscription(): Added BTCUSD,BTCUSD,Minute,TradeBar,Trade,Adjusted. Start: 1/6/2021 1:52:50 AM. End: 12/31/2050 5:00:00 AM
20210106 01:52:50.243 Trace:: BitfinexBrokerage.Subscribe(): Sent subscribe for BTCUSD/Quote.
20210106 01:52:50.654 Trace:: BitfinexSubscriptionManager.OnSubscribe(): Channel subscribed: Id:791641 BTCUSD/book
20210106 01:52:50.654 Trace:: DataManager.AddSubscription(): Added BTCUSD,BTCUSD,Minute,QuoteBar,Quote,Adjusted. Start: 1/6/2021 1:52:50 AM. End: 12/31/2050 5:00:00 AM
20210106 01:52:50.664 Trace:: DataManager.AddSubscription(): Added SPY,SPY,Minute,TradeBar,Trade,Adjusted,Internal. Start: 1/5/2021 8:59:00 PM. End: 12/31/2050 5:00:00 AM
20210106 01:52:50.664 Trace:: UniverseSelection.AddPendingInternalDataFeeds(): Adding internal benchmark data feed SPY,SPY,Minute,TradeBar,Trade,Adjusted,Internal
20210106 01:52:50.666 Trace:: DataManager.RemoveSubscription(): Removed SPY,SPY,Minute,TradeBar,Trade,Adjusted,Internal
20210106 01:52:50.671 Trace:: AlgorithmManager.Stream(): Finished warmup
20210106 01:52:50.704 Trace:: Debug: Bitfinex account base currency: USD
Algorithm finished warming up.
20210106 01:52:50.705 ERROR:: Brokerage Warning: The history request's end date is not a full multiple of a resolution. Bitfinex API only allows to support trade bar history requests. The start and end dates of a such request are expected to match exactly with the beginning of the first bar and ending of the last
Brokerage Warning: The history request's end date is not a full multiple of a resolution. Bitfinex API only allows to support trade bar history requests. The start and end dates of a such request are expected to match exactly with the beginning of the first bar and ending of the last
20210106 01:53:49.395 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 44, Sample: 76, App: 431, CurrentTimeStepElapsed: 00:00.000
20210106 01:54:49.451 Trace:: Isolator.ExecuteWithTimeLimit(): Used: 60, Sample: 76, App: 432, CurrentTimeStepElapsed: 00:00.000

```

### PR DESCRIPTION
**Pull request by IlshatGaripov**
#### Description
Bitfinex api requires that history request's start and end dates were rounded down to the resolution. This fixes a bug.

#### Related Issue
Closes #5173

#### Motivation and Context
Closing an issue

#### Requires Documentation Change
NA

#### How Has This Been Tested?
Tested on live algo, logged the results.

#### Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [ ] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by Martin-Molinero — APPROVED** [review]
Thanks!

File: Brokerages/Bitfinex/BitfinexBrokerage.cs [hunk 1]
```diff
@@ -269,7 +273,9 @@ public override List<CashAmount> GetCashBalance()
 
             if (response.StatusCode != HttpStatusCode.OK)
             {
-                throw new Exception($"BitfinexBrokerage.GetCashBalance: request failed: [{(int)response.StatusCode}] {response.StatusDescription}, Content: {response.Content}, ErrorMessage: {response.ErrorMessage}");
+                throw new Exception($"BitfinexBrokerage.GetCashBalance: request failed: " +
+                                    $"[{(int)response.StatusCode}] {response.StatusDescription}, " +
+                                    $"Content: {response.Content}, ErrorMessage: {response.ErrorMessage}");
```
Comment (Martin-Molinero) [inline Brokerages/Bitfinex/BitfinexBrokerage.cs:278]: Just a general comment: should avoid format/style changes like these in PRs with other objectives, like fixing a bug.
