### PR TITLE
Fix bug in Momentum indicator

### LINKED ISSUE #7403: Momentum Indicator IsReady pre-maturely
#### Expected Behavior

If we use `Momentum(1)`, the indicator `IsReady` after it's seen 2 samples.

#### Actual Behavior

The indicator `IsReady` after seeing just 1 sample.

#### Potential Solution

N/A

#### Reproducing the Problem

```
indicator = Momentum(1)
indicator.Update(datetime.now(), 1.0)
print(indicator.IsReady)
print(indicator.Current.Value)
indicator.Update(datetime.now(), 1.5)
print(indicator.IsReady)
print(indicator.Current.Value)
indicator.Update(datetime.now(), 1.5)
print(indicator.IsReady)
print(indicator.Current.Value)
```
> True
0.0
True
0.5
True
0.0

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Marinovsky**
#### Description

Override the `IsReady` property in `Momentum.cs`
#### Related Issue

Closes #7403 
#### Motivation and Context

With this change momentum indicator will work as expected
#### Requires Documentation Change

N/A
#### How Has This Been Tested?

A unit test that already tested the IsReady method, was modified to assert now the indicator worked as expected
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Indicators/Momentum.cs [hunk 1]
```diff
@@ -26,6 +26,11 @@ public class Momentum : WindowIndicator<IndicatorDataPoint>, IIndicatorWarmUpPer
         /// </summary>
         public int WarmUpPeriod => Period;
 
+        /// <summary>
+        /// Gets a flag indicating when this indicator is ready and fully initialized
+        /// </summary>
+        public override bool IsReady => Samples > WarmUpPeriod;
```
Comment (AlexCatarino) [inline Indicators/Momentum.cs:32]: If the indicator is ready when `Samples` is greater than `WarmUpPeriod`, it means that `WarmUpPeriod` is incorrect, because we need `WarmUpPeriod + 1` to be ready.
```csharp
public int WarmUpPeriod => Period + 1;
public override bool IsReady => Samples > Period;
```

**Review by Martin-Molinero — APPROVED** [review]
Thank you!
