### PR TITLE
Don't raise IBrokerage.OptionPositionAssigned on exercise

### LINKED ISSUE #4800: BacktestingBrokerage.OptionPositionAssigned is raised for exercises
#### Expected Behavior

Event only raised for option assignment.

#### Actual Behavior

Event is raised for assignment _and_ exercise.

#### Potential Solution

Check `OrderEvent.IsAssignment` before raising event and remove this same check from `BrokerageTransactionHandler.HandlePositionAssigned`

#### Reproducing the Problem

Code review.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by mchandschuh**
#### Description

Don't raise IBrokerage.OptionPositionAssigned on exercise

#### Related Issue

Fixes #4800

#### Motivation and Context

Abiding by interface contracts is important.

#### Requires Documentation Change

No.

#### How Has This Been Tested?

Code review and existing test suite.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by Martin-Molinero — APPROVED** [review]

File: Engine/TransactionHandlers/BrokerageTransactionHandler.cs [hunk 1]
```diff
@@ -1083,10 +1083,7 @@ private void HandleAccountChanged(AccountEvent account)
         private void HandlePositionAssigned(OrderEvent fill)
         {
             // informing user algorithm that option position has been assigned
-            if (fill.IsAssignment)
-            {
-                _algorithm.OnAssignmentOrderEvent(fill);
-            }
+            _algorithm.OnAssignmentOrderEvent(fill);
```
Comment (Martin-Molinero) [inline Engine/TransactionHandlers/BrokerageTransactionHandler.cs:1086]: Curious why we have a broker,transactionHandler & algorithm callback for option assignment but not for exercise. I gave the `OptionExerciseAssignRegressionAlgorithm` a test, and the event actually also seems to go through the `OnOrderEvent`:
```
OrderEvent Time: 12/25/2015 05:00:00 OrderID: 4 EventID: 2 Symbol: GOOG  151224C00745000 Status: Filled Quantity: 1 FillQuantity: 1 FillPrice: 0  Message: Automatic Assignment
Assignment Time: 12/25/2015 05:00:00 OrderID: 4 EventID: 2 Symbol: GOOG  151224C00745000 Status: Filled Quantity: 1 FillQuantity: 1 FillPrice: 0  Message: Option Expired - Automatic Assignment
```

Comment (Martin-Molinero) [reply Engine/TransactionHandlers/BrokerageTransactionHandler.cs:1086]: *Not really related to the objective of this PR changes, but the PR triggered me to look deeper 😁

Comment (mchandschuh) [reply Engine/TransactionHandlers/BrokerageTransactionHandler.cs:1086]: Both of those appear to be assignment events -- this change aimed at not raising the event for exercises. The tx handler was filtering out exercise events by checking `IsAssignment == false`
