### PR TITLE
Fixes History Request Data Time Zone

### LINKED ISSUE #4471: Futures' History Request Empty On Data Day Change
#### Expected Behavior
History request is not empty when there is data.

#### Actual Behavior
History requests for Futures between 8 pm and 12 am returns an empty list.

#### Potential Solution
N/A

#### Reproducing the Problem
```python
class BasicTemplateFuturesAlgorithm(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2013, 10, 8)
        self.SetEndDate(2013, 10, 10)
        self.AddFuture(Futures.Indices.SP500EMini).SetFilter(0, 90)

    def OnData(self, slice):
        if self.Time.hour < 21:
            return

        for chain in slice.FutureChains:
            contracts = sorted([x for x in chain.Value if x.OpenInterest > 1000],
                              key=lambda x: x.OpenInterest, reverse=True)

            if len(contracts) == 0: continue
            symbol = contracts[0].Symbol

            if self.History(symbol, 60).empty:
                self.Log(f'{self.Time} :: {symbol.Value}')
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by AlexCatarino**
#### Description
The tradable days of the history request should respect the data time zone since the data source files also do.

Upgrade `BasicTemplateFuturesHistoryAlgorithm` to a regression algorithm and add a scheduled event to test history requests every hour.

#### Related Issue
Closes #4471

#### Motivation and Context
Bug fix.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
New regression tests.
Run algorithm from the community forum, [History Bug when using Futures Contracts](https://www.quantconnect.com/forum/discussion/8238), in QuantConnect Cloud.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/HistoricalData/SubscriptionDataReaderHistoryProvider.cs [hunk 1]
```diff
@@ -79,6 +79,11 @@ public override IEnumerable<Slice> GetHistory(IEnumerable<HistoryRequest> reques
         /// </summary>
         protected virtual Subscription CreateSubscription(HistoryRequest request, DateTime start, DateTime end)
         {
+            // Tradable dates are defined with the data time zone to access the right source
+            var tradableDates = Time.EachTradeableDay(request.ExchangeHours,
+                start.ConvertFromUtc(request.DataTimeZone),
+                end.ConvertFromUtc(request.DataTimeZone));
+
             // data reader expects these values in local times
             start = start.ConvertFromUtc(request.ExchangeHours.TimeZone);
```
Comment (adam-may) [inline Engine/HistoricalData/SubscriptionDataReaderHistoryProvider.cs:88]: I'd be tempted to create a new variable for start (e.g. exchangeTimeStart) rather than re-using the existing one. This is for 2 reasons - firstly, it gives context to the timezone you're expecting and secondly, it prevents errors such as if these two lines were put above the tradableDates variable creation above.

File: Engine/HistoricalData/SubscriptionDataReaderHistoryProvider.cs [hunk 2]
```diff
@@ -79,6 +79,11 @@ public override IEnumerable<Slice> GetHistory(IEnumerable<HistoryRequest> reques
         /// </summary>
         protected virtual Subscription CreateSubscription(HistoryRequest request, DateTime start, DateTime end)
         {
+            // Tradable dates are defined with the data time zone to access the right source
+            var tradableDates = Time.EachTradeableDay(request.ExchangeHours,
```
Comment (Martin-Molinero) [inline Engine/HistoricalData/SubscriptionDataReaderHistoryProvider.cs:83]: Believe we should use `EachTradeableDayInTimeZone` the same as the data subscription stack, see https://github.com/QuantConnect/Lean/blob/master/Common/Data/UniverseSelection/SubscriptionRequest.cs#L77, which checks the exchange is open in exchange tz, versus here we will be checking the exchange is open in data tz.

File: Algorithm.CSharp/BasicTemplateFuturesHistoryAlgorithm.cs [hunk 3]
```diff
@@ -54,6 +57,17 @@ public override void Initialize()
...
 
             SetBenchmark(d => 1000000);
+
+            Schedule.On(DateRules.EveryDay(), TimeRules.Every(TimeSpan.FromHours(1)), MakeHistoryCall);
+        }
+
+        private void MakeHistoryCall()
+        {
+            var history = History(10, Resolution.Minute);
+            if (history.IsNullOrEmpty())
```
Comment (Martin-Molinero) [inline Algorithm.CSharp/BasicTemplateFuturesHistoryAlgorithm.cs:67]: To be more precise could we assert on the data quantity? Would be nice to have an `OnEndOfAlgorithm` which also asserts the final count or something alike as a safe guard if this method was never called

File: Engine/HistoricalData/SubscriptionDataReaderHistoryProvider.cs (hunk 1 above)
Comment (AlexCatarino) [reply Engine/HistoricalData/SubscriptionDataReaderHistoryProvider.cs]: Thank you, @adam-may. I used `startTimeLocal` and `endTimeLocal` to be coherent with naming across Lean where "Local" means "Exchange".

File: Algorithm.Python/BasicTemplateFuturesHistoryAlgorithm.py [hunk 4]
```diff
@@ -46,32 +46,40 @@ def Initialize(self):
...
+        self.successCount = 0
+
+    def MakeHistoryCall(self):
+        history = self.History(self.Securities.keys(), 10, Resolution.Minute)
+        if len(history) < 10:
+            raise Exception(f'Empty history at {self.Time}')
+        self.successCount += 1
+
+    def OnEndOfAlgorithm(self):
+        if self.successCount < 49:
```
Comment (Martin-Molinero) [inline Algorithm.Python/BasicTemplateFuturesHistoryAlgorithm.py:62]: Nice 👍
A nice improvement would be registering with a comment how did this 49 come to be
