### PR TITLE
Fix Cashbook Settlement for Oanda/FXCM CFD Trades

### LINKED ISSUE #2955: Oanda/FXCM CFD Profits Accrued in QuoteCurrency instead of AccountCurrency
#### Expected Behavior
With Oanda and FXCM brokerages, profits for CFD trades should be accrued to the cashbook in the `Account Currency`.

#### Actual Behavior
With Oanda and FXCM brokerages, profits for CFD trades are accrued to the cashbook in the asset's `Quote Currency`.

#### Potential Solution
- Define a new `AccountCurrencyImmediateSettlementModel` and use it for Oanda/FXCM cashbook updates instead of the default `ImmediateSettlementModel`.
- The new model can be returned only for the `CFD` security type by the Oanda/FXCM brokerage models in `GetSettlementModel`

#### Reproducing the Problem
With an Oanda `USD` account, open and close a position for a `CFD` with a `non-USD` quote currency (e.g. `DE30EUR`). We can observe that the profit/loss is accrued to the `EUR` cashbook entry. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
- Added new `AccountCurrencyImmediateSettlementModel` class to model CFD settlement for FXCM and Oanda brokerages (the settlement model is overridden in the brokerage models).

#### Related Issue
Closes #2955 

#### Motivation and Context
With Oanda and FXCM brokerages, profits for CFD trades were accrued to the cashbook in the asset's `Quote Currency` instead of the `Account Currency`.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
New and updated unit tests + live CFD trades with Oanda and FXCM.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Common/Brokerages/FxcmBrokerageModel.cs [hunk 1]
```diff
@@ -190,6 +190,18 @@ public override ISlippageModel GetSlippageModel(Security security)
...
+        /// <summary>
+        /// Gets a new settlement model for the security
+        /// </summary>
+        /// <param name="security">The security to get a settlement model for</param>
+        /// <returns>The settlement model for this brokerage</returns>
+        public override ISettlementModel GetSettlementModel(Security security)
+        {
+            return security.Type == SecurityType.Cfd
+                ? new AccountCurrencyImmediateSettlementModel() :
+                (ISettlementModel)new ImmediateSettlementModel();
```
Comment (jaredbroad) [inline Common/Brokerages/FxcmBrokerageModel.cs]: I view this as pending work for issue #110 - ideally please make the `ImmediateSettlementModel` support generic account currencies.
