### PR TITLE
Fix SSL/TLS error in LiveOptionChainProvider

### LINKED ISSUE #1952: SSL/TLS error in LiveOptionChainProvider
#### Expected Behavior
No error should be thrown when calling the `GetOptionContractList` method.

#### Actual Behavior
When calling `GetOptionContractList` method this error is thrown:
- Mono:
```System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.)```
- Windows:
```System.Net.WebException : The request was aborted: Could not create SSL/TLS secure channel.```

#### Potential Solution
The `LiveOptionChainProvider` fetches the option chain information from the OCC website.
Apparently, it seems they upgraded the security protocol in their web server and our web request is failing, at least `TLS 1.1` is now required and NET 4.5.2 does not have it enabled by default.

#### Reproducing the Problem
This unit test is now failing on current master branch:
```
        [Test]
        public void LiveOptionChainProviderReturnsData()
        {
            var provider = new LiveOptionChainProvider();
            var result = provider.GetOptionContractList(Symbols.AAPL, DateTime.Today);

            Assert.IsTrue(result.Any());
        }
```

#### System Information
NET 4.5.2 and Mono in QC cloud

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by StefanoRaggi**
#### Description
The `LiveOptionChainProvider` has been updated to enable the newer security protocols (`TLS 1.1` and `TLS 1.2`)

#### Related Issue
Closes #1952

#### Motivation and Context
The `GetOptionContractList` method is always throwing a security error.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Unit test included.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/ect)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description` or `feature-<issue#>-<description>`

### CODE REVIEW

File: Engine/DataFeeds/LiveOptionChainProvider.cs [hunk 1]
```diff
@@ -27,6 +27,16 @@ namespace QuantConnect.Lean.Engine.DataFeeds
...
     public class LiveOptionChainProvider : IOptionChainProvider
     {
+        /// <summary>
+        /// Initializes a new instance of the <see cref="LiveOptionChainProvider"/> class
+        /// </summary>
+        public LiveOptionChainProvider()
+        {
+            // The OCC website now requires at least TLS 1.1 for API requests.
+            // NET 4.5.2 and below does not enable these more secure protocols by default, so we add them in here
+            ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
```
Comment (mchandschuh) [inline Engine/DataFeeds/LiveOptionChainProvider.cs]: This type of initialization code is typically placed in a static context. We can move it to the static constructor or to the application context (closer to main)
